--------------------------------------------------------------------------------
-- 10_tables.sql — 테이블 76종 + 로그인 뷰 COMVNUSERMASTER
-- RegNex(규정 단독, PostgreSQL) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: regnex. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 원천: Oracle DDL 자동변환 — VARCHAR2→VARCHAR, NUMBER→INT/NUMERIC, CLOB→TEXT, DATE→TIMESTAMP.
-- ※ 식별자 큰따옴표 전면 제거(PG 소문자 폴딩 ← 매퍼 SQL 비따옴표와 일치).
-- ※ 컬럼/테이블 코멘트는 12_comments.sql(COMMENT ON — PG 네이티브)이 담당. 합성 1종(COMTH 변경이력)은 후반부.
--------------------------------------------------------------------------------

-- TABLE COMTCCMMNCODE
CREATE TABLE COMTCCMMNCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE_ID_NM VARCHAR(60),
	CODE_ID_DC VARCHAR(200),
	USE_AT CHAR(1),
	CL_CODE CHAR(3),
	FRST_REGIST_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID) ) ;

-- TABLE COMTCCMMNDETAILCODE
CREATE TABLE COMTCCMMNDETAILCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	CODE_NM VARCHAR(60),
	CODE_DC VARCHAR(200),
	USE_AT CHAR(1),
	FRST_REGIST_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID, CODE) ) ;

-- TABLE COMTECOPSEQ
CREATE TABLE COMTECOPSEQ
   (	TABLE_NAME VARCHAR(20) NOT NULL,
	NEXT_ID NUMERIC(30,0),
	 CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME) ) ;

-- TABLE COMTNAUTHORGROUPINFO
CREATE TABLE COMTNAUTHORGROUPINFO
   (	GROUP_ID CHAR(20) NOT NULL,
	GROUP_NM VARCHAR(60) NOT NULL,
	GROUP_CREAT_DE CHAR(20) NOT NULL,
	GROUP_DC VARCHAR(100),
	 CONSTRAINT COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID) ) ;

-- TABLE COMTNAUTHORINFO
CREATE TABLE COMTNAUTHORINFO
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	AUTHOR_NM VARCHAR(60) NOT NULL,
	AUTHOR_DC VARCHAR(200),
	AUTHOR_CREAT_DE CHAR(20) NOT NULL,
	 CONSTRAINT COMTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE) ) ;

-- TABLE COMTNAUTHORROLERELATE
CREATE TABLE COMTNAUTHORROLERELATE
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	ROLE_CODE VARCHAR(50) NOT NULL,
	CREAT_DT TIMESTAMP,
	 CONSTRAINT COMTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE, ROLE_CODE) ) ;

-- TABLE COMTNBANNER
CREATE TABLE COMTNBANNER
   (	BANNER_ID CHAR(20) NOT NULL,
	BANNER_NM VARCHAR(60) NOT NULL,
	LINK_URL VARCHAR(255) NOT NULL,
	BANNER_IMAGE VARCHAR(60) NOT NULL,
	BANNER_DC VARCHAR(200),
	REFLCT_AT CHAR(1) NOT NULL,
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	BANNER_IMAGE_FILE VARCHAR(60),
	SORT_ORDR NUMERIC(8,0),
	 CONSTRAINT COMTNBANNER_PK PRIMARY KEY (BANNER_ID) ) ;

-- TABLE COMTNBBS
CREATE TABLE COMTNBBS
   (	NTT_ID NUMERIC(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL,
	NTT_NO NUMERIC(20,0),
	NTT_SJ VARCHAR(2000),
	NTT_CN TEXT,
	ANSWER_AT CHAR(1),
	PARNTSCTT_NO NUMERIC(10,0),
	ANSWER_LC NUMERIC(8,0),
	SORT_ORDR NUMERIC(8,0),
	RDCNT NUMERIC(10,0),
	USE_AT CHAR(1) NOT NULL,
	NTCE_BGNDE CHAR(20),
	NTCE_ENDDE CHAR(20),
	NTCR_ID VARCHAR(20),
	NTCR_NM VARCHAR(20),
	PASSWORD VARCHAR(200),
	ATCH_FILE_ID CHAR(20),
	NOTICE_AT CHAR(1),
	SJ_BOLD_AT CHAR(1),
	SECRET_AT CHAR(1),
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	BLOG_ID CHAR(20),
	NTT_EXTRA_FIELD_1 VARCHAR(200),
	NTT_EXTRA_FIELD_2 VARCHAR(200),
	NTT_EXTRA_FIELD_3 VARCHAR(200),
	NTT_EXTRA_FIELD_4 VARCHAR(200),
	NTT_EXTRA_FIELD_5 VARCHAR(200),
	NTT_EXTRA_FIELD_6 VARCHAR(200),
	NTT_EXTRA_FIELD_7 VARCHAR(200),
	NTT_EXTRA_FIELD_8 VARCHAR(200),
	NTT_EXTRA_FIELD_9 VARCHAR(200),
	NTT_EXTRA_FIELD_10 VARCHAR(200),
	 CONSTRAINT COMTNBBS_PK PRIMARY KEY (NTT_ID, BBS_ID) ) ;

-- TABLE COMTNBBSMASTER
CREATE TABLE COMTNBBSMASTER
   (	BBS_ID CHAR(30) NOT NULL,
	BBS_NM VARCHAR(255) NOT NULL,
	BBS_INTRCN VARCHAR(2400),
	BBS_TY_CODE CHAR(6) NOT NULL,
	REPLY_POSBL_AT CHAR(1),
	FILE_ATCH_POSBL_AT CHAR(1) NOT NULL,
	ATCH_POSBL_FILE_NUMBER NUMERIC(2,0) NOT NULL,
	ATCH_POSBL_FILE_SIZE NUMERIC(8,0),
	USE_AT CHAR(1) NOT NULL,
	TMPLAT_ID CHAR(20),
	CMMNTY_ID CHAR(20),
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	BLOG_ID CHAR(20),
	BLOG_AT CHAR(2),
	BBS_SKIN_CODE VARCHAR(30) DEFAULT 'BASIC',
	BBS_EXTRA_FIELD_1 VARCHAR(200),
	BBS_EXTRA_FIELD_2 VARCHAR(200),
	BBS_EXTRA_FIELD_3 VARCHAR(200),
	BBS_EXTRA_FIELD_4 VARCHAR(200),
	BBS_EXTRA_FIELD_5 VARCHAR(200),
	BBS_EXTRA_FIELD_6 VARCHAR(200),
	BBS_EXTRA_FIELD_7 VARCHAR(200),
	BBS_EXTRA_FIELD_8 VARCHAR(200),
	BBS_EXTRA_FIELD_9 VARCHAR(200),
	BBS_EXTRA_FIELD_10 VARCHAR(200),
	BBS_EXTRA_FIELD_TYPE_1 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_2 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_3 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_4 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_5 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_6 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_7 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_8 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_9 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_10 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_CODE_ID_1 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_2 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_3 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_4 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_5 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_6 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_7 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_8 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_9 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_10 VARCHAR(30),
	LIST_PAGE_UNIT VARCHAR(50),
	SECRET_POSBL_AT CHAR(1) DEFAULT 'Y',
	RICH_EDITOR_AT CHAR(1) DEFAULT 'Y',
	SEARCH_INCLD_AT CHAR(1) DEFAULT 'Y',
	PAGING_AT CHAR(1) DEFAULT 'Y',
	SEARCH_BOX_AT CHAR(1) DEFAULT 'Y',
	 CONSTRAINT COMTNBBSMASTER_PK PRIMARY KEY (BBS_ID) ) ;

-- TABLE COMTNBBSMASTEROPTN
CREATE TABLE COMTNBBSMASTEROPTN
   (	BBS_ID CHAR(30) NOT NULL,
	ANSWER_AT CHAR(1) NOT NULL,
	STSFDG_AT CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID) ) ;

-- 게시판별 작성권한. 열람권한은 메뉴 역할매핑(COMTNMENUCREATDTLS)이 원천이지만,
-- 메뉴가 보인다와 글을 쓸 수 있다는 다른 축이라 별도 매핑이 필요하다.
CREATE TABLE COMTNBBSWRITEAUTHOR (
	BBS_ID      CHAR(30)     NOT NULL,
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	CONSTRAINT COMTNBBSWRITEAUTHOR_PK PRIMARY KEY (BBS_ID, AUTHOR_CODE)
);

-- TABLE COMTNCOMMENT
CREATE TABLE COMTNCOMMENT
   (	NTT_ID NUMERIC(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL,
	ANSWER_NO NUMERIC(20,0) NOT NULL,
	WRTER_ID VARCHAR(20),
	-- 표준 원형은 VARCHAR(20) 이라 USER_NM(60) 이 긴 사용자는 ORA-12899 → 60 으로 확장(2026-07-10)
	WRTER_NM VARCHAR(60),
	-- 표준 원형은 VARCHAR(200)(바이트) 이라 한글 약 66자에서 ORA-12899 → 문자기준 1000 으로 확장(2026-07-10, UI 글자수 카운터)
	ANSWER VARCHAR(1000),
	USE_AT CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	PASSWORD VARCHAR(200),
	 CONSTRAINT COMTNCOMMENT_PK PRIMARY KEY (NTT_ID, BBS_ID, ANSWER_NO) ) ;

-- TABLE COMTNEMPLYRINFO
CREATE TABLE COMTNEMPLYRINFO
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	ORGNZT_ID CHAR(20),
	USER_NM VARCHAR(60) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	EMPL_NO VARCHAR(20),
	IHIDNUM VARCHAR(200),
	SEXDSTN_CODE CHAR(1),
	BRTHDY CHAR(20),
	FXNUM VARCHAR(20),
	HOUSE_ADRES VARCHAR(100),
	PASSWORD_HINT VARCHAR(100),
	PASSWORD_CNSR VARCHAR(100),
	HOUSE_END_TELNO VARCHAR(4),
	AREA_NO VARCHAR(4),
	DETAIL_ADRES VARCHAR(100),
	ZIP VARCHAR(6),
	OFFM_TELNO VARCHAR(20),
	MBTLNUM VARCHAR(20),
	EMAIL_ADRES VARCHAR(50),
	OFCPS_NM VARCHAR(60),
	HOUSE_MIDDLE_TELNO VARCHAR(4),
	GROUP_ID CHAR(20),
	PSTINST_CODE CHAR(8),
	EMPLYR_STTUS_CODE CHAR(1) NOT NULL,
	ESNTL_ID CHAR(20) NOT NULL,
	CRTFC_DN_VALUE VARCHAR(100),
	SBSCRB_DE TIMESTAMP,
	LOCK_AT CHAR(1),
	LOCK_CNT NUMERIC(3,0),
	LOCK_LAST_PNTTM TIMESTAMP,
	CHG_PWD_LAST_PNTTM TIMESTAMP,
	 CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID) ) ;

-- TABLE COMTNEMPLYRSCRTYESTBS
CREATE TABLE COMTNEMPLYRSCRTYESTBS
   (	SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
	MBER_TY_CODE CHAR(5),
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	 CONSTRAINT COMTNEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID) ) ;

-- TABLE COMTNFAQINFO
CREATE TABLE COMTNFAQINFO
   (	FAQ_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255),
	QESTN_CN VARCHAR(2500),
	ANSWER_CN VARCHAR(2500),
	RDCNT NUMERIC(10,0),
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
	ATCH_FILE_ID CHAR(20),
	QNA_PROCESS_STTUS_CODE CHAR(1),
	FAQ_CODE VARCHAR(15),
	 CONSTRAINT COMTNFAQINFO_PK PRIMARY KEY (FAQ_ID) ) ;

-- TABLE COMTNFILE
CREATE TABLE COMTNFILE
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	CREAT_DT TIMESTAMP NOT NULL,
	USE_AT CHAR(1),
	 CONSTRAINT COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID) ) ;

-- TABLE COMTNFILEDETAIL
CREATE TABLE COMTNFILEDETAIL
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	FILE_SN NUMERIC(10,0) NOT NULL,
	FILE_STRE_COURS VARCHAR(2000) NOT NULL,
	STRE_FILE_NM VARCHAR(255) NOT NULL,
	ORIGNL_FILE_NM VARCHAR(255),
	FILE_EXTSN VARCHAR(20) NOT NULL,
	FILE_CN TEXT,
	FILE_SIZE NUMERIC(8,0),
	DWLD_CO NUMERIC(8,0) DEFAULT 0,
	 CONSTRAINT COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN) ) ;

-- TABLE COMTNGNRLMBER
CREATE TABLE COMTNGNRLMBER
   (	MBER_ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	PASSWORD_HINT VARCHAR(100),
	PASSWORD_CNSR VARCHAR(100),
	IHIDNUM VARCHAR(200),
	MBER_NM VARCHAR(50) NOT NULL,
	ZIP VARCHAR(6),
	ADRES VARCHAR(100),
	AREA_NO VARCHAR(4) NOT NULL,
	MBER_STTUS VARCHAR(15),
	DETAIL_ADRES VARCHAR(100),
	END_TELNO VARCHAR(4) NOT NULL,
	MBTLNUM VARCHAR(20) NOT NULL,
	GROUP_ID CHAR(20),
	MBER_FXNUM VARCHAR(20),
	MBER_EMAIL_ADRES VARCHAR(50),
	MIDDLE_TELNO VARCHAR(4) NOT NULL,
	SBSCRB_DE TIMESTAMP,
	SEXDSTN_CODE CHAR(1),
	ESNTL_ID CHAR(20) NOT NULL,
	LOCK_AT CHAR(1),
	LOCK_CNT NUMERIC(3,0),
	LOCK_LAST_PNTTM TIMESTAMP,
	CHG_PWD_LAST_PNTTM TIMESTAMP,
	ORGNZT_ID VARCHAR(20),
	EMPL_NO VARCHAR(20),
	 CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID) ) ;

-- TABLE COMTNLOGINLOG
CREATE TABLE COMTNLOGINLOG
   (	LOG_ID CHAR(20) NOT NULL,
	CONECT_ID VARCHAR(20),
	CONECT_IP VARCHAR(23),
	CONECT_MTHD CHAR(4),
	ERROR_OCCRRNC_AT CHAR(1),
	ERROR_CODE CHAR(3),
	CREAT_DT TIMESTAMP,
	 CONSTRAINT COMTNLOGINLOG_PK PRIMARY KEY (LOG_ID) ) ;

-- TABLE COMTNLOGINPOLICY
CREATE TABLE COMTNLOGINPOLICY
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	IP_INFO VARCHAR(23) NOT NULL,
	DPLCT_PERM_AT CHAR(1) NOT NULL,
	LMTT_AT CHAR(1) NOT NULL,
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	 CONSTRAINT COMTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID) ) ;

-- TABLE COMTNMENUCREATDTLS
CREATE TABLE COMTNMENUCREATDTLS
   (	MENU_NO NUMERIC(20,0) NOT NULL,
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	MAPNG_CREAT_ID VARCHAR(30),
	 CONSTRAINT COMTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO, AUTHOR_CODE) ) ;

-- TABLE COMTNMENUINFO
CREATE TABLE COMTNMENUINFO
   (	MENU_NM VARCHAR(60) NOT NULL,
	PROGRM_FILE_NM VARCHAR(60) NOT NULL,
	MENU_NO NUMERIC(20,0) NOT NULL,
	UPPER_MENU_NO NUMERIC(20,0),
	MENU_ORDR NUMERIC(5,0) NOT NULL,
	MENU_DC VARCHAR(250),
	RELATE_IMAGE_PATH VARCHAR(100),
	RELATE_IMAGE_NM VARCHAR(60),
	MENU_SE VARCHAR(20),
	 CONSTRAINT COMTNMENUINFO_PK PRIMARY KEY (MENU_NO) ) ;

-- TABLE COMTNORGNZTINFO (2026-07-27 트리 전환: UPPER_ORGNZT_ID 자기참조 + ORDR 표시순서)
CREATE TABLE COMTNORGNZTINFO
   (	ORGNZT_ID CHAR(20) NOT NULL,
	ORGNZT_NM VARCHAR(255) NOT NULL,
	ORGNZT_DC VARCHAR(500),
	UPPER_ORGNZT_ID CHAR(20),
	ORDR NUMERIC(5,0),
	 CONSTRAINT COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID) ) ;

-- TABLE COMTNPOPUPMANAGE
CREATE TABLE COMTNPOPUPMANAGE
   (	POPUP_ID VARCHAR(20) NOT NULL,
	POPUP_SJ_NM VARCHAR(1024),
	FILE_URL VARCHAR(1024),
	POPUP_WIDTH_LC VARCHAR(20),
	POPUP_WIDTH_SIZE NUMERIC,
	NTCE_BGNDE CHAR(20),
	NTCE_ENDDE CHAR(20),
	STOPVEW_SETUP_AT CHAR(1),
	NTCE_AT CHAR(1),
	POPUP_VRTICL_LC VARCHAR(20),
	POPUP_VRTICL_SIZE NUMERIC,
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	POPUP_CN TEXT,
	CN_SE VARCHAR(1) DEFAULT 'F',
	 CONSTRAINT COMTNPOPUPMANAGE_PK PRIMARY KEY (POPUP_ID) ) ;

-- TABLE COMTNPRIVACYLOG
CREATE TABLE COMTNPRIVACYLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	INQIRE_DT TIMESTAMP NOT NULL,
	SRVC_NM VARCHAR(500),
	INQIRE_INFO VARCHAR(100),
	RQESTER_ID VARCHAR(20),
	RQESTER_IP VARCHAR(23),
	 CONSTRAINT REQUST_ID_PK PRIMARY KEY (REQUST_ID) ) ;

-- TABLE COMTNPROGRMLIST
CREATE TABLE COMTNPROGRMLIST
   (	PROGRM_FILE_NM VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH VARCHAR(100) NOT NULL,
	PROGRM_KOREAN_NM VARCHAR(60),
	PROGRM_DC VARCHAR(200),
	URL VARCHAR(100) NOT NULL,
	 CONSTRAINT COMTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM) ) ;

-- TABLE COMTNQAINFO
CREATE TABLE COMTNQAINFO
   (	QA_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255),
	QESTN_CN VARCHAR(2500),
	WRITNG_DE CHAR(20),
	RDCNT NUMERIC(10,0),
	EMAIL_ADRES VARCHAR(50),
	FRST_REGIST_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	QNA_PROCESS_STTUS_CODE CHAR(1),
	WRTER_NM VARCHAR(20),
	ANSWER_CN VARCHAR(2500),
	WRITNG_PASSWORD VARCHAR(20),
	ANSWER_DE CHAR(20),
	EMAIL_ANSWER_AT CHAR(1),
	AREA_NO VARCHAR(4),
	MIDDLE_TELNO VARCHAR(4),
	END_TELNO VARCHAR(4),
	 CONSTRAINT COMTNQAINFO_PK PRIMARY KEY (QA_ID) ) ;

-- TABLE COMTNROLEINFO
CREATE TABLE COMTNROLEINFO
   (	ROLE_CODE VARCHAR(50) NOT NULL,
	ROLE_NM VARCHAR(60) NOT NULL,
	ROLE_PTTRN VARCHAR(300),
	ROLE_DC VARCHAR(200),
	ROLE_TY VARCHAR(80),
	ROLE_SORT VARCHAR(10),
	ROLE_CREAT_DE CHAR(20) NOT NULL,
	 CONSTRAINT COMTNROLEINFO_PK PRIMARY KEY (ROLE_CODE) ) ;

-- TABLE COMTNROLES_HIERARCHY
CREATE TABLE COMTNROLES_HIERARCHY
   (	PARNTS_ROLE VARCHAR(30) NOT NULL,
	CHLDRN_ROLE VARCHAR(30) NOT NULL,
	 CONSTRAINT COMTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE, CHLDRN_ROLE) ) ;

-- TABLE COMTNSITEMAP
CREATE TABLE COMTNSITEMAP
   (	MAPNG_CREAT_ID VARCHAR(30) NOT NULL,
	CREATR_ID VARCHAR(20) NOT NULL,
	MAPNG_FILE_NM VARCHAR(60) NOT NULL,
	MAPNG_FILE_PATH VARCHAR(100) NOT NULL,
	 CONSTRAINT COMTNSITEMAP_PK PRIMARY KEY (MAPNG_CREAT_ID) ) ;

-- TABLE COMTNSTSFDG
CREATE TABLE COMTNSTSFDG
   (	STSFDG_NO NUMERIC(20,0) NOT NULL,
	NTT_ID NUMERIC(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL,
	WRTER_ID VARCHAR(20),
	-- 표준 원형 20 → USER_NM(60) 초과 시 ORA-12899. 60 으로 확장(2026-07-10, 만족도 JSON UI)
	WRTER_NM VARCHAR(60),
	PASSWORD VARCHAR(200),
	STSFDG NUMERIC(1,0) NOT NULL,
	-- 표준 원형 200바이트(한글 약66자) → 1000 CHAR 로 확장(2026-07-10, UI 글자수 카운터)
	STSFDG_CN VARCHAR(1000),
	USE_AT CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTNSTSFDG_PK PRIMARY KEY (STSFDG_NO) ) ;

-- TABLE COMTNSYSLOG
CREATE TABLE COMTNSYSLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	JOB_SE_CODE CHAR(3),
	INSTT_CODE CHAR(7),
	OCCRRNC_DE TIMESTAMP,
	RQESTER_IP VARCHAR(23),
	RQESTER_ID VARCHAR(20),
	TRGET_MENU_NM VARCHAR(255),
	SVC_NM VARCHAR(255),
	METHOD_NM VARCHAR(60),
	PROCESS_SE_CODE CHAR(3),
	PROCESS_CO NUMERIC(10,0),
	PROCESS_TIME VARCHAR(14),
	RSPNS_CODE CHAR(3),
	ERROR_SE CHAR(1),
	ERROR_CO NUMERIC(10,0),
	ERROR_CODE CHAR(3),
	 CONSTRAINT COMTNSYSLOG_PK PRIMARY KEY (REQUST_ID) ) ;

-- TABLE COMTNTMPLATINFO
-- 게시판 템플릿 정본(2026-07 재정의): TMPLAT_SE_CODE=렌더엔진코드(COM005), TMPLAT_CONFIG_CN=표현설정(JSON)
CREATE TABLE COMTNTMPLATINFO
   (	TMPLAT_ID CHAR(20) NOT NULL,
	TMPLAT_NM VARCHAR(255),
	TMPLAT_COURS VARCHAR(2000),
	USE_AT CHAR(1),
	TMPLAT_SE_CODE VARCHAR(20),
	TMPLAT_CONFIG_CN VARCHAR(2000),
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	 CONSTRAINT COMTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID) ) ;

-- TABLE COMTNUSERLOG
CREATE TABLE COMTNUSERLOG
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	RQESTER_ID VARCHAR(20) NOT NULL,
	SVC_NM VARCHAR(255) NOT NULL,
	METHOD_NM VARCHAR(60) NOT NULL,
	CREAT_CO NUMERIC(10,0),
	UPDT_CO NUMERIC(10,0),
	RDCNT NUMERIC(10,0),
	DELETE_CO NUMERIC(10,0),
	OUTPT_CO NUMERIC(10,0),
	ERROR_CO NUMERIC(10,0),
	 CONSTRAINT COMTNUSERLOG_PK PRIMARY KEY (OCCRRNC_DE, RQESTER_ID, SVC_NM, METHOD_NM) ) ;

-- TABLE COMTNWEBLOG (2026-07-20 접속통계 확장: 기기/브라우저/세션 컬럼 + 일자 인덱스)
CREATE TABLE COMTNWEBLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	OCCRRNC_DE TIMESTAMP,
	URL VARCHAR(200),
	RQESTER_ID VARCHAR(20),
	RQESTER_IP VARCHAR(23),
	DVICE_SE VARCHAR(10),
	BROWSER_NM VARCHAR(30),
	SESN_ID VARCHAR(60),
	 CONSTRAINT COMTNWEBLOG_PK PRIMARY KEY (REQUST_ID) ) ;
  CREATE INDEX IX_COMTNWEBLOG_DT ON COMTNWEBLOG (OCCRRNC_DE)
  ;

-- TABLE COMTSSYSLOGSUMMARY
CREATE TABLE COMTSSYSLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	SVC_NM VARCHAR(255) NOT NULL,
	METHOD_NM VARCHAR(60) NOT NULL,
	CREAT_CO NUMERIC(10,0),
	UPDT_CO NUMERIC(10,0),
	RDCNT NUMERIC(10,0),
	DELETE_CO NUMERIC(10,0),
	OUTPT_CO NUMERIC(10,0),
	ERROR_CO NUMERIC(10,0),
	 CONSTRAINT COMTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, SVC_NM, METHOD_NM) ) ;

-- TABLE COMTSWEBLOGSUMMARY
CREATE TABLE COMTSWEBLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	URL VARCHAR(200) NOT NULL,
	RDCNT NUMERIC(10,0),
	 CONSTRAINT COMTSWEBLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, URL) ) ;

-- TABLE TB_ACT_LOG
CREATE TABLE TB_ACT_LOG
   (	IALOG_NO NUMERIC NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL,
	IREF_NO NUMERIC NOT NULL,
	SNAME VARCHAR(255) NOT NULL,
	STASK VARCHAR(255) NOT NULL,
	SUSER_ID VARCHAR(255) NOT NULL,
	SUSER_NAME VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	SINS_IP VARCHAR(255)
   ) ;
ALTER TABLE TB_ACT_LOG ADD CONSTRAINT PK_TB_ACT_LOG PRIMARY KEY (IALOG_NO) ;

-- TABLE TB_ATTACH
CREATE TABLE TB_ATTACH
   (	IATT_NO NUMERIC NOT NULL,
	SCATE_ID VARCHAR(255) NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL,
	IREF_NO NUMERIC NOT NULL,
	SPATH VARCHAR(255) NOT NULL,
	SNAME VARCHAR(255) NOT NULL,
	SMAPPING VARCHAR(255) NOT NULL,
	SEXT VARCHAR(255) NOT NULL,
	SMETA VARCHAR(255) NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SCONTENTS TEXT,
	ISEQ NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	ISIZE NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255),
	-- (2026-07-30) 다운로드 집계. 상세 이력은 TB_ACT_LOG(STASK='파일 다운로드')가 별도로 남긴다.
	IDOWN_CNT NUMERIC DEFAULT 0 NOT NULL
   ) ;
ALTER TABLE TB_ATTACH ADD CONSTRAINT PK_TB_ATTACH PRIMARY KEY (IATT_NO) ;

-- TABLE TB_CATE
CREATE TABLE TB_CATE
   (	ICATE_NO NUMERIC NOT NULL,
	SGUBUN_ID VARCHAR(255) NOT NULL,
	SNAME VARCHAR(255) NOT NULL,
	SFULL_NAME VARCHAR(255) NOT NULL,
	ILEVEL NUMERIC NOT NULL,
	IREF NUMERIC NOT NULL,
	IREF_LV_1 NUMERIC NOT NULL,
	IREF_LV_2 NUMERIC NOT NULL,
	IREF_LV_3 NUMERIC NOT NULL,
	IREF_LV_4 NUMERIC NOT NULL,
	IREF_LV_5 NUMERIC NOT NULL,
	IREF_LV_6 NUMERIC NOT NULL,
	IREF_LV_7 NUMERIC NOT NULL,
	IREF_LV_8 NUMERIC NOT NULL,
	IREF_LV_9 NUMERIC NOT NULL,
	IREF_LV_10 NUMERIC NOT NULL,
	SDISP_YN VARCHAR(255) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SDEL_YN VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_CATE ADD CONSTRAINT PK_TB_CATE PRIMARY KEY (ICATE_NO) ;

-- TABLE TB_CATE_OWNER
CREATE TABLE TB_CATE_OWNER
   (	ICATE_NO NUMERIC NOT NULL,
	OWNER_TY VARCHAR(10) NOT NULL,
	OWNER_ID VARCHAR(50) NOT NULL,
	INHERIT_YN CHAR(1) DEFAULT 'Y' NOT NULL,
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(LOCALTIMESTAMP,'YYYYMMDDHH24MISS'),
	SINS_ID VARCHAR(50),
	 CONSTRAINT TB_CATE_OWNER_CK1 CHECK (OWNER_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_CATE_OWNER_PK PRIMARY KEY (ICATE_NO, OWNER_TY, OWNER_ID) ) ;

-- TABLE TB_CATE_READER
CREATE TABLE TB_CATE_READER
   (	ICATE_NO NUMERIC NOT NULL,
	READER_TY VARCHAR(10) NOT NULL,
	READER_ID VARCHAR(50) NOT NULL,
	INHERIT_YN CHAR(1) DEFAULT 'Y' NOT NULL,
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(LOCALTIMESTAMP,'YYYYMMDDHH24MISS'),
	SINS_ID VARCHAR(50),
	 CONSTRAINT TB_CATE_READER_CK1 CHECK (READER_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_CATE_READER_PK PRIMARY KEY (ICATE_NO, READER_TY, READER_ID) ) ;

-- TABLE TB_DOCU
CREATE TABLE TB_DOCU
   (	IDOCU_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SITEM VARCHAR(255) NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SCONTENTS TEXT,
	SGAEJUNG_TYPE VARCHAR(255) NOT NULL,
	SDISP_YN VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSTART_DT VARCHAR(255) NOT NULL,
	SREASON TEXT,
	SSEARCH_TEXT TEXT,
	SSYS_ID VARCHAR(255),
	SGRP_TITLE VARCHAR(255) NOT NULL
   ) ;
ALTER TABLE TB_DOCU ADD CONSTRAINT PK_TB_DOCU PRIMARY KEY (IDOCU_NO) ;

-- (2026-07-30 폐기) TABLE TB_DOCU_FILE — 신규 DB·레거시 레거시 DB 양쪽 모두 0행이라 DROP.
--   별표/별지서식의 개별 첨부는 관련자료 축을 재사용한다:
--     TB_REL_VRSN(SFLAG='DOCUMENT', SFULL_ITEM=TB_DOCU.SITEM) → TB_REL_FILE → TB_ATTACH
--   삭제 연쇄는 TRG_DEL_DOCU(13_triggers_functions.sql)가 담당.

-- TABLE TB_FAVOR
CREATE TABLE TB_FAVOR
   (	IFAVOR_NO NUMERIC NOT NULL,
	SGUBUN VARCHAR(255) NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	SITEM VARCHAR(255) NOT NULL,
	SDESC VARCHAR(4000) NOT NULL,
	SUSER_ID VARCHAR(255) NOT NULL,
	SUSER_NAME VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	ISEEN_LAW_NO NUMERIC
   ) ;
ALTER TABLE TB_FAVOR ADD CONSTRAINT PK_TB_FAVOR PRIMARY KEY (IFAVOR_NO) ;

-- TABLE TB_GAEJUNG
CREATE TABLE TB_GAEJUNG
   (	IGAEJUNG_NO NUMERIC NOT NULL,
	SNAME VARCHAR(255) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	SDIFF_YN VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SDEL_YN VARCHAR(255) NOT NULL
   ) ;
ALTER TABLE TB_GAEJUNG ADD CONSTRAINT PK_TB_GAEJUNG PRIMARY KEY (IGAEJUNG_NO) ;

-- TABLE TB_GAEJUNG_LOG
CREATE TABLE TB_GAEJUNG_LOG
   (	IPROM_NO NUMERIC NOT NULL,
	IBUSEO_NO NUMERIC NOT NULL,
	IUSER_NO NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL
   ) ;
ALTER TABLE TB_GAEJUNG_LOG ADD CONSTRAINT PK_TB_GAEJUNG_LOG PRIMARY KEY (IPROM_NO) ;

-- TABLE TB_GUBUN_READER
CREATE TABLE TB_GUBUN_READER
   (	SGUBUN_ID VARCHAR(50) NOT NULL,
	READER_TY VARCHAR(10) NOT NULL,
	READER_ID VARCHAR(50) NOT NULL,
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(LOCALTIMESTAMP,'YYYYMMDDHH24MISS'),
	SINS_ID VARCHAR(50),
	 CONSTRAINT TB_GUBUN_READER_CK1 CHECK (READER_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_GUBUN_READER_PK PRIMARY KEY (SGUBUN_ID, READER_TY, READER_ID) ) ;

-- TABLE TB_LAWQUEST
CREATE TABLE TB_LAWQUEST
   (	NO NUMERIC(38,0) NOT NULL,
	ID VARCHAR(30) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	YEAR CHAR(4) NOT NULL,
	TYPE VARCHAR(20) NOT NULL,
	SOSOK VARCHAR(30),
	GIGWAN CHAR(30),
	LAWER VARCHAR(50),
	GUMAEK NUMERIC(10,0) NOT NULL,
	ILJA1 CHAR(8),
	ILJA2 CHAR(8),
	SUBJECT VARCHAR(200) NOT NULL,
	QUEST_CON TEXT,
	RESPO_CON TEXT,
	WRITEDAY TIMESTAMP NOT NULL,
	READNUM NUMERIC(38,0) NOT NULL,
	BUGET VARCHAR(200),
	PUBLIC_YN VARCHAR(10) DEFAULT '2'
   ) ;
ALTER TABLE TB_LAWQUEST ADD CONSTRAINT PK_COUNTLAW PRIMARY KEY (NO) ;

-- TABLE TB_LAWQUEST_ADMIN
CREATE TABLE TB_LAWQUEST_ADMIN
   (	ADMIN_SABUN VARCHAR(20) NOT NULL,
	ADMIN_NAME VARCHAR(30)
   ) ;

-- TABLE TB_MEMO
CREATE TABLE TB_MEMO
   (	IMEMO_NO NUMERIC NOT NULL,
	SGUBUN VARCHAR(255) NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	SITEM VARCHAR(255) NOT NULL,
	SDESC VARCHAR(4000) NOT NULL,
	SUSER_ID VARCHAR(255) NOT NULL,
	SUSER_NAME VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SBUSEO_ID VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_MEMO ADD CONSTRAINT PK_TB_MEMO PRIMARY KEY (IMEMO_NO) ;

-- TABLE TB_PROM
CREATE TABLE TB_PROM
   (	IPROM_NO NUMERIC NOT NULL,
	SGUBUN_ID VARCHAR(255) NOT NULL,
	ICATE_NO NUMERIC NOT NULL,
	IGAEJUNG_NO NUMERIC NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	ILAW_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SNUM VARCHAR(255) NOT NULL,
	SPROM_DT VARCHAR(255) NOT NULL,
	SSTART_DT VARCHAR(255) NOT NULL,
	SNULL_DT VARCHAR(255) NOT NULL,
	SNULL_DT_PEND VARCHAR(255),
	SURL VARCHAR(255) NOT NULL,
	SPROV_FG VARCHAR(255) NOT NULL,
	SPROV_STYLE_CD VARCHAR(255) NOT NULL,
	SPROV_FILE_NO VARCHAR(255) NOT NULL,
	SDISP_YN VARCHAR(255) NOT NULL,
	SEXISTING_YN VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SGAEJUNG TEXT,
	SREASON TEXT,
	SBYLAW TEXT,
	SSEARCH_TEXT TEXT,
	ISEQ NUMERIC DEFAULT 0 NOT NULL,
	SPREAMBLE TEXT,
	SEXT_DISP_YN VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	IBUSEO_NO NUMERIC NOT NULL,
	SSTATUS VARCHAR(255) NOT NULL,
	SDPL_ITEM_YN VARCHAR(255) NOT NULL,
	-- (2026-07-30 폐기) SSTOR_FILE_YN/DT/NM/PATH/DOC_NM/HWP_NM/PDF_NM 7종 —
	--   레거시 은 회차별 원본 문서(DOC/HWP/PDF)를 미리 만들어 보관했으나 RLMS 는 저장하지 않는다.
	--   본문 문서는 /rlms/fulltext/exportProm.do 가 요청 시 PDF/DOCX/HWPX 로 생성(조 범위 발췌 포함).
	SREL_FILE_VIEW_YN VARCHAR(255),
	SSUB_TITLE VARCHAR(255),
	SPARTY VARCHAR(4000),
	SORDERIDX NUMERIC(3,0) DEFAULT 50,
	SGAEJUNG_CODE VARCHAR(20),
	SBUSEO_ORGNZT_ID CHAR(20),
	SSTSFDG_YN VARCHAR(255) DEFAULT 'N'
   ) ;
ALTER TABLE TB_PROM ADD CONSTRAINT PK_TB_PROM PRIMARY KEY (IPROM_NO) ;

-- TABLE TB_PROM_ACT_LOG
CREATE TABLE TB_PROM_ACT_LOG
   (	IPALOG_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255) NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL,
	IREF_NO VARCHAR(255) NOT NULL,
	SACT_TYPE VARCHAR(255) NOT NULL,
	SACT_NM VARCHAR(255),
	SACT_DC VARCHAR(4000) NOT NULL,
	SUSER_ID VARCHAR(255) NOT NULL,
	SUSER_NM VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	IPWRK_NO NUMERIC NOT NULL,
	SFIELD_LOG TEXT
   ) ;
ALTER TABLE TB_PROM_ACT_LOG ADD CONSTRAINT PK_TB_PROM_ACT_LOG PRIMARY KEY (IPALOG_NO) ;

-- TABLE TB_PROM_STSFDG (규정 만족도 조사 — 회차별 1인 1회, 2026-07-20 rlms_prom_stsfdg.sql)
CREATE TABLE TB_PROM_STSFDG
   (	IPROM_NO NUMERIC NOT NULL,
	SINS_ID VARCHAR(50) NOT NULL,
	ISTSFDG NUMERIC(1,0) NOT NULL,
	SSTSFDG_CN VARCHAR(1000),
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(LOCALTIMESTAMP,'YYYYMMDDHH24MISS'),
	SUPD_DT VARCHAR(14),
	 CONSTRAINT TB_PROM_STSFDG_CK1 CHECK (ISTSFDG BETWEEN 1 AND 5),
	 CONSTRAINT TB_PROM_STSFDG_PK PRIMARY KEY (IPROM_NO, SINS_ID) ) ;

-- TABLE TB_PROM_MAP
CREATE TABLE TB_PROM_MAP
   (	IPMAP_NO NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255),
	SNAME VARCHAR(255) NOT NULL,
	SFULL_NAME VARCHAR(255) NOT NULL,
	SPROM_YN VARCHAR(255) NOT NULL,
	ILEVEL NUMERIC NOT NULL,
	IREF NUMERIC NOT NULL,
	SDISP_YN VARCHAR(255) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	IPROM_NO NUMERIC NOT NULL
   ) ;
ALTER TABLE TB_PROM_MAP ADD CONSTRAINT PK_TB_PROM_MAP PRIMARY KEY (IPMAP_NO) ;

-- TABLE TB_PROM_WRK
CREATE TABLE TB_PROM_WRK
   (	IPWRK_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255),
	SSTATUS VARCHAR(255) NOT NULL,
	SUSER_ID VARCHAR(255) NOT NULL,
	SUSER_NM VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SREASON TEXT,
	SACT_NM VARCHAR(255)
   ) ;
ALTER TABLE TB_PROM_WRK ADD CONSTRAINT PK_TB_PROM_WRK PRIMARY KEY (IPWRK_NO) ;

-- TABLE TB_PROV_HTML
CREATE TABLE TB_PROV_HTML
   (	IPHTML_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SITEM VARCHAR(255) NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SCONTENTS TEXT,
	SGAEJUNG_TYPE VARCHAR(255) NOT NULL,
	SDISP_YN VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSTART_DT VARCHAR(255) NOT NULL,
	SREASON TEXT,
	SSEARCH_TEXT TEXT,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_PROV_HTML ADD CONSTRAINT PK_TB_PROV_HTML PRIMARY KEY (IPHTML_NO) ;

-- TABLE TB_PROV_TEXT_HST
CREATE TABLE TB_PROV_TEXT_HST
   (	IPTHST_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SUSER_ID VARCHAR(255),
	SINS_DT VARCHAR(255),
	STEXT TEXT
   ) ;
ALTER TABLE TB_PROV_TEXT_HST ADD CONSTRAINT PK_TB_PROV_TEXT_HST PRIMARY KEY (IPTHST_NO) ;

-- TABLE TB_PROV_VRSN
CREATE TABLE TB_PROV_VRSN
   (	IPVRSN_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SFULL_ITEM VARCHAR(255) NOT NULL,
	SITEM VARCHAR(255) NOT NULL,
	SSUB_ITEM VARCHAR(255) NOT NULL,
	SSTYLE_ID VARCHAR(255) NOT NULL,
	SUNIT_TYPE VARCHAR(255) NOT NULL,
	SNATIVE_TYPE VARCHAR(255) NOT NULL,
	ILEVEL NUMERIC NOT NULL,
	IINDEX NUMERIC NOT NULL,
	STITLE VARCHAR(500),
	SREASON TEXT,
	SCONTENTS TEXT,
	SGAEJUNG_TYPE VARCHAR(255) NOT NULL,
	SDISP_YN VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSTART_DT VARCHAR(255) NOT NULL,
	SUSER_MODIFIED_YN VARCHAR(255) NOT NULL,
	SMOVE_FULL_ITEM VARCHAR(255),
	SSEARCH_TEXT TEXT,
	SGAEJUNG_HIDE_YN VARCHAR(255),
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_PROV_VRSN ADD CONSTRAINT PK_TB_PROV_VRSN PRIMARY KEY (IPVRSN_NO) ;

-- TABLE TB_READ_DUTY (필수 열람 지정 — 2026-07-28 rlms_read_duty.sql)
CREATE TABLE TB_READ_DUTY
   (	IDUTY_NO NUMERIC NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	SALL_YN CHAR(1) DEFAULT 'N' NOT NULL,
	SDUE_DT VARCHAR(8),
	SINS_ID VARCHAR(50),
	SINS_NM VARCHAR(50),
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(LOCALTIMESTAMP,'YYYYMMDDHH24MISS'),
	 CONSTRAINT TB_READ_DUTY_CK1 CHECK (SALL_YN IN ('Y','N')),
	 CONSTRAINT TB_READ_DUTY_PK PRIMARY KEY (IDUTY_NO) ) ;

-- TABLE TB_READ_DUTY_TGT (필수 열람 대상 행 — DEPT/USER 혼합)
CREATE TABLE TB_READ_DUTY_TGT
   (	IDUTY_NO NUMERIC NOT NULL,
	STGT_TY VARCHAR(10) NOT NULL,
	STGT_ID VARCHAR(50) NOT NULL,
	 CONSTRAINT TB_READ_DUTY_TGT_CK1 CHECK (STGT_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_READ_DUTY_TGT_PK PRIMARY KEY (IDUTY_NO, STGT_TY, STGT_ID) ) ;

-- TABLE TB_READ_DUTY_CHK (필수 열람 확인 — 열람 자동/숙지 버튼 2단계)
CREATE TABLE TB_READ_DUTY_CHK
   (	IDUTY_NO NUMERIC NOT NULL,
	SUSER_ID VARCHAR(50) NOT NULL,
	SUSER_NM VARCHAR(50),
	SORGNZT_ID VARCHAR(50),
	SREAD_DT VARCHAR(14),
	SCONF_DT VARCHAR(14),
	 CONSTRAINT TB_READ_DUTY_CHK_PK PRIMARY KEY (IDUTY_NO, SUSER_ID) ) ;

-- TABLE TB_REL_DMN_LNK
CREATE TABLE TB_REL_DMN_LNK
   (	IRDLNK_NO NUMERIC NOT NULL,
	SFLAG VARCHAR(255) NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	SFULL_ITEM VARCHAR(255) NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	ILAW_NO NUMERIC NOT NULL,
	SAWS_LST_YN VARCHAR(255) NOT NULL,
	IRVRSN_NO VARCHAR(255) NOT NULL,
	SFILE_ITEM NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_REL_DMN_LNK ADD CONSTRAINT PK_TB_REL_DMN_LNK PRIMARY KEY (IRDLNK_NO) ;

-- TABLE TB_REL_EXCL_LNK
CREATE TABLE TB_REL_EXCL_LNK
   (	IRELNK_NO NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255),
	SFLAG VARCHAR(255) NOT NULL,
	SGUBUN_ID VARCHAR(255),
	ICATE_NO NUMERIC,
	ILAW_ID NUMERIC,
	SINS_DT VARCHAR(255) NOT NULL,
	IEXCL_LAW_ID NUMERIC NOT NULL
   ) ;
ALTER TABLE TB_REL_EXCL_LNK ADD CONSTRAINT PK_TB_REL_EXCL_LNK PRIMARY KEY (IRELNK_NO) ;

-- TABLE TB_REL_FILE
CREATE TABLE TB_REL_FILE
   (	IRFILE_NO NUMERIC NOT NULL,
	IATT_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SCATE VARCHAR(255) NOT NULL,
	IRVRSN_NO NUMERIC NOT NULL,
	SDEL_YN VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	SVIEW_YN VARCHAR(255) DEFAULT 'N',
	SVIEW_CMPLT_YN VARCHAR(255) DEFAULT 'N'
   ) ;
ALTER TABLE TB_REL_FILE ADD CONSTRAINT PK_TB_REL_FILE PRIMARY KEY (IRFILE_NO) ;

-- TABLE TB_REL_HTML
CREATE TABLE TB_REL_HTML
   (	IRHTML_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SHTML TEXT,
	SINS_DT VARCHAR(255) NOT NULL,
	IRVRSN_NO NUMERIC NOT NULL,
	SDEL_YN VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_REL_HTML ADD CONSTRAINT PK_TB_REL_HTML PRIMARY KEY (IRHTML_NO) ;

-- TABLE TB_REL_IMG
CREATE TABLE TB_REL_IMG
   (	IRIMG_NO NUMERIC NOT NULL,
	IATT_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	IRVRSN_NO NUMERIC NOT NULL,
	SDEL_YN VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_REL_IMG ADD CONSTRAINT PK_TB_REL_IMG PRIMARY KEY (IRIMG_NO) ;

-- TABLE TB_REL_LNK
CREATE TABLE TB_REL_LNK
   (	IRLINK_NO NUMERIC NOT NULL,
	SCATE VARCHAR(255) NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SURL VARCHAR(255) NOT NULL,
	IREF_NO NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	IRVRSN_NO NUMERIC NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_REL_LNK ADD CONSTRAINT PK_TB_REL_LNK PRIMARY KEY (IRLINK_NO) ;

-- TABLE TB_REL_ORGN
CREATE TABLE TB_REL_ORGN
   (	IRORGN_NO NUMERIC NOT NULL,
	IATT_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	IRVRSN_NO NUMERIC NOT NULL,
	SDEL_YN VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_REL_ORGN ADD CONSTRAINT PK_TB_REL_ORGN PRIMARY KEY (IRORGN_NO) ;

-- TABLE TB_REL_VRSN
CREATE TABLE TB_REL_VRSN
   (	IRVRSN_NO NUMERIC NOT NULL,
	IPROM_NO NUMERIC NOT NULL,
	ICTNS_ID NUMERIC NOT NULL,
	SVRSN_YN VARCHAR(255) NOT NULL,
	STABLE VARCHAR(255) NOT NULL,
	SFLAG VARCHAR(255) NOT NULL,
	SFULL_ITEM VARCHAR(255) NOT NULL,
	STITLE VARCHAR(4000) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	SURL VARCHAR(255),
	IRVCATE_NO NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	IRVCATE_NM VARCHAR(100) DEFAULT '미선택',
	IRVCATE_ODR NUMERIC(10,0) DEFAULT 0
   ) ;
ALTER TABLE TB_REL_VRSN ADD CONSTRAINT PK_TB_REL_VRSN PRIMARY KEY (IRVRSN_NO) ;

-- TABLE TB_REL_VRSN_CATE
CREATE TABLE TB_REL_VRSN_CATE
   (	IRVCATE_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	ISEQ NUMERIC NOT NULL,
	SHIDE_DT VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	STEMP VARCHAR(255),
	SORGNDOWN_YN VARCHAR(255) DEFAULT 'Y'
   ) ;
ALTER TABLE TB_REL_VRSN_CATE ADD CONSTRAINT PK_TB_REL_VRSN_CATE PRIMARY KEY (IRVCATE_NO) ;

-- TABLE TB_REL_WORD
CREATE TABLE TB_REL_WORD
   (	IRWORD_NO NUMERIC NOT NULL,
	IATT_NO NUMERIC NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SHTML TEXT,
	SINS_DT VARCHAR(255) NOT NULL,
	IRVRSN_NO NUMERIC NOT NULL,
	STYPE VARCHAR(255),
	SDEL_YN VARCHAR(255) NOT NULL,
	SSEARCH_TEXT TEXT,
	SSYS_ID VARCHAR(255),
	SHTML_PATH VARCHAR(255),
	SSEARCH_TEXT_PATH VARCHAR(255),
	SCLOB_FILE_YN VARCHAR(255) DEFAULT 'N',
	SPATH VARCHAR(255)
   ) ;

-- TABLE TB_SRC_STORED
CREATE TABLE TB_SRC_STORED
   (	ISSTOR_NO NUMERIC NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL,
	SREF_ITEM VARCHAR(255) NOT NULL,
	SGUBUN VARCHAR(255) NOT NULL,
	SFLAG VARCHAR(255) NOT NULL,
	STITLE VARCHAR(255) NOT NULL,
	SFULL_TITLE VARCHAR(4000) NOT NULL,
	SCONTENTS TEXT,
	SLAW_URL VARCHAR(500) NOT NULL,
	SCONTENTS_URL VARCHAR(500) NOT NULL,
	SPOPUP_YN VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	ILAW_ID NUMERIC NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_SRC_STORED ADD CONSTRAINT PK_TB_SRC_STORED PRIMARY KEY (ISSTOR_NO) ;

-- TABLE TB_STATS_BBS_VIEW (2026-07-20 신설 — 게시판 조회통계 적재)
CREATE TABLE TB_STATS_BBS_VIEW
   (	ISBVIEW_NO NUMERIC NOT NULL,
	SBBS_ID VARCHAR(30) NOT NULL,
	INTT_ID NUMERIC NOT NULL,
	ICNT NUMERIC NOT NULL,
	SINS_DT VARCHAR(10) NOT NULL
   ) ;
ALTER TABLE TB_STATS_BBS_VIEW ADD CONSTRAINT PK_TB_STATS_BBS_VIEW PRIMARY KEY (ISBVIEW_NO) ;

-- TABLE TB_STATS_FT_VIEW
CREATE TABLE TB_STATS_FT_VIEW
   (	SGUBUN_ID VARCHAR(255) NOT NULL,
	ISFVIEW_NO NUMERIC NOT NULL,
	ICNT NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	ILAW_ID NUMERIC NOT NULL
   ) ;
ALTER TABLE TB_STATS_FT_VIEW ADD CONSTRAINT PK_TB_STATS_FT_VIEW PRIMARY KEY (ISFVIEW_NO) ;

-- TABLE TB_STATS_KWD
CREATE TABLE TB_STATS_KWD
   (	ISKWD_NO NUMERIC NOT NULL,
	SKWD VARCHAR(255) NOT NULL,
	ICNT NUMERIC NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255)
   ) ;
ALTER TABLE TB_STATS_KWD ADD CONSTRAINT PK_TB_STATS_KWD PRIMARY KEY (ISKWD_NO) ;

-- VIEW COMVNUSERMASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID) AS 
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR' AS USER_SE, ORGNZT_ID
    FROM COMTNGNRLMBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
    FROM COMTNEMPLYRINFO;

--------------------------------------------------------------------------------
-- 합성 테이블 1종 — 레거시 운영 DB 에 없으나 라이브 필수 경로가 참조.
-- (죽은 흐름용 방어 테이블 6종은 2026-07-10 사용자 확정으로 제외 — 미생성 목록은 README 참조)
--------------------------------------------------------------------------------

-- COMTHEMPLYRINFOCHANGEDTLS (합성 근거: mapper\com\uss\umt\EgovUserManage_SQL_oracle.xml insertUserHistory —
--   사용자정보 수정 이력. 레거시 COMTN- 변형 구조 1:1, 매퍼가 쓰는 COMTH- 이름으로 생성)
CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID           VARCHAR(20)   NOT NULL,
  CHANGE_DE           CHAR(20)       NOT NULL,
  ORGNZT_ID           CHAR(20),
  GROUP_ID            CHAR(20),
  EMPL_NO             VARCHAR(20),
  SEXDSTN_CODE        CHAR(1),
  BRTHDY              CHAR(20),
  FXNUM               VARCHAR(20),
  HOUSE_ADRES         VARCHAR(100),
  HOUSE_END_TELNO     VARCHAR(4),
  AREA_NO             VARCHAR(4),
  DETAIL_ADRES        VARCHAR(100),
  ZIP                 VARCHAR(6),
  OFFM_TELNO          VARCHAR(20),
  MBTLNUM             VARCHAR(20),
  EMAIL_ADRES         VARCHAR(50),
  HOUSE_MIDDLE_TELNO  VARCHAR(4),
  PSTINST_CODE        CHAR(8),
  EMPLYR_STTUS_CODE   CHAR(1),
  ESNTL_ID            CHAR(20),
  CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE)
);

-- 브랜드설정 — 로고(텍스트/이미지)·파비콘. 고객사별 리브랜딩 지점, BRAND_ID='S' 단일 행 (2026-07-31)
CREATE TABLE COM_BRAND (
  BRAND_ID              CHAR(1)       NOT NULL,
  LOGO_TY_CODE          VARCHAR(10)  DEFAULT 'TEXT' NOT NULL,
  LOGO_TEXT             VARCHAR(300),
  LOGO_ATCH_FILE_ID     CHAR(20),
  FAVICON_ATCH_FILE_ID  CHAR(20),
  LAST_UPDUSR_ID        VARCHAR(20),
  LAST_UPDT_PNTTM       TIMESTAMP,
  CONSTRAINT PK_COM_BRAND PRIMARY KEY (BRAND_ID)
);
--------------------------------------------------------------------------------
-- Oracle 호환 DUAL (1행) — 공유 인가 SQL(context-security.xml 쌍둥이)이
-- FROM DUAL 을 대량 사용하므로 PG 에도 동명 테이블을 둔다(고전 이식 심).
-- 매퍼(*_SQL_postgres.xml)는 FROM DUAL 을 이미 제거했으므로 이 테이블 미의존.
--------------------------------------------------------------------------------
CREATE TABLE DUAL (DUMMY VARCHAR(1));
INSERT INTO DUAL VALUES ('X');
COMMENT ON TABLE DUAL IS 'Oracle 호환 DUAL(1행) — 공유 인가 SQL(context-security)의 FROM DUAL 지원용';
COMMENT ON COLUMN DUAL.DUMMY IS '더미(X 1행 고정)';
