--------------------------------------------------------------------------------
-- 13_triggers_functions.sql — 트리거 7종 + 함수 1종 (PostgreSQL 판)
-- RegNex(규정 단독, PostgreSQL) 클린 설치 세트. 실행 계정: regnex.
--
-- Oracle 판(newdb/13_triggers_functions.sql)에서 이식. 변환 요점:
--   · PG 트리거는 본문을 별도 트리거 함수(RETURNS TRIGGER)로 분리 — *_FN() 8쌍 구조
--   · `:OLD.COL` → `OLD.COL`, BEFORE DELETE 행 트리거는 RETURN OLD 필수(NULL 이면 삭제 취소)
--   · 함수의 `START WITH ... CONNECT BY PRIOR` 계층질의 → `WITH RECURSIVE` 재귀 CTE
--   · `EXCEPTION WHEN NO_DATA_FOUND` → 집계(MIN) + COALESCE 로 대체(예외 핸들러 불요)
--   · 식별자 비따옴표(소문자 폴딩) — 매퍼 SQL 의 비따옴표 호출과 일치
--
-- [트리거 이식 기준 — Oracle 판과 동일]
--  · 이식 7종: 규정 삭제(deleteProm)가 앱 코드 대신 트리거 cascade 에 명시 의존하는 체인
--      TRG_DEL_PROM → TRG_DEL_PROV_HTML / TRG_DEL_PROV_VRSN / TRG_DEL_REL_VRSN
--                   → TRG_DEL_REL_FILE / TRG_DEL_REL_IMG  (+ 별표 삭제 TRG_DEL_DOCU)
--------------------------------------------------------------------------------

-- ★규정 회차 삭제의 핵심 cascade (앱 PromServiceImpl.deleteProm 이 명시 의존)
CREATE OR REPLACE FUNCTION TRG_DEL_PROM_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_PROV_VRSN WHERE IPROM_NO = OLD.IPROM_NO;
    DELETE FROM TB_PROV_HTML WHERE IPROM_NO = OLD.IPROM_NO;
    DELETE FROM TB_DOCU WHERE IPROM_NO = OLD.IPROM_NO;
    DELETE FROM TB_SRC_STORED WHERE ILAW_ID = OLD.ILAW_ID;
    DELETE FROM TB_REL_VRSN WHERE IPROM_NO = OLD.IPROM_NO;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_PROM ON TB_PROM;
CREATE TRIGGER TRG_DEL_PROM
BEFORE DELETE ON TB_PROM
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_PROM_FN();

-- 별표/별지서식 삭제 시 개별 첨부 정리 (앱이 명시 의존)
--   관련자료 마스터를 지우면 TRG_DEL_REL_VRSN → TB_REL_FILE → TRG_DEL_REL_FILE → TB_ATTACH 까지 연쇄된다.
CREATE OR REPLACE FUNCTION TRG_DEL_DOCU_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_REL_VRSN
    WHERE IPROM_NO = OLD.IPROM_NO
    AND SFLAG = 'DOCUMENT'
    AND SFULL_ITEM = OLD.SITEM;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_DOCU ON TB_DOCU;
CREATE TRIGGER TRG_DEL_DOCU
BEFORE DELETE ON TB_DOCU
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_DOCU_FN();

-- 전문HTML 삭제 시 관련자료 앵커 + 첨부 정리 (앱이 명시 의존)
CREATE OR REPLACE FUNCTION TRG_DEL_PROV_HTML_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_REL_VRSN
    WHERE IPROM_NO = OLD.IPROM_NO
    AND SFLAG = 'PROVISION'
    AND SFULL_ITEM = OLD.SITEM;

    DELETE FROM TB_ATTACH
    WHERE IREF_NO = OLD.IPHTML_NO
    AND SREF_TABLE = 'TB_PROV_HTML';
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_PROV_HTML ON TB_PROV_HTML;
CREATE TRIGGER TRG_DEL_PROV_HTML
BEFORE DELETE ON TB_PROV_HTML
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_PROV_HTML_FN();

-- 조문 삭제(저장 시 delete+reinsert 패턴 포함) 시 관련자료 앵커 정리
CREATE OR REPLACE FUNCTION TRG_DEL_PROV_VRSN_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_REL_VRSN
    WHERE IPROM_NO = OLD.IPROM_NO
    AND SFLAG = 'PROVISION'
    AND SFULL_ITEM = OLD.SITEM;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_PROV_VRSN ON TB_PROV_VRSN;
CREATE TRIGGER TRG_DEL_PROV_VRSN
BEFORE DELETE ON TB_PROV_VRSN
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_PROV_VRSN_FN();

-- 관련자료 마스터 삭제 시 자식 6종 정리 (규정삭제 cascade 의 중간 고리)
CREATE OR REPLACE FUNCTION TRG_DEL_REL_VRSN_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_REL_HTML WHERE IRVRSN_NO = OLD.IRVRSN_NO;
    DELETE FROM TB_REL_FILE WHERE IRVRSN_NO = OLD.IRVRSN_NO;
    DELETE FROM TB_REL_IMG WHERE IRVRSN_NO = OLD.IRVRSN_NO;
    DELETE FROM TB_REL_LNK WHERE IRVRSN_NO = OLD.IRVRSN_NO;
    DELETE FROM TB_REL_DMN_LNK WHERE IRVRSN_NO = OLD.IRVRSN_NO;
    DELETE FROM TB_REL_WORD WHERE IRVRSN_NO = OLD.IRVRSN_NO;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_REL_VRSN ON TB_REL_VRSN;
CREATE TRIGGER TRG_DEL_REL_VRSN
BEFORE DELETE ON TB_REL_VRSN
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_REL_VRSN_FN();

-- 관련파일 삭제 시 첨부 정리 (원본에서 TB_REL_REF 라인 제거)
CREATE OR REPLACE FUNCTION TRG_DEL_REL_FILE_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_ATTACH WHERE SREF_TABLE = 'TB_REL_FILE' AND IATT_NO = OLD.IATT_NO;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_REL_FILE ON TB_REL_FILE;
CREATE TRIGGER TRG_DEL_REL_FILE
BEFORE DELETE ON TB_REL_FILE
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_REL_FILE_FN();

-- 관련이미지 삭제 시 첨부 정리 (원본에서 TB_REL_REF 라인 제거)
CREATE OR REPLACE FUNCTION TRG_DEL_REL_IMG_FN() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM TB_ATTACH WHERE SREF_TABLE = 'TB_REL_IMG' AND IATT_NO = OLD.IATT_NO;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_DEL_REL_IMG ON TB_REL_IMG;
CREATE TRIGGER TRG_DEL_REL_IMG
BEFORE DELETE ON TB_REL_IMG
FOR EACH ROW EXECUTE FUNCTION TRG_DEL_REL_IMG_FN();

--------------------------------------------------------------------------------
-- 함수 GET_FULL_NAME_BY_CATE_NO — 분류 풀네임 "구분명>상위분류>...>자기분류"
--
-- Oracle 판의 `START WITH ICATE_NO = V_CATE_NO CONNECT BY PRIOR IREF = ICATE_NO`
-- (자기 → 상위로 거슬러 오르는 역방향 계층질의)를 재귀 CTE 로 옮겼다.
-- ILEVEL 오름차순 연결 순서는 Oracle 판과 동일(최상위부터 자기 자신까지).
-- V_DB_SUFFIX 는 호출부 시그니처 호환을 위해 유지(전 호출부가 'NONE' 전달, 분기 없음).
--   호출부: Prom_SQL_postgres.xml 9곳 / Cate_SQL_postgres.xml / RelExclLnk_SQL_postgres.xml
-- NO_DATA_FOUND 핸들러는 집계(MIN)+COALESCE 로 대체 — 매칭 0행이어도 빈 문자열.
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION GET_FULL_NAME_BY_CATE_NO(
    V_DB_SUFFIX     VARCHAR DEFAULT 'NONE',
    V_CATE_NO       NUMERIC DEFAULT NULL)
RETURNS VARCHAR AS $$
DECLARE
    V_NAME VARCHAR(255) := '';
    V_PATH VARCHAR(255) := '';
BEGIN
    -- 구분명(ccm 'SGUBUN') — 없으면 빈 문자열
    SELECT COALESCE(MIN(D.CODE_NM), '')
      INTO V_NAME
      FROM COMTCCMMNDETAILCODE D
     WHERE D.CODE_ID = 'SGUBUN'
       AND D.CODE = (SELECT SGUBUN_ID FROM TB_CATE WHERE ICATE_NO = V_CATE_NO);

    -- 자기 → 상위로 거슬러 올라간 뒤 ILEVEL 오름차순으로 '>' 연결
    WITH RECURSIVE ANC (ICATE_NO, IREF, SNAME, ILEVEL) AS (
        SELECT ICATE_NO, IREF, SNAME, ILEVEL
          FROM TB_CATE
         WHERE ICATE_NO = V_CATE_NO
        UNION ALL
        SELECT C.ICATE_NO, C.IREF, C.SNAME, C.ILEVEL
          FROM TB_CATE C
          JOIN ANC A ON C.ICATE_NO = A.IREF
    )
    SELECT COALESCE(STRING_AGG('>' || SNAME, '' ORDER BY ILEVEL), '')
      INTO V_PATH
      FROM (SELECT DISTINCT SNAME, ILEVEL FROM ANC) T;

    RETURN V_NAME || COALESCE(V_PATH, '');
END;
$$ LANGUAGE plpgsql STABLE;
