--------------------------------------------------------------------------------
-- 23_seed_org_accounts.sql — 예시 부서 2 + 예시 계정 3(관리자/승인자/사용자)
-- RegNex(PostgreSQL) 클린 설치 세트. 실행 계정: regnex.
--
-- ★전부 예시 데이터 (사용자 확정 2026-07-10) — 운영 전 반드시 비밀번호 변경.
--   초기 비밀번호: sysmen=asdqwe123! (기존 관리자 계정 승계, 2026-07-10 사용자 변경) / approver·user=rlms1234!
--   해시 = EgovFileScrty.encryptPassword(평문, 로그인ID) — SHA-256, ★솔트=로그인ID(ID 바꾸면 해시 재생성 필수).
--   비번 변경 도구: tools/encpw (java EncPw <평문> <로그인ID>)
--
-- 계정 구성(사용자 2분할 정책):
--   sysmen   → COMTNEMPLYRINFO (USR축, 로그인 후 관리자 대시보드) + ROLE_ADMIN
--   approver → COMTNEMPLYRINFO (USR축, 관리자 대시보드)          + ROLE_APPROVER
--   user     → COMTNGNRLMBER  (GNR축, 로그인 후 사용자 홈)        + ROLE_USER
--   역할 = COMTNEMPLYRSCRTYESTBS 사용자당 1행 (PK=SCRTY_DTRMN_TRGET_ID=ESNTL_ID)
--------------------------------------------------------------------------------


-- 조직 트리 (2026-07-27) — 기본 최상위 본사·지사1·지사2 + 예시 부서 2건(본사 아래).
-- ORGNZT_ID 는 부서관리 화면 채번 컨벤션 'ORGNZT_'+13자리. 26_seed_idgn 의 COMTECOPSEQ ORGNZT_ID NEXT_ID(11)는 5 초과 유지.
INSERT INTO COMTNORGNZTINFO (ORGNZT_ID, ORGNZT_NM, ORGNZT_DC, UPPER_ORGNZT_ID, ORDR)
VALUES ('ORGNZT_0000000000003', '본사', '기본 최상위 조직', NULL, 1);
INSERT INTO COMTNORGNZTINFO (ORGNZT_ID, ORGNZT_NM, ORGNZT_DC, UPPER_ORGNZT_ID, ORDR)
VALUES ('ORGNZT_0000000000004', '지사1', '기본 최상위 조직', NULL, 2);
INSERT INTO COMTNORGNZTINFO (ORGNZT_ID, ORGNZT_NM, ORGNZT_DC, UPPER_ORGNZT_ID, ORDR)
VALUES ('ORGNZT_0000000000005', '지사2', '기본 최상위 조직', NULL, 3);
INSERT INTO COMTNORGNZTINFO (ORGNZT_ID, ORGNZT_NM, ORGNZT_DC, UPPER_ORGNZT_ID, ORDR)
VALUES ('ORGNZT_0000000000001', '경영지원부', '예시 부서 1', 'ORGNZT_0000000000003', 1);
INSERT INTO COMTNORGNZTINFO (ORGNZT_ID, ORGNZT_NM, ORGNZT_DC, UPPER_ORGNZT_ID, ORDR)
VALUES ('ORGNZT_0000000000002', '법무팀', '예시 부서 2', 'ORGNZT_0000000000003', 2);

-- 관리자 (sysmen / asdqwe123!)
INSERT INTO COMTNEMPLYRINFO (EMPLYR_ID, ORGNZT_ID, USER_NM, PASSWORD, EMPL_NO,
    SEXDSTN_CODE, HOUSE_ADRES, PASSWORD_HINT, PASSWORD_CNSR, HOUSE_END_TELNO,
    AREA_NO, ZIP, HOUSE_MIDDLE_TELNO, EMAIL_ADRES, OFCPS_NM, GROUP_ID,
    PSTINST_CODE, EMPLYR_STTUS_CODE, ESNTL_ID, SBSCRB_DE, CHG_PWD_LAST_PNTTM)
VALUES ('sysmen', 'ORGNZT_0000000000001', '관리자',
    'V0iV5Z3c2QF2qEdLVRZMJKiSZgzqppyWsqEwPEy14dU=',
    NULL, 'M', '-', 'P01', '-', '0000', '02', '000000', '0000',
    NULL, '시스템관리자', 'GROUP_00000000000000', '00000001', 'P',
    'USRCNFRM_00000000000', LOCALTIMESTAMP, LOCALTIMESTAMP);

-- 승인자 (approver / rlms1234!)
INSERT INTO COMTNEMPLYRINFO (EMPLYR_ID, ORGNZT_ID, USER_NM, PASSWORD, EMPL_NO,
    SEXDSTN_CODE, HOUSE_ADRES, PASSWORD_HINT, PASSWORD_CNSR, HOUSE_END_TELNO,
    AREA_NO, ZIP, HOUSE_MIDDLE_TELNO, EMAIL_ADRES, OFCPS_NM, GROUP_ID,
    PSTINST_CODE, EMPLYR_STTUS_CODE, ESNTL_ID, SBSCRB_DE, CHG_PWD_LAST_PNTTM)
VALUES ('approver', 'ORGNZT_0000000000002', '승인자',
    'srkcpw1rmOT0bG8VYTG7QRaG6I+sG8/cAxcFw/ZSDkw=',
    NULL, 'M', '-', 'P01', '-', '0000', '02', '000000', '0000',
    NULL, '승인자', 'GROUP_00000000000000', '00000001', 'P',
    'USRCNFRM_00000000001', LOCALTIMESTAMP, LOCALTIMESTAMP);

-- 일반 사용자 (user / rlms1234!)
INSERT INTO COMTNGNRLMBER (MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, AREA_NO,
    MBER_STTUS, END_TELNO, MBTLNUM, MIDDLE_TELNO, MBER_EMAIL_ADRES,
    SBSCRB_DE, SEXDSTN_CODE, ESNTL_ID, ORGNZT_ID, CHG_PWD_LAST_PNTTM)
VALUES ('user', 'KHhth+7NvZhV21Ins7/Njl/tNly91OiHf+eB/AMeZFA=', '사용자',
    '000000', '-', '02', 'P', '0000', '010-0000-0000', '0000',
    NULL, LOCALTIMESTAMP, 'M', 'USRCNFRM_00000000002', 'ORGNZT_0000000000002', LOCALTIMESTAMP);

-- 역할 부여 (사용자당 1행 — PK 단독)
INSERT INTO COMTNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE)
VALUES ('USRCNFRM_00000000000', 'USR03', 'ROLE_ADMIN');
INSERT INTO COMTNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE)
VALUES ('USRCNFRM_00000000001', 'USR03', 'ROLE_APPROVER');
INSERT INTO COMTNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE)
VALUES ('USRCNFRM_00000000002', 'USR01', 'ROLE_USER');

-- 로그인 정책 — 중복로그인 차단 유지(라이브 정책 f928640: DPLCT_PERM_AT='N').
-- IP 제한은 미사용(LMTT_AT='N' — IP_INFO 는 NOT NULL 이라 형식값).
INSERT INTO COMTNLOGINPOLICY (EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM)
VALUES ('sysmen', '127.0.0.1', 'N', 'N', 'USRCNFRM_00000000000', LOCALTIMESTAMP);
INSERT INTO COMTNLOGINPOLICY (EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM)
VALUES ('approver', '127.0.0.1', 'N', 'N', 'USRCNFRM_00000000000', LOCALTIMESTAMP);
INSERT INTO COMTNLOGINPOLICY (EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM)
VALUES ('user', '127.0.0.1', 'N', 'N', 'USRCNFRM_00000000000', LOCALTIMESTAMP);

COMMIT;