-- ============================================================================
-- rlms_law_install.sql — 송무(law) 옵션 모듈 설치 ① DDL·채번·코드·시드
--   (LAW_MODULE_DESIGN.md §4·§5, 2026-07-21 생성)
--
--   구성: 1) LAW_* 18테이블 DDL + 코멘트 전수 + 인덱스
--         2) COMTECOPSEQ 채번 17행
--         3) ccm 공통코드 15그룹(레거시 tbetia09/10 — SB_CD 보존)
--         4) LAW_COURT 대표 시드 22행(레거시 tbetia31 발췌 — 부족분은 운영 등록)
--         5) LAW_CALC_RATE 현행 요율 1세트(APPLY_DT=20260101)
--
--   실행: RLMS 계정. 재실행 시 CREATE 는 ORA-00955(무시), 시드는 NOT EXISTS 스킵.
--   ⚠️ 옵션 메뉴·권한은 rlms_law_menu.sql 별도(§9 설치 순서: regroup 후 install, menu, 재기동).
-- ============================================================================

-- ============================================================
-- 1) 테이블 DDL — 공통 규약(§4.1):
--    날짜 VARCHAR(8) 'YYYYMMDD', 시각 VARCHAR(14) 'YYYYMMDDHH24MISS',
--    금액 NUMERIC(19), 코드 VARCHAR(10), 감사 4종(REG/UPD_USER_ID·DT).
-- ============================================================

-- ── 1.1 LAW_SUIT 사건 마스터 (심급 단위 1행) ← tbetia11 ──
CREATE TABLE LAW_SUIT (
    SUIT_ID           BIGINT      NOT NULL,
    FIRST_SUIT_ID     BIGINT,
    CASE_KIND_CD      VARCHAR(10),
    INSTANCE_CD       VARCHAR(10),
    COURT_ID          BIGINT,
    COURT_NM          VARCHAR(150),
    CASE_YEAR         VARCHAR(4),
    CASE_SIGN_CD      VARCHAR(10),
    CASE_SERIAL       VARCHAR(20),
    CASE_NO           VARCHAR(100),
    CASE_NM_CD        VARCHAR(10),
    CASE_NM           VARCHAR(200),
    CIVIL_CASE_CD     VARCHAR(10),
    ITPT_KIND_CD      VARCHAR(10),
    SUIT_AMT          NUMERIC(19),
    OFFICE_RECEIPT_DT VARCHAR(8),
    FR_DT             VARCHAR(8),
    STC_DT            VARCHAR(8),
    DCSN_DT           VARCHAR(8),
    RSLT_KIND_CD      VARCHAR(10),
    RSLT_KIND_NM      VARCHAR(200),
    WIN_AMT           NUMERIC(19),
    LOSE_AMT          NUMERIC(19),
    LOSS_CAUSE_CD     VARCHAR(10),
    MERGE_CASE        VARCHAR(500),
    COST_FIX_DT       VARCHAR(8),
    COST_FIX_AMT      NUMERIC(19),
    COST_RCV_AMT      NUMERIC(19),
    RETAINER_AMT      NUMERIC(19),
    SUCCESS_AMT       NUMERIC(19),
    SPECIAL_DESC      VARCHAR(4000),
    DEL_YN            CHAR(1) DEFAULT 'N' NOT NULL,
    REG_USER_ID       VARCHAR(20),
    REG_DT            VARCHAR(14),
    UPD_USER_ID       VARCHAR(20),
    UPD_DT            VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT PRIMARY KEY (SUIT_ID)
);
COMMENT ON TABLE  LAW_SUIT IS '송무 사건 마스터 — 심급 단위 1행, 사건군 그룹핑은 FIRST_SUIT_ID(§4.5) ← tbetia11';
COMMENT ON COLUMN LAW_SUIT.SUIT_ID           IS '사건 ID (채번 LAW_SUIT_ID) ← tbetia11.LAWSUIT_SEQ';
COMMENT ON COLUMN LAW_SUIT.FIRST_SUIT_ID     IS '사건군 최초 심급 사건 ID — 최초심=자기 ID, 상급심=원심 값 승계(레거시 tbetia16/33 재귀 연결 폐지)';
COMMENT ON COLUMN LAW_SUIT.CASE_KIND_CD      IS '소송구분(LAW_CASE_KIND) — 통계 4축 S001민사/S002행정/S012국가/S009심판 ← tbetia11.LAWSUIT_CASE_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.INSTANCE_CD       IS '심급(LAW_INSTANCE) — 심급별 통계 3축 S001/S002/S004 ← tbetia11.LAWSUIT_REL_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.COURT_ID          IS '법원 ID (LAW_COURT FK, 직접입력 시 NULL) ← tbetia11.COURT_SEQ';
COMMENT ON COLUMN LAW_SUIT.COURT_NM          IS '법원명 (표시용 — 선택 시 LAW_COURT.COURT_NM 복사, 직접입력 허용) ← tbetia11.COURT_NM_IN';
COMMENT ON COLUMN LAW_SUIT.CASE_YEAR         IS '사건번호 연도 (YYYY) ← tbetia11.LAWSUIT_MGMT_YYYY';
COMMENT ON COLUMN LAW_SUIT.CASE_SIGN_CD      IS '사건부호(LAW_CASE_SIGN — 대법원 사건부호) ← tbetia11.LAWSUIT_MGMT_SIGN';
COMMENT ON COLUMN LAW_SUIT.CASE_SERIAL       IS '사건번호 일련 ← tbetia11.LAWSUIT_MGMT_ISSUE_NO';
COMMENT ON COLUMN LAW_SUIT.CASE_NO           IS '사건번호 표시용 결합 (예: 2026가합1234) ← tbetia11.LAWSUIT_CASE_NO';
COMMENT ON COLUMN LAW_SUIT.CASE_NM_CD        IS '사건명 코드(LAW_CASE_NM, S999=직접입력) ← tbetia11.LAWSUIT_CASE_NM_CD';
COMMENT ON COLUMN LAW_SUIT.CASE_NM           IS '사건명 (코드 선택 시 명칭 복사, 직접입력 허용) ← tbetia11.CASE_NM_IN';
COMMENT ON COLUMN LAW_SUIT.CIVIL_CASE_CD     IS '사건유형(LAW_CIVIL_CASE) ← tbetia11.CIVIL_CASE_CD';
COMMENT ON COLUMN LAW_SUIT.ITPT_KIND_CD      IS '제·피소구분(LAW_ITPT_KIND) ← tbetia11.LAWSUIT_ITPT_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.SUIT_AMT          IS '소가(소송가액, 원) ← tbetia11.LAWSUIT_APLY_AMT';
COMMENT ON COLUMN LAW_SUIT.OFFICE_RECEIPT_DT IS '행정청 접수일 (YYYYMMDD) ← tbetia11.OFFICE_RECEIPT_DT';
COMMENT ON COLUMN LAW_SUIT.FR_DT             IS '소제기일 (YYYYMMDD) ← tbetia11.LAWSUIT_FR_DT';
COMMENT ON COLUMN LAW_SUIT.STC_DT            IS '최종 선고일 (YYYYMMDD) ← tbetia11.LAWSUIT_STC_DT';
COMMENT ON COLUMN LAW_SUIT.DCSN_DT           IS '확정일 (YYYYMMDD) ← tbetia11.LAWSUIT_DCSN_DT';
COMMENT ON COLUMN LAW_SUIT.RSLT_KIND_CD      IS '소송결과(LAW_RESULT) — 승소그룹 S002/S003/S005/S006/S008/S997, 패소그룹 S004/S100/S101/S102/S998 ← tbetia11.LAWSUIT_RSLT_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.RSLT_KIND_NM      IS '소송결과 직접입력 명칭 ← tbetia11.LAWSUIT_RSLT_KIND_NM';
COMMENT ON COLUMN LAW_SUIT.WIN_AMT           IS '승소금액(원) ← tbetia11.LAWSUIT_DECS_AMT(승패소 단일컬럼의 분해)';
COMMENT ON COLUMN LAW_SUIT.LOSE_AMT          IS '패소금액(원) ← tbetia11.LAWSUIT_DECS_AMT(승패소 단일컬럼의 분해)';
COMMENT ON COLUMN LAW_SUIT.LOSS_CAUSE_CD     IS '패소원인(LAW_LOSS_CAUSE) ← tbetia11.LOSS_CAUSE_CD';
COMMENT ON COLUMN LAW_SUIT.MERGE_CASE        IS '병합사건 텍스트(사건번호 나열)';
COMMENT ON COLUMN LAW_SUIT.COST_FIX_DT       IS '소송비용 확정결정일 (YYYYMMDD) ← tbetia11.LAWSUIT_FEE_DECISION_DT';
COMMENT ON COLUMN LAW_SUIT.COST_FIX_AMT      IS '소송비용 확정액(원) ← tbetia11.FEE_DCSN_AMT';
COMMENT ON COLUMN LAW_SUIT.COST_RCV_AMT      IS '소송비용 회수액(원) ← tbetia11.FEE_RETR_AMT';
COMMENT ON COLUMN LAW_SUIT.RETAINER_AMT      IS '착수금(원, 예비 — 선임 보수관리는 비범위) ← tbetia11.RETAINING_FEE';
COMMENT ON COLUMN LAW_SUIT.SUCCESS_AMT       IS '성공보수(원, 예비) ← tbetia11.CONTINGENT_FEE';
COMMENT ON COLUMN LAW_SUIT.SPECIAL_DESC      IS '특이사항 ← tbetia11.LAWSUIT_MGMT_BLBD_CONTN';
COMMENT ON COLUMN LAW_SUIT.DEL_YN            IS '소프트삭제 여부 (Y/N) ← tbetia11.DEL_YN';
COMMENT ON COLUMN LAW_SUIT.REG_USER_ID       IS '등록자 ID (COMTNEMPLYRINFO.EMPLYR_ID)';
COMMENT ON COLUMN LAW_SUIT.REG_DT            IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT.UPD_USER_ID       IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT.UPD_DT            IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_01 ON LAW_SUIT (DEL_YN, CASE_KIND_CD);
CREATE INDEX IX_LAW_SUIT_02 ON LAW_SUIT (FIRST_SUIT_ID);
CREATE INDEX IX_LAW_SUIT_03 ON LAW_SUIT (CASE_NO);
CREATE INDEX IX_LAW_SUIT_04 ON LAW_SUIT (FR_DT);
CREATE INDEX IX_LAW_SUIT_05 ON LAW_SUIT (RSLT_KIND_CD);

-- ── 1.2 LAW_SUIT_PARTY 당사자 ← tbetia14 ──
CREATE TABLE LAW_SUIT_PARTY (
    PARTY_ID    BIGINT    NOT NULL,
    SUIT_ID     BIGINT    NOT NULL,
    PARTY_TYPE  CHAR(1)       NOT NULL,
    PARTY_NM    VARCHAR(200),
    BIRTH       VARCHAR(10),
    JUMIN_ENC   VARCHAR(256),
    AGENT_NM    VARCHAR(100),
    SORT_ORDR   INT DEFAULT 0,
    REG_USER_ID VARCHAR(20),
    REG_DT      VARCHAR(14),
    UPD_USER_ID VARCHAR(20),
    UPD_DT      VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_PARTY PRIMARY KEY (PARTY_ID)
);
COMMENT ON TABLE  LAW_SUIT_PARTY IS '송무 사건 당사자 (원고/피고/보조참가인) ← tbetia14';
COMMENT ON COLUMN LAW_SUIT_PARTY.PARTY_ID    IS '당사자 ID (채번 LAW_PARTY_ID) ← tbetia14.ITPT_SEQ';
COMMENT ON COLUMN LAW_SUIT_PARTY.SUIT_ID     IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_PARTY.PARTY_TYPE  IS '당사자 구분 (P=원고, D=피고, S=보조참가인) ← tbetia14.ACUSR_DFDNT_TYPE';
COMMENT ON COLUMN LAW_SUIT_PARTY.PARTY_NM    IS '성명(법인명) ← tbetia14.ITPT_NM';
COMMENT ON COLUMN LAW_SUIT_PARTY.BIRTH       IS '생년월일 (YYYYMMDD 또는 YYMMDD — 주민번호 입력 시 앞6자리 자동 파생) ← tbetia14.BIRTH';
COMMENT ON COLUMN LAW_SUIT_PARTY.JUMIN_ENC   IS '주민등록번호 양방향 암호문(EgovGeneralCryptoService PBE, 키=Globals.law.cryptoKey, Base64) — 평문 저장·화면 복호 표시 금지, 항상 마스킹(§4.4) ← tbetia14.JUMIN_NO(레거시 평문의 암호화 대체)';
COMMENT ON COLUMN LAW_SUIT_PARTY.AGENT_NM    IS '대리인 성명';
COMMENT ON COLUMN LAW_SUIT_PARTY.SORT_ORDR   IS '표시 순서 (0부터 — 목록 대표자=구분별 최솟값 행)';
COMMENT ON COLUMN LAW_SUIT_PARTY.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_PARTY.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_PARTY.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_PARTY.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_PARTY_01 ON LAW_SUIT_PARTY (SUIT_ID);

-- ── 1.3 LAW_SUIT_STAFF 소송수행자 ← tbetia50 ──
CREATE TABLE LAW_SUIT_STAFF (
    STAFF_ID    BIGINT  NOT NULL,
    SUIT_ID     BIGINT  NOT NULL,
    ORGNZT_ID   CHAR(20),
    STAFF_NM    VARCHAR(100),
    ASSIGN_DT   VARCHAR(8),
    SORT_ORDR   INT DEFAULT 0,
    REG_USER_ID VARCHAR(20),
    REG_DT      VARCHAR(14),
    UPD_USER_ID VARCHAR(20),
    UPD_DT      VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_STAFF PRIMARY KEY (STAFF_ID)
);
COMMENT ON TABLE  LAW_SUIT_STAFF IS '송무 사건 소송수행자 (부서=표준 COMTNORGNZTINFO 연동 — 레거시 김해 부서코드 A33 폐기) ← tbetia50';
COMMENT ON COLUMN LAW_SUIT_STAFF.STAFF_ID    IS '수행자 행 ID (채번 LAW_STAFF_ID) ← tbetia50.SEQ';
COMMENT ON COLUMN LAW_SUIT_STAFF.SUIT_ID     IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_STAFF.ORGNZT_ID   IS '수행 부서 ID (COMTNORGNZTINFO.ORGNZT_ID) ← tbetia50.TEAM_CD(김해 코드의 표준 대체)';
COMMENT ON COLUMN LAW_SUIT_STAFF.STAFF_NM    IS '수행자 성명 ← tbetia50.NAME';
COMMENT ON COLUMN LAW_SUIT_STAFF.ASSIGN_DT   IS '지정일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_STAFF.SORT_ORDR   IS '표시 순서 (0=수행자, 1=보조수행자 — 일정관리 열 규약)';
COMMENT ON COLUMN LAW_SUIT_STAFF.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_STAFF.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_STAFF.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_STAFF.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_STAFF_01 ON LAW_SUIT_STAFF (SUIT_ID);

-- ── 1.4 LAW_SUIT_LAND 사건토지 ← tbetia53(+tbetia11 토지 필드) ──
CREATE TABLE LAW_SUIT_LAND (
    LAND_ID     BIGINT  NOT NULL,
    SUIT_ID     BIGINT  NOT NULL,
    LOCATION    VARCHAR(255),
    JIBUN       VARCHAR(255),
    SORT_ORDR   INT DEFAULT 0,
    REG_USER_ID VARCHAR(20),
    REG_DT      VARCHAR(14),
    UPD_USER_ID VARCHAR(20),
    UPD_DT      VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_LAND PRIMARY KEY (LAND_ID)
);
COMMENT ON TABLE  LAW_SUIT_LAND IS '송무 사건토지 (행 단위 정규화 — 사건지번표시도(Kakao Geocoder) 원천) ← tbetia53 + tbetia11.CASE_LAND_*';
COMMENT ON COLUMN LAW_SUIT_LAND.LAND_ID     IS '토지 행 ID (채번 LAW_LAND_ID)';
COMMENT ON COLUMN LAW_SUIT_LAND.SUIT_ID     IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_LAND.LOCATION    IS '소재지 (지오코딩 주소) ← tbetia11.CASE_LAND_LOCATION';
COMMENT ON COLUMN LAW_SUIT_LAND.JIBUN       IS '지번 ← tbetia11.CASE_LAND_JIBUN';
COMMENT ON COLUMN LAW_SUIT_LAND.SORT_ORDR   IS '표시 순서';
COMMENT ON COLUMN LAW_SUIT_LAND.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_LAND.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_LAND.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_LAND.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_LAND_01 ON LAW_SUIT_LAND (SUIT_ID);

-- ── 1.5 LAW_SUIT_PROG 진행상황·기일 겸용 ← tbetia19 ──
CREATE TABLE LAW_SUIT_PROG (
    PROG_ID      BIGINT  NOT NULL,
    SUIT_ID      BIGINT  NOT NULL,
    PROG_KIND_CD VARCHAR(10),
    DYPR_KIND_CD VARCHAR(10),
    PROG_DT      VARCHAR(8),
    PROG_TM      VARCHAR(4),
    PLACE        VARCHAR(200),
    PROG_DESC    VARCHAR(1000),
    STAT_CD      VARCHAR(10),
    RESULT_DESC  VARCHAR(1000),
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_PROG PRIMARY KEY (PROG_ID)
);
COMMENT ON TABLE  LAW_SUIT_PROG IS '송무 진행상황·기일 겸용 — 소송등록 진행상황 그리드와 일정관리(달력)가 같은 테이블(§7.5) ← tbetia19';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_ID      IS '진행 행 ID (채번 LAW_PROG_ID) ← tbetia19.DYPR_SEQ';
COMMENT ON COLUMN LAW_SUIT_PROG.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_KIND_CD IS '진행종류(LAW_PROG_KIND — 기일/피고제출/원고제출/본부보고) ← tbetia19.DDT_CD';
COMMENT ON COLUMN LAW_SUIT_PROG.DYPR_KIND_CD IS '기일구분(LAW_DYPR_KIND — 진행종류가 기일일 때) ← tbetia19.DYPR_KIND_CD';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_DT      IS '진행(기일)일자 (YYYYMMDD) ← tbetia19.DYPR_DT';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_TM      IS '시각 (HHMM) ← tbetia19.DYPR_TM';
COMMENT ON COLUMN LAW_SUIT_PROG.PLACE        IS '장소 ← tbetia19.DYPR_PLC';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_DESC    IS '내용 ← tbetia19.DYPR_DESC';
COMMENT ON COLUMN LAW_SUIT_PROG.STAT_CD      IS '진행상태(LAW_PROG_STAT — 진행/완료) ← tbetia19.PROG_STAT_CD';
COMMENT ON COLUMN LAW_SUIT_PROG.RESULT_DESC  IS '결과';
COMMENT ON COLUMN LAW_SUIT_PROG.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_PROG.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_PROG.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_PROG.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_PROG_01 ON LAW_SUIT_PROG (SUIT_ID);
CREATE INDEX IX_LAW_SUIT_PROG_02 ON LAW_SUIT_PROG (PROG_DT);

-- ── 1.6 LAW_SUIT_RSLT_HIST 결과변경 이력 ← tbetia34 슬림화 ──
CREATE TABLE LAW_SUIT_RSLT_HIST (
    HIST_ID      BIGINT  NOT NULL,
    SUIT_ID      BIGINT  NOT NULL,
    HIST_SEQ     INT   DEFAULT 1,
    RSLT_KIND_CD VARCHAR(10),
    RSLT_KIND_NM VARCHAR(200),
    END_DT       VARCHAR(8),
    HIST_DESC    VARCHAR(1000),
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_RSLT_HIST PRIMARY KEY (HIST_ID)
);
COMMENT ON TABLE  LAW_SUIT_RSLT_HIST IS '송무 결과변경 이력 — 결과 필드만 이력화(레거시 전체 스냅샷 폐지) ← tbetia34';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.HIST_ID      IS '이력 ID (채번 LAW_RSLT_HIST_ID)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.HIST_SEQ     IS '사건 내 이력 순번 (1부터 증가)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.RSLT_KIND_CD IS '변경 시점 소송결과(LAW_RESULT)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.RSLT_KIND_NM IS '변경 시점 소송결과 직접입력 명칭';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.END_DT       IS '종결일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.HIST_DESC    IS '변경 사유·비고';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_RSLT_HIST_01 ON LAW_SUIT_RSLT_HIST (SUIT_ID);

-- ── 1.7 LAW_SUIT_DOC 소송문서 (표준 첨부 + 승인 워크플로 §7.2) ← tbetia17 ──
CREATE TABLE LAW_SUIT_DOC (
    DOC_ID       BIGINT  NOT NULL,
    SUIT_ID      BIGINT  NOT NULL,
    DOC_KIND_CD  VARCHAR(10),
    DOC_TITL     VARCHAR(200),
    DOC_MEMO     VARCHAR(4000),
    ATCH_FILE_ID CHAR(20),
    APP_STS_CD   VARCHAR(10) DEFAULT 'S001',
    APP_USER_ID  VARCHAR(20),
    APP_USER_NM  VARCHAR(60),
    APP_DT       VARCHAR(14),
    APP_OPINION  VARCHAR(1000),
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_DOC PRIMARY KEY (DOC_ID)
);
COMMENT ON TABLE  LAW_SUIT_DOC IS '송무 소송문서 — 첨부=표준 COMTNFILE/COMTNFILEDETAIL(다중), 등록=승인대기·수정 시 대기 리셋(§7.2) ← tbetia17';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_ID       IS '문서 ID (채번 LAW_DOC_ID) ← tbetia17.DOC_SEQ';
COMMENT ON COLUMN LAW_SUIT_DOC.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_KIND_CD  IS '문서종류(LAW_DOC_KIND — 소장~항고장 21종) ← tbetia17.DOC_KIND_CD';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_TITL     IS '문서 제목 ← tbetia17.DOC_TITL';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_MEMO     IS '메모 ← tbetia17.DOC_MEMO';
COMMENT ON COLUMN LAW_SUIT_DOC.ATCH_FILE_ID IS '첨부파일 ID (표준 COMTNFILE — 다중 파일은 COMTNFILEDETAIL 행들, 레거시 tbetia18 대체)';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_STS_CD   IS '승인상태(LAW_DOC_APP_STATUS — S001 대기/S002 승인/S003 반려, 기본 대기) ← tbetia17.DOC_APP_STS(텍스트의 코드화)';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_USER_ID  IS '승인(반려)자 ID ← tbetia17.DOC_APP_EMP_NO';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_USER_NM  IS '승인(반려)자 성명 ← tbetia17.DOC_APP_EMP_NM';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_DT       IS '승인(반려)일시 (YYYYMMDDHH24MISS) ← tbetia17.DOC_APP_DTTM';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_OPINION  IS '승인 의견·반려 사유 ← tbetia17.DOC_APP_BLBD';
COMMENT ON COLUMN LAW_SUIT_DOC.REG_USER_ID  IS '등록자(신청인) ID';
COMMENT ON COLUMN LAW_SUIT_DOC.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_DOC.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_DOC.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_DOC_01 ON LAW_SUIT_DOC (SUIT_ID);
CREATE INDEX IX_LAW_SUIT_DOC_02 ON LAW_SUIT_DOC (APP_STS_CD);

-- ── 1.8 LAW_SUIT_COST 소송비용 ← tbetia20+21 통합 ──
CREATE TABLE LAW_SUIT_COST (
    COST_ID      BIGINT  NOT NULL,
    SUIT_ID      BIGINT  NOT NULL,
    COST_KIND_CD VARCHAR(10),
    COST_AMT     NUMERIC(19),
    COST_DESC    VARCHAR(1000),
    PAY_DMND_DT  VARCHAR(8),
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_COST PRIMARY KEY (COST_ID)
);
COMMENT ON TABLE  LAW_SUIT_COST IS '송무 소송비용 (단일행 — 레거시 신청/지급 2테이블 통합) ← tbetia20+tbetia21';
COMMENT ON COLUMN LAW_SUIT_COST.COST_ID      IS '비용 행 ID (채번 LAW_COST_ID)';
COMMENT ON COLUMN LAW_SUIT_COST.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_COST.COST_KIND_CD IS '비용종류(LAW_COST_KIND — 인지액/송달료/지연이자/공탁금/변호사비용/조세비용/조정중재/기타)';
COMMENT ON COLUMN LAW_SUIT_COST.COST_AMT     IS '금액(원)';
COMMENT ON COLUMN LAW_SUIT_COST.COST_DESC    IS '내역';
COMMENT ON COLUMN LAW_SUIT_COST.PAY_DMND_DT  IS '지급요청일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_COST.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_COST.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_COST.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_COST.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_COST_01 ON LAW_SUIT_COST (SUIT_ID);

-- ── 1.9 LAW_LAWYER 변호사 명부 ← tbetia51 ──
CREATE TABLE LAW_LAWYER (
    LAWYER_ID   BIGINT  NOT NULL,
    LAW_FIRM    VARCHAR(200),
    LAWYER_NM   VARCHAR(100),
    EMAIL       VARCHAR(100),
    TEL         VARCHAR(50),
    MOBILE      VARCHAR(50),
    DEL_YN      CHAR(1) DEFAULT 'N' NOT NULL,
    REG_USER_ID VARCHAR(20),
    REG_DT      VARCHAR(14),
    UPD_USER_ID VARCHAR(20),
    UPD_DT      VARCHAR(14),
    CONSTRAINT PK_LAW_LAWYER PRIMARY KEY (LAWYER_ID)
);
COMMENT ON TABLE  LAW_LAWYER IS '송무 변호사 명부 — 법무법인은 텍스트(마스터 비범위 §1.2) ← tbetia51';
COMMENT ON COLUMN LAW_LAWYER.LAWYER_ID   IS '변호사 ID (채번 LAW_LAWYER_ID) ← tbetia51.SEQ';
COMMENT ON COLUMN LAW_LAWYER.LAW_FIRM    IS '법무법인명(텍스트) ← tbetia51.LAW_FIRM';
COMMENT ON COLUMN LAW_LAWYER.LAWYER_NM   IS '변호사 성명 ← tbetia51.NAME';
COMMENT ON COLUMN LAW_LAWYER.EMAIL       IS '이메일 ← tbetia51.EMAIL';
COMMENT ON COLUMN LAW_LAWYER.TEL         IS '전화(사무실) ← tbetia51.TEL';
COMMENT ON COLUMN LAW_LAWYER.MOBILE      IS '휴대폰 ← tbetia51.PHONE';
COMMENT ON COLUMN LAW_LAWYER.DEL_YN      IS '소프트삭제 여부 (Y/N — 선임 참조 시 삭제 차단 안내 §7.7)';
COMMENT ON COLUMN LAW_LAWYER.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_LAWYER.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_LAWYER.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_LAWYER.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';

-- ── 1.10 LAW_SUIT_LAWYER 선임 ← tbetia52 ──
CREATE TABLE LAW_SUIT_LAWYER (
    ASSIGN_ID    BIGINT  NOT NULL,
    SUIT_ID      BIGINT  NOT NULL,
    LAWYER_ID    BIGINT  NOT NULL,
    ASSIGN_DT    VARCHAR(8),
    ATCH_FILE_ID CHAR(20),
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_LAWYER PRIMARY KEY (ASSIGN_ID)
);
COMMENT ON TABLE  LAW_SUIT_LAWYER IS '송무 선임 (사건×변호사) — 만족도 평가 대상 단위(§4.3) ← tbetia52';
COMMENT ON COLUMN LAW_SUIT_LAWYER.ASSIGN_ID    IS '선임 ID (채번 LAW_ASSIGN_ID) ← tbetia52.SEQ';
COMMENT ON COLUMN LAW_SUIT_LAWYER.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.LAWYER_ID    IS '변호사 ID (LAW_LAWYER FK) ← tbetia52.TBETIA51_SEQ';
COMMENT ON COLUMN LAW_SUIT_LAWYER.ASSIGN_DT    IS '선임일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.ATCH_FILE_ID IS '계약서 첨부파일 ID (표준 COMTNFILE)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_LAWYER.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_LAWYER.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_LAWYER_01 ON LAW_SUIT_LAWYER (SUIT_ID);
CREATE INDEX IX_LAW_SUIT_LAWYER_02 ON LAW_SUIT_LAWYER (LAWYER_ID);

-- ── 1.11 LAW_COURT 법원 ← tbetia31 ──
CREATE TABLE LAW_COURT (
    COURT_ID       BIGINT  NOT NULL,
    UPPER_COURT_ID BIGINT,
    COURT_NM       VARCHAR(150),
    SORT_ORDR      BIGINT DEFAULT 0,
    USE_YN         CHAR(1) DEFAULT 'Y' NOT NULL,
    RMK            VARCHAR(1000),
    REG_USER_ID    VARCHAR(20),
    REG_DT         VARCHAR(14),
    UPD_USER_ID    VARCHAR(20),
    UPD_DT         VARCHAR(14),
    CONSTRAINT PK_LAW_COURT PRIMARY KEY (COURT_ID)
);
COMMENT ON TABLE  LAW_COURT IS '송무 법원 마스터 (계층 — 루트 COURT_ID=0) ← tbetia31. 대표 시드 22행, 부족분은 운영 등록';
COMMENT ON COLUMN LAW_COURT.COURT_ID       IS '법원 ID (채번 LAW_COURT_ID — 시드 최대 194, NEXT_ID 200부터) ← tbetia31.COURT_SEQ';
COMMENT ON COLUMN LAW_COURT.UPPER_COURT_ID IS '상위 법원 ID (루트=NULL) ← tbetia31.SPST_COURT_SEQ';
COMMENT ON COLUMN LAW_COURT.COURT_NM       IS '법원명 ← tbetia31.COURT_NM';
COMMENT ON COLUMN LAW_COURT.SORT_ORDR      IS '표시 순서 ← tbetia31.ORD';
COMMENT ON COLUMN LAW_COURT.USE_YN         IS '사용 여부 (Y/N)';
COMMENT ON COLUMN LAW_COURT.RMK            IS '비고 — 레거시 승계 시 해당 법원 취급 사건부호(LAW_CASE_SIGN) 파이프 목록 ← tbetia31.RMK';
COMMENT ON COLUMN LAW_COURT.REG_USER_ID    IS '등록자 ID';
COMMENT ON COLUMN LAW_COURT.REG_DT         IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_COURT.UPD_USER_ID    IS '수정자 ID';
COMMENT ON COLUMN LAW_COURT.UPD_DT         IS '수정일시 (YYYYMMDDHH24MISS)';

-- ── 1.12 LAW_SUIT_REQ 소송의뢰 ← tbetia40 ──
CREATE TABLE LAW_SUIT_REQ (
    REQ_ID        BIGINT  NOT NULL,
    REQ_TITL      VARCHAR(200),
    REQ_CN        VARCHAR(4000),
    REQ_ORGNZT_ID CHAR(20),
    REQ_USER_ID   VARCHAR(20),
    REQ_USER_NM   VARCHAR(60),
    REQ_DT        VARCHAR(8),
    STATUS_CD     VARCHAR(10) DEFAULT 'S001',
    APRV_USER_ID  VARCHAR(20),
    APRV_USER_NM  VARCHAR(60),
    APRV_DT       VARCHAR(14),
    RETURN_RSN    VARCHAR(1000),
    SUIT_ID       BIGINT,
    ATCH_FILE_ID  CHAR(20),
    REG_USER_ID   VARCHAR(20),
    REG_DT        VARCHAR(14),
    UPD_USER_ID   VARCHAR(20),
    UPD_DT        VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_REQ PRIMARY KEY (REQ_ID)
);
COMMENT ON TABLE  LAW_SUIT_REQ IS '송무 소송의뢰 — 사용자(front) 신청, 법무팀 승인/반려, 승인 후 소송등록 연계(§7.8·7.9) ← tbetia40';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_ID        IS '의뢰 ID (채번 LAW_REQ_ID) ← tbetia40.REQ_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_TITL      IS '사건명(의뢰 제목) ← tbetia40.REQ_TITL';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_CN        IS '사실관계 ← tbetia40.REQ_BLBD_CONTN';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_ORGNZT_ID IS '의뢰부서 ID (COMTNORGNZTINFO — 신청자 소속 자동) ← tbetia40.REQ_PSTN_CD';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_USER_ID   IS '의뢰담당자 ID ← tbetia40.REQ_EMP_NO';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_USER_NM   IS '의뢰담당자 성명 ← tbetia40.REQ_EMP_NM';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_DT        IS '의뢰일자 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_REQ.STATUS_CD     IS '의뢰상태(LAW_REQ_STATUS — S001 신청/S002 승인/S003 반려) ← tbetia40.REQ_RSLT_PROC';
COMMENT ON COLUMN LAW_SUIT_REQ.APRV_USER_ID  IS '승인(반려)자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ.APRV_USER_NM  IS '승인(반려)자 성명';
COMMENT ON COLUMN LAW_SUIT_REQ.APRV_DT       IS '승인(반려)일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ.RETURN_RSN    IS '반려 사유 (그리드 사유 열)';
COMMENT ON COLUMN LAW_SUIT_REQ.SUIT_ID       IS '승인 후 연계 등록된 사건 ID (LAW_SUIT — 소송등록 시 역기입)';
COMMENT ON COLUMN LAW_SUIT_REQ.ATCH_FILE_ID  IS '기타자료 첨부파일 ID (표준 COMTNFILE, 다중)';
COMMENT ON COLUMN LAW_SUIT_REQ.REG_USER_ID   IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ.REG_DT        IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ.UPD_USER_ID   IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ.UPD_DT        IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_REQ_01 ON LAW_SUIT_REQ (STATUS_CD);
CREATE INDEX IX_LAW_SUIT_REQ_02 ON LAW_SUIT_REQ (REG_USER_ID);

-- ── 1.13 LAW_SUIT_REQ_HIST 의뢰 사건경과 ← tbetia41 ──
CREATE TABLE LAW_SUIT_REQ_HIST (
    HIST_ID      BIGINT  NOT NULL,
    REQ_ID       BIGINT  NOT NULL,
    STA_DT       VARCHAR(8),
    END_DT       VARCHAR(8),
    HIST_CN      VARCHAR(1000),
    ATCH_FILE_ID CHAR(20),
    SORT_ORDR    INT DEFAULT 0,
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_REQ_HIST PRIMARY KEY (HIST_ID)
);
COMMENT ON TABLE  LAW_SUIT_REQ_HIST IS '송무 소송의뢰 사건경과 내역 (행별 첨부 1건) ← tbetia41';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.HIST_ID      IS '경과 행 ID (채번 LAW_REQ_HIST_ID) ← tbetia41.HST_REQ_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.REQ_ID       IS '의뢰 ID (LAW_SUIT_REQ FK)';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.STA_DT       IS '기간 시작일 (YYYYMMDD) ← tbetia41.STA_DTTM';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.END_DT       IS '기간 종료일 (YYYYMMDD) ← tbetia41.END_DTTM';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.HIST_CN      IS '경과 내용 ← tbetia41.HST_BLBD_CONTN';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.ATCH_FILE_ID IS '행별 첨부파일 ID (표준 COMTNFILE)';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.SORT_ORDR    IS '표시 순서';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_REQ_HIST_01 ON LAW_SUIT_REQ_HIST (REQ_ID);

-- ── 1.14 LAW_SUIT_REQ_HELPER 의뢰 소송수행 보조자 ← ReqLawsuitChps(tbetia13 재사용분) ──
CREATE TABLE LAW_SUIT_REQ_HELPER (
    HELPER_ID   BIGINT  NOT NULL,
    REQ_ID      BIGINT  NOT NULL,
    DEPT_NM     VARCHAR(100),
    HELPER_NM   VARCHAR(60),
    TEL         VARCHAR(50),
    MOBILE      VARCHAR(50),
    EMAIL       VARCHAR(100),
    SORT_ORDR   INT DEFAULT 0,
    REG_USER_ID VARCHAR(20),
    REG_DT      VARCHAR(14),
    UPD_USER_ID VARCHAR(20),
    UPD_DT      VARCHAR(14),
    CONSTRAINT PK_LAW_SUIT_REQ_HELPER PRIMARY KEY (HELPER_ID)
);
COMMENT ON TABLE  LAW_SUIT_REQ_HELPER IS '송무 소송의뢰 수행 보조자 (부서명은 자유 텍스트 — 외부 인원 허용) ← tbetia13(ReqLawsuitChps 재사용분)';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.HELPER_ID   IS '보조자 행 ID (채번 LAW_REQ_HELPER_ID) ← tbetia13.LAWSUIT_CHPS_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.REQ_ID      IS '의뢰 ID (LAW_SUIT_REQ FK) ← tbetia13.REQ_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.DEPT_NM     IS '부서명 ← tbetia13.PSTN_NM';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.HELPER_NM   IS '담당자 성명 ← tbetia13.CHPS_EMP_NM';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.TEL         IS '전화 ← tbetia13.CHPS_EMP_PHONE';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.MOBILE      IS '휴대폰 ← tbetia13.CHPS_EMP_MOBILE';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.EMAIL       IS '이메일 ← tbetia13.CHPS_EMP_EMAIL';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.SORT_ORDR   IS '표시 순서';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_REQ_HELPER_01 ON LAW_SUIT_REQ_HELPER (REQ_ID);

-- ── 1.15 LAW_SEIZE 가압류·가처분 ← tc_seize ──
CREATE TABLE LAW_SEIZE (
    SEIZE_ID     BIGINT  NOT NULL,
    CREDITOR     VARCHAR(200),
    DEBTOR       VARCHAR(200),
    THIRD_DEBTOR VARCHAR(200),
    ORGNZT_ID    CHAR(20),
    COURT_NM     VARCHAR(150),
    CASE_NO      VARCHAR(100),
    MEMO         TEXT,
    READ_CNT     BIGINT DEFAULT 0,
    ATCH_FILE_ID CHAR(20),
    REG_USER_ID  VARCHAR(20),
    REG_DT       VARCHAR(14),
    UPD_USER_ID  VARCHAR(20),
    UPD_DT       VARCHAR(14),
    CONSTRAINT PK_LAW_SEIZE PRIMARY KEY (SEIZE_ID)
);
COMMENT ON TABLE  LAW_SEIZE IS '송무 압류관리(가압류·가처분) — 게시판형, 첨부 5개·10MB 제한(서버 검증 §7.10) ← tc_seize';
COMMENT ON COLUMN LAW_SEIZE.SEIZE_ID     IS '압류 ID (채번 LAW_SEIZE_ID) ← tc_seize.SEIZE_ID';
COMMENT ON COLUMN LAW_SEIZE.CREDITOR     IS '채권자 ← tc_seize.CHEKWON';
COMMENT ON COLUMN LAW_SEIZE.DEBTOR       IS '채무자 ← tc_seize.CHEMOO';
COMMENT ON COLUMN LAW_SEIZE.THIRD_DEBTOR IS '제3채무자 ← tc_seize.CHEMOO3';
COMMENT ON COLUMN LAW_SEIZE.ORGNZT_ID    IS '담당부서 ID (COMTNORGNZTINFO) ← tc_seize.DAMDANG_BUSEO(텍스트의 표준 대체)';
COMMENT ON COLUMN LAW_SEIZE.COURT_NM     IS '관할법원명 ← tc_seize.BUBWON';
COMMENT ON COLUMN LAW_SEIZE.CASE_NO      IS '사건번호 ← tc_seize.SAGUN_NO';
COMMENT ON COLUMN LAW_SEIZE.MEMO         IS '메모 ← tc_seize.MEMO';
COMMENT ON COLUMN LAW_SEIZE.READ_CNT     IS '조회수 (상세 열람 시 증가) ← tc_seize.READ_CNT';
COMMENT ON COLUMN LAW_SEIZE.ATCH_FILE_ID IS '첨부파일 ID (표준 COMTNFILE — 문서파일 5개·10MB 제한) ← tc_seizeattach 대체';
COMMENT ON COLUMN LAW_SEIZE.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SEIZE.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SEIZE.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SEIZE.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SEIZE_01 ON LAW_SEIZE (REG_DT);

-- ── 1.16 LAW_COURT_RECEIPT 법원서류접수 ← tbetia44 ──
CREATE TABLE LAW_COURT_RECEIPT (
    RECEIPT_ID     BIGINT  NOT NULL,
    RECEIPT_TITL   VARCHAR(200),
    ORGNZT_ID      CHAR(20),
    REL_ORGNZT_ID1 CHAR(20),
    REL_ORGNZT_ID2 CHAR(20),
    ATCH_FILE_ID   CHAR(20),
    REG_USER_ID    VARCHAR(20),
    REG_DT         VARCHAR(14),
    UPD_USER_ID    VARCHAR(20),
    UPD_DT         VARCHAR(14),
    CONSTRAINT PK_LAW_COURT_RECEIPT PRIMARY KEY (RECEIPT_ID)
);
COMMENT ON TABLE  LAW_COURT_RECEIPT IS '송무 법원서류접수 — 접수+관련부서 지정·표시까지(알림 발송은 비범위 §1.2) ← tbetia44';
COMMENT ON COLUMN LAW_COURT_RECEIPT.RECEIPT_ID     IS '접수 ID (채번 LAW_RECEIPT_ID) ← tbetia44.ACC_SEQ';
COMMENT ON COLUMN LAW_COURT_RECEIPT.RECEIPT_TITL   IS '제목 ← tbetia44.ACC_TITL';
COMMENT ON COLUMN LAW_COURT_RECEIPT.ORGNZT_ID      IS '등록부서 ID (등록자 소속 자동, COMTNORGNZTINFO) ← tbetia44.ACC_PSTN_CD';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REL_ORGNZT_ID1 IS '관련부서 1 (COMTNORGNZTINFO) ← tbetia44.ACC_PSTN_CD2';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REL_ORGNZT_ID2 IS '관련부서 2 (COMTNORGNZTINFO)';
COMMENT ON COLUMN LAW_COURT_RECEIPT.ATCH_FILE_ID   IS '관련자료 첨부파일 ID (표준 COMTNFILE) ← tbetia44.ACC_FILE_NM 대체';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REG_USER_ID    IS '등록자 ID ← tbetia44.ACC_EMP_NO';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REG_DT         IS '등록일시 (YYYYMMDDHH24MISS) ← tbetia44.ACC_REG_DTTM';
COMMENT ON COLUMN LAW_COURT_RECEIPT.UPD_USER_ID    IS '수정자 ID';
COMMENT ON COLUMN LAW_COURT_RECEIPT.UPD_DT         IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_COURT_RECEIPT_01 ON LAW_COURT_RECEIPT (REG_DT);

-- ── 1.17 LAW_CALC_RATE 계산기 요율 (신규 — 레거시 JS 하드코딩의 DB화 §4.3) ──
CREATE TABLE LAW_CALC_RATE (
    RATE_ID     BIGINT   NOT NULL,
    CALC_TYPE   VARCHAR(20) NOT NULL,
    ITEM_CD     VARCHAR(20),
    APPLY_DT    VARCHAR(8)  NOT NULL,
    SECTION_AMT NUMERIC(19),
    RATE_VAL    NUMERIC(12,6),
    ADD_AMT     NUMERIC(19),
    RMK         VARCHAR(200),
    USE_YN      CHAR(1) DEFAULT 'Y' NOT NULL,
    REG_USER_ID VARCHAR(20),
    REG_DT      VARCHAR(14),
    UPD_USER_ID VARCHAR(20),
    UPD_DT      VARCHAR(14),
    CONSTRAINT PK_LAW_CALC_RATE PRIMARY KEY (RATE_ID)
);
COMMENT ON TABLE  LAW_CALC_RATE IS '송무 소송비용 계산기 요율 — 타입×항목×적용시작일 시점별 세트, 기준일 조회=APPLY_DT 이하 최신 세트(§7.4·7.13). 공식 뼈대는 JS, 숫자만 DB';
COMMENT ON COLUMN LAW_CALC_RATE.RATE_ID     IS '요율 행 ID (채번 LAW_CALC_RATE_ID)';
COMMENT ON COLUMN LAW_CALC_RATE.CALC_TYPE   IS '계산기 타입 — STAMP(인지액 구간표)/STAMP_MULT(인지액 사건종류 배율)/POST_UNIT(송달료 우편료 단가)/POST_COUNT(송달료 사건유형별 회수)/LAWYER(변호사비 산입 구간표)/LEGAL_INT(법정이율 프리셋)';
COMMENT ON COLUMN LAW_CALC_RATE.ITEM_CD     IS '항목 식별 — STAMP_MULT=사건종류(C1~C8, 레거시 select 값 승계)·MIN_AMT(최소 인지액), POST_COUNT=송달 사건유형(T01~T17), LEGAL_INT=CIVIL/COMM/SOCHOK. 구간표·단가 행은 NULL';
COMMENT ON COLUMN LAW_CALC_RATE.APPLY_DT    IS '적용시작일 (YYYYMMDD — 개정 시행일. 같은 타입·항목에 시점별 세트 공존)';
COMMENT ON COLUMN LAW_CALC_RATE.SECTION_AMT IS '구간 하한(소가, 원 — 구간표 행만. 단일값 행은 NULL)';
COMMENT ON COLUMN LAW_CALC_RATE.RATE_VAL    IS '값 — 타입별 의미: 율(0.005)·단가(5500)·배율(1.5)·회수(15)·이율(12). 배율 행에서 0이면 ADD_AMT 고정액 사건';
COMMENT ON COLUMN LAW_CALC_RATE.ADD_AMT     IS '구간 가산액(원 — 인지액·변호사비 구간표) 또는 고정액(배율 행 RATE_VAL=0 일 때)';
COMMENT ON COLUMN LAW_CALC_RATE.RMK         IS '근거 (고시·규칙 번호 등)';
COMMENT ON COLUMN LAW_CALC_RATE.USE_YN      IS '사용 여부 (Y/N — 과거 세트 이력 보존용 소프트 삭제 §7.13)';
COMMENT ON COLUMN LAW_CALC_RATE.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_CALC_RATE.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_CALC_RATE.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_CALC_RATE.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_CALC_RATE_01 ON LAW_CALC_RATE (CALC_TYPE, APPLY_DT);

-- ── 1.18 LAW_LAWYER_SATIS 법무법인 만족도(간이) ← tbetia45 대체 ──
CREATE TABLE LAW_LAWYER_SATIS (
    ASSIGN_ID BIGINT   NOT NULL,
    EMPLYR_ID VARCHAR(20) NOT NULL,
    SCORE     SMALLINT    NOT NULL,
    OPINION   VARCHAR(1000),
    REG_DT    VARCHAR(14),
    UPD_DT    VARCHAR(14),
    CONSTRAINT PK_LAW_LAWYER_SATIS PRIMARY KEY (ASSIGN_ID, EMPLYR_ID)
);
COMMENT ON TABLE  LAW_LAWYER_SATIS IS '송무 법무법인 만족도(간이 별점+의견) — 평가 대상=선임(사건×변호사) 단위, 1인 1회 MERGE(TB_PROM_STSFDG 패턴) ← tbetia45(9문항 가중 설문의 간소화 대체 §1.2)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.ASSIGN_ID IS '선임 ID (LAW_SUIT_LAWYER FK — 복합 PK)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.EMPLYR_ID IS '평가자 ID (COMTNEMPLYRINFO.EMPLYR_ID — 복합 PK, 1인 1회)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.SCORE     IS '별점 (1~5)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.OPINION   IS '의견 (선택)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.REG_DT    IS '최초 평가일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.UPD_DT    IS '재평가일시 (YYYYMMDDHH24MISS — MERGE 갱신)';

COMMIT;

COMMIT;

COMMIT;

COMMIT;

-- 검증:
--   코멘트 전수: SELECT COUNT(*) FROM user_col_comments WHERE table_name LIKE 'LAW_%' AND comments IS NULL;  (0 이어야)
--                SELECT COUNT(*) FROM user_tab_comments WHERE table_name LIKE 'LAW_%' AND comments IS NULL;  (0 이어야)
--   코드:       SELECT CODE_ID, COUNT(*) FROM COMTCCMMNDETAILCODE WHERE CODE_ID LIKE 'LAW_%' GROUP BY CODE_ID ORDER BY CODE_ID;
--   법원:       SELECT COUNT(*) FROM LAW_COURT;  (22)
--   요율:       SELECT CALC_TYPE, COUNT(*) FROM LAW_CALC_RATE GROUP BY CALC_TYPE;  (STAMP 5/STAMP_MULT 8/POST_UNIT 1/POST_COUNT 17/LAWYER 7/LEGAL_INT 3)
