--------------------------------------------------------------------------------
-- 30_fks.sql — FK 제약 (시드 적재 후 마지막 실행 = 정합 검증 겸용)
-- RLMS 통합본(PostgreSQL) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: rlms. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- COMTHEMPLYRINFOCHANGEDTLS_FK1 은 제외(라이브 FK 는 미생성 대상인 COMTN- 변형 테이블 위의 것).
--------------------------------------------------------------------------------

ALTER TABLE COMTCCMMNDETAILCODE ADD CONSTRAINT COMTCCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE (CODE_ID);
ALTER TABLE COMTNAUTHORROLERELATE ADD CONSTRAINT COMTNAUTHORROLERELATE_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE;
ALTER TABLE COMTNAUTHORROLERELATE ADD CONSTRAINT COMTNAUTHORROLERELATE_FK2 FOREIGN KEY (ROLE_CODE) REFERENCES COMTNROLEINFO (ROLE_CODE) ON DELETE CASCADE;
ALTER TABLE COMTNBBS ADD CONSTRAINT COMTNBBS_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER (BBS_ID);
ALTER TABLE COMTNCOMMENT ADD CONSTRAINT COMTNCOMMENT_FK1 FOREIGN KEY (NTT_ID, BBS_ID) REFERENCES COMTNBBS (NTT_ID, BBS_ID);
ALTER TABLE COMTNEMPLYRINFO ADD CONSTRAINT COMTNEMPLYRINFO_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE;
ALTER TABLE COMTNEMPLYRINFO ADD CONSTRAINT COMTNEMPLYRINFO_FK2 FOREIGN KEY (ORGNZT_ID) REFERENCES COMTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE;
ALTER TABLE COMTNORGNZTINFO ADD CONSTRAINT FK_COMTNORGNZT_UPPER FOREIGN KEY (UPPER_ORGNZT_ID) REFERENCES COMTNORGNZTINFO (ORGNZT_ID);
ALTER TABLE COMTNFAQINFO ADD CONSTRAINT COMTNFAQINFO_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE (ATCH_FILE_ID) ON DELETE SET NULL;
ALTER TABLE COMTNFILEDETAIL ADD CONSTRAINT COMTNFILEDETAIL_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE (ATCH_FILE_ID);
ALTER TABLE COMTNGNRLMBER ADD CONSTRAINT COMTNGNRLMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE;
ALTER TABLE COMTNBBSWRITEAUTHOR ADD CONSTRAINT COMTNBBSWRITEAUTHOR_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER (BBS_ID) ON DELETE CASCADE;
ALTER TABLE COMTNBBSWRITEAUTHOR ADD CONSTRAINT COMTNBBSWRITEAUTHOR_FK2 FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO (AUTHOR_CODE);
ALTER TABLE COMTNMENUCREATDTLS ADD CONSTRAINT COMTNMENUCREATDTLS_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO (AUTHOR_CODE);
ALTER TABLE COMTNMENUCREATDTLS ADD CONSTRAINT COMTNMENUCREATDTLS_FK2 FOREIGN KEY (MENU_NO) REFERENCES COMTNMENUINFO (MENU_NO) ON DELETE CASCADE;
ALTER TABLE COMTNMENUCREATDTLS ADD CONSTRAINT COMTNMENUCREATDTLS_FK3 FOREIGN KEY (MAPNG_CREAT_ID) REFERENCES COMTNSITEMAP (MAPNG_CREAT_ID) ON DELETE CASCADE;
ALTER TABLE COMTNMENUINFO ADD CONSTRAINT COMTNMENUINFO_FK1 FOREIGN KEY (UPPER_MENU_NO) REFERENCES COMTNMENUINFO (MENU_NO) ON DELETE CASCADE;
ALTER TABLE COMTNMENUINFO ADD CONSTRAINT COMTNMENUINFO_FK2 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES COMTNPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE;
ALTER TABLE COMTNROLES_HIERARCHY ADD CONSTRAINT COMTNROLES_HIERARCHY_FK1 FOREIGN KEY (PARNTS_ROLE) REFERENCES COMTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE;
ALTER TABLE COMTNROLES_HIERARCHY ADD CONSTRAINT COMTNROLES_HIERARCHY_FK2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES COMTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE;
ALTER TABLE TB_CATE_OWNER ADD CONSTRAINT TB_CATE_OWNER_FK1 FOREIGN KEY (ICATE_NO) REFERENCES TB_CATE (ICATE_NO);
ALTER TABLE TB_CATE_READER ADD CONSTRAINT TB_CATE_READER_FK1 FOREIGN KEY (ICATE_NO) REFERENCES TB_CATE (ICATE_NO);
ALTER TABLE TB_PROM_STSFDG ADD CONSTRAINT FK_TB_PROM_STSFDG_PROM FOREIGN KEY (IPROM_NO) REFERENCES TB_PROM (IPROM_NO) ON DELETE CASCADE;
ALTER TABLE TB_READ_DUTY ADD CONSTRAINT TB_READ_DUTY_FK1 FOREIGN KEY (IPROM_NO) REFERENCES TB_PROM (IPROM_NO) ON DELETE CASCADE;
ALTER TABLE TB_READ_DUTY_TGT ADD CONSTRAINT TB_READ_DUTY_TGT_FK1 FOREIGN KEY (IDUTY_NO) REFERENCES TB_READ_DUTY (IDUTY_NO) ON DELETE CASCADE;
ALTER TABLE TB_READ_DUTY_CHK ADD CONSTRAINT TB_READ_DUTY_CHK_FK1 FOREIGN KEY (IDUTY_NO) REFERENCES TB_READ_DUTY (IDUTY_NO) ON DELETE CASCADE;