--------------------------------------------------------------------------------
-- 10_tables.sql — 테이블 76종 + 로그인 뷰 COMVNUSERMASTER
-- 신규 스키마 RLMS 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: RLMS. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 원천: DBMS_METADATA.GET_DDL (스키마 한정자/스토리지 절 제거). 합성 1종(COMTH 변경이력)은 후반부.
--------------------------------------------------------------------------------

-- TABLE COMTCCMMNCODE
CREATE TABLE "COMTCCMMNCODE" 
   (	"CODE_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CODE_ID_NM" VARCHAR2(60), 
	"CODE_ID_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"CL_CODE" CHAR(3), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNCODE_PK" PRIMARY KEY ("CODE_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTCCMMNDETAILCODE
CREATE TABLE "COMTCCMMNDETAILCODE" 
   (	"CODE_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"CODE_NM" VARCHAR2(60), 
	"CODE_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNDETAILCODE_PK" PRIMARY KEY ("CODE_ID", "CODE")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTECOPSEQ
CREATE TABLE "COMTECOPSEQ" 
   (	"TABLE_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"NEXT_ID" NUMBER(30,0), 
	 CONSTRAINT "COMTECOPSEQ_PK" PRIMARY KEY ("TABLE_NAME")
  USING INDEX  ENABLE
   ) ;


-- TABLE COMTNAUTHORGROUPINFO
CREATE TABLE "COMTNAUTHORGROUPINFO" 
   (	"GROUP_ID" CHAR(20) NOT NULL ENABLE, 
	"GROUP_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"GROUP_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	"GROUP_DC" VARCHAR2(100), 
	 CONSTRAINT "COMTNAUTHORGROUPINFO_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNAUTHORINFO
CREATE TABLE "COMTNAUTHORINFO" 
   (	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHOR_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"AUTHOR_DC" VARCHAR2(200), 
	"AUTHOR_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNAUTHORINFO_PK" PRIMARY KEY ("AUTHOR_CODE")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNAUTHORROLERELATE
CREATE TABLE "COMTNAUTHORROLERELATE" 
   (	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"CREAT_DT" DATE, 
	 CONSTRAINT "COMTNAUTHORROLERELATE_PK" PRIMARY KEY ("AUTHOR_CODE", "ROLE_CODE")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNBANNER
CREATE TABLE "COMTNBANNER" 
   (	"BANNER_ID" CHAR(20) NOT NULL ENABLE, 
	"BANNER_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"LINK_URL" VARCHAR2(255) NOT NULL ENABLE, 
	"BANNER_IMAGE" VARCHAR2(60) NOT NULL ENABLE, 
	"BANNER_DC" VARCHAR2(200), 
	"REFLCT_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"BANNER_IMAGE_FILE" VARCHAR2(60), 
	"SORT_ORDR" NUMBER(8,0), 
	 CONSTRAINT "COMTNBANNER_PK" PRIMARY KEY ("BANNER_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNBBS
CREATE TABLE "COMTNBBS" 
   (	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"NTT_NO" NUMBER(20,0), 
	"NTT_SJ" VARCHAR2(2000), 
	"NTT_CN" CLOB, 
	"ANSWER_AT" CHAR(1), 
	"PARNTSCTT_NO" NUMBER(10,0), 
	"ANSWER_LC" NUMBER(8,0), 
	"SORT_ORDR" NUMBER(8,0), 
	"RDCNT" NUMBER(10,0), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"NTCE_BGNDE" CHAR(20), 
	"NTCE_ENDDE" CHAR(20), 
	"NTCR_ID" VARCHAR2(20), 
	"NTCR_NM" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(200), 
	"ATCH_FILE_ID" CHAR(20), 
	"NOTICE_AT" CHAR(1), 
	"SJ_BOLD_AT" CHAR(1), 
	"SECRET_AT" CHAR(1), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"BLOG_ID" CHAR(20), 
	"NTT_EXTRA_FIELD_1" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_2" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_3" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_4" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_5" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_6" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_7" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_8" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_9" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_10" VARCHAR2(200), 
	 CONSTRAINT "COMTNBBS_PK" PRIMARY KEY ("NTT_ID", "BBS_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNBBSMASTER
CREATE TABLE "COMTNBBSMASTER" 
   (	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"BBS_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"BBS_INTRCN" VARCHAR2(2400), 
	"BBS_TY_CODE" CHAR(6) NOT NULL ENABLE, 
	"REPLY_POSBL_AT" CHAR(1), 
	"FILE_ATCH_POSBL_AT" CHAR(1) NOT NULL ENABLE, 
	"ATCH_POSBL_FILE_NUMBER" NUMBER(2,0) NOT NULL ENABLE, 
	"ATCH_POSBL_FILE_SIZE" NUMBER(8,0), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"TMPLAT_ID" CHAR(20), 
	"CMMNTY_ID" CHAR(20), 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"BLOG_ID" CHAR(20), 
	"BLOG_AT" CHAR(2), 
	"BBS_SKIN_CODE" VARCHAR2(30) DEFAULT 'BASIC', 
	"BBS_EXTRA_FIELD_1" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_2" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_3" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_4" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_5" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_6" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_7" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_8" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_9" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_10" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_TYPE_1" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_2" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_3" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_4" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_5" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_6" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_7" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_8" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_9" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_10" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_CODE_ID_1" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_2" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_3" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_4" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_5" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_6" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_7" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_8" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_9" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_10" VARCHAR2(30),
	"LIST_PAGE_UNIT" VARCHAR2(50),
	"SECRET_POSBL_AT" CHAR(1) DEFAULT 'Y',
	"RICH_EDITOR_AT" CHAR(1) DEFAULT 'Y',
	"SEARCH_INCLD_AT" CHAR(1) DEFAULT 'Y',
	"PAGING_AT" CHAR(1) DEFAULT 'Y',
	"SEARCH_BOX_AT" CHAR(1) DEFAULT 'Y',
	 CONSTRAINT "COMTNBBSMASTER_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNBBSMASTEROPTN
CREATE TABLE "COMTNBBSMASTEROPTN" 
   (	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"ANSWER_AT" CHAR(1) NOT NULL ENABLE, 
	"STSFDG_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNBBSMASTEROPTN_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX  ENABLE
   ) ;



-- 게시판별 작성권한. 열람권한은 메뉴 역할매핑(COMTNMENUCREATDTLS)이 원천이지만,
-- "메뉴가 보인다"와 "글을 쓸 수 있다"는 다른 축이라 별도 매핑이 필요하다.
CREATE TABLE COMTNBBSWRITEAUTHOR (
	BBS_ID      CHAR(30)     NOT NULL,
	AUTHOR_CODE VARCHAR2(30) NOT NULL,
	CONSTRAINT COMTNBBSWRITEAUTHOR_PK PRIMARY KEY (BBS_ID, AUTHOR_CODE)
);

-- TABLE COMTNCOMMENT
CREATE TABLE "COMTNCOMMENT" 
   (	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"ANSWER_NO" NUMBER(20,0) NOT NULL ENABLE,
	"WRTER_ID" VARCHAR2(20),
	-- 표준 원형은 VARCHAR2(20) 이라 USER_NM(60) 이 긴 사용자는 ORA-12899 → 60 으로 확장(2026-07-10)
	"WRTER_NM" VARCHAR2(60),
	-- 표준 원형은 VARCHAR2(200)(바이트) 이라 한글 약 66자에서 ORA-12899 → 문자기준 1000 으로 확장(2026-07-10, UI 글자수 카운터)
	"ANSWER" VARCHAR2(1000 CHAR),
	"USE_AT" CHAR(1) NOT NULL ENABLE,
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE,
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(200), 
	 CONSTRAINT "COMTNCOMMENT_PK" PRIMARY KEY ("NTT_ID", "BBS_ID", "ANSWER_NO")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNEMPLYRINFO
CREATE TABLE "COMTNEMPLYRINFO" 
   (	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGNZT_ID" CHAR(20), 
	"USER_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"EMPL_NO" VARCHAR2(20), 
	"IHIDNUM" VARCHAR2(200), 
	"SEXDSTN_CODE" CHAR(1), 
	"BRTHDY" CHAR(20), 
	"FXNUM" VARCHAR2(20), 
	"HOUSE_ADRES" VARCHAR2(100), 
	"PASSWORD_HINT" VARCHAR2(100), 
	"PASSWORD_CNSR" VARCHAR2(100), 
	"HOUSE_END_TELNO" VARCHAR2(4), 
	"AREA_NO" VARCHAR2(4), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"ZIP" VARCHAR2(6), 
	"OFFM_TELNO" VARCHAR2(20), 
	"MBTLNUM" VARCHAR2(20), 
	"EMAIL_ADRES" VARCHAR2(50), 
	"OFCPS_NM" VARCHAR2(60), 
	"HOUSE_MIDDLE_TELNO" VARCHAR2(4), 
	"GROUP_ID" CHAR(20), 
	"PSTINST_CODE" CHAR(8), 
	"EMPLYR_STTUS_CODE" CHAR(1) NOT NULL ENABLE, 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	"CRTFC_DN_VALUE" VARCHAR2(100), 
	"SBSCRB_DE" DATE, 
	"LOCK_AT" CHAR(1), 
	"LOCK_CNT" NUMBER(3,0), 
	"LOCK_LAST_PNTTM" DATE, 
	"CHG_PWD_LAST_PNTTM" DATE, 
	 CONSTRAINT "COMTNEMPLYRINFO_PK" PRIMARY KEY ("EMPLYR_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNEMPLYRSCRTYESTBS
CREATE TABLE "COMTNEMPLYRSCRTYESTBS" 
   (	"SCRTY_DTRMN_TRGET_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MBER_TY_CODE" CHAR(5), 
	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNEMPLYRSCRTYESTBS_PK" PRIMARY KEY ("SCRTY_DTRMN_TRGET_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNFAQINFO
CREATE TABLE "COMTNFAQINFO" 
   (	"FAQ_ID" CHAR(20) NOT NULL ENABLE, 
	"QESTN_SJ" VARCHAR2(255), 
	"QESTN_CN" VARCHAR2(2500), 
	"ANSWER_CN" VARCHAR2(2500), 
	"RDCNT" NUMBER(10,0), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ATCH_FILE_ID" CHAR(20), 
	"QNA_PROCESS_STTUS_CODE" CHAR(1), 
	"FAQ_CODE" VARCHAR2(15), 
	 CONSTRAINT "COMTNFAQINFO_PK" PRIMARY KEY ("FAQ_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNFILE
CREATE TABLE "COMTNFILE" 
   (	"ATCH_FILE_ID" CHAR(20) NOT NULL ENABLE, 
	"CREAT_DT" DATE NOT NULL ENABLE, 
	"USE_AT" CHAR(1), 
	 CONSTRAINT "COMTNFILE_PK" PRIMARY KEY ("ATCH_FILE_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNFILEDETAIL
CREATE TABLE "COMTNFILEDETAIL" 
   (	"ATCH_FILE_ID" CHAR(20) NOT NULL ENABLE, 
	"FILE_SN" NUMBER(10,0) NOT NULL ENABLE, 
	"FILE_STRE_COURS" VARCHAR2(2000) NOT NULL ENABLE, 
	"STRE_FILE_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"ORIGNL_FILE_NM" VARCHAR2(255), 
	"FILE_EXTSN" VARCHAR2(20) NOT NULL ENABLE,
	"FILE_CN" CLOB,
	"FILE_SIZE" NUMBER(8,0),
	"DWLD_CO" NUMBER(8,0) DEFAULT 0,
	 CONSTRAINT "COMTNFILEDETAIL_PK" PRIMARY KEY ("ATCH_FILE_ID", "FILE_SN")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNGNRLMBER
CREATE TABLE "COMTNGNRLMBER" 
   (	"MBER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"PASSWORD_HINT" VARCHAR2(100), 
	"PASSWORD_CNSR" VARCHAR2(100), 
	"IHIDNUM" VARCHAR2(200), 
	"MBER_NM" VARCHAR2(50) NOT NULL ENABLE, 
	"ZIP" VARCHAR2(6), 
	"ADRES" VARCHAR2(100), 
	"AREA_NO" VARCHAR2(4) NOT NULL ENABLE, 
	"MBER_STTUS" VARCHAR2(15), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"END_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"MBTLNUM" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" CHAR(20), 
	"MBER_FXNUM" VARCHAR2(20), 
	"MBER_EMAIL_ADRES" VARCHAR2(50), 
	"MIDDLE_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"SBSCRB_DE" DATE, 
	"SEXDSTN_CODE" CHAR(1), 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	"LOCK_AT" CHAR(1), 
	"LOCK_CNT" NUMBER(3,0), 
	"LOCK_LAST_PNTTM" DATE, 
	"CHG_PWD_LAST_PNTTM" DATE,
	"ORGNZT_ID" VARCHAR2(20),
	"EMPL_NO" VARCHAR2(20),
	 CONSTRAINT "COMTNGNRLMBER_PK" PRIMARY KEY ("MBER_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNLOGINLOG
CREATE TABLE "COMTNLOGINLOG" 
   (	"LOG_ID" CHAR(20) NOT NULL ENABLE, 
	"CONECT_ID" VARCHAR2(20), 
	"CONECT_IP" VARCHAR2(23), 
	"CONECT_MTHD" CHAR(4), 
	"ERROR_OCCRRNC_AT" CHAR(1), 
	"ERROR_CODE" CHAR(3), 
	"CREAT_DT" DATE, 
	 CONSTRAINT "COMTNLOGINLOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNLOGINPOLICY
CREATE TABLE "COMTNLOGINPOLICY" 
   (	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"IP_INFO" VARCHAR2(23) NOT NULL ENABLE, 
	"DPLCT_PERM_AT" CHAR(1) NOT NULL ENABLE, 
	"LMTT_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	 CONSTRAINT "COMTNLOGINPOLICY_PK" PRIMARY KEY ("EMPLYR_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNMENUCREATDTLS
CREATE TABLE "COMTNMENUCREATDTLS" 
   (	"MENU_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"MAPNG_CREAT_ID" VARCHAR2(30), 
	 CONSTRAINT "COMTNMENUCREATDTLS_PK" PRIMARY KEY ("MENU_NO", "AUTHOR_CODE")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNMENUINFO
CREATE TABLE "COMTNMENUINFO" 
   (	"MENU_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"MENU_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"UPPER_MENU_NO" NUMBER(20,0), 
	"MENU_ORDR" NUMBER(5,0) NOT NULL ENABLE, 
	"MENU_DC" VARCHAR2(250), 
	"RELATE_IMAGE_PATH" VARCHAR2(100), 
	"RELATE_IMAGE_NM" VARCHAR2(60), 
	"MENU_SE" VARCHAR2(20), 
	 CONSTRAINT "COMTNMENUINFO_PK" PRIMARY KEY ("MENU_NO")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNORGNZTINFO (2026-07-27 트리 전환: UPPER_ORGNZT_ID 자기참조 + ORDR 표시순서)
CREATE TABLE "COMTNORGNZTINFO"
   (	"ORGNZT_ID" CHAR(20) NOT NULL ENABLE,
	"ORGNZT_NM" VARCHAR2(255) NOT NULL ENABLE,
	"ORGNZT_DC" VARCHAR2(500),
	"UPPER_ORGNZT_ID" CHAR(20),
	"ORDR" NUMBER(5,0),
	 CONSTRAINT "COMTNORGNZTINFO_PK" PRIMARY KEY ("ORGNZT_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNPOPUPMANAGE
CREATE TABLE "COMTNPOPUPMANAGE" 
   (	"POPUP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"POPUP_SJ_NM" VARCHAR2(1024), 
	"FILE_URL" VARCHAR2(1024), 
	"POPUP_WIDTH_LC" VARCHAR2(20), 
	"POPUP_WIDTH_SIZE" NUMBER, 
	"NTCE_BGNDE" CHAR(20), 
	"NTCE_ENDDE" CHAR(20), 
	"STOPVEW_SETUP_AT" CHAR(1), 
	"NTCE_AT" CHAR(1), 
	"POPUP_VRTICL_LC" VARCHAR2(20), 
	"POPUP_VRTICL_SIZE" NUMBER, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"POPUP_CN" CLOB, 
	"CN_SE" VARCHAR2(1) DEFAULT 'F', 
	 CONSTRAINT "COMTNPOPUPMANAGE_PK" PRIMARY KEY ("POPUP_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNPRIVACYLOG
CREATE TABLE "COMTNPRIVACYLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"INQIRE_DT" DATE NOT NULL ENABLE, 
	"SRVC_NM" VARCHAR2(500), 
	"INQIRE_INFO" VARCHAR2(100), 
	"RQESTER_ID" VARCHAR2(20), 
	"RQESTER_IP" VARCHAR2(23), 
	 CONSTRAINT "REQUST_ID_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNPROGRMLIST
CREATE TABLE "COMTNPROGRMLIST" 
   (	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_STRE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	"PROGRM_KOREAN_NM" VARCHAR2(60), 
	"PROGRM_DC" VARCHAR2(200), 
	"URL" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNPROGRMLIST_PK" PRIMARY KEY ("PROGRM_FILE_NM")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNQAINFO
CREATE TABLE "COMTNQAINFO" 
   (	"QA_ID" CHAR(20) NOT NULL ENABLE, 
	"QESTN_SJ" VARCHAR2(255), 
	"QESTN_CN" VARCHAR2(2500), 
	"WRITNG_DE" CHAR(20), 
	"RDCNT" NUMBER(10,0), 
	"EMAIL_ADRES" VARCHAR2(50), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"QNA_PROCESS_STTUS_CODE" CHAR(1), 
	"WRTER_NM" VARCHAR2(20), 
	"ANSWER_CN" VARCHAR2(2500), 
	"WRITNG_PASSWORD" VARCHAR2(20), 
	"ANSWER_DE" CHAR(20), 
	"EMAIL_ANSWER_AT" CHAR(1), 
	"AREA_NO" VARCHAR2(4), 
	"MIDDLE_TELNO" VARCHAR2(4), 
	"END_TELNO" VARCHAR2(4), 
	 CONSTRAINT "COMTNQAINFO_PK" PRIMARY KEY ("QA_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNROLEINFO
CREATE TABLE "COMTNROLEINFO" 
   (	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"ROLE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"ROLE_PTTRN" VARCHAR2(300), 
	"ROLE_DC" VARCHAR2(200), 
	"ROLE_TY" VARCHAR2(80), 
	"ROLE_SORT" VARCHAR2(10), 
	"ROLE_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNROLEINFO_PK" PRIMARY KEY ("ROLE_CODE")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNROLES_HIERARCHY
CREATE TABLE "COMTNROLES_HIERARCHY" 
   (	"PARNTS_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	"CHLDRN_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNROLES_HIERARCHY_PK" PRIMARY KEY ("PARNTS_ROLE", "CHLDRN_ROLE")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNSITEMAP
CREATE TABLE "COMTNSITEMAP" 
   (	"MAPNG_CREAT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MAPNG_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"MAPNG_FILE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNSITEMAP_PK" PRIMARY KEY ("MAPNG_CREAT_ID")
  USING INDEX  ENABLE
   ) ;


-- TABLE COMTNSTSFDG
CREATE TABLE "COMTNSTSFDG" 
   (	"STSFDG_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"WRTER_ID" VARCHAR2(20),
	-- 표준 원형 20 → USER_NM(60) 초과 시 ORA-12899. 60 으로 확장(2026-07-10, 만족도 JSON UI)
	"WRTER_NM" VARCHAR2(60),
	"PASSWORD" VARCHAR2(200),
	"STSFDG" NUMBER(1,0) NOT NULL ENABLE,
	-- 표준 원형 200바이트(한글 약66자) → 1000 CHAR 로 확장(2026-07-10, UI 글자수 카운터)
	"STSFDG_CN" VARCHAR2(1000 CHAR),
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNSTSFDG_PK" PRIMARY KEY ("STSFDG_NO")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNSYSLOG
CREATE TABLE "COMTNSYSLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"JOB_SE_CODE" CHAR(3), 
	"INSTT_CODE" CHAR(7), 
	"OCCRRNC_DE" DATE, 
	"RQESTER_IP" VARCHAR2(23), 
	"RQESTER_ID" VARCHAR2(20), 
	"TRGET_MENU_NM" VARCHAR2(255), 
	"SVC_NM" VARCHAR2(255), 
	"METHOD_NM" VARCHAR2(60), 
	"PROCESS_SE_CODE" CHAR(3), 
	"PROCESS_CO" NUMBER(10,0), 
	"PROCESS_TIME" VARCHAR2(14), 
	"RSPNS_CODE" CHAR(3), 
	"ERROR_SE" CHAR(1), 
	"ERROR_CO" NUMBER(10,0), 
	"ERROR_CODE" CHAR(3), 
	 CONSTRAINT "COMTNSYSLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNTMPLATINFO
-- 게시판 템플릿 정본(2026-07 재정의): TMPLAT_SE_CODE=렌더엔진코드(COM005), TMPLAT_CONFIG_CN=표현설정(JSON)
CREATE TABLE "COMTNTMPLATINFO"
   (	"TMPLAT_ID" CHAR(20) NOT NULL ENABLE,
	"TMPLAT_NM" VARCHAR2(255),
	"TMPLAT_COURS" VARCHAR2(2000),
	"USE_AT" CHAR(1),
	"TMPLAT_SE_CODE" VARCHAR2(20),
	"TMPLAT_CONFIG_CN" VARCHAR2(2000),
	"FRST_REGISTER_ID" VARCHAR2(20),
	"FRST_REGIST_PNTTM" DATE,
	"LAST_UPDUSR_ID" VARCHAR2(20),
	"LAST_UPDT_PNTTM" DATE,
	 CONSTRAINT "COMTNTMPLATINFO_PK" PRIMARY KEY ("TMPLAT_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNUSERLOG
CREATE TABLE "COMTNUSERLOG" 
   (	"OCCRRNC_DE" CHAR(8) NOT NULL ENABLE, 
	"RQESTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"METHOD_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CREAT_CO" NUMBER(10,0), 
	"UPDT_CO" NUMBER(10,0), 
	"RDCNT" NUMBER(10,0), 
	"DELETE_CO" NUMBER(10,0), 
	"OUTPT_CO" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTNUSERLOG_PK" PRIMARY KEY ("OCCRRNC_DE", "RQESTER_ID", "SVC_NM", "METHOD_NM")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTNWEBLOG (2026-07-20 접속통계 확장: 기기/브라우저/세션 컬럼 + 일자 인덱스)
CREATE TABLE "COMTNWEBLOG"
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE,
	"OCCRRNC_DE" DATE,
	"URL" VARCHAR2(200),
	"RQESTER_ID" VARCHAR2(20),
	"RQESTER_IP" VARCHAR2(23),
	"DVICE_SE" VARCHAR2(10),
	"BROWSER_NM" VARCHAR2(30),
	"SESN_ID" VARCHAR2(60),
	 CONSTRAINT "COMTNWEBLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX  ENABLE
   ) ;
  CREATE INDEX "IX_COMTNWEBLOG_DT" ON "COMTNWEBLOG" ("OCCRRNC_DE")
  ;

-- TABLE COMTSSYSLOGSUMMARY
CREATE TABLE "COMTSSYSLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(8) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"METHOD_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CREAT_CO" NUMBER(10,0), 
	"UPDT_CO" NUMBER(10,0), 
	"RDCNT" NUMBER(10,0), 
	"DELETE_CO" NUMBER(10,0), 
	"OUTPT_CO" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTSSYSLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "SVC_NM", "METHOD_NM")
  USING INDEX  ENABLE
   ) ;

-- TABLE COMTSWEBLOGSUMMARY
CREATE TABLE "COMTSWEBLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(8) NOT NULL ENABLE, 
	"URL" VARCHAR2(200) NOT NULL ENABLE, 
	"RDCNT" NUMBER(10,0), 
	 CONSTRAINT "COMTSWEBLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "URL")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_ACT_LOG
CREATE TABLE "TB_ACT_LOG" 
   (	"IALOG_NO" NUMBER NOT NULL ENABLE, 
	"SREF_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"IREF_NO" NUMBER NOT NULL ENABLE, 
	"SNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"STASK" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"SINS_IP" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_ACT_LOG" ON "TB_ACT_LOG" ("IALOG_NO") 
  ;
ALTER TABLE "TB_ACT_LOG" ADD CONSTRAINT "PK_TB_ACT_LOG" PRIMARY KEY ("IALOG_NO")
  USING INDEX "PK_TB_ACT_LOG"  ENABLE;

-- TABLE TB_ATTACH
CREATE TABLE "TB_ATTACH" 
   (	"IATT_NO" NUMBER NOT NULL ENABLE, 
	"SCATE_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SREF_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"IREF_NO" NUMBER NOT NULL ENABLE, 
	"SPATH" VARCHAR2(255) NOT NULL ENABLE, 
	"SNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SMAPPING" VARCHAR2(255) NOT NULL ENABLE, 
	"SEXT" VARCHAR2(255) NOT NULL ENABLE, 
	"SMETA" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SCONTENTS" CLOB, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"ISIZE" NUMBER NOT NULL ENABLE,
	"SSYS_ID" VARCHAR2(255),
	-- (2026-07-30) 다운로드 집계. 상세 이력은 TB_ACT_LOG(STASK='파일 다운로드')가 별도로 남긴다.
	"IDOWN_CNT" NUMBER DEFAULT 0 NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_ATTACH" ON "TB_ATTACH" ("IATT_NO")
  ;
ALTER TABLE "TB_ATTACH" ADD CONSTRAINT "PK_TB_ATTACH" PRIMARY KEY ("IATT_NO")
  USING INDEX "PK_TB_ATTACH"  ENABLE;

-- TABLE TB_CATE
CREATE TABLE "TB_CATE" 
   (	"ICATE_NO" NUMBER NOT NULL ENABLE, 
	"SGUBUN_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SFULL_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"ILEVEL" NUMBER NOT NULL ENABLE, 
	"IREF" NUMBER NOT NULL ENABLE, 
	"IREF_LV_1" NUMBER NOT NULL ENABLE, 
	"IREF_LV_2" NUMBER NOT NULL ENABLE, 
	"IREF_LV_3" NUMBER NOT NULL ENABLE, 
	"IREF_LV_4" NUMBER NOT NULL ENABLE, 
	"IREF_LV_5" NUMBER NOT NULL ENABLE, 
	"IREF_LV_6" NUMBER NOT NULL ENABLE, 
	"IREF_LV_7" NUMBER NOT NULL ENABLE, 
	"IREF_LV_8" NUMBER NOT NULL ENABLE, 
	"IREF_LV_9" NUMBER NOT NULL ENABLE, 
	"IREF_LV_10" NUMBER NOT NULL ENABLE, 
	"SDISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_CATE" ON "TB_CATE" ("ICATE_NO") 
  ;
ALTER TABLE "TB_CATE" ADD CONSTRAINT "PK_TB_CATE" PRIMARY KEY ("ICATE_NO")
  USING INDEX "PK_TB_CATE"  ENABLE;

-- TABLE TB_CATE_OWNER
CREATE TABLE "TB_CATE_OWNER" 
   (	"ICATE_NO" NUMBER NOT NULL ENABLE, 
	"OWNER_TY" VARCHAR2(10) NOT NULL ENABLE, 
	"OWNER_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"INHERIT_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'), 
	"SINS_ID" VARCHAR2(50), 
	 CONSTRAINT "TB_CATE_OWNER_CK1" CHECK (OWNER_TY IN ('DEPT','USER')) ENABLE, 
	 CONSTRAINT "TB_CATE_OWNER_PK" PRIMARY KEY ("ICATE_NO", "OWNER_TY", "OWNER_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_CATE_READER
CREATE TABLE "TB_CATE_READER" 
   (	"ICATE_NO" NUMBER NOT NULL ENABLE, 
	"READER_TY" VARCHAR2(10) NOT NULL ENABLE, 
	"READER_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"INHERIT_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'), 
	"SINS_ID" VARCHAR2(50), 
	 CONSTRAINT "TB_CATE_READER_CK1" CHECK (READER_TY IN ('DEPT','USER')) ENABLE, 
	 CONSTRAINT "TB_CATE_READER_PK" PRIMARY KEY ("ICATE_NO", "READER_TY", "READER_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_DOCU
CREATE TABLE "TB_DOCU" 
   (	"IDOCU_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SCONTENTS" CLOB, 
	"SGAEJUNG_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"SDISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSTART_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SREASON" CLOB, 
	"SSEARCH_TEXT" CLOB, 
	"SSYS_ID" VARCHAR2(255), 
	"SGRP_TITLE" VARCHAR2(255) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_DOCU" ON "TB_DOCU" ("IDOCU_NO") 
  ;
ALTER TABLE "TB_DOCU" ADD CONSTRAINT "PK_TB_DOCU" PRIMARY KEY ("IDOCU_NO")
  USING INDEX "PK_TB_DOCU"  ENABLE;

-- (2026-07-30 폐기) TABLE TB_DOCU_FILE — 신규 DB·레거시 DB 양쪽 모두 0행이라 DROP.
--   별표/별지서식의 개별 첨부는 관련자료 축을 재사용한다:
--     TB_REL_VRSN(SFLAG='DOCUMENT', SFULL_ITEM=TB_DOCU.SITEM) → TB_REL_FILE → TB_ATTACH
--   삭제 연쇄는 TRG_DEL_DOCU(13_triggers_functions.sql)가 담당.

-- TABLE TB_FAVOR
CREATE TABLE "TB_FAVOR" 
   (	"IFAVOR_NO" NUMBER NOT NULL ENABLE, 
	"SGUBUN" VARCHAR2(255) NOT NULL ENABLE, 
	"ILAW_ID" NUMBER NOT NULL ENABLE, 
	"SITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"SDESC" VARCHAR2(4000) NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE,
	"SSYS_ID" VARCHAR2(255),
	"ISEEN_LAW_NO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PK_TB_FAVOR" ON "TB_FAVOR" ("IFAVOR_NO")
  ;
ALTER TABLE "TB_FAVOR" ADD CONSTRAINT "PK_TB_FAVOR" PRIMARY KEY ("IFAVOR_NO")
  USING INDEX "PK_TB_FAVOR"  ENABLE;

-- TABLE TB_GAEJUNG
CREATE TABLE "TB_GAEJUNG" 
   (	"IGAEJUNG_NO" NUMBER NOT NULL ENABLE, 
	"SNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SDIFF_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_GAEJUNG" ON "TB_GAEJUNG" ("IGAEJUNG_NO") 
  ;
ALTER TABLE "TB_GAEJUNG" ADD CONSTRAINT "PK_TB_GAEJUNG" PRIMARY KEY ("IGAEJUNG_NO")
  USING INDEX "PK_TB_GAEJUNG"  ENABLE;

-- TABLE TB_GAEJUNG_LOG
CREATE TABLE "TB_GAEJUNG_LOG" 
   (	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"IBUSEO_NO" NUMBER NOT NULL ENABLE, 
	"IUSER_NO" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_GAEJUNG_LOG" ON "TB_GAEJUNG_LOG" ("IPROM_NO") 
  ;
ALTER TABLE "TB_GAEJUNG_LOG" ADD CONSTRAINT "PK_TB_GAEJUNG_LOG" PRIMARY KEY ("IPROM_NO")
  USING INDEX "PK_TB_GAEJUNG_LOG"  ENABLE;

-- TABLE TB_GUBUN_READER
CREATE TABLE "TB_GUBUN_READER" 
   (	"SGUBUN_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"READER_TY" VARCHAR2(10) NOT NULL ENABLE, 
	"READER_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'), 
	"SINS_ID" VARCHAR2(50), 
	 CONSTRAINT "TB_GUBUN_READER_CK1" CHECK (READER_TY IN ('DEPT','USER')) ENABLE, 
	 CONSTRAINT "TB_GUBUN_READER_PK" PRIMARY KEY ("SGUBUN_ID", "READER_TY", "READER_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_LAWQUEST
CREATE TABLE "TB_LAWQUEST" 
   (	"NO" NUMBER(38,0) NOT NULL ENABLE, 
	"ID" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"YEAR" CHAR(4 CHAR) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"SOSOK" VARCHAR2(30 CHAR), 
	"GIGWAN" CHAR(30 CHAR), 
	"LAWER" VARCHAR2(50 CHAR), 
	"GUMAEK" NUMBER(10,0) NOT NULL ENABLE, 
	"ILJA1" CHAR(8 CHAR), 
	"ILJA2" CHAR(8 CHAR), 
	"SUBJECT" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"QUEST_CON" CLOB, 
	"RESPO_CON" CLOB, 
	"WRITEDAY" DATE NOT NULL ENABLE, 
	"READNUM" NUMBER(38,0) NOT NULL ENABLE, 
	"BUGET" VARCHAR2(200 CHAR), 
	"PUBLIC_YN" VARCHAR2(10) DEFAULT '2'
   ) ;
  CREATE UNIQUE INDEX "PK_COUNTLAW" ON "TB_LAWQUEST" ("NO") 
  ;
ALTER TABLE "TB_LAWQUEST" ADD CONSTRAINT "PK_COUNTLAW" PRIMARY KEY ("NO")
  USING INDEX "PK_COUNTLAW"  ENABLE;

-- TABLE TB_LAWQUEST_ADMIN
CREATE TABLE "TB_LAWQUEST_ADMIN" 
   (	"ADMIN_SABUN" VARCHAR2(20) NOT NULL ENABLE, 
	"ADMIN_NAME" VARCHAR2(30 CHAR)
   ) ;

-- TABLE TB_MEMO
CREATE TABLE "TB_MEMO" 
   (	"IMEMO_NO" NUMBER NOT NULL ENABLE, 
	"SGUBUN" VARCHAR2(255) NOT NULL ENABLE, 
	"ILAW_ID" NUMBER NOT NULL ENABLE, 
	"SITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"SDESC" VARCHAR2(4000) NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SBUSEO_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_MEMO" ON "TB_MEMO" ("IMEMO_NO") 
  ;
ALTER TABLE "TB_MEMO" ADD CONSTRAINT "PK_TB_MEMO" PRIMARY KEY ("IMEMO_NO")
  USING INDEX "PK_TB_MEMO"  ENABLE;

-- TABLE TB_PROM
CREATE TABLE "TB_PROM" 
   (	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SGUBUN_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"ICATE_NO" NUMBER NOT NULL ENABLE, 
	"IGAEJUNG_NO" NUMBER NOT NULL ENABLE, 
	"ILAW_ID" NUMBER NOT NULL ENABLE, 
	"ILAW_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SNUM" VARCHAR2(255) NOT NULL ENABLE, 
	"SPROM_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSTART_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SNULL_DT" VARCHAR2(255) NOT NULL ENABLE,
	"SNULL_DT_PEND" VARCHAR2(255),
	"SURL" VARCHAR2(255) NOT NULL ENABLE,
	"SPROV_FG" VARCHAR2(255) NOT NULL ENABLE,
	"SPROV_STYLE_CD" VARCHAR2(255) NOT NULL ENABLE, 
	"SPROV_FILE_NO" VARCHAR2(255) NOT NULL ENABLE, 
	"SDISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SEXISTING_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SGAEJUNG" CLOB, 
	"SREASON" CLOB, 
	"SBYLAW" CLOB, 
	"SSEARCH_TEXT" CLOB, 
	"ISEQ" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"SPREAMBLE" CLOB, 
	"SEXT_DISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"IBUSEO_NO" NUMBER NOT NULL ENABLE, 
	"SSTATUS" VARCHAR2(255) NOT NULL ENABLE, 
	"SDPL_ITEM_YN" VARCHAR2(255) NOT NULL ENABLE, 
	-- (2026-07-30 폐기) SSTOR_FILE_YN/DT/NM/PATH/DOC_NM/HWP_NM/PDF_NM 7종 —
	--   레거시는 회차별 원본 문서(DOC/HWP/PDF)를 미리 만들어 보관했으나 RLMS 는 저장하지 않는다.
	--   본문 문서는 /rlms/fulltext/exportProm.do 가 요청 시 PDF/DOCX/HWPX 로 생성(조 범위 발췌 포함).
	"SREL_FILE_VIEW_YN" VARCHAR2(255),
	"SSUB_TITLE" VARCHAR2(255),
	"SPARTY" VARCHAR2(4000),
	"SORDERIDX" NUMBER(3,0) DEFAULT 50,
	"SGAEJUNG_CODE" VARCHAR2(20),
	"SBUSEO_ORGNZT_ID" CHAR(20),
	"SSTSFDG_YN" VARCHAR2(255) DEFAULT 'N'
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROM" ON "TB_PROM" ("IPROM_NO") 
  ;
ALTER TABLE "TB_PROM" ADD CONSTRAINT "PK_TB_PROM" PRIMARY KEY ("IPROM_NO")
  USING INDEX "PK_TB_PROM"  ENABLE;

-- TABLE TB_PROM_ACT_LOG
CREATE TABLE "TB_PROM_ACT_LOG" 
   (	"IPALOG_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SREF_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"IREF_NO" VARCHAR2(255) NOT NULL ENABLE, 
	"SACT_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"SACT_NM" VARCHAR2(255), 
	"SACT_DC" VARCHAR2(4000) NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IPWRK_NO" NUMBER NOT NULL ENABLE, 
	"SFIELD_LOG" CLOB
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROM_ACT_LOG" ON "TB_PROM_ACT_LOG" ("IPALOG_NO") 
  ;
ALTER TABLE "TB_PROM_ACT_LOG" ADD CONSTRAINT "PK_TB_PROM_ACT_LOG" PRIMARY KEY ("IPALOG_NO")
  USING INDEX "PK_TB_PROM_ACT_LOG"  ENABLE;

-- TABLE TB_PROM_STSFDG (규정 만족도 조사 — 회차별 1인 1회, 2026-07-20 rlms_prom_stsfdg.sql)
CREATE TABLE "TB_PROM_STSFDG"
   (	"IPROM_NO" NUMBER NOT NULL ENABLE,
	"SINS_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISTSFDG" NUMBER(1,0) NOT NULL ENABLE,
	"SSTSFDG_CN" VARCHAR2(1000 CHAR),
	"SINS_DT" VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
	"SUPD_DT" VARCHAR2(14),
	 CONSTRAINT "TB_PROM_STSFDG_CK1" CHECK (ISTSFDG BETWEEN 1 AND 5) ENABLE,
	 CONSTRAINT "TB_PROM_STSFDG_PK" PRIMARY KEY ("IPROM_NO", "SINS_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_PROM_MAP
CREATE TABLE "TB_PROM_MAP"
   (	"IPMAP_NO" NUMBER NOT NULL ENABLE,
	"SSYS_ID" VARCHAR2(255),
	"SNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SFULL_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SPROM_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"ILEVEL" NUMBER NOT NULL ENABLE, 
	"IREF" NUMBER NOT NULL ENABLE, 
	"SDISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROM_MAP" ON "TB_PROM_MAP" ("IPMAP_NO") 
  ;
ALTER TABLE "TB_PROM_MAP" ADD CONSTRAINT "PK_TB_PROM_MAP" PRIMARY KEY ("IPMAP_NO")
  USING INDEX "PK_TB_PROM_MAP"  ENABLE;

-- TABLE TB_PROM_WRK
CREATE TABLE "TB_PROM_WRK" 
   (	"IPWRK_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"SSTATUS" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SREASON" CLOB, 
	"SACT_NM" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROM_WRK" ON "TB_PROM_WRK" ("IPWRK_NO") 
  ;
ALTER TABLE "TB_PROM_WRK" ADD CONSTRAINT "PK_TB_PROM_WRK" PRIMARY KEY ("IPWRK_NO")
  USING INDEX "PK_TB_PROM_WRK"  ENABLE;

-- TABLE TB_PROV_HTML
CREATE TABLE "TB_PROV_HTML" 
   (	"IPHTML_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SCONTENTS" CLOB, 
	"SGAEJUNG_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"SDISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSTART_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SREASON" CLOB, 
	"SSEARCH_TEXT" CLOB, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROV_HTML" ON "TB_PROV_HTML" ("IPHTML_NO") 
  ;
ALTER TABLE "TB_PROV_HTML" ADD CONSTRAINT "PK_TB_PROV_HTML" PRIMARY KEY ("IPHTML_NO")
  USING INDEX "PK_TB_PROV_HTML"  ENABLE;

-- TABLE TB_PROV_TEXT_HST
CREATE TABLE "TB_PROV_TEXT_HST" 
   (	"IPTHST_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255), 
	"SINS_DT" VARCHAR2(255), 
	"STEXT" CLOB
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROV_TEXT_HST" ON "TB_PROV_TEXT_HST" ("IPTHST_NO") 
  ;
ALTER TABLE "TB_PROV_TEXT_HST" ADD CONSTRAINT "PK_TB_PROV_TEXT_HST" PRIMARY KEY ("IPTHST_NO")
  USING INDEX "PK_TB_PROV_TEXT_HST"  ENABLE;

-- TABLE TB_PROV_VRSN
CREATE TABLE "TB_PROV_VRSN" 
   (	"IPVRSN_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"SFULL_ITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"SITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"SSUB_ITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"SSTYLE_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUNIT_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"SNATIVE_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"ILEVEL" NUMBER NOT NULL ENABLE, 
	"IINDEX" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(500), 
	"SREASON" CLOB, 
	"SCONTENTS" CLOB, 
	"SGAEJUNG_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"SDISP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSTART_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_MODIFIED_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SMOVE_FULL_ITEM" VARCHAR2(255), 
	"SSEARCH_TEXT" CLOB, 
	"SGAEJUNG_HIDE_YN" VARCHAR2(255), 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_PROV_VRSN" ON "TB_PROV_VRSN" ("IPVRSN_NO") 
  ;
ALTER TABLE "TB_PROV_VRSN" ADD CONSTRAINT "PK_TB_PROV_VRSN" PRIMARY KEY ("IPVRSN_NO")
  USING INDEX "PK_TB_PROV_VRSN"  ENABLE;

-- TABLE TB_READ_DUTY (필수 열람 지정 — 2026-07-28 rlms_read_duty.sql)
CREATE TABLE "TB_READ_DUTY"
   (	"IDUTY_NO" NUMBER NOT NULL ENABLE,
	"ILAW_ID" NUMBER NOT NULL ENABLE,
	"IPROM_NO" NUMBER NOT NULL ENABLE,
	"SALL_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"SDUE_DT" VARCHAR2(8),
	"SINS_ID" VARCHAR2(50),
	"SINS_NM" VARCHAR2(50),
	"SINS_DT" VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
	 CONSTRAINT "TB_READ_DUTY_CK1" CHECK (SALL_YN IN ('Y','N')) ENABLE,
	 CONSTRAINT "TB_READ_DUTY_PK" PRIMARY KEY ("IDUTY_NO")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_READ_DUTY_TGT (필수 열람 대상 행 — DEPT/USER 혼합)
CREATE TABLE "TB_READ_DUTY_TGT"
   (	"IDUTY_NO" NUMBER NOT NULL ENABLE,
	"STGT_TY" VARCHAR2(10) NOT NULL ENABLE,
	"STGT_ID" VARCHAR2(50) NOT NULL ENABLE,
	 CONSTRAINT "TB_READ_DUTY_TGT_CK1" CHECK (STGT_TY IN ('DEPT','USER')) ENABLE,
	 CONSTRAINT "TB_READ_DUTY_TGT_PK" PRIMARY KEY ("IDUTY_NO", "STGT_TY", "STGT_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_READ_DUTY_CHK (필수 열람 확인 — 열람 자동/숙지 버튼 2단계)
CREATE TABLE "TB_READ_DUTY_CHK"
   (	"IDUTY_NO" NUMBER NOT NULL ENABLE,
	"SUSER_ID" VARCHAR2(50) NOT NULL ENABLE,
	"SUSER_NM" VARCHAR2(50),
	"SORGNZT_ID" VARCHAR2(50),
	"SREAD_DT" VARCHAR2(14),
	"SCONF_DT" VARCHAR2(14),
	 CONSTRAINT "TB_READ_DUTY_CHK_PK" PRIMARY KEY ("IDUTY_NO", "SUSER_ID")
  USING INDEX  ENABLE
   ) ;

-- TABLE TB_REL_DMN_LNK
CREATE TABLE "TB_REL_DMN_LNK" 
   (	"IRDLNK_NO" NUMBER NOT NULL ENABLE, 
	"SFLAG" VARCHAR2(255) NOT NULL ENABLE, 
	"ILAW_ID" NUMBER NOT NULL ENABLE, 
	"SFULL_ITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"ILAW_NO" NUMBER NOT NULL ENABLE, 
	"SAWS_LST_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"IRVRSN_NO" VARCHAR2(255) NOT NULL ENABLE, 
	"SFILE_ITEM" NUMBER NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_DMN_LNK" ON "TB_REL_DMN_LNK" ("IRDLNK_NO") 
  ;
ALTER TABLE "TB_REL_DMN_LNK" ADD CONSTRAINT "PK_TB_REL_DMN_LNK" PRIMARY KEY ("IRDLNK_NO")
  USING INDEX "PK_TB_REL_DMN_LNK"  ENABLE;

-- TABLE TB_REL_EXCL_LNK
CREATE TABLE "TB_REL_EXCL_LNK" 
   (	"IRELNK_NO" NUMBER NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"SFLAG" VARCHAR2(255) NOT NULL ENABLE, 
	"SGUBUN_ID" VARCHAR2(255), 
	"ICATE_NO" NUMBER, 
	"ILAW_ID" NUMBER, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IEXCL_LAW_ID" NUMBER NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_EXCL_LNK" ON "TB_REL_EXCL_LNK" ("IRELNK_NO") 
  ;
ALTER TABLE "TB_REL_EXCL_LNK" ADD CONSTRAINT "PK_TB_REL_EXCL_LNK" PRIMARY KEY ("IRELNK_NO")
  USING INDEX "PK_TB_REL_EXCL_LNK"  ENABLE;

-- TABLE TB_REL_FILE
CREATE TABLE "TB_REL_FILE" 
   (	"IRFILE_NO" NUMBER NOT NULL ENABLE, 
	"IATT_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SCATE" VARCHAR2(255) NOT NULL ENABLE, 
	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"SVIEW_YN" VARCHAR2(255) DEFAULT 'N', 
	"SVIEW_CMPLT_YN" VARCHAR2(255) DEFAULT 'N'
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_FILE" ON "TB_REL_FILE" ("IRFILE_NO") 
  ;
ALTER TABLE "TB_REL_FILE" ADD CONSTRAINT "PK_TB_REL_FILE" PRIMARY KEY ("IRFILE_NO")
  USING INDEX "PK_TB_REL_FILE"  ENABLE;

-- TABLE TB_REL_HTML
CREATE TABLE "TB_REL_HTML" 
   (	"IRHTML_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SHTML" CLOB, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_HTML" ON "TB_REL_HTML" ("IRHTML_NO") 
  ;
ALTER TABLE "TB_REL_HTML" ADD CONSTRAINT "PK_TB_REL_HTML" PRIMARY KEY ("IRHTML_NO")
  USING INDEX "PK_TB_REL_HTML"  ENABLE;

-- TABLE TB_REL_IMG
CREATE TABLE "TB_REL_IMG" 
   (	"IRIMG_NO" NUMBER NOT NULL ENABLE, 
	"IATT_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_IMG" ON "TB_REL_IMG" ("IRIMG_NO") 
  ;
ALTER TABLE "TB_REL_IMG" ADD CONSTRAINT "PK_TB_REL_IMG" PRIMARY KEY ("IRIMG_NO")
  USING INDEX "PK_TB_REL_IMG"  ENABLE;

-- TABLE TB_REL_LNK
CREATE TABLE "TB_REL_LNK" 
   (	"IRLINK_NO" NUMBER NOT NULL ENABLE, 
	"SCATE" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SURL" VARCHAR2(255) NOT NULL ENABLE, 
	"IREF_NO" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"SREF_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_LNK" ON "TB_REL_LNK" ("IRLINK_NO") 
  ;
ALTER TABLE "TB_REL_LNK" ADD CONSTRAINT "PK_TB_REL_LNK" PRIMARY KEY ("IRLINK_NO")
  USING INDEX "PK_TB_REL_LNK"  ENABLE;

-- TABLE TB_REL_ORGN
CREATE TABLE "TB_REL_ORGN" 
   (	"IRORGN_NO" NUMBER NOT NULL ENABLE, 
	"IATT_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_ORGN" ON "TB_REL_ORGN" ("IRORGN_NO") 
  ;
ALTER TABLE "TB_REL_ORGN" ADD CONSTRAINT "PK_TB_REL_ORGN" PRIMARY KEY ("IRORGN_NO")
  USING INDEX "PK_TB_REL_ORGN"  ENABLE;

-- TABLE TB_REL_VRSN
CREATE TABLE "TB_REL_VRSN" 
   (	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"IPROM_NO" NUMBER NOT NULL ENABLE, 
	"ICTNS_ID" NUMBER NOT NULL ENABLE, 
	"SVRSN_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"STABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SFLAG" VARCHAR2(255) NOT NULL ENABLE, 
	"SFULL_ITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(4000) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SURL" VARCHAR2(255), 
	"IRVCATE_NO" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"IRVCATE_NM" VARCHAR2(100) DEFAULT '미선택', 
	"IRVCATE_ODR" NUMBER(10,0) DEFAULT 0
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_VRSN" ON "TB_REL_VRSN" ("IRVRSN_NO") 
  ;
ALTER TABLE "TB_REL_VRSN" ADD CONSTRAINT "PK_TB_REL_VRSN" PRIMARY KEY ("IRVRSN_NO")
  USING INDEX "PK_TB_REL_VRSN"  ENABLE;

-- TABLE TB_REL_VRSN_CATE
CREATE TABLE "TB_REL_VRSN_CATE" 
   (	"IRVCATE_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"ISEQ" NUMBER NOT NULL ENABLE, 
	"SHIDE_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"ILAW_ID" NUMBER NOT NULL ENABLE, 
	"STEMP" VARCHAR2(255), 
	"SORGNDOWN_YN" VARCHAR2(255) DEFAULT 'Y'
   ) ;
  CREATE UNIQUE INDEX "PK_TB_REL_VRSN_CATE" ON "TB_REL_VRSN_CATE" ("IRVCATE_NO") 
  ;
ALTER TABLE "TB_REL_VRSN_CATE" ADD CONSTRAINT "PK_TB_REL_VRSN_CATE" PRIMARY KEY ("IRVCATE_NO")
  USING INDEX "PK_TB_REL_VRSN_CATE"  ENABLE;

-- TABLE TB_REL_WORD
CREATE TABLE "TB_REL_WORD" 
   (	"IRWORD_NO" NUMBER NOT NULL ENABLE, 
	"IATT_NO" NUMBER NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SHTML" CLOB, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"IRVRSN_NO" NUMBER NOT NULL ENABLE, 
	"STYPE" VARCHAR2(255), 
	"SDEL_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SSEARCH_TEXT" CLOB, 
	"SSYS_ID" VARCHAR2(255), 
	"SHTML_PATH" VARCHAR2(255), 
	"SSEARCH_TEXT_PATH" VARCHAR2(255), 
	"SCLOB_FILE_YN" VARCHAR2(255) DEFAULT 'N', 
	"SPATH" VARCHAR2(255)
   ) ;

-- TABLE TB_SRC_STORED
CREATE TABLE "TB_SRC_STORED" 
   (	"ISSTOR_NO" NUMBER NOT NULL ENABLE, 
	"SREF_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SREF_ITEM" VARCHAR2(255) NOT NULL ENABLE, 
	"SGUBUN" VARCHAR2(255) NOT NULL ENABLE, 
	"SFLAG" VARCHAR2(255) NOT NULL ENABLE, 
	"STITLE" VARCHAR2(255) NOT NULL ENABLE, 
	"SFULL_TITLE" VARCHAR2(4000) NOT NULL ENABLE, 
	"SCONTENTS" CLOB, 
	"SLAW_URL" VARCHAR2(500) NOT NULL ENABLE, 
	"SCONTENTS_URL" VARCHAR2(500) NOT NULL ENABLE, 
	"SPOPUP_YN" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"ILAW_ID" NUMBER NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_SRC_STORED" ON "TB_SRC_STORED" ("ISSTOR_NO") 
  ;
ALTER TABLE "TB_SRC_STORED" ADD CONSTRAINT "PK_TB_SRC_STORED" PRIMARY KEY ("ISSTOR_NO")
  USING INDEX "PK_TB_SRC_STORED"  ENABLE;

-- TABLE TB_STATS_BBS_VIEW (2026-07-20 신설 — 게시판 조회통계 적재)
CREATE TABLE "TB_STATS_BBS_VIEW"
   (	"ISBVIEW_NO" NUMBER NOT NULL ENABLE,
	"SBBS_ID" VARCHAR2(30) NOT NULL ENABLE,
	"INTT_ID" NUMBER NOT NULL ENABLE,
	"ICNT" NUMBER NOT NULL ENABLE,
	"SINS_DT" VARCHAR2(10) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_STATS_BBS_VIEW" ON "TB_STATS_BBS_VIEW" ("ISBVIEW_NO")
  ;
ALTER TABLE "TB_STATS_BBS_VIEW" ADD CONSTRAINT "PK_TB_STATS_BBS_VIEW" PRIMARY KEY ("ISBVIEW_NO")
  USING INDEX "PK_TB_STATS_BBS_VIEW"  ENABLE;

-- TABLE TB_STATS_FT_VIEW
CREATE TABLE "TB_STATS_FT_VIEW" 
   (	"SGUBUN_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"ISFVIEW_NO" NUMBER NOT NULL ENABLE, 
	"ICNT" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"ILAW_ID" NUMBER NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "PK_TB_STATS_FT_VIEW" ON "TB_STATS_FT_VIEW" ("ISFVIEW_NO") 
  ;
ALTER TABLE "TB_STATS_FT_VIEW" ADD CONSTRAINT "PK_TB_STATS_FT_VIEW" PRIMARY KEY ("ISFVIEW_NO")
  USING INDEX "PK_TB_STATS_FT_VIEW"  ENABLE;

-- TABLE TB_STATS_KWD
CREATE TABLE "TB_STATS_KWD" 
   (	"ISKWD_NO" NUMBER NOT NULL ENABLE, 
	"SKWD" VARCHAR2(255) NOT NULL ENABLE, 
	"ICNT" NUMBER NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255)
   ) ;
  CREATE UNIQUE INDEX "PK_TB_STATS_KWD" ON "TB_STATS_KWD" ("ISKWD_NO") 
  ;
ALTER TABLE "TB_STATS_KWD" ADD CONSTRAINT "PK_TB_STATS_KWD" PRIMARY KEY ("ISKWD_NO")
  USING INDEX "PK_TB_STATS_KWD"  ENABLE;

-- VIEW COMVNUSERMASTER
CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "COMVNUSERMASTER" ("ESNTL_ID", "USER_ID", "PASSWORD", "USER_NM", "USER_ZIP", "USER_ADRES", "USER_EMAIL", "GROUP_ID", "USER_SE", "ORGNZT_ID") AS 
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR' AS USER_SE, ORGNZT_ID
    FROM COMTNGNRLMBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
    FROM COMTNEMPLYRINFO;


--------------------------------------------------------------------------------
-- 합성 테이블 1종 — 레거시 운영 DB 에 없으나 라이브 필수 경로가 참조.
-- (죽은 흐름용 방어 테이블 6종은 2026-07-10 사용자 확정으로 제외 — 미생성 목록은 README 참조)
--------------------------------------------------------------------------------

-- COMTHEMPLYRINFOCHANGEDTLS (합성 근거: mapper\com\uss\umt\EgovUserManage_SQL_oracle.xml insertUserHistory —
--   사용자정보 수정 이력. 레거시 COMTN- 변형 구조 1:1, 매퍼가 쓰는 COMTH- 이름으로 생성)
CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID           VARCHAR2(20)   NOT NULL,
  CHANGE_DE           CHAR(20)       NOT NULL,
  ORGNZT_ID           CHAR(20),
  GROUP_ID            CHAR(20),
  EMPL_NO             VARCHAR2(20),
  SEXDSTN_CODE        CHAR(1),
  BRTHDY              CHAR(20),
  FXNUM               VARCHAR2(20),
  HOUSE_ADRES         VARCHAR2(100),
  HOUSE_END_TELNO     VARCHAR2(4),
  AREA_NO             VARCHAR2(4),
  DETAIL_ADRES        VARCHAR2(100),
  ZIP                 VARCHAR2(6),
  OFFM_TELNO          VARCHAR2(20),
  MBTLNUM             VARCHAR2(20),
  EMAIL_ADRES         VARCHAR2(50),
  HOUSE_MIDDLE_TELNO  VARCHAR2(4),
  PSTINST_CODE        CHAR(8),
  EMPLYR_STTUS_CODE   CHAR(1),
  ESNTL_ID            CHAR(20),
  CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE)
);

-- 브랜드설정 — 로고(텍스트/이미지)·파비콘. 고객사별 리브랜딩 지점, BRAND_ID='S' 단일 행 (2026-07-31)
CREATE TABLE COM_BRAND (
  BRAND_ID              CHAR(1)       NOT NULL,
  LOGO_TY_CODE          VARCHAR2(10)  DEFAULT 'TEXT' NOT NULL,
  LOGO_TEXT             VARCHAR2(300),
  LOGO_ATCH_FILE_ID     CHAR(20),
  FAVICON_ATCH_FILE_ID  CHAR(20),
  LAST_UPDUSR_ID        VARCHAR2(20),
  LAST_UPDT_PNTTM       DATE,
  CONSTRAINT PK_COM_BRAND PRIMARY KEY (BRAND_ID)
);
