--------------------------------------------------------------------------------
-- 10_tables.sql — 공통 테이블 46종 + 로그인 뷰 COMVNUSERMASTER
-- LexPortal(송무 단독) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: lexportal. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 원천: DBMS_METADATA.GET_DDL (스키마 한정자/스토리지 절 제거). 합성 1종(COMTH 변경이력)은 후반부.
--------------------------------------------------------------------------------


-- TABLE COMTCCMMNCODE
CREATE TABLE "COMTCCMMNCODE" 
   (	"CODE_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CODE_ID_NM" VARCHAR2(60), 
	"CODE_ID_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"CL_CODE" CHAR(3), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNCODE_PK" PRIMARY KEY ("CODE_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTCCMMNDETAILCODE
CREATE TABLE "COMTCCMMNDETAILCODE" 
   (	"CODE_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"CODE_NM" VARCHAR2(60), 
	"CODE_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNDETAILCODE_PK" PRIMARY KEY ("CODE_ID", "CODE")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTECOPSEQ
CREATE TABLE "COMTECOPSEQ" 
   (	"TABLE_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"NEXT_ID" NUMBER(30,0), 
	 CONSTRAINT "COMTECOPSEQ_PK" PRIMARY KEY ("TABLE_NAME")
  USING INDEX  ENABLE
   ) ;




-- TABLE COMTNAUTHORGROUPINFO
CREATE TABLE "COMTNAUTHORGROUPINFO" 
   (	"GROUP_ID" CHAR(20) NOT NULL ENABLE, 
	"GROUP_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"GROUP_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	"GROUP_DC" VARCHAR2(100), 
	 CONSTRAINT "COMTNAUTHORGROUPINFO_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNAUTHORINFO
CREATE TABLE "COMTNAUTHORINFO" 
   (	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHOR_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"AUTHOR_DC" VARCHAR2(200), 
	"AUTHOR_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNAUTHORINFO_PK" PRIMARY KEY ("AUTHOR_CODE")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNAUTHORROLERELATE
CREATE TABLE "COMTNAUTHORROLERELATE" 
   (	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"CREAT_DT" DATE, 
	 CONSTRAINT "COMTNAUTHORROLERELATE_PK" PRIMARY KEY ("AUTHOR_CODE", "ROLE_CODE")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNBANNER
CREATE TABLE "COMTNBANNER" 
   (	"BANNER_ID" CHAR(20) NOT NULL ENABLE, 
	"BANNER_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"LINK_URL" VARCHAR2(255) NOT NULL ENABLE, 
	"BANNER_IMAGE" VARCHAR2(60) NOT NULL ENABLE, 
	"BANNER_DC" VARCHAR2(200), 
	"REFLCT_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"BANNER_IMAGE_FILE" VARCHAR2(60), 
	"SORT_ORDR" NUMBER(8,0), 
	 CONSTRAINT "COMTNBANNER_PK" PRIMARY KEY ("BANNER_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNBBS
CREATE TABLE "COMTNBBS" 
   (	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"NTT_NO" NUMBER(20,0), 
	"NTT_SJ" VARCHAR2(2000), 
	"NTT_CN" CLOB, 
	"ANSWER_AT" CHAR(1), 
	"PARNTSCTT_NO" NUMBER(10,0), 
	"ANSWER_LC" NUMBER(8,0), 
	"SORT_ORDR" NUMBER(8,0), 
	"RDCNT" NUMBER(10,0), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"NTCE_BGNDE" CHAR(20), 
	"NTCE_ENDDE" CHAR(20), 
	"NTCR_ID" VARCHAR2(20), 
	"NTCR_NM" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(200), 
	"ATCH_FILE_ID" CHAR(20), 
	"NOTICE_AT" CHAR(1), 
	"SJ_BOLD_AT" CHAR(1), 
	"SECRET_AT" CHAR(1), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"BLOG_ID" CHAR(20), 
	"NTT_EXTRA_FIELD_1" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_2" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_3" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_4" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_5" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_6" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_7" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_8" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_9" VARCHAR2(200), 
	"NTT_EXTRA_FIELD_10" VARCHAR2(200), 
	 CONSTRAINT "COMTNBBS_PK" PRIMARY KEY ("NTT_ID", "BBS_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNBBSMASTER
CREATE TABLE "COMTNBBSMASTER" 
   (	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"BBS_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"BBS_INTRCN" VARCHAR2(2400), 
	"BBS_TY_CODE" CHAR(6) NOT NULL ENABLE, 
	"REPLY_POSBL_AT" CHAR(1), 
	"FILE_ATCH_POSBL_AT" CHAR(1) NOT NULL ENABLE, 
	"ATCH_POSBL_FILE_NUMBER" NUMBER(2,0) NOT NULL ENABLE, 
	"ATCH_POSBL_FILE_SIZE" NUMBER(8,0), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"TMPLAT_ID" CHAR(20), 
	"CMMNTY_ID" CHAR(20), 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"BLOG_ID" CHAR(20), 
	"BLOG_AT" CHAR(2), 
	"BBS_SKIN_CODE" VARCHAR2(30) DEFAULT 'BASIC', 
	"BBS_EXTRA_FIELD_1" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_2" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_3" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_4" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_5" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_6" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_7" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_8" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_9" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_10" VARCHAR2(200), 
	"BBS_EXTRA_FIELD_TYPE_1" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_2" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_3" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_4" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_5" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_6" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_7" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_8" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_9" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_TYPE_10" VARCHAR2(20) DEFAULT 'text', 
	"BBS_EXTRA_FIELD_CODE_ID_1" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_2" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_3" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_4" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_5" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_6" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_7" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_8" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_9" VARCHAR2(30), 
	"BBS_EXTRA_FIELD_CODE_ID_10" VARCHAR2(30),
	"LIST_PAGE_UNIT" VARCHAR2(50),
	"SECRET_POSBL_AT" CHAR(1) DEFAULT 'Y',
	"RICH_EDITOR_AT" CHAR(1) DEFAULT 'Y',
	"SEARCH_INCLD_AT" CHAR(1) DEFAULT 'Y',
	"PAGING_AT" CHAR(1) DEFAULT 'Y',
	"SEARCH_BOX_AT" CHAR(1) DEFAULT 'Y',
	 CONSTRAINT "COMTNBBSMASTER_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNBBSMASTEROPTN
CREATE TABLE "COMTNBBSMASTEROPTN" 
   (	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"ANSWER_AT" CHAR(1) NOT NULL ENABLE, 
	"STSFDG_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNBBSMASTEROPTN_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX  ENABLE
   ) ;





-- 게시판별 작성권한. 열람권한은 메뉴 역할매핑(COMTNMENUCREATDTLS)이 원천이지만,
-- "메뉴가 보인다"와 "글을 쓸 수 있다"는 다른 축이라 별도 매핑이 필요하다.
CREATE TABLE COMTNBBSWRITEAUTHOR (
	BBS_ID      CHAR(30)     NOT NULL,
	AUTHOR_CODE VARCHAR2(30) NOT NULL,
	CONSTRAINT COMTNBBSWRITEAUTHOR_PK PRIMARY KEY (BBS_ID, AUTHOR_CODE)
);



-- TABLE COMTNCOMMENT
CREATE TABLE "COMTNCOMMENT" 
   (	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"ANSWER_NO" NUMBER(20,0) NOT NULL ENABLE,
	"WRTER_ID" VARCHAR2(20),
	-- 표준 원형은 VARCHAR2(20) 이라 USER_NM(60) 이 긴 사용자는 ORA-12899 → 60 으로 확장(2026-07-10)
	"WRTER_NM" VARCHAR2(60),
	-- 표준 원형은 VARCHAR2(200)(바이트) 이라 한글 약 66자에서 ORA-12899 → 문자기준 1000 으로 확장(2026-07-10, UI 글자수 카운터)
	"ANSWER" VARCHAR2(1000 CHAR),
	"USE_AT" CHAR(1) NOT NULL ENABLE,
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE,
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(200), 
	 CONSTRAINT "COMTNCOMMENT_PK" PRIMARY KEY ("NTT_ID", "BBS_ID", "ANSWER_NO")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNEMPLYRINFO
CREATE TABLE "COMTNEMPLYRINFO" 
   (	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGNZT_ID" CHAR(20), 
	"USER_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"EMPL_NO" VARCHAR2(20), 
	"IHIDNUM" VARCHAR2(200), 
	"SEXDSTN_CODE" CHAR(1), 
	"BRTHDY" CHAR(20), 
	"FXNUM" VARCHAR2(20), 
	"HOUSE_ADRES" VARCHAR2(100), 
	"PASSWORD_HINT" VARCHAR2(100), 
	"PASSWORD_CNSR" VARCHAR2(100), 
	"HOUSE_END_TELNO" VARCHAR2(4), 
	"AREA_NO" VARCHAR2(4), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"ZIP" VARCHAR2(6), 
	"OFFM_TELNO" VARCHAR2(20), 
	"MBTLNUM" VARCHAR2(20), 
	"EMAIL_ADRES" VARCHAR2(50), 
	"OFCPS_NM" VARCHAR2(60), 
	"HOUSE_MIDDLE_TELNO" VARCHAR2(4), 
	"GROUP_ID" CHAR(20), 
	"PSTINST_CODE" CHAR(8), 
	"EMPLYR_STTUS_CODE" CHAR(1) NOT NULL ENABLE, 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	"CRTFC_DN_VALUE" VARCHAR2(100), 
	"SBSCRB_DE" DATE, 
	"LOCK_AT" CHAR(1), 
	"LOCK_CNT" NUMBER(3,0), 
	"LOCK_LAST_PNTTM" DATE, 
	"CHG_PWD_LAST_PNTTM" DATE, 
	 CONSTRAINT "COMTNEMPLYRINFO_PK" PRIMARY KEY ("EMPLYR_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNEMPLYRSCRTYESTBS
CREATE TABLE "COMTNEMPLYRSCRTYESTBS" 
   (	"SCRTY_DTRMN_TRGET_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MBER_TY_CODE" CHAR(5), 
	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNEMPLYRSCRTYESTBS_PK" PRIMARY KEY ("SCRTY_DTRMN_TRGET_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNFAQINFO
CREATE TABLE "COMTNFAQINFO" 
   (	"FAQ_ID" CHAR(20) NOT NULL ENABLE, 
	"QESTN_SJ" VARCHAR2(255), 
	"QESTN_CN" VARCHAR2(2500), 
	"ANSWER_CN" VARCHAR2(2500), 
	"RDCNT" NUMBER(10,0), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ATCH_FILE_ID" CHAR(20), 
	"QNA_PROCESS_STTUS_CODE" CHAR(1), 
	"FAQ_CODE" VARCHAR2(15), 
	 CONSTRAINT "COMTNFAQINFO_PK" PRIMARY KEY ("FAQ_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNFILE
CREATE TABLE "COMTNFILE" 
   (	"ATCH_FILE_ID" CHAR(20) NOT NULL ENABLE, 
	"CREAT_DT" DATE NOT NULL ENABLE, 
	"USE_AT" CHAR(1), 
	 CONSTRAINT "COMTNFILE_PK" PRIMARY KEY ("ATCH_FILE_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNFILEDETAIL
CREATE TABLE "COMTNFILEDETAIL" 
   (	"ATCH_FILE_ID" CHAR(20) NOT NULL ENABLE, 
	"FILE_SN" NUMBER(10,0) NOT NULL ENABLE, 
	"FILE_STRE_COURS" VARCHAR2(2000) NOT NULL ENABLE, 
	"STRE_FILE_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"ORIGNL_FILE_NM" VARCHAR2(255), 
	"FILE_EXTSN" VARCHAR2(20) NOT NULL ENABLE,
	"FILE_CN" CLOB,
	"FILE_SIZE" NUMBER(8,0),
	"DWLD_CO" NUMBER(8,0) DEFAULT 0,
	 CONSTRAINT "COMTNFILEDETAIL_PK" PRIMARY KEY ("ATCH_FILE_ID", "FILE_SN")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNGNRLMBER
CREATE TABLE "COMTNGNRLMBER" 
   (	"MBER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"PASSWORD_HINT" VARCHAR2(100), 
	"PASSWORD_CNSR" VARCHAR2(100), 
	"IHIDNUM" VARCHAR2(200), 
	"MBER_NM" VARCHAR2(50) NOT NULL ENABLE, 
	"ZIP" VARCHAR2(6), 
	"ADRES" VARCHAR2(100), 
	"AREA_NO" VARCHAR2(4) NOT NULL ENABLE, 
	"MBER_STTUS" VARCHAR2(15), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"END_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"MBTLNUM" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" CHAR(20), 
	"MBER_FXNUM" VARCHAR2(20), 
	"MBER_EMAIL_ADRES" VARCHAR2(50), 
	"MIDDLE_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"SBSCRB_DE" DATE, 
	"SEXDSTN_CODE" CHAR(1), 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	"LOCK_AT" CHAR(1), 
	"LOCK_CNT" NUMBER(3,0), 
	"LOCK_LAST_PNTTM" DATE, 
	"CHG_PWD_LAST_PNTTM" DATE,
	"ORGNZT_ID" VARCHAR2(20),
	"EMPL_NO" VARCHAR2(20),
	 CONSTRAINT "COMTNGNRLMBER_PK" PRIMARY KEY ("MBER_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNLOGINLOG
CREATE TABLE "COMTNLOGINLOG" 
   (	"LOG_ID" CHAR(20) NOT NULL ENABLE, 
	"CONECT_ID" VARCHAR2(20), 
	"CONECT_IP" VARCHAR2(23), 
	"CONECT_MTHD" CHAR(4), 
	"ERROR_OCCRRNC_AT" CHAR(1), 
	"ERROR_CODE" CHAR(3), 
	"CREAT_DT" DATE, 
	 CONSTRAINT "COMTNLOGINLOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNLOGINPOLICY
CREATE TABLE "COMTNLOGINPOLICY" 
   (	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"IP_INFO" VARCHAR2(23) NOT NULL ENABLE, 
	"DPLCT_PERM_AT" CHAR(1) NOT NULL ENABLE, 
	"LMTT_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	 CONSTRAINT "COMTNLOGINPOLICY_PK" PRIMARY KEY ("EMPLYR_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNMENUCREATDTLS
CREATE TABLE "COMTNMENUCREATDTLS" 
   (	"MENU_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"MAPNG_CREAT_ID" VARCHAR2(30), 
	 CONSTRAINT "COMTNMENUCREATDTLS_PK" PRIMARY KEY ("MENU_NO", "AUTHOR_CODE")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNMENUINFO
CREATE TABLE "COMTNMENUINFO" 
   (	"MENU_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"MENU_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"UPPER_MENU_NO" NUMBER(20,0), 
	"MENU_ORDR" NUMBER(5,0) NOT NULL ENABLE, 
	"MENU_DC" VARCHAR2(250), 
	"RELATE_IMAGE_PATH" VARCHAR2(100), 
	"RELATE_IMAGE_NM" VARCHAR2(60), 
	"MENU_SE" VARCHAR2(20), 
	 CONSTRAINT "COMTNMENUINFO_PK" PRIMARY KEY ("MENU_NO")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNORGNZTINFO (2026-07-27 트리 전환: UPPER_ORGNZT_ID 자기참조 + ORDR 표시순서)
CREATE TABLE "COMTNORGNZTINFO"
   (	"ORGNZT_ID" CHAR(20) NOT NULL ENABLE,
	"ORGNZT_NM" VARCHAR2(255) NOT NULL ENABLE,
	"ORGNZT_DC" VARCHAR2(500),
	"UPPER_ORGNZT_ID" CHAR(20),
	"ORDR" NUMBER(5,0),
	 CONSTRAINT "COMTNORGNZTINFO_PK" PRIMARY KEY ("ORGNZT_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNPOPUPMANAGE
CREATE TABLE "COMTNPOPUPMANAGE" 
   (	"POPUP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"POPUP_SJ_NM" VARCHAR2(1024), 
	"FILE_URL" VARCHAR2(1024), 
	"POPUP_WIDTH_LC" VARCHAR2(20), 
	"POPUP_WIDTH_SIZE" NUMBER, 
	"NTCE_BGNDE" CHAR(20), 
	"NTCE_ENDDE" CHAR(20), 
	"STOPVEW_SETUP_AT" CHAR(1), 
	"NTCE_AT" CHAR(1), 
	"POPUP_VRTICL_LC" VARCHAR2(20), 
	"POPUP_VRTICL_SIZE" NUMBER, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"POPUP_CN" CLOB, 
	"CN_SE" VARCHAR2(1) DEFAULT 'F', 
	 CONSTRAINT "COMTNPOPUPMANAGE_PK" PRIMARY KEY ("POPUP_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNPRIVACYLOG
CREATE TABLE "COMTNPRIVACYLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"INQIRE_DT" DATE NOT NULL ENABLE, 
	"SRVC_NM" VARCHAR2(500), 
	"INQIRE_INFO" VARCHAR2(100), 
	"RQESTER_ID" VARCHAR2(20), 
	"RQESTER_IP" VARCHAR2(23), 
	 CONSTRAINT "REQUST_ID_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNPROGRMLIST
CREATE TABLE "COMTNPROGRMLIST" 
   (	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_STRE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	"PROGRM_KOREAN_NM" VARCHAR2(60), 
	"PROGRM_DC" VARCHAR2(200), 
	"URL" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNPROGRMLIST_PK" PRIMARY KEY ("PROGRM_FILE_NM")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNQAINFO
CREATE TABLE "COMTNQAINFO" 
   (	"QA_ID" CHAR(20) NOT NULL ENABLE, 
	"QESTN_SJ" VARCHAR2(255), 
	"QESTN_CN" VARCHAR2(2500), 
	"WRITNG_DE" CHAR(20), 
	"RDCNT" NUMBER(10,0), 
	"EMAIL_ADRES" VARCHAR2(50), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"QNA_PROCESS_STTUS_CODE" CHAR(1), 
	"WRTER_NM" VARCHAR2(20), 
	"ANSWER_CN" VARCHAR2(2500), 
	"WRITNG_PASSWORD" VARCHAR2(20), 
	"ANSWER_DE" CHAR(20), 
	"EMAIL_ANSWER_AT" CHAR(1), 
	"AREA_NO" VARCHAR2(4), 
	"MIDDLE_TELNO" VARCHAR2(4), 
	"END_TELNO" VARCHAR2(4), 
	 CONSTRAINT "COMTNQAINFO_PK" PRIMARY KEY ("QA_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNROLEINFO
CREATE TABLE "COMTNROLEINFO" 
   (	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"ROLE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"ROLE_PTTRN" VARCHAR2(300), 
	"ROLE_DC" VARCHAR2(200), 
	"ROLE_TY" VARCHAR2(80), 
	"ROLE_SORT" VARCHAR2(10), 
	"ROLE_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNROLEINFO_PK" PRIMARY KEY ("ROLE_CODE")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNROLES_HIERARCHY
CREATE TABLE "COMTNROLES_HIERARCHY" 
   (	"PARNTS_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	"CHLDRN_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNROLES_HIERARCHY_PK" PRIMARY KEY ("PARNTS_ROLE", "CHLDRN_ROLE")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNSITEMAP
CREATE TABLE "COMTNSITEMAP" 
   (	"MAPNG_CREAT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MAPNG_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"MAPNG_FILE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNSITEMAP_PK" PRIMARY KEY ("MAPNG_CREAT_ID")
  USING INDEX  ENABLE
   ) ;




-- TABLE COMTNSTSFDG
CREATE TABLE "COMTNSTSFDG" 
   (	"STSFDG_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(30) NOT NULL ENABLE, 
	"WRTER_ID" VARCHAR2(20),
	-- 표준 원형 20 → USER_NM(60) 초과 시 ORA-12899. 60 으로 확장(2026-07-10, 만족도 JSON UI)
	"WRTER_NM" VARCHAR2(60),
	"PASSWORD" VARCHAR2(200),
	"STSFDG" NUMBER(1,0) NOT NULL ENABLE,
	-- 표준 원형 200바이트(한글 약66자) → 1000 CHAR 로 확장(2026-07-10, UI 글자수 카운터)
	"STSFDG_CN" VARCHAR2(1000 CHAR),
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNSTSFDG_PK" PRIMARY KEY ("STSFDG_NO")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNSYSLOG
CREATE TABLE "COMTNSYSLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"JOB_SE_CODE" CHAR(3), 
	"INSTT_CODE" CHAR(7), 
	"OCCRRNC_DE" DATE, 
	"RQESTER_IP" VARCHAR2(23), 
	"RQESTER_ID" VARCHAR2(20), 
	"TRGET_MENU_NM" VARCHAR2(255), 
	"SVC_NM" VARCHAR2(255), 
	"METHOD_NM" VARCHAR2(60), 
	"PROCESS_SE_CODE" CHAR(3), 
	"PROCESS_CO" NUMBER(10,0), 
	"PROCESS_TIME" VARCHAR2(14), 
	"RSPNS_CODE" CHAR(3), 
	"ERROR_SE" CHAR(1), 
	"ERROR_CO" NUMBER(10,0), 
	"ERROR_CODE" CHAR(3), 
	 CONSTRAINT "COMTNSYSLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNTMPLATINFO
-- 게시판 템플릿 정본(2026-07 재정의): TMPLAT_SE_CODE=렌더엔진코드(COM005), TMPLAT_CONFIG_CN=표현설정(JSON)
CREATE TABLE "COMTNTMPLATINFO"
   (	"TMPLAT_ID" CHAR(20) NOT NULL ENABLE,
	"TMPLAT_NM" VARCHAR2(255),
	"TMPLAT_COURS" VARCHAR2(2000),
	"USE_AT" CHAR(1),
	"TMPLAT_SE_CODE" VARCHAR2(20),
	"TMPLAT_CONFIG_CN" VARCHAR2(2000),
	"FRST_REGISTER_ID" VARCHAR2(20),
	"FRST_REGIST_PNTTM" DATE,
	"LAST_UPDUSR_ID" VARCHAR2(20),
	"LAST_UPDT_PNTTM" DATE,
	 CONSTRAINT "COMTNTMPLATINFO_PK" PRIMARY KEY ("TMPLAT_ID")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNUSERLOG
CREATE TABLE "COMTNUSERLOG" 
   (	"OCCRRNC_DE" CHAR(8) NOT NULL ENABLE, 
	"RQESTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"METHOD_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CREAT_CO" NUMBER(10,0), 
	"UPDT_CO" NUMBER(10,0), 
	"RDCNT" NUMBER(10,0), 
	"DELETE_CO" NUMBER(10,0), 
	"OUTPT_CO" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTNUSERLOG_PK" PRIMARY KEY ("OCCRRNC_DE", "RQESTER_ID", "SVC_NM", "METHOD_NM")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTNWEBLOG (2026-07-20 접속통계 확장: 기기/브라우저/세션 컬럼 + 일자 인덱스)
CREATE TABLE "COMTNWEBLOG"
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE,
	"OCCRRNC_DE" DATE,
	"URL" VARCHAR2(200),
	"RQESTER_ID" VARCHAR2(20),
	"RQESTER_IP" VARCHAR2(23),
	"DVICE_SE" VARCHAR2(10),
	"BROWSER_NM" VARCHAR2(30),
	"SESN_ID" VARCHAR2(60),
	 CONSTRAINT "COMTNWEBLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE INDEX "IX_COMTNWEBLOG_DT" ON "COMTNWEBLOG" ("OCCRRNC_DE")
  ;



-- TABLE COMTSSYSLOGSUMMARY
CREATE TABLE "COMTSSYSLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(8) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"METHOD_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CREAT_CO" NUMBER(10,0), 
	"UPDT_CO" NUMBER(10,0), 
	"RDCNT" NUMBER(10,0), 
	"DELETE_CO" NUMBER(10,0), 
	"OUTPT_CO" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTSSYSLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "SVC_NM", "METHOD_NM")
  USING INDEX  ENABLE
   ) ;



-- TABLE COMTSWEBLOGSUMMARY
CREATE TABLE "COMTSWEBLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(8) NOT NULL ENABLE, 
	"URL" VARCHAR2(200) NOT NULL ENABLE, 
	"RDCNT" NUMBER(10,0), 
	 CONSTRAINT "COMTSWEBLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "URL")
  USING INDEX  ENABLE
   ) ;



-- TABLE TB_ACT_LOG
CREATE TABLE "TB_ACT_LOG" 
   (	"IALOG_NO" NUMBER NOT NULL ENABLE, 
	"SREF_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"IREF_NO" NUMBER NOT NULL ENABLE, 
	"SNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"STASK" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"SUSER_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SINS_DT" VARCHAR2(255) NOT NULL ENABLE, 
	"SSYS_ID" VARCHAR2(255), 
	"SINS_IP" VARCHAR2(255)
   ) ;


  CREATE UNIQUE INDEX "PK_TB_ACT_LOG" ON "TB_ACT_LOG" ("IALOG_NO") 
  ;


ALTER TABLE "TB_ACT_LOG" ADD CONSTRAINT "PK_TB_ACT_LOG" PRIMARY KEY ("IALOG_NO")
  USING INDEX "PK_TB_ACT_LOG"  ENABLE;



-- TABLE TB_STATS_BBS_VIEW (2026-07-20 신설 — 게시판 조회통계 적재)
CREATE TABLE "TB_STATS_BBS_VIEW"
   (	"ISBVIEW_NO" NUMBER NOT NULL ENABLE,
	"SBBS_ID" VARCHAR2(30) NOT NULL ENABLE,
	"INTT_ID" NUMBER NOT NULL ENABLE,
	"ICNT" NUMBER NOT NULL ENABLE,
	"SINS_DT" VARCHAR2(10) NOT NULL ENABLE
   ) ;


  CREATE UNIQUE INDEX "PK_TB_STATS_BBS_VIEW" ON "TB_STATS_BBS_VIEW" ("ISBVIEW_NO")
  ;


ALTER TABLE "TB_STATS_BBS_VIEW" ADD CONSTRAINT "PK_TB_STATS_BBS_VIEW" PRIMARY KEY ("ISBVIEW_NO")
  USING INDEX "PK_TB_STATS_BBS_VIEW"  ENABLE;



-- VIEW COMVNUSERMASTER
CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "COMVNUSERMASTER" ("ESNTL_ID", "USER_ID", "PASSWORD", "USER_NM", "USER_ZIP", "USER_ADRES", "USER_EMAIL", "GROUP_ID", "USER_SE", "ORGNZT_ID") AS 
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR' AS USER_SE, ORGNZT_ID
    FROM COMTNGNRLMBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
    FROM COMTNEMPLYRINFO;




--------------------------------------------------------------------------------
-- 합성 테이블 1종 — 레거시 운영 DB 에 없으나 라이브 필수 경로가 참조.
-- (죽은 흐름용 방어 테이블 6종은 2026-07-10 사용자 확정으로 제외 — 미생성 목록은 README 참조)
--------------------------------------------------------------------------------

-- COMTHEMPLYRINFOCHANGEDTLS (합성 근거: mapper\com\uss\umt\EgovUserManage_SQL_oracle.xml insertUserHistory —
--   사용자정보 수정 이력. 레거시 COMTN- 변형 구조 1:1, 매퍼가 쓰는 COMTH- 이름으로 생성)
CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID           VARCHAR2(20)   NOT NULL,
  CHANGE_DE           CHAR(20)       NOT NULL,
  ORGNZT_ID           CHAR(20),
  GROUP_ID            CHAR(20),
  EMPL_NO             VARCHAR2(20),
  SEXDSTN_CODE        CHAR(1),
  BRTHDY              CHAR(20),
  FXNUM               VARCHAR2(20),
  HOUSE_ADRES         VARCHAR2(100),
  HOUSE_END_TELNO     VARCHAR2(4),
  AREA_NO             VARCHAR2(4),
  DETAIL_ADRES        VARCHAR2(100),
  ZIP                 VARCHAR2(6),
  OFFM_TELNO          VARCHAR2(20),
  MBTLNUM             VARCHAR2(20),
  EMAIL_ADRES         VARCHAR2(50),
  HOUSE_MIDDLE_TELNO  VARCHAR2(4),
  PSTINST_CODE        CHAR(8),
  EMPLYR_STTUS_CODE   CHAR(1),
  ESNTL_ID            CHAR(20),
  CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE)
);



-- 브랜드설정 — 로고(텍스트/이미지)·파비콘·연락처. 고객사별 리브랜딩 지점, BRAND_ID='S' 단일 행 (2026-07-31, 연락처 2026-08-04)
CREATE TABLE COM_BRAND (
  BRAND_ID              CHAR(1)       NOT NULL,
  LOGO_TY_CODE          VARCHAR2(10)  DEFAULT 'TEXT' NOT NULL,
  LOGO_TEXT             VARCHAR2(300),
  LOGO_ATCH_FILE_ID     CHAR(20),
  FAVICON_ATCH_FILE_ID  CHAR(20),
  CNTC_ADRES            VARCHAR2(300),
  CNTC_TELNO            VARCHAR2(30),
  CNTC_FXNUM            VARCHAR2(30),
  CNTC_EMAIL_ADRES      VARCHAR2(100),
  LAST_UPDUSR_ID        VARCHAR2(20),
  LAST_UPDT_PNTTM       DATE,
  CONSTRAINT PK_COM_BRAND PRIMARY KEY (BRAND_ID)
);
