--------------------------------------------------------------------------------
-- 11_indexes.sql — 비제약 인덱스(PK/UK 제외)
-- LexPortal(송무 단독) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: lexportal. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- Oracle Text 도메인 인덱스(IDX_PROV_VRSN_FT)는 14_oracle_text.sql 별도.
--------------------------------------------------------------------------------

CREATE INDEX COMTCCMMNCODE_I01 ON COMTCCMMNCODE (CL_CODE);
CREATE INDEX COMTCCMMNDETAILCODE_I01 ON COMTCCMMNDETAILCODE (CODE_ID);
CREATE INDEX COMTNAUTHORROLERELATE_I01 ON COMTNAUTHORROLERELATE (AUTHOR_CODE);
CREATE INDEX COMTNAUTHORROLERELATE_I02 ON COMTNAUTHORROLERELATE (ROLE_CODE);
CREATE INDEX COMTNBBS_I01 ON COMTNBBS (BBS_ID);
CREATE INDEX COMTNCOMMENT_I01 ON COMTNCOMMENT (NTT_ID, BBS_ID);
CREATE INDEX COMTNEMPLYRINFO_I01 ON COMTNEMPLYRINFO (ORGNZT_ID);
CREATE INDEX COMTNEMPLYRINFO_I02 ON COMTNEMPLYRINFO (GROUP_ID);
CREATE INDEX COMTNEMPLYRSCRTYESTBS_I04 ON COMTNEMPLYRSCRTYESTBS (AUTHOR_CODE);
CREATE INDEX COMTNFAQINFO_I01 ON COMTNFAQINFO (ATCH_FILE_ID);
CREATE INDEX COMTNFILEDETAIL_I01 ON COMTNFILEDETAIL (ATCH_FILE_ID);
CREATE INDEX COMTNGNRLMBER_I01 ON COMTNGNRLMBER (GROUP_ID);
CREATE INDEX COMTNMENUCREATDTLS_I02 ON COMTNMENUCREATDTLS (MENU_NO);
CREATE INDEX COMTNMENUCREATDTLS_I03 ON COMTNMENUCREATDTLS (MAPNG_CREAT_ID);
CREATE INDEX COMTNMENUCREATDTLS_I04 ON COMTNMENUCREATDTLS (AUTHOR_CODE);
CREATE INDEX COMTNMENUINFO_I02 ON COMTNMENUINFO (UPPER_MENU_NO);
CREATE INDEX COMTNROLES_HIERARCHY_I01 ON COMTNROLES_HIERARCHY (PARNTS_ROLE);
CREATE INDEX COMTNROLES_HIERARCHY_I02 ON COMTNROLES_HIERARCHY (CHLDRN_ROLE);
