-- ============================================================================
-- rlms_law_install.sql — 송무(law) 옵션 모듈 설치 ① DDL·채번·코드·시드
--   (LAW_MODULE_DESIGN.md §4·§5, 2026-07-21 생성)
--
--   구성: 1) LAW_* 18테이블 DDL + 코멘트 전수 + 인덱스
--         2) COMTECOPSEQ 채번 17행
--         3) ccm 공통코드 15그룹(레거시 tbetia09/10 — SB_CD 보존)
--         4) LAW_COURT 대표 시드 22행(레거시 tbetia31 발췌 — 부족분은 운영 등록)
--         5) LAW_CALC_RATE 현행 요율 1세트(APPLY_DT=20260101)
--
--   실행: RLMS 계정. 재실행 시 CREATE 는 ORA-00955(무시), 시드는 NOT EXISTS 스킵.
--   ⚠️ 옵션 메뉴·권한은 rlms_law_menu.sql 별도(§9 설치 순서: regroup 후 install, menu, 재기동).
-- ============================================================================
SET DEFINE OFF;

-- ============================================================
-- 1) 테이블 DDL — 공통 규약(§4.1):
--    날짜 VARCHAR2(8) 'YYYYMMDD', 시각 VARCHAR2(14) 'YYYYMMDDHH24MISS',
--    금액 NUMBER(19), 코드 VARCHAR2(10), 감사 4종(REG/UPD_USER_ID·DT).
-- ============================================================

-- ── 1.1 LAW_SUIT 사건 마스터 (심급 단위 1행) ← tbetia11 ──
CREATE TABLE LAW_SUIT (
    SUIT_ID           NUMBER(10)      NOT NULL,
    FIRST_SUIT_ID     NUMBER(10),
    CASE_KIND_CD      VARCHAR2(10),
    INSTANCE_CD       VARCHAR2(10),
    COURT_ID          NUMBER(10),
    COURT_NM          VARCHAR2(150),
    CASE_YEAR         VARCHAR2(4),
    CASE_SIGN_CD      VARCHAR2(10),
    CASE_SERIAL       VARCHAR2(20),
    CASE_NO           VARCHAR2(100),
    CASE_NM_CD        VARCHAR2(10),
    CASE_NM           VARCHAR2(200),
    CIVIL_CASE_CD     VARCHAR2(10),
    ITPT_KIND_CD      VARCHAR2(10),
    SUIT_AMT          NUMBER(19),
    OFFICE_RECEIPT_DT VARCHAR2(8),
    FR_DT             VARCHAR2(8),
    STC_DT            VARCHAR2(8),
    DCSN_DT           VARCHAR2(8),
    RSLT_KIND_CD      VARCHAR2(10),
    RSLT_KIND_NM      VARCHAR2(200),
    WIN_AMT           NUMBER(19),
    LOSE_AMT          NUMBER(19),
    LOSS_CAUSE_CD     VARCHAR2(10),
    MERGE_CASE        VARCHAR2(500),
    COST_FIX_DT       VARCHAR2(8),
    COST_FIX_AMT      NUMBER(19),
    COST_RCV_AMT      NUMBER(19),
    RETAINER_AMT      NUMBER(19),
    SUCCESS_AMT       NUMBER(19),
    SPECIAL_DESC      VARCHAR2(4000),
    DEL_YN            CHAR(1) DEFAULT 'N' NOT NULL,
    REG_USER_ID       VARCHAR2(20),
    REG_DT            VARCHAR2(14),
    UPD_USER_ID       VARCHAR2(20),
    UPD_DT            VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT PRIMARY KEY (SUIT_ID)
);
COMMENT ON TABLE  LAW_SUIT IS '송무 사건 마스터 — 심급 단위 1행, 사건군 그룹핑은 FIRST_SUIT_ID(§4.5) ← tbetia11';
COMMENT ON COLUMN LAW_SUIT.SUIT_ID           IS '사건 ID (채번 LAW_SUIT_ID) ← tbetia11.LAWSUIT_SEQ';
COMMENT ON COLUMN LAW_SUIT.FIRST_SUIT_ID     IS '사건군 최초 심급 사건 ID — 최초심=자기 ID, 상급심=원심 값 승계(레거시 tbetia16/33 재귀 연결 폐지)';
COMMENT ON COLUMN LAW_SUIT.CASE_KIND_CD      IS '소송구분(LAW_CASE_KIND) — 통계 4축 S001민사/S002행정/S012국가/S009심판 ← tbetia11.LAWSUIT_CASE_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.INSTANCE_CD       IS '심급(LAW_INSTANCE) — 심급별 통계 3축 S001/S002/S004 ← tbetia11.LAWSUIT_REL_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.COURT_ID          IS '법원 ID (LAW_COURT FK, 직접입력 시 NULL) ← tbetia11.COURT_SEQ';
COMMENT ON COLUMN LAW_SUIT.COURT_NM          IS '법원명 (표시용 — 선택 시 LAW_COURT.COURT_NM 복사, 직접입력 허용) ← tbetia11.COURT_NM_IN';
COMMENT ON COLUMN LAW_SUIT.CASE_YEAR         IS '사건번호 연도 (YYYY) ← tbetia11.LAWSUIT_MGMT_YYYY';
COMMENT ON COLUMN LAW_SUIT.CASE_SIGN_CD      IS '사건부호(LAW_CASE_SIGN — 대법원 사건부호) ← tbetia11.LAWSUIT_MGMT_SIGN';
COMMENT ON COLUMN LAW_SUIT.CASE_SERIAL       IS '사건번호 일련 ← tbetia11.LAWSUIT_MGMT_ISSUE_NO';
COMMENT ON COLUMN LAW_SUIT.CASE_NO           IS '사건번호 표시용 결합 (예: 2026가합1234) ← tbetia11.LAWSUIT_CASE_NO';
COMMENT ON COLUMN LAW_SUIT.CASE_NM_CD        IS '사건명 코드(LAW_CASE_NM, S999=직접입력) ← tbetia11.LAWSUIT_CASE_NM_CD';
COMMENT ON COLUMN LAW_SUIT.CASE_NM           IS '사건명 (코드 선택 시 명칭 복사, 직접입력 허용) ← tbetia11.CASE_NM_IN';
COMMENT ON COLUMN LAW_SUIT.CIVIL_CASE_CD     IS '사건유형(LAW_CIVIL_CASE) ← tbetia11.CIVIL_CASE_CD';
COMMENT ON COLUMN LAW_SUIT.ITPT_KIND_CD      IS '제·피소구분(LAW_ITPT_KIND) ← tbetia11.LAWSUIT_ITPT_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.SUIT_AMT          IS '소가(소송가액, 원) ← tbetia11.LAWSUIT_APLY_AMT';
COMMENT ON COLUMN LAW_SUIT.OFFICE_RECEIPT_DT IS '행정청 접수일 (YYYYMMDD) ← tbetia11.OFFICE_RECEIPT_DT';
COMMENT ON COLUMN LAW_SUIT.FR_DT             IS '소제기일 (YYYYMMDD) ← tbetia11.LAWSUIT_FR_DT';
COMMENT ON COLUMN LAW_SUIT.STC_DT            IS '최종 선고일 (YYYYMMDD) ← tbetia11.LAWSUIT_STC_DT';
COMMENT ON COLUMN LAW_SUIT.DCSN_DT           IS '확정일 (YYYYMMDD) ← tbetia11.LAWSUIT_DCSN_DT';
COMMENT ON COLUMN LAW_SUIT.RSLT_KIND_CD      IS '소송결과(LAW_RESULT) — 승소그룹 S002/S003/S005/S006/S008/S997, 패소그룹 S004/S100/S101/S102/S998 ← tbetia11.LAWSUIT_RSLT_KIND_CD';
COMMENT ON COLUMN LAW_SUIT.RSLT_KIND_NM      IS '소송결과 직접입력 명칭 ← tbetia11.LAWSUIT_RSLT_KIND_NM';
COMMENT ON COLUMN LAW_SUIT.WIN_AMT           IS '승소금액(원) ← tbetia11.LAWSUIT_DECS_AMT(승패소 단일컬럼의 분해)';
COMMENT ON COLUMN LAW_SUIT.LOSE_AMT          IS '패소금액(원) ← tbetia11.LAWSUIT_DECS_AMT(승패소 단일컬럼의 분해)';
COMMENT ON COLUMN LAW_SUIT.LOSS_CAUSE_CD     IS '패소원인(LAW_LOSS_CAUSE) ← tbetia11.LOSS_CAUSE_CD';
COMMENT ON COLUMN LAW_SUIT.MERGE_CASE        IS '병합사건 텍스트(사건번호 나열)';
COMMENT ON COLUMN LAW_SUIT.COST_FIX_DT       IS '소송비용 확정결정일 (YYYYMMDD) ← tbetia11.LAWSUIT_FEE_DECISION_DT';
COMMENT ON COLUMN LAW_SUIT.COST_FIX_AMT      IS '소송비용 확정액(원) ← tbetia11.FEE_DCSN_AMT';
COMMENT ON COLUMN LAW_SUIT.COST_RCV_AMT      IS '소송비용 회수액(원) ← tbetia11.FEE_RETR_AMT';
COMMENT ON COLUMN LAW_SUIT.RETAINER_AMT      IS '착수금(원, 예비 — 선임 보수관리는 비범위) ← tbetia11.RETAINING_FEE';
COMMENT ON COLUMN LAW_SUIT.SUCCESS_AMT       IS '성공보수(원, 예비) ← tbetia11.CONTINGENT_FEE';
COMMENT ON COLUMN LAW_SUIT.SPECIAL_DESC      IS '특이사항 ← tbetia11.LAWSUIT_MGMT_BLBD_CONTN';
COMMENT ON COLUMN LAW_SUIT.DEL_YN            IS '소프트삭제 여부 (Y/N) ← tbetia11.DEL_YN';
COMMENT ON COLUMN LAW_SUIT.REG_USER_ID       IS '등록자 ID (COMTNEMPLYRINFO.EMPLYR_ID)';
COMMENT ON COLUMN LAW_SUIT.REG_DT            IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT.UPD_USER_ID       IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT.UPD_DT            IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_01 ON LAW_SUIT (DEL_YN, CASE_KIND_CD);
CREATE INDEX IX_LAW_SUIT_02 ON LAW_SUIT (FIRST_SUIT_ID);
CREATE INDEX IX_LAW_SUIT_03 ON LAW_SUIT (CASE_NO);
CREATE INDEX IX_LAW_SUIT_04 ON LAW_SUIT (FR_DT);
CREATE INDEX IX_LAW_SUIT_05 ON LAW_SUIT (RSLT_KIND_CD);

-- ── 1.2 LAW_SUIT_PARTY 당사자 ← tbetia14 ──
CREATE TABLE LAW_SUIT_PARTY (
    PARTY_ID    NUMBER(10)    NOT NULL,
    SUIT_ID     NUMBER(10)    NOT NULL,
    PARTY_TYPE  CHAR(1)       NOT NULL,
    PARTY_NM    VARCHAR2(200),
    BIRTH       VARCHAR2(10),
    JUMIN_ENC   VARCHAR2(256),
    AGENT_NM    VARCHAR2(100),
    SORT_ORDR   NUMBER(5) DEFAULT 0,
    REG_USER_ID VARCHAR2(20),
    REG_DT      VARCHAR2(14),
    UPD_USER_ID VARCHAR2(20),
    UPD_DT      VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_PARTY PRIMARY KEY (PARTY_ID)
);
COMMENT ON TABLE  LAW_SUIT_PARTY IS '송무 사건 당사자 (원고/피고/보조참가인) ← tbetia14';
COMMENT ON COLUMN LAW_SUIT_PARTY.PARTY_ID    IS '당사자 ID (채번 LAW_PARTY_ID) ← tbetia14.ITPT_SEQ';
COMMENT ON COLUMN LAW_SUIT_PARTY.SUIT_ID     IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_PARTY.PARTY_TYPE  IS '당사자 구분 (P=원고, D=피고, S=보조참가인) ← tbetia14.ACUSR_DFDNT_TYPE';
COMMENT ON COLUMN LAW_SUIT_PARTY.PARTY_NM    IS '성명(법인명) ← tbetia14.ITPT_NM';
COMMENT ON COLUMN LAW_SUIT_PARTY.BIRTH       IS '생년월일 (YYYYMMDD 또는 YYMMDD — 주민번호 입력 시 앞6자리 자동 파생) ← tbetia14.BIRTH';
COMMENT ON COLUMN LAW_SUIT_PARTY.JUMIN_ENC   IS '주민등록번호 양방향 암호문(EgovGeneralCryptoService PBE, 키=Globals.law.cryptoKey, Base64) — 평문 저장·화면 복호 표시 금지, 항상 마스킹(§4.4) ← tbetia14.JUMIN_NO(레거시 평문의 암호화 대체)';
COMMENT ON COLUMN LAW_SUIT_PARTY.AGENT_NM    IS '대리인 성명';
COMMENT ON COLUMN LAW_SUIT_PARTY.SORT_ORDR   IS '표시 순서 (0부터 — 목록 대표자=구분별 최솟값 행)';
COMMENT ON COLUMN LAW_SUIT_PARTY.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_PARTY.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_PARTY.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_PARTY.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_PARTY_01 ON LAW_SUIT_PARTY (SUIT_ID);

-- ── 1.3 LAW_SUIT_STAFF 소송수행자 ← tbetia50 ──
CREATE TABLE LAW_SUIT_STAFF (
    STAFF_ID    NUMBER(10)  NOT NULL,
    SUIT_ID     NUMBER(10)  NOT NULL,
    ORGNZT_ID   CHAR(20),
    STAFF_NM    VARCHAR2(100),
    ASSIGN_DT   VARCHAR2(8),
    SORT_ORDR   NUMBER(5) DEFAULT 0,
    REG_USER_ID VARCHAR2(20),
    REG_DT      VARCHAR2(14),
    UPD_USER_ID VARCHAR2(20),
    UPD_DT      VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_STAFF PRIMARY KEY (STAFF_ID)
);
COMMENT ON TABLE  LAW_SUIT_STAFF IS '송무 사건 소송수행자 (부서=표준 COMTNORGNZTINFO 연동 — 레거시 김해 부서코드 A33 폐기) ← tbetia50';
COMMENT ON COLUMN LAW_SUIT_STAFF.STAFF_ID    IS '수행자 행 ID (채번 LAW_STAFF_ID) ← tbetia50.SEQ';
COMMENT ON COLUMN LAW_SUIT_STAFF.SUIT_ID     IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_STAFF.ORGNZT_ID   IS '수행 부서 ID (COMTNORGNZTINFO.ORGNZT_ID) ← tbetia50.TEAM_CD(김해 코드의 표준 대체)';
COMMENT ON COLUMN LAW_SUIT_STAFF.STAFF_NM    IS '수행자 성명 ← tbetia50.NAME';
COMMENT ON COLUMN LAW_SUIT_STAFF.ASSIGN_DT   IS '지정일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_STAFF.SORT_ORDR   IS '표시 순서 (0=수행자, 1=보조수행자 — 일정관리 열 규약)';
COMMENT ON COLUMN LAW_SUIT_STAFF.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_STAFF.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_STAFF.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_STAFF.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_STAFF_01 ON LAW_SUIT_STAFF (SUIT_ID);

-- ── 1.4 LAW_SUIT_LAND 사건토지 ← tbetia53(+tbetia11 토지 필드) ──
CREATE TABLE LAW_SUIT_LAND (
    LAND_ID     NUMBER(10)  NOT NULL,
    SUIT_ID     NUMBER(10)  NOT NULL,
    LOCATION    VARCHAR2(255),
    JIBUN       VARCHAR2(255),
    SORT_ORDR   NUMBER(5) DEFAULT 0,
    REG_USER_ID VARCHAR2(20),
    REG_DT      VARCHAR2(14),
    UPD_USER_ID VARCHAR2(20),
    UPD_DT      VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_LAND PRIMARY KEY (LAND_ID)
);
COMMENT ON TABLE  LAW_SUIT_LAND IS '송무 사건토지 (행 단위 정규화 — 사건지번표시도(Kakao Geocoder) 원천) ← tbetia53 + tbetia11.CASE_LAND_*';
COMMENT ON COLUMN LAW_SUIT_LAND.LAND_ID     IS '토지 행 ID (채번 LAW_LAND_ID)';
COMMENT ON COLUMN LAW_SUIT_LAND.SUIT_ID     IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_LAND.LOCATION    IS '소재지 (지오코딩 주소) ← tbetia11.CASE_LAND_LOCATION';
COMMENT ON COLUMN LAW_SUIT_LAND.JIBUN       IS '지번 ← tbetia11.CASE_LAND_JIBUN';
COMMENT ON COLUMN LAW_SUIT_LAND.SORT_ORDR   IS '표시 순서';
COMMENT ON COLUMN LAW_SUIT_LAND.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_LAND.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_LAND.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_LAND.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_LAND_01 ON LAW_SUIT_LAND (SUIT_ID);

-- ── 1.5 LAW_SUIT_PROG 진행상황·기일 겸용 ← tbetia19 ──
CREATE TABLE LAW_SUIT_PROG (
    PROG_ID      NUMBER(10)  NOT NULL,
    SUIT_ID      NUMBER(10)  NOT NULL,
    PROG_KIND_CD VARCHAR2(10),
    DYPR_KIND_CD VARCHAR2(10),
    PROG_DT      VARCHAR2(8),
    PROG_TM      VARCHAR2(4),
    PLACE        VARCHAR2(200),
    PROG_DESC    VARCHAR2(1000),
    STAT_CD      VARCHAR2(10),
    RESULT_DESC  VARCHAR2(1000),
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_PROG PRIMARY KEY (PROG_ID)
);
COMMENT ON TABLE  LAW_SUIT_PROG IS '송무 진행상황·기일 겸용 — 소송등록 진행상황 그리드와 일정관리(달력)가 같은 테이블(§7.5) ← tbetia19';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_ID      IS '진행 행 ID (채번 LAW_PROG_ID) ← tbetia19.DYPR_SEQ';
COMMENT ON COLUMN LAW_SUIT_PROG.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_KIND_CD IS '진행종류(LAW_PROG_KIND — 기일/피고제출/원고제출/본부보고) ← tbetia19.DDT_CD';
COMMENT ON COLUMN LAW_SUIT_PROG.DYPR_KIND_CD IS '기일구분(LAW_DYPR_KIND — 진행종류가 기일일 때) ← tbetia19.DYPR_KIND_CD';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_DT      IS '진행(기일)일자 (YYYYMMDD) ← tbetia19.DYPR_DT';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_TM      IS '시각 (HHMM) ← tbetia19.DYPR_TM';
COMMENT ON COLUMN LAW_SUIT_PROG.PLACE        IS '장소 ← tbetia19.DYPR_PLC';
COMMENT ON COLUMN LAW_SUIT_PROG.PROG_DESC    IS '내용 ← tbetia19.DYPR_DESC';
COMMENT ON COLUMN LAW_SUIT_PROG.STAT_CD      IS '진행상태(LAW_PROG_STAT — 진행/완료) ← tbetia19.PROG_STAT_CD';
COMMENT ON COLUMN LAW_SUIT_PROG.RESULT_DESC  IS '결과';
COMMENT ON COLUMN LAW_SUIT_PROG.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_PROG.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_PROG.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_PROG.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_PROG_01 ON LAW_SUIT_PROG (SUIT_ID);
CREATE INDEX IX_LAW_SUIT_PROG_02 ON LAW_SUIT_PROG (PROG_DT);

-- ── 1.6 LAW_SUIT_RSLT_HIST 결과변경 이력 ← tbetia34 슬림화 ──
CREATE TABLE LAW_SUIT_RSLT_HIST (
    HIST_ID      NUMBER(10)  NOT NULL,
    SUIT_ID      NUMBER(10)  NOT NULL,
    HIST_SEQ     NUMBER(5)   DEFAULT 1,
    RSLT_KIND_CD VARCHAR2(10),
    RSLT_KIND_NM VARCHAR2(200),
    END_DT       VARCHAR2(8),
    HIST_DESC    VARCHAR2(1000),
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_RSLT_HIST PRIMARY KEY (HIST_ID)
);
COMMENT ON TABLE  LAW_SUIT_RSLT_HIST IS '송무 결과변경 이력 — 결과 필드만 이력화(레거시 전체 스냅샷 폐지) ← tbetia34';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.HIST_ID      IS '이력 ID (채번 LAW_RSLT_HIST_ID)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.HIST_SEQ     IS '사건 내 이력 순번 (1부터 증가)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.RSLT_KIND_CD IS '변경 시점 소송결과(LAW_RESULT)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.RSLT_KIND_NM IS '변경 시점 소송결과 직접입력 명칭';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.END_DT       IS '종결일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.HIST_DESC    IS '변경 사유·비고';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_RSLT_HIST.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_RSLT_HIST_01 ON LAW_SUIT_RSLT_HIST (SUIT_ID);

-- ── 1.7 LAW_SUIT_DOC 소송문서 (표준 첨부 + 승인 워크플로 §7.2) ← tbetia17 ──
CREATE TABLE LAW_SUIT_DOC (
    DOC_ID       NUMBER(10)  NOT NULL,
    SUIT_ID      NUMBER(10)  NOT NULL,
    DOC_KIND_CD  VARCHAR2(10),
    DOC_TITL     VARCHAR2(200),
    DOC_MEMO     VARCHAR2(4000),
    ATCH_FILE_ID CHAR(20),
    APP_STS_CD   VARCHAR2(10) DEFAULT 'S001',
    APP_USER_ID  VARCHAR2(20),
    APP_USER_NM  VARCHAR2(60),
    APP_DT       VARCHAR2(14),
    APP_OPINION  VARCHAR2(1000),
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_DOC PRIMARY KEY (DOC_ID)
);
COMMENT ON TABLE  LAW_SUIT_DOC IS '송무 소송문서 — 첨부=표준 COMTNFILE/COMTNFILEDETAIL(다중), 등록=승인대기·수정 시 대기 리셋(§7.2) ← tbetia17';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_ID       IS '문서 ID (채번 LAW_DOC_ID) ← tbetia17.DOC_SEQ';
COMMENT ON COLUMN LAW_SUIT_DOC.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_KIND_CD  IS '문서종류(LAW_DOC_KIND — 소장~항고장 21종) ← tbetia17.DOC_KIND_CD';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_TITL     IS '문서 제목 ← tbetia17.DOC_TITL';
COMMENT ON COLUMN LAW_SUIT_DOC.DOC_MEMO     IS '메모 ← tbetia17.DOC_MEMO';
COMMENT ON COLUMN LAW_SUIT_DOC.ATCH_FILE_ID IS '첨부파일 ID (표준 COMTNFILE — 다중 파일은 COMTNFILEDETAIL 행들, 레거시 tbetia18 대체)';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_STS_CD   IS '승인상태(LAW_DOC_APP_STATUS — S001 대기/S002 승인/S003 반려, 기본 대기) ← tbetia17.DOC_APP_STS(텍스트의 코드화)';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_USER_ID  IS '승인(반려)자 ID ← tbetia17.DOC_APP_EMP_NO';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_USER_NM  IS '승인(반려)자 성명 ← tbetia17.DOC_APP_EMP_NM';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_DT       IS '승인(반려)일시 (YYYYMMDDHH24MISS) ← tbetia17.DOC_APP_DTTM';
COMMENT ON COLUMN LAW_SUIT_DOC.APP_OPINION  IS '승인 의견·반려 사유 ← tbetia17.DOC_APP_BLBD';
COMMENT ON COLUMN LAW_SUIT_DOC.REG_USER_ID  IS '등록자(신청인) ID';
COMMENT ON COLUMN LAW_SUIT_DOC.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_DOC.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_DOC.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_DOC_01 ON LAW_SUIT_DOC (SUIT_ID);
CREATE INDEX IX_LAW_SUIT_DOC_02 ON LAW_SUIT_DOC (APP_STS_CD);

-- ── 1.8 LAW_SUIT_COST 소송비용 ← tbetia20+21 통합 ──
CREATE TABLE LAW_SUIT_COST (
    COST_ID      NUMBER(10)  NOT NULL,
    SUIT_ID      NUMBER(10)  NOT NULL,
    COST_KIND_CD VARCHAR2(10),
    COST_AMT     NUMBER(19),
    COST_DESC    VARCHAR2(1000),
    PAY_DMND_DT  VARCHAR2(8),
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_COST PRIMARY KEY (COST_ID)
);
COMMENT ON TABLE  LAW_SUIT_COST IS '송무 소송비용 (단일행 — 레거시 신청/지급 2테이블 통합) ← tbetia20+tbetia21';
COMMENT ON COLUMN LAW_SUIT_COST.COST_ID      IS '비용 행 ID (채번 LAW_COST_ID)';
COMMENT ON COLUMN LAW_SUIT_COST.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_COST.COST_KIND_CD IS '비용종류(LAW_COST_KIND — 인지액/송달료/지연이자/공탁금/변호사비용/조세비용/조정중재/기타)';
COMMENT ON COLUMN LAW_SUIT_COST.COST_AMT     IS '금액(원)';
COMMENT ON COLUMN LAW_SUIT_COST.COST_DESC    IS '내역';
COMMENT ON COLUMN LAW_SUIT_COST.PAY_DMND_DT  IS '지급요청일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_COST.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_COST.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_COST.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_COST.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_COST_01 ON LAW_SUIT_COST (SUIT_ID);

-- ── 1.9 LAW_LAWYER 변호사 명부 ← tbetia51 ──
CREATE TABLE LAW_LAWYER (
    LAWYER_ID   NUMBER(10)  NOT NULL,
    LAW_FIRM    VARCHAR2(200),
    LAWYER_NM   VARCHAR2(100),
    EMAIL       VARCHAR2(100),
    TEL         VARCHAR2(50),
    MOBILE      VARCHAR2(50),
    DEL_YN      CHAR(1) DEFAULT 'N' NOT NULL,
    REG_USER_ID VARCHAR2(20),
    REG_DT      VARCHAR2(14),
    UPD_USER_ID VARCHAR2(20),
    UPD_DT      VARCHAR2(14),
    CONSTRAINT PK_LAW_LAWYER PRIMARY KEY (LAWYER_ID)
);
COMMENT ON TABLE  LAW_LAWYER IS '송무 변호사 명부 — 법무법인은 텍스트(마스터 비범위 §1.2) ← tbetia51';
COMMENT ON COLUMN LAW_LAWYER.LAWYER_ID   IS '변호사 ID (채번 LAW_LAWYER_ID) ← tbetia51.SEQ';
COMMENT ON COLUMN LAW_LAWYER.LAW_FIRM    IS '법무법인명(텍스트) ← tbetia51.LAW_FIRM';
COMMENT ON COLUMN LAW_LAWYER.LAWYER_NM   IS '변호사 성명 ← tbetia51.NAME';
COMMENT ON COLUMN LAW_LAWYER.EMAIL       IS '이메일 ← tbetia51.EMAIL';
COMMENT ON COLUMN LAW_LAWYER.TEL         IS '전화(사무실) ← tbetia51.TEL';
COMMENT ON COLUMN LAW_LAWYER.MOBILE      IS '휴대폰 ← tbetia51.PHONE';
COMMENT ON COLUMN LAW_LAWYER.DEL_YN      IS '소프트삭제 여부 (Y/N — 선임 참조 시 삭제 차단 안내 §7.7)';
COMMENT ON COLUMN LAW_LAWYER.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_LAWYER.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_LAWYER.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_LAWYER.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';

-- ── 1.10 LAW_SUIT_LAWYER 선임 ← tbetia52 ──
CREATE TABLE LAW_SUIT_LAWYER (
    ASSIGN_ID    NUMBER(10)  NOT NULL,
    SUIT_ID      NUMBER(10)  NOT NULL,
    LAWYER_ID    NUMBER(10)  NOT NULL,
    ASSIGN_DT    VARCHAR2(8),
    ATCH_FILE_ID CHAR(20),
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_LAWYER PRIMARY KEY (ASSIGN_ID)
);
COMMENT ON TABLE  LAW_SUIT_LAWYER IS '송무 선임 (사건×변호사) — 만족도 평가 대상 단위(§4.3) ← tbetia52';
COMMENT ON COLUMN LAW_SUIT_LAWYER.ASSIGN_ID    IS '선임 ID (채번 LAW_ASSIGN_ID) ← tbetia52.SEQ';
COMMENT ON COLUMN LAW_SUIT_LAWYER.SUIT_ID      IS '사건 ID (LAW_SUIT FK)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.LAWYER_ID    IS '변호사 ID (LAW_LAWYER FK) ← tbetia52.TBETIA51_SEQ';
COMMENT ON COLUMN LAW_SUIT_LAWYER.ASSIGN_DT    IS '선임일 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.ATCH_FILE_ID IS '계약서 첨부파일 ID (표준 COMTNFILE)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_LAWYER.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_LAWYER.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_LAWYER.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_LAWYER_01 ON LAW_SUIT_LAWYER (SUIT_ID);
CREATE INDEX IX_LAW_SUIT_LAWYER_02 ON LAW_SUIT_LAWYER (LAWYER_ID);

-- ── 1.11 LAW_COURT 법원 ← tbetia31 ──
CREATE TABLE LAW_COURT (
    COURT_ID       NUMBER(10)  NOT NULL,
    UPPER_COURT_ID NUMBER(10),
    COURT_NM       VARCHAR2(150),
    SORT_ORDR      NUMBER(10) DEFAULT 0,
    USE_YN         CHAR(1) DEFAULT 'Y' NOT NULL,
    RMK            VARCHAR2(1000),
    REG_USER_ID    VARCHAR2(20),
    REG_DT         VARCHAR2(14),
    UPD_USER_ID    VARCHAR2(20),
    UPD_DT         VARCHAR2(14),
    CONSTRAINT PK_LAW_COURT PRIMARY KEY (COURT_ID)
);
COMMENT ON TABLE  LAW_COURT IS '송무 법원 마스터 (계층 — 루트 COURT_ID=0) ← tbetia31. 대표 시드 22행, 부족분은 운영 등록';
COMMENT ON COLUMN LAW_COURT.COURT_ID       IS '법원 ID (채번 LAW_COURT_ID — 시드 최대 194, NEXT_ID 200부터) ← tbetia31.COURT_SEQ';
COMMENT ON COLUMN LAW_COURT.UPPER_COURT_ID IS '상위 법원 ID (루트=NULL) ← tbetia31.SPST_COURT_SEQ';
COMMENT ON COLUMN LAW_COURT.COURT_NM       IS '법원명 ← tbetia31.COURT_NM';
COMMENT ON COLUMN LAW_COURT.SORT_ORDR      IS '표시 순서 ← tbetia31.ORD';
COMMENT ON COLUMN LAW_COURT.USE_YN         IS '사용 여부 (Y/N)';
COMMENT ON COLUMN LAW_COURT.RMK            IS '비고 — 레거시 승계 시 해당 법원 취급 사건부호(LAW_CASE_SIGN) 파이프 목록 ← tbetia31.RMK';
COMMENT ON COLUMN LAW_COURT.REG_USER_ID    IS '등록자 ID';
COMMENT ON COLUMN LAW_COURT.REG_DT         IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_COURT.UPD_USER_ID    IS '수정자 ID';
COMMENT ON COLUMN LAW_COURT.UPD_DT         IS '수정일시 (YYYYMMDDHH24MISS)';

-- ── 1.12 LAW_SUIT_REQ 소송의뢰 ← tbetia40 ──
CREATE TABLE LAW_SUIT_REQ (
    REQ_ID        NUMBER(10)  NOT NULL,
    REQ_TITL      VARCHAR2(200),
    REQ_CN        VARCHAR2(4000),
    REQ_ORGNZT_ID CHAR(20),
    REQ_USER_ID   VARCHAR2(20),
    REQ_USER_NM   VARCHAR2(60),
    REQ_DT        VARCHAR2(8),
    STATUS_CD     VARCHAR2(10) DEFAULT 'S001',
    APRV_USER_ID  VARCHAR2(20),
    APRV_USER_NM  VARCHAR2(60),
    APRV_DT       VARCHAR2(14),
    RETURN_RSN    VARCHAR2(1000),
    SUIT_ID       NUMBER(10),
    ATCH_FILE_ID  CHAR(20),
    REG_USER_ID   VARCHAR2(20),
    REG_DT        VARCHAR2(14),
    UPD_USER_ID   VARCHAR2(20),
    UPD_DT        VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_REQ PRIMARY KEY (REQ_ID)
);
COMMENT ON TABLE  LAW_SUIT_REQ IS '송무 소송의뢰 — 사용자(front) 신청, 법무팀 승인/반려, 승인 후 소송등록 연계(§7.8·7.9) ← tbetia40';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_ID        IS '의뢰 ID (채번 LAW_REQ_ID) ← tbetia40.REQ_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_TITL      IS '사건명(의뢰 제목) ← tbetia40.REQ_TITL';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_CN        IS '사실관계 ← tbetia40.REQ_BLBD_CONTN';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_ORGNZT_ID IS '의뢰부서 ID (COMTNORGNZTINFO — 신청자 소속 자동) ← tbetia40.REQ_PSTN_CD';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_USER_ID   IS '의뢰담당자 ID ← tbetia40.REQ_EMP_NO';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_USER_NM   IS '의뢰담당자 성명 ← tbetia40.REQ_EMP_NM';
COMMENT ON COLUMN LAW_SUIT_REQ.REQ_DT        IS '의뢰일자 (YYYYMMDD)';
COMMENT ON COLUMN LAW_SUIT_REQ.STATUS_CD     IS '의뢰상태(LAW_REQ_STATUS — S001 신청/S002 승인/S003 반려) ← tbetia40.REQ_RSLT_PROC';
COMMENT ON COLUMN LAW_SUIT_REQ.APRV_USER_ID  IS '승인(반려)자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ.APRV_USER_NM  IS '승인(반려)자 성명';
COMMENT ON COLUMN LAW_SUIT_REQ.APRV_DT       IS '승인(반려)일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ.RETURN_RSN    IS '반려 사유 (그리드 사유 열)';
COMMENT ON COLUMN LAW_SUIT_REQ.SUIT_ID       IS '승인 후 연계 등록된 사건 ID (LAW_SUIT — 소송등록 시 역기입)';
COMMENT ON COLUMN LAW_SUIT_REQ.ATCH_FILE_ID  IS '기타자료 첨부파일 ID (표준 COMTNFILE, 다중)';
COMMENT ON COLUMN LAW_SUIT_REQ.REG_USER_ID   IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ.REG_DT        IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ.UPD_USER_ID   IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ.UPD_DT        IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_REQ_01 ON LAW_SUIT_REQ (STATUS_CD);
CREATE INDEX IX_LAW_SUIT_REQ_02 ON LAW_SUIT_REQ (REG_USER_ID);

-- ── 1.13 LAW_SUIT_REQ_HIST 의뢰 사건경과 ← tbetia41 ──
CREATE TABLE LAW_SUIT_REQ_HIST (
    HIST_ID      NUMBER(10)  NOT NULL,
    REQ_ID       NUMBER(10)  NOT NULL,
    STA_DT       VARCHAR2(8),
    END_DT       VARCHAR2(8),
    HIST_CN      VARCHAR2(1000),
    ATCH_FILE_ID CHAR(20),
    SORT_ORDR    NUMBER(5) DEFAULT 0,
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_REQ_HIST PRIMARY KEY (HIST_ID)
);
COMMENT ON TABLE  LAW_SUIT_REQ_HIST IS '송무 소송의뢰 사건경과 내역 (행별 첨부 1건) ← tbetia41';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.HIST_ID      IS '경과 행 ID (채번 LAW_REQ_HIST_ID) ← tbetia41.HST_REQ_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.REQ_ID       IS '의뢰 ID (LAW_SUIT_REQ FK)';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.STA_DT       IS '기간 시작일 (YYYYMMDD) ← tbetia41.STA_DTTM';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.END_DT       IS '기간 종료일 (YYYYMMDD) ← tbetia41.END_DTTM';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.HIST_CN      IS '경과 내용 ← tbetia41.HST_BLBD_CONTN';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.ATCH_FILE_ID IS '행별 첨부파일 ID (표준 COMTNFILE)';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.SORT_ORDR    IS '표시 순서';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HIST.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_REQ_HIST_01 ON LAW_SUIT_REQ_HIST (REQ_ID);

-- ── 1.14 LAW_SUIT_REQ_HELPER 의뢰 소송수행 보조자 ← ReqLawsuitChps(tbetia13 재사용분) ──
CREATE TABLE LAW_SUIT_REQ_HELPER (
    HELPER_ID   NUMBER(10)  NOT NULL,
    REQ_ID      NUMBER(10)  NOT NULL,
    DEPT_NM     VARCHAR2(100),
    HELPER_NM   VARCHAR2(60),
    TEL         VARCHAR2(50),
    MOBILE      VARCHAR2(50),
    EMAIL       VARCHAR2(100),
    SORT_ORDR   NUMBER(5) DEFAULT 0,
    REG_USER_ID VARCHAR2(20),
    REG_DT      VARCHAR2(14),
    UPD_USER_ID VARCHAR2(20),
    UPD_DT      VARCHAR2(14),
    CONSTRAINT PK_LAW_SUIT_REQ_HELPER PRIMARY KEY (HELPER_ID)
);
COMMENT ON TABLE  LAW_SUIT_REQ_HELPER IS '송무 소송의뢰 수행 보조자 (부서명은 자유 텍스트 — 외부 인원 허용) ← tbetia13(ReqLawsuitChps 재사용분)';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.HELPER_ID   IS '보조자 행 ID (채번 LAW_REQ_HELPER_ID) ← tbetia13.LAWSUIT_CHPS_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.REQ_ID      IS '의뢰 ID (LAW_SUIT_REQ FK) ← tbetia13.REQ_SEQ';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.DEPT_NM     IS '부서명 ← tbetia13.PSTN_NM';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.HELPER_NM   IS '담당자 성명 ← tbetia13.CHPS_EMP_NM';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.TEL         IS '전화 ← tbetia13.CHPS_EMP_PHONE';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.MOBILE      IS '휴대폰 ← tbetia13.CHPS_EMP_MOBILE';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.EMAIL       IS '이메일 ← tbetia13.CHPS_EMP_EMAIL';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.SORT_ORDR   IS '표시 순서';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_SUIT_REQ_HELPER.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SUIT_REQ_HELPER_01 ON LAW_SUIT_REQ_HELPER (REQ_ID);

-- ── 1.15 LAW_SEIZE 가압류·가처분 ← tc_seize ──
CREATE TABLE LAW_SEIZE (
    SEIZE_ID     NUMBER(10)  NOT NULL,
    CREDITOR     VARCHAR2(200),
    DEBTOR       VARCHAR2(200),
    THIRD_DEBTOR VARCHAR2(200),
    ORGNZT_ID    CHAR(20),
    COURT_NM     VARCHAR2(150),
    CASE_NO      VARCHAR2(100),
    MEMO         CLOB,
    READ_CNT     NUMBER(10) DEFAULT 0,
    ATCH_FILE_ID CHAR(20),
    REG_USER_ID  VARCHAR2(20),
    REG_DT       VARCHAR2(14),
    UPD_USER_ID  VARCHAR2(20),
    UPD_DT       VARCHAR2(14),
    CONSTRAINT PK_LAW_SEIZE PRIMARY KEY (SEIZE_ID)
);
COMMENT ON TABLE  LAW_SEIZE IS '송무 압류관리(가압류·가처분) — 게시판형, 첨부 5개·10MB 제한(서버 검증 §7.10) ← tc_seize';
COMMENT ON COLUMN LAW_SEIZE.SEIZE_ID     IS '압류 ID (채번 LAW_SEIZE_ID) ← tc_seize.SEIZE_ID';
COMMENT ON COLUMN LAW_SEIZE.CREDITOR     IS '채권자 ← tc_seize.CHEKWON';
COMMENT ON COLUMN LAW_SEIZE.DEBTOR       IS '채무자 ← tc_seize.CHEMOO';
COMMENT ON COLUMN LAW_SEIZE.THIRD_DEBTOR IS '제3채무자 ← tc_seize.CHEMOO3';
COMMENT ON COLUMN LAW_SEIZE.ORGNZT_ID    IS '담당부서 ID (COMTNORGNZTINFO) ← tc_seize.DAMDANG_BUSEO(텍스트의 표준 대체)';
COMMENT ON COLUMN LAW_SEIZE.COURT_NM     IS '관할법원명 ← tc_seize.BUBWON';
COMMENT ON COLUMN LAW_SEIZE.CASE_NO      IS '사건번호 ← tc_seize.SAGUN_NO';
COMMENT ON COLUMN LAW_SEIZE.MEMO         IS '메모 ← tc_seize.MEMO';
COMMENT ON COLUMN LAW_SEIZE.READ_CNT     IS '조회수 (상세 열람 시 증가) ← tc_seize.READ_CNT';
COMMENT ON COLUMN LAW_SEIZE.ATCH_FILE_ID IS '첨부파일 ID (표준 COMTNFILE — 문서파일 5개·10MB 제한) ← tc_seizeattach 대체';
COMMENT ON COLUMN LAW_SEIZE.REG_USER_ID  IS '등록자 ID';
COMMENT ON COLUMN LAW_SEIZE.REG_DT       IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_SEIZE.UPD_USER_ID  IS '수정자 ID';
COMMENT ON COLUMN LAW_SEIZE.UPD_DT       IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_SEIZE_01 ON LAW_SEIZE (REG_DT);

-- ── 1.16 LAW_COURT_RECEIPT 법원서류접수 ← tbetia44 ──
CREATE TABLE LAW_COURT_RECEIPT (
    RECEIPT_ID     NUMBER(10)  NOT NULL,
    RECEIPT_TITL   VARCHAR2(200),
    ORGNZT_ID      CHAR(20),
    REL_ORGNZT_ID1 CHAR(20),
    REL_ORGNZT_ID2 CHAR(20),
    ATCH_FILE_ID   CHAR(20),
    REG_USER_ID    VARCHAR2(20),
    REG_DT         VARCHAR2(14),
    UPD_USER_ID    VARCHAR2(20),
    UPD_DT         VARCHAR2(14),
    CONSTRAINT PK_LAW_COURT_RECEIPT PRIMARY KEY (RECEIPT_ID)
);
COMMENT ON TABLE  LAW_COURT_RECEIPT IS '송무 법원서류접수 — 접수+관련부서 지정·표시까지(알림 발송은 비범위 §1.2) ← tbetia44';
COMMENT ON COLUMN LAW_COURT_RECEIPT.RECEIPT_ID     IS '접수 ID (채번 LAW_RECEIPT_ID) ← tbetia44.ACC_SEQ';
COMMENT ON COLUMN LAW_COURT_RECEIPT.RECEIPT_TITL   IS '제목 ← tbetia44.ACC_TITL';
COMMENT ON COLUMN LAW_COURT_RECEIPT.ORGNZT_ID      IS '등록부서 ID (등록자 소속 자동, COMTNORGNZTINFO) ← tbetia44.ACC_PSTN_CD';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REL_ORGNZT_ID1 IS '관련부서 1 (COMTNORGNZTINFO) ← tbetia44.ACC_PSTN_CD2';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REL_ORGNZT_ID2 IS '관련부서 2 (COMTNORGNZTINFO)';
COMMENT ON COLUMN LAW_COURT_RECEIPT.ATCH_FILE_ID   IS '관련자료 첨부파일 ID (표준 COMTNFILE) ← tbetia44.ACC_FILE_NM 대체';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REG_USER_ID    IS '등록자 ID ← tbetia44.ACC_EMP_NO';
COMMENT ON COLUMN LAW_COURT_RECEIPT.REG_DT         IS '등록일시 (YYYYMMDDHH24MISS) ← tbetia44.ACC_REG_DTTM';
COMMENT ON COLUMN LAW_COURT_RECEIPT.UPD_USER_ID    IS '수정자 ID';
COMMENT ON COLUMN LAW_COURT_RECEIPT.UPD_DT         IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_COURT_RECEIPT_01 ON LAW_COURT_RECEIPT (REG_DT);

-- ── 1.17 LAW_CALC_RATE 계산기 요율 (신규 — 레거시 JS 하드코딩의 DB화 §4.3) ──
CREATE TABLE LAW_CALC_RATE (
    RATE_ID     NUMBER(10)   NOT NULL,
    CALC_TYPE   VARCHAR2(20) NOT NULL,
    ITEM_CD     VARCHAR2(20),
    APPLY_DT    VARCHAR2(8)  NOT NULL,
    SECTION_AMT NUMBER(19),
    RATE_VAL    NUMBER(12,6),
    ADD_AMT     NUMBER(19),
    RMK         VARCHAR2(200),
    USE_YN      CHAR(1) DEFAULT 'Y' NOT NULL,
    REG_USER_ID VARCHAR2(20),
    REG_DT      VARCHAR2(14),
    UPD_USER_ID VARCHAR2(20),
    UPD_DT      VARCHAR2(14),
    CONSTRAINT PK_LAW_CALC_RATE PRIMARY KEY (RATE_ID)
);
COMMENT ON TABLE  LAW_CALC_RATE IS '송무 소송비용 계산기 요율 — 타입×항목×적용시작일 시점별 세트, 기준일 조회=APPLY_DT 이하 최신 세트(§7.4·7.13). 공식 뼈대는 JS, 숫자만 DB';
COMMENT ON COLUMN LAW_CALC_RATE.RATE_ID     IS '요율 행 ID (채번 LAW_CALC_RATE_ID)';
COMMENT ON COLUMN LAW_CALC_RATE.CALC_TYPE   IS '계산기 타입 — STAMP(인지액 구간표)/STAMP_MULT(인지액 사건종류 배율)/POST_UNIT(송달료 우편료 단가)/POST_COUNT(송달료 사건유형별 회수)/LAWYER(변호사비 산입 구간표)/LEGAL_INT(법정이율 프리셋)';
COMMENT ON COLUMN LAW_CALC_RATE.ITEM_CD     IS '항목 식별 — STAMP_MULT=사건종류(C1~C8, 레거시 select 값 승계)·MIN_AMT(최소 인지액), POST_COUNT=송달 사건유형(T01~T17), LEGAL_INT=CIVIL/COMM/SOCHOK. 구간표·단가 행은 NULL';
COMMENT ON COLUMN LAW_CALC_RATE.APPLY_DT    IS '적용시작일 (YYYYMMDD — 개정 시행일. 같은 타입·항목에 시점별 세트 공존)';
COMMENT ON COLUMN LAW_CALC_RATE.SECTION_AMT IS '구간 하한(소가, 원 — 구간표 행만. 단일값 행은 NULL)';
COMMENT ON COLUMN LAW_CALC_RATE.RATE_VAL    IS '값 — 타입별 의미: 율(0.005)·단가(5500)·배율(1.5)·회수(15)·이율(12). 배율 행에서 0이면 ADD_AMT 고정액 사건';
COMMENT ON COLUMN LAW_CALC_RATE.ADD_AMT     IS '구간 가산액(원 — 인지액·변호사비 구간표) 또는 고정액(배율 행 RATE_VAL=0 일 때)';
COMMENT ON COLUMN LAW_CALC_RATE.RMK         IS '근거 (고시·규칙 번호 등)';
COMMENT ON COLUMN LAW_CALC_RATE.USE_YN      IS '사용 여부 (Y/N — 과거 세트 이력 보존용 소프트 삭제 §7.13)';
COMMENT ON COLUMN LAW_CALC_RATE.REG_USER_ID IS '등록자 ID';
COMMENT ON COLUMN LAW_CALC_RATE.REG_DT      IS '등록일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_CALC_RATE.UPD_USER_ID IS '수정자 ID';
COMMENT ON COLUMN LAW_CALC_RATE.UPD_DT      IS '수정일시 (YYYYMMDDHH24MISS)';
CREATE INDEX IX_LAW_CALC_RATE_01 ON LAW_CALC_RATE (CALC_TYPE, APPLY_DT);

-- ── 1.18 LAW_LAWYER_SATIS 법무법인 만족도(간이) ← tbetia45 대체 ──
CREATE TABLE LAW_LAWYER_SATIS (
    ASSIGN_ID NUMBER(10)   NOT NULL,
    EMPLYR_ID VARCHAR2(20) NOT NULL,
    SCORE     NUMBER(1)    NOT NULL,
    OPINION   VARCHAR2(1000),
    REG_DT    VARCHAR2(14),
    UPD_DT    VARCHAR2(14),
    CONSTRAINT PK_LAW_LAWYER_SATIS PRIMARY KEY (ASSIGN_ID, EMPLYR_ID)
);
COMMENT ON TABLE  LAW_LAWYER_SATIS IS '송무 법무법인 만족도(간이 별점+의견) — 평가 대상=선임(사건×변호사) 단위, 1인 1회 MERGE(TB_PROM_STSFDG 패턴) ← tbetia45(9문항 가중 설문의 간소화 대체 §1.2)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.ASSIGN_ID IS '선임 ID (LAW_SUIT_LAWYER FK — 복합 PK)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.EMPLYR_ID IS '평가자 ID (COMTNEMPLYRINFO.EMPLYR_ID — 복합 PK, 1인 1회)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.SCORE     IS '별점 (1~5)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.OPINION   IS '의견 (선택)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.REG_DT    IS '최초 평가일시 (YYYYMMDDHH24MISS)';
COMMENT ON COLUMN LAW_LAWYER_SATIS.UPD_DT    IS '재평가일시 (YYYYMMDDHH24MISS — MERGE 갱신)';

-- ============================================================
-- 2) COMTECOPSEQ 채번 17행 (EgovIdGnrService — SQ_*.NEXTVAL 금지)
--    ⚠️ 시드가 ID 를 선점하는 테이블은 시작점 상향(채번충돌 방지):
--       LAW_COURT_ID=200(시드 최대 194), LAW_CALC_RATE_ID=100(요율 시드 41행).
-- ============================================================
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
SELECT s.T, s.N FROM (
  SELECT 'LAW_SUIT_ID' T, 1 N FROM DUAL UNION ALL
  SELECT 'LAW_PARTY_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_STAFF_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_LAND_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_PROG_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_RSLT_HIST_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_DOC_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_COST_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_LAWYER_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_ASSIGN_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_COURT_ID', 200 FROM DUAL UNION ALL
  SELECT 'LAW_REQ_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_REQ_HIST_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_REQ_HELPER_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_SEIZE_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_RECEIPT_ID', 1 FROM DUAL UNION ALL
  SELECT 'LAW_CALC_RATE_ID', 100 FROM DUAL
) s
 WHERE NOT EXISTS (SELECT 1 FROM COMTECOPSEQ ex WHERE ex.TABLE_NAME = s.T);

COMMIT;

-- ============================================================
-- 3) ccm 공통코드 — 그룹 15 + 상세 298
--    레거시 tbetia09/10 이관 13그룹(SB_CD 원값 보존 — 통계 축·승소그룹 참조) + 신규 2그룹.
--    CODE_DC = 'NNN_명칭' (정렬 정본 — 운영에서 접두 순번만 고치면 순서 반영).
-- ============================================================
INSERT INTO COMTCCMMNCODE (CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT s.CODE_ID, s.CODE_ID_NM, s.CODE_ID_DC, 'Y', NULL, SYSDATE, 'LAW_SEED' FROM (
  SELECT 'LAW_CASE_KIND' CODE_ID, '소송구분' CODE_ID_NM, '송무 소송구분 (레거시 A02 — 통계 4축 S001 민사/S002 행정/S012 국가/S009 심판, SB_CD 보존 필수)' CODE_ID_DC FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND', '제·피소구분', '송무 제·피소구분 (레거시 A03)' FROM DUAL UNION ALL
  SELECT 'LAW_RESULT', '소송결과', '송무 소송결과 (레거시 A04 — 승소그룹 S002/S003/S005/S006/S008/S997, 패소그룹 S004/S100/S101/S102/S998, SB_CD 보존 필수)' FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE', '심급', '송무 심급 (레거시 A07 — 심급별 통계 3축 S001/S002/S004, SB_CD 보존 필수)' FROM DUAL UNION ALL
  SELECT 'LAW_PROG_KIND', '진행종류', '송무 진행종류 (레거시 A10 — 기일/피고제출/원고제출/본부보고)' FROM DUAL UNION ALL
  SELECT 'LAW_PROG_STAT', '진행상태', '송무 진행상태 (레거시 A11 — 진행/완료)' FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND', '기일구분', '송무 기일구분 (레거시 A12)' FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND', '소송비용종류', '송무 소송비용종류 (레거시 A13)' FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND', '문서종류', '송무 소송문서 종류 (레거시 A19 — 소장~항고장 21종)' FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN', '사건부호', '송무 대법원 사건부호 (레거시 A28)' FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM', '사건명', '송무 사건명 (레거시 A29 — S999 직접입력)' FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE', '패소원인', '송무 패소원인 (레거시 A34)' FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE', '사건유형', '송무 사건유형 (레거시 A35)' FROM DUAL UNION ALL
  SELECT 'LAW_REQ_STATUS', '의뢰상태', '송무 소송의뢰 상태 (신규 — S001 신청/S002 승인/S003 반려)' FROM DUAL UNION ALL
  SELECT 'LAW_DOC_APP_STATUS', '문서 승인상태', '송무 소송문서 승인상태 (신규 — S001 대기/S002 승인/S003 반려, 레거시 DOC_APP_STS 텍스트의 코드화)' FROM DUAL
) s
 WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNCODE ex WHERE ex.CODE_ID = s.CODE_ID);

INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT s.CODE_ID, s.CODE, s.CODE_NM, s.CODE_DC, s.USE_AT, SYSDATE, 'LAW_SEED' FROM (
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S001' CODE, '민사' CODE_NM, '001_민사' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S002' CODE, '행정' CODE_NM, '002_행정' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S012' CODE, '국가' CODE_NM, '003_국가' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S004' CODE, '신청' CODE_NM, '005_신청' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S009' CODE, '행정심판' CODE_NM, '006_행정심판' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S006' CODE, '형사' CODE_NM, '007_형사' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S005' CODE, '집행' CODE_NM, '008_집행' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S011' CODE, '중재' CODE_NM, '009_중재' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S008' CODE, '민사조정' CODE_NM, '010_민사조정' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S007' CODE, '비송/도산' CODE_NM, '011_비송/도산' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S003' CODE, '헌재' CODE_NM, '012_헌재' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_KIND' CODE_ID, 'S010' CODE, '기타' CODE_NM, '013_기타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND' CODE_ID, 'S001' CODE, '제소' CODE_NM, '001_제소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND' CODE_ID, 'S002' CODE, '피소' CODE_NM, '002_피소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND' CODE_ID, 'S005' CODE, '항소' CODE_NM, '003_항소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND' CODE_ID, 'S006' CODE, '피항소' CODE_NM, '004_피항소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND' CODE_ID, 'S003' CODE, '상고' CODE_NM, '005_상고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_ITPT_KIND' CODE_ID, 'S004' CODE, '피상고' CODE_NM, '006_피상고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S001' CODE, '진행중' CODE_NM, '001_진행중' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S002' CODE, '승소' CODE_NM, '002_승소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S003' CODE, '일부승소' CODE_NM, '003_일부승소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S005' CODE, '취하' CODE_NM, '004_취하' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S006' CODE, '조정(권고)' CODE_NM, '005_조정(권고)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S008' CODE, '화해(권고)' CODE_NM, '006_화해(권고)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S004' CODE, '패소' CODE_NM, '500_패소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S100' CODE, '일부패소' CODE_NM, '510_일부패소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S101' CODE, '포기' CODE_NM, '520_포기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S102' CODE, '인낙' CODE_NM, '530_인낙' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S997' CODE, '기타(승소)' CODE_NM, '997_기타(승소)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_RESULT' CODE_ID, 'S998' CODE, '기타(패소)' CODE_NM, '998_기타(패소)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S001' CODE, '1심' CODE_NM, '001_1심' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S002' CODE, '2심' CODE_NM, '002_2심' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S003' CODE, '2심재심' CODE_NM, '003_2심재심' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S004' CODE, '3심' CODE_NM, '004_3심' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S005' CODE, '3심재심' CODE_NM, '005_3심재심' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S006' CODE, '행심' CODE_NM, '006_행심' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_INSTANCE' CODE_ID, 'S007' CODE, '기타' CODE_NM, '007_기타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_PROG_KIND' CODE_ID, 'S001' CODE, '기일' CODE_NM, '001_기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_PROG_KIND' CODE_ID, 'S002' CODE, '피고제출' CODE_NM, '002_피고제출' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_PROG_KIND' CODE_ID, 'S003' CODE, '원고제출' CODE_NM, '003_원고제출' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_PROG_KIND' CODE_ID, 'S004' CODE, '본부보고' CODE_NM, '004_본부보고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_PROG_STAT' CODE_ID, 'S001' CODE, '진행' CODE_NM, '001_진행' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_PROG_STAT' CODE_ID, 'S002' CODE, '완료' CODE_NM, '002_완료' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S001' CODE, '제출기일' CODE_NM, '001_제출기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S002' CODE, '변론기일' CODE_NM, '002_변론기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S003' CODE, '재결일' CODE_NM, '003_재결일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S004' CODE, '변론준비기일' CODE_NM, '004_변론준비기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S005' CODE, '감정기일' CODE_NM, '005_감정기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S006' CODE, '검증기일' CODE_NM, '006_검증기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S007' CODE, '판결선고기일' CODE_NM, '007_판결선고기일' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DYPR_KIND' CODE_ID, 'S999' CODE, '기타' CODE_NM, '009_기타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S001' CODE, '인지액' CODE_NM, '001_인지액' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S002' CODE, '송달료' CODE_NM, '002_송달료' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S003' CODE, '지연이자' CODE_NM, '003_지연이자' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S004' CODE, '공탁금' CODE_NM, '004_공탁금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S005' CODE, '변호사비용' CODE_NM, '005_변호사비용' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S006' CODE, '조세비용' CODE_NM, '006_조세비용' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S007' CODE, '조정 및  중재비용' CODE_NM, '007_조정 및  중재비용' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_COST_KIND' CODE_ID, 'S008' CODE, '기타' CODE_NM, '008_기타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S001' CODE, '소장' CODE_NM, '001_소장' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S002' CODE, '답변서' CODE_NM, '002_답변서' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S003' CODE, '준비서면' CODE_NM, '003_준비서면' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S004' CODE, '판결문' CODE_NM, '004_판결문' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S005' CODE, '참고서면' CODE_NM, '005_참고서면' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S006' CODE, '사실조회신청서' CODE_NM, '006_사실조회신청서' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S007' CODE, '감정신청' CODE_NM, '007_감정신청' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S008' CODE, '증인신청' CODE_NM, '008_증인신청' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S009' CODE, '화해권고결정문' CODE_NM, '009_화해권고결정문' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S010' CODE, '조정결정문' CODE_NM, '010_조정결정문' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S011' CODE, '소취하서' CODE_NM, '011_소취하서' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S012' CODE, '변론기일연기신청' CODE_NM, '012_변론기일연기신청' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S013' CODE, '발생보고' CODE_NM, '013_발생보고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S014' CODE, '종결보고' CODE_NM, '014_종결보고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S015' CODE, '기타' CODE_NM, '015_기타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S016' CODE, '청구서' CODE_NM, '016_청구서' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S017' CODE, '보충서면' CODE_NM, '017_보충서면' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S018' CODE, '재결서' CODE_NM, '018_재결서' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S019' CODE, '항소장' CODE_NM, '019_항소장' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S020' CODE, '상고장' CODE_NM, '020_상고장' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_DOC_KIND' CODE_ID, 'S021' CODE, '항고장' CODE_NM, '021_항고장' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S008' CODE, '가단' CODE_NM, '001_가단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S009' CODE, '가합' CODE_NM, '002_가합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S010' CODE, '가소' CODE_NM, '003_가소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S011' CODE, '나' CODE_NM, '004_나' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S012' CODE, '다' CODE_NM, '005_다' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S127' CODE, '구단' CODE_NM, '006_구단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S128' CODE, '구합' CODE_NM, '007_구합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S109' CODE, '누' CODE_NM, '008_누' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S110' CODE, '두' CODE_NM, '009_두' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S001' CODE, '호파' CODE_NM, '011_호파' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S002' CODE, '호' CODE_NM, '012_호' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S003' CODE, '금' CODE_NM, '013_금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S004' CODE, '증' CODE_NM, '014_증' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S005' CODE, '물' CODE_NM, '015_물' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S006' CODE, '영장' CODE_NM, '016_영장' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S007' CODE, '차전' CODE_NM, '017_차전' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S013' CODE, '라' CODE_NM, '023_라' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S014' CODE, '마' CODE_NM, '024_마' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S015' CODE, '바' CODE_NM, '025_바' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S016' CODE, '자' CODE_NM, '026_자' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S017' CODE, '차' CODE_NM, '027_차' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S018' CODE, '러' CODE_NM, '028_러' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S019' CODE, '머' CODE_NM, '029_머' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S020' CODE, '그' CODE_NM, '030_그' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S021' CODE, '재가단' CODE_NM, '031_재가단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S022' CODE, '재가합' CODE_NM, '032_재가합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S023' CODE, '재가소' CODE_NM, '033_재가소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S024' CODE, '재나' CODE_NM, '034_재나' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S025' CODE, '재다' CODE_NM, '035_재다' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S026' CODE, '재차' CODE_NM, '036_재차' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S027' CODE, '재머' CODE_NM, '037_재머' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S028' CODE, '준재가단' CODE_NM, '038_준재가단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S029' CODE, '준재가합' CODE_NM, '039_준재가합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S030' CODE, '준재가소' CODE_NM, '040_준재가소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S031' CODE, '준재나' CODE_NM, '041_준재나' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S032' CODE, '준재머' CODE_NM, '042_준재머' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S033' CODE, '재마' CODE_NM, '043_재마' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S034' CODE, '재그' CODE_NM, '044_재그' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S035' CODE, '준재마' CODE_NM, '045_준재마' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S036' CODE, '재자' CODE_NM, '046_재자' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S037' CODE, '재라' CODE_NM, '047_재라' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S038' CODE, '준재다' CODE_NM, '048_준재다' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S039' CODE, '준재라' CODE_NM, '049_준재라' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S041' CODE, '파' CODE_NM, '051_파' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S042' CODE, '하' CODE_NM, '052_하' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S043' CODE, '거' CODE_NM, '053_거' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S044' CODE, '재하' CODE_NM, '054_재하' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S045' CODE, '준재하' CODE_NM, '055_준재하' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S046' CODE, '과' CODE_NM, '056_과' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S047' CODE, '회' CODE_NM, '057_회' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S048' CODE, '선' CODE_NM, '058_선' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S049' CODE, '유' CODE_NM, '059_유' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S050' CODE, '화' CODE_NM, '060_화' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S051' CODE, '책' CODE_NM, '061_책' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S052' CODE, '파합' CODE_NM, '062_파합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S053' CODE, '파단' CODE_NM, '063_파단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S054' CODE, '하합' CODE_NM, '064_하합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S055' CODE, '하단' CODE_NM, '065_하단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S056' CODE, '하면' CODE_NM, '066_하면' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S057' CODE, '비합' CODE_NM, '067_비합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S058' CODE, '비단' CODE_NM, '068_비단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S059' CODE, '재과' CODE_NM, '069_재과' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S060' CODE, '준재과' CODE_NM, '070_준재과' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S061' CODE, '개회' CODE_NM, '071_개회' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S062' CODE, '개확' CODE_NM, '072_개확' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S063' CODE, '개보' CODE_NM, '073_개보' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S064' CODE, '하보' CODE_NM, '074_하보' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S065' CODE, '화보' CODE_NM, '075_화보' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S066' CODE, '회보' CODE_NM, '076_회보' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S067' CODE, '재비합' CODE_NM, '077_재비합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S068' CODE, '재비단' CODE_NM, '078_재비단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S069' CODE, '개기' CODE_NM, '079_개기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S070' CODE, '하확' CODE_NM, '080_하확' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S071' CODE, '하기' CODE_NM, '081_하기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S072' CODE, '국승' CODE_NM, '082_국승' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S073' CODE, '국지' CODE_NM, '083_국지' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S074' CODE, '회단' CODE_NM, '084_회단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S075' CODE, '회합' CODE_NM, '085_회합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S076' CODE, '회확' CODE_NM, '086_회확' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S077' CODE, '회기' CODE_NM, '087_회기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S078' CODE, '카' CODE_NM, '088_카' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S079' CODE, '카공' CODE_NM, '089_카공' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S080' CODE, '카합' CODE_NM, '090_카합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S081' CODE, '카단' CODE_NM, '091_카단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S082' CODE, '카담' CODE_NM, '092_카담' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S083' CODE, '카기' CODE_NM, '093_카기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S084' CODE, '재카합' CODE_NM, '094_재카합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S085' CODE, '재카단' CODE_NM, '095_재카단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S086' CODE, '재카담' CODE_NM, '096_재카담' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S087' CODE, '재카기' CODE_NM, '097_재카기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S088' CODE, '카명' CODE_NM, '098_카명' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S089' CODE, '카조' CODE_NM, '099_카조' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S090' CODE, '카구' CODE_NM, '100_카구' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S091' CODE, '재카구' CODE_NM, '101_재카구' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S092' CODE, '준재카합' CODE_NM, '102_준재카합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S093' CODE, '준재카단' CODE_NM, '103_준재카단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S094' CODE, '준재카담' CODE_NM, '104_준재카담' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S095' CODE, '준재카기' CODE_NM, '105_준재카기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S096' CODE, '카기전' CODE_NM, '106_카기전' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S097' CODE, '카확' CODE_NM, '107_카확' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S098' CODE, '타경' CODE_NM, '108_타경' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S099' CODE, '타기' CODE_NM, '109_타기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S100' CODE, '타' CODE_NM, '110_타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S101' CODE, '재타경' CODE_NM, '111_재타경' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S102' CODE, '준재타경' CODE_NM, '112_준재타경' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S103' CODE, '타채' CODE_NM, '113_타채' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S104' CODE, '재타기' CODE_NM, '114_재타기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S105' CODE, '본' CODE_NM, '115_본' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S106' CODE, '가' CODE_NM, '116_가' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S107' CODE, '징' CODE_NM, '117_징' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S108' CODE, '구' CODE_NM, '118_구' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S111' CODE, '루' CODE_NM, '121_루' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S112' CODE, '부' CODE_NM, '122_부' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S113' CODE, '재구' CODE_NM, '123_재구' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S114' CODE, '재누' CODE_NM, '124_재누' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S115' CODE, '사' CODE_NM, '125_사' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S116' CODE, '아' CODE_NM, '126_아' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S117' CODE, '재두' CODE_NM, '127_재두' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S118' CODE, '무' CODE_NM, '128_무' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S119' CODE, '재아' CODE_NM, '129_재아' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S120' CODE, '준재구' CODE_NM, '130_준재구' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S121' CODE, '준재누' CODE_NM, '131_준재누' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S122' CODE, '준재아' CODE_NM, '132_준재아' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S123' CODE, '준재두' CODE_NM, '133_준재두' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S124' CODE, '재무' CODE_NM, '134_재무' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S125' CODE, '준재루' CODE_NM, '135_준재루' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S126' CODE, '재루' CODE_NM, '136_재루' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S129' CODE, '재구단' CODE_NM, '139_재구단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S130' CODE, '재구합' CODE_NM, '140_재구합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S131' CODE, '준재구단' CODE_NM, '141_준재구단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S132' CODE, '준재구합' CODE_NM, '142_준재구합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S133' CODE, '고합' CODE_NM, '143_고합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S134' CODE, '감고' CODE_NM, '144_감고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S135' CODE, '고단' CODE_NM, '145_고단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S136' CODE, '고약' CODE_NM, '146_고약' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S137' CODE, '노' CODE_NM, '147_노' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S138' CODE, '감노' CODE_NM, '148_감노' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S139' CODE, '도' CODE_NM, '149_도' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S140' CODE, '감도' CODE_NM, '150_감도' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S141' CODE, '로' CODE_NM, '151_로' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S142' CODE, '감로' CODE_NM, '152_감로' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S143' CODE, '모' CODE_NM, '153_모' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S144' CODE, '감모' CODE_NM, '154_감모' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S145' CODE, '보' CODE_NM, '155_보' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S146' CODE, '오' CODE_NM, '156_오' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S147' CODE, '감오' CODE_NM, '157_감오' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S148' CODE, '조' CODE_NM, '158_조' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S149' CODE, '초' CODE_NM, '159_초' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S150' CODE, '감초' CODE_NM, '160_감초' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S151' CODE, '코' CODE_NM, '161_코' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S152' CODE, '토' CODE_NM, '162_토' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S153' CODE, '감토' CODE_NM, '163_감토' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S154' CODE, '재고합' CODE_NM, '164_재고합' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S155' CODE, '재고단' CODE_NM, '165_재고단' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S156' CODE, '재고약' CODE_NM, '166_재고약' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S157' CODE, '재노' CODE_NM, '167_재노' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S158' CODE, '재도' CODE_NM, '168_재도' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S159' CODE, '재감고' CODE_NM, '169_재감고' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S160' CODE, '재감노' CODE_NM, '170_재감노' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S161' CODE, '재감도' CODE_NM, '171_재감도' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S162' CODE, '초적' CODE_NM, '172_초적' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S163' CODE, '초보' CODE_NM, '173_초보' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S164' CODE, '초기' CODE_NM, '174_초기' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S165' CODE, '고정' CODE_NM, '175_고정' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S166' CODE, '재고정' CODE_NM, '176_재고정' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S167' CODE, '헌가' CODE_NM, '177_헌가' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S168' CODE, '헌나' CODE_NM, '178_헌나' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S169' CODE, '헌다' CODE_NM, '179_헌다' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S170' CODE, '헌라' CODE_NM, '180_헌라' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S171' CODE, '헌마' CODE_NM, '181_헌마' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S172' CODE, '헌바' CODE_NM, '182_헌바' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S173' CODE, '헌사' CODE_NM, '183_헌사' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S174' CODE, '헌아' CODE_NM, '184_헌아' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_SIGN' CODE_ID, 'S175' CODE, '부해' CODE_NM, '185_부해' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S014' CODE, '손해배상(기)' CODE_NM, '001_손해배상(기)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S010' CODE, '손해배상(자)' CODE_NM, '002_손해배상(자)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S015' CODE, '손해배상(지)' CODE_NM, '003_손해배상(지)' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S002' CODE, '양수금' CODE_NM, '004_양수금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S001' CODE, '대여금' CODE_NM, '005_대여금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S003' CODE, '임금' CODE_NM, '006_임금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S004' CODE, '약정금' CODE_NM, '007_약정금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S005' CODE, '임대차보증금' CODE_NM, '008_임대차보증금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S006' CODE, '매매대금' CODE_NM, '009_매매대금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S007' CODE, '물품대금' CODE_NM, '010_물품대금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S008' CODE, '공사대금' CODE_NM, '011_공사대금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S009' CODE, '어음금' CODE_NM, '012_어음금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S012' CODE, '건물명도' CODE_NM, '013_건물명도' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S011' CODE, '수표금' CODE_NM, '014_수표금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S016' CODE, '부당이득금' CODE_NM, '015_부당이득금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S017' CODE, '부당해고구제신청' CODE_NM, '016_부당해고구제신청' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S018' CODE, '부당해고구제재심판정취소' CODE_NM, '017_부당해고구제재심판정취소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CASE_NM' CODE_ID, 'S999' CODE, '직접입력' CODE_NM, '999_직접입력' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S001' CODE, '사건의 성질상 패소' CODE_NM, '001_사건의 성질상 패소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S002' CODE, '하자있는 행정처분' CODE_NM, '002_하자있는 행정처분' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S003' CODE, '증거멸실' CODE_NM, '003_증거멸실' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S004' CODE, '법령해석의 견해차이' CODE_NM, '004_법령해석의 견해차이' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S005' CODE, '증거판단의 견해차이' CODE_NM, '005_증거판단의 견해차이' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S006' CODE, '재량권 범위 등에 관한 견해차이' CODE_NM, '006_재량권 범위 등에 관한 견해차이' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S007' CODE, '소송수행 잘못' CODE_NM, '007_소송수행 잘못' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_LOSS_CAUSE' CODE_ID, 'S008' CODE, '기타' CODE_NM, '008_기타' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S001' CODE, '소유권 확인' CODE_NM, '001_소유권 확인' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S002' CODE, '조세관계' CODE_NM, '002_조세관계' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S003' CODE, '국토/도시계획 관련 허가사항' CODE_NM, '003_국토/도시계획 관련 허가사항' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S004' CODE, '영업허가 취소, 정지' CODE_NM, '004_영업허가 취소, 정지' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S005' CODE, '과징금 등 부과취소' CODE_NM, '005_과징금 등 부과취소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S013' CODE, '토지 등 손실(수용)보상' CODE_NM, '006_토지 등 손실(수용)보상' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S007' CODE, '행정 기타사건' CODE_NM, '007_행정 기타사건' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S008' CODE, '부당이득금' CODE_NM, '008_부당이득금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S009' CODE, '손해배상' CODE_NM, '009_손해배상' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S010' CODE, '구상금' CODE_NM, '010_구상금' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S011' CODE, '소유권 이전, 말소' CODE_NM, '011_소유권 이전, 말소' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_CIVIL_CASE' CODE_ID, 'S012' CODE, '민사 기타사건' CODE_NM, '012_민사 기타사건' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_REQ_STATUS' CODE_ID, 'S001' CODE, '신청' CODE_NM, '001_신청' CODE_DC, 'Y' USE_AT FROM DUAL UNION ALL
  SELECT 'LAW_REQ_STATUS', 'S002', '승인', '002_승인', 'Y' FROM DUAL UNION ALL
  SELECT 'LAW_REQ_STATUS', 'S003', '반려', '003_반려', 'Y' FROM DUAL UNION ALL
  SELECT 'LAW_DOC_APP_STATUS', 'S001', '대기', '001_대기', 'Y' FROM DUAL UNION ALL
  SELECT 'LAW_DOC_APP_STATUS', 'S002', '승인', '002_승인', 'Y' FROM DUAL UNION ALL
  SELECT 'LAW_DOC_APP_STATUS', 'S003', '반려', '003_반려', 'Y' FROM DUAL
) s
 WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE ex WHERE ex.CODE_ID = s.CODE_ID AND ex.CODE = s.CODE);

COMMIT;

-- ============================================================
-- 4) LAW_COURT 대표 시드 22행 (레거시 tbetia31 발췌 — 트리 정합 유지)
--    루트(0)+대법원+고법 5+창원재판부+특허/가정/행정+주요 지법+창원지법·김해시법원+헌재·행심위.
--    ⚠️ 김해시법원 UPPER 는 레거시 오류(울산 28)를 창원지법(135)으로 정정.
--    RMK = 해당 법원 취급 사건부호 화이트리스트(파이프 구분 — 원본 보존).
-- ============================================================
INSERT INTO LAW_COURT (COURT_ID, UPPER_COURT_ID, COURT_NM, SORT_ORDR, USE_YN, RMK, REG_USER_ID, REG_DT)
SELECT s.COURT_ID, s.UPPER_COURT_ID, s.COURT_NM, s.SORT_ORDR, 'Y', s.RMK, 'LAW_SEED', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') FROM (
  SELECT 0 COURT_ID, NULL UPPER_COURT_ID, '법원' COURT_NM, 0 SORT_ORDR, NULL RMK FROM DUAL UNION ALL
  SELECT 1 COURT_ID, 0 UPPER_COURT_ID, '대법원' COURT_NM, 0 SORT_ORDR, 'S140|S144|S147|S150|S020|S109|S012|S139|S110|S014|S019|S143|S118|S015|S112|S115|S116|S146|S161|S034|S114|S025|S158|S117|S033|S124|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 2 COURT_ID, 0 UPPER_COURT_ID, '서울고등법원' COURT_NM, 1 SORT_ORDR, 'S138|S142|S150|S108|S127|S128|S011|S137|S109|S013|S141|S111|S019|S145|S116|S016|S160|S113|S129|S130|S024|S157|S114|S037|S126|S027|S120|S031|S121|S032|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 4 COURT_ID, 0 UPPER_COURT_ID, '대전고등법원' COURT_NM, 3 SORT_ORDR, 'S138|S142|S150|S108|S127|S128|S011|S137|S109|S013|S141|S111|S019|S145|S116|S016|S160|S113|S129|S130|S024|S157|S114|S037|S126|S027|S120|S031|S121|S032|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 6 COURT_ID, 0 UPPER_COURT_ID, '대구고등법원' COURT_NM, 5 SORT_ORDR, 'S138|S142|S150|S108|S127|S128|S011|S137|S109|S013|S141|S111|S019|S145|S116|S016|S160|S113|S129|S130|S024|S157|S114|S037|S126|S027|S120|S031|S121|S032|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 7 COURT_ID, 0 UPPER_COURT_ID, '부산고등법원' COURT_NM, 6 SORT_ORDR, 'S138|S142|S150|S108|S127|S128|S011|S137|S109|S013|S141|S111|S019|S145|S116|S016|S160|S113|S129|S130|S024|S157|S114|S037|S126|S027|S120|S031|S121|S032|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 8 COURT_ID, 0 UPPER_COURT_ID, '부산고등법원(창원재판부)' COURT_NM, 7 SORT_ORDR, 'S138|S142|S150|S108|S127|S128|S011|S137|S109|S013|S141|S111|S019|S145|S116|S016|S160|S113|S129|S130|S024|S157|S114|S037|S126|S027|S120|S031|S121|S032|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 9 COURT_ID, 0 UPPER_COURT_ID, '광주고등법원' COURT_NM, 8 SORT_ORDR, 'S138|S142|S150|S108|S127|S128|S011|S137|S109|S013|S141|S111|S019|S145|S116|S016|S160|S113|S129|S130|S024|S157|S114|S037|S126|S027|S120|S031|S121|S032|S149|S164|S163|S162|S078|S083|S096|S082|S088|S080|S097|S151' RMK FROM DUAL UNION ALL
  SELECT 12 COURT_ID, 0 UPPER_COURT_ID, '특허법원' COURT_NM, 11 SORT_ORDR, 'S176|S175' RMK FROM DUAL UNION ALL
  SELECT 13 COURT_ID, 0 UPPER_COURT_ID, '서울가정법원' COURT_NM, 12 SORT_ORDR, 'S013|S111|S016|S037|S126|S001' RMK FROM DUAL UNION ALL
  SELECT 14 COURT_ID, 0 UPPER_COURT_ID, '서울행정법원' COURT_NM, 13 SORT_ORDR, 'S108|S127|S128|S116|S016|S113|S129|S130|S120' RMK FROM DUAL UNION ALL
  SELECT 15 COURT_ID, 0 UPPER_COURT_ID, '서울중앙지방법원' COURT_NM, 14 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S024|S157|S037|S126|S027|S028|S030|S029|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 21 COURT_ID, 0 UPPER_COURT_ID, '인천지방법원' COURT_NM, 20 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 22 COURT_ID, 0 UPPER_COURT_ID, '수원지방법원' COURT_NM, 21 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 24 COURT_ID, 0 UPPER_COURT_ID, '대전지방법원' COURT_NM, 23 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 26 COURT_ID, 0 UPPER_COURT_ID, '대구지방법원' COURT_NM, 25 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 27 COURT_ID, 0 UPPER_COURT_ID, '부산지방법원' COURT_NM, 26 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 28 COURT_ID, 0 UPPER_COURT_ID, '울산지방법원' COURT_NM, 27 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 135 COURT_ID, 0 UPPER_COURT_ID, '창원지방법원' COURT_NM, 28 SORT_ORDR, 'S008|S010|S009|S134|S138|S142|S150|S069|S063|S062|S061|S135|S136|S165|S133|S108|S127|S128|S011|S137|S013|S141|S111|S019|S145|S116|S016|S021|S023|S022|S159|S160|S155|S166|S154|S113|S129|S130|S024|S157|S037|S126|S027|S028|S030|S029|S120|S031|S032|S017|S007|S149|S164|S163|S162|S079|S083|S096|S081|S082|S088|S089|S080|S097|S151|S099|S103|S071|S055|S056|S054|S070|S001|S077|S074|S075|S076' RMK FROM DUAL UNION ALL
  SELECT 142 COURT_ID, 135 UPPER_COURT_ID, '김해시법원' COURT_NM, 9 SORT_ORDR, 'S008|S010|S019|S016|S023|S027|S030|S032|S017|S007|S083|S081|S082|S097|S001' RMK FROM DUAL UNION ALL
  SELECT 193 COURT_ID, 0 UPPER_COURT_ID, '헌법재판소' COURT_NM, 33 SORT_ORDR, 'S001|S002|S003|S004|S005|S006|S007|S008|S009|S010|S011|S012|S013|S014|S015|S016|S017|S018|S019|S020|S021|S022|S023|S024|S025|S026|S027|S028|S029|S030|S031|S032|S033|S034|S035|S036|S037|S038|S039|S041|S042|S043|S044|S045|S046|S047|S048|S049|S050|S051|S052|S053|S054|S055|S056|S057|S058|S059|S060|S061|S062|S063|S064|S065|S066|S067|S068|S069|S070|S071|S072|S073|S074|S075|S076|S077|S078|S079|S080|S081|S082|S083|S084|S085|S086|S087|S088|S089|S090|S091|S092|S093|S094|S095|S096|S097|S098|S099|S100|S101|S102|S103|S104|S105|S106|S107|S108|S109|S110|S111|S112|S113|S114|S115|S116|S117|S118|S119|S120|S121|S122|S123|S124|S125|S126|S127|S128|S129|S130|S131|S132|S133|S134|S135|S136|S137|S138|S139|S140|S141|S142|S143|S144|S145|S146|S147|S148|S149|S150|S151|S152|S153|S154|S155|S156|S157|S158|S159|S160|S161|S162|S163|S164|S165|S166|S167|S168|S169|S170|S171|S172|S173|S174|S175|S176|S177' RMK FROM DUAL UNION ALL
  SELECT 194 COURT_ID, 0 UPPER_COURT_ID, '행정심판위원회' COURT_NM, 34 SORT_ORDR, NULL RMK FROM DUAL
) s
 WHERE NOT EXISTS (SELECT 1 FROM LAW_COURT ex WHERE ex.COURT_ID = s.COURT_ID);

COMMIT;

-- ============================================================
-- 5) LAW_CALC_RATE 현행 요율 1세트 (APPLY_DT=20260101)
--    공식 뼈대(구간 곱셈+가산·배율·당사자수×단가×회수·100원 미만 절사)는 JS,
--    숫자만 여기서 온다(§7.4). 과거 세트·개정 세트는 요율설정 화면(§7.13)에서 운영 등록.
--    레거시 popupMoneyPlan.jsp 하드코딩 추출 + 현행 고시 반영
--    (송달료 1회분 5,500원 = 과학기술정보통신부고시 제2025-24호 2025.6.1 시행 확인).
-- ============================================================
INSERT INTO LAW_CALC_RATE (RATE_ID, CALC_TYPE, ITEM_CD, APPLY_DT, SECTION_AMT, RATE_VAL, ADD_AMT, RMK, USE_YN, REG_USER_ID, REG_DT)
SELECT ROWNUM, s.CT, s.IC, '20260101', s.SA, s.RV, s.AA, s.RMK, 'Y', 'LAW_SEED', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') FROM (
  SELECT 'STAMP' CT, CAST(NULL AS VARCHAR2(20)) IC, 0 SA, 0.005 RV, 0 AA, '인지액 구간 — 소가 1천만원 미만 0.5% (민사소송등인지법 2조)' RMK FROM DUAL UNION ALL
  SELECT 'STAMP', NULL, 10000000, 0.0045, 5000, '인지액 구간 — 1천만원 이상 1억원 미만 0.45%+5,000' FROM DUAL UNION ALL
  SELECT 'STAMP', NULL, 100000000, 0.004, 55000, '인지액 구간 — 1억원 이상 10억원 미만 0.4%+55,000' FROM DUAL UNION ALL
  SELECT 'STAMP', NULL, 1000000000, 0.0035, 555000, '인지액 구간 — 10억원 이상 0.35%+555,000' FROM DUAL UNION ALL
  SELECT 'STAMP', 'MIN_AMT', NULL, 1000, NULL, '최소 인지액 — 산출액 1,000원 미만은 1,000원' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C1', NULL, 1, NULL, '민사 제1심 소장 — 기본 1배' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C2', NULL, 1.5, NULL, '항소장 — 1.5배' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C3', NULL, 2, NULL, '상고장 — 2배' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C4', NULL, 1, NULL, '청구변경신청 — 1배(차액 기준 계산은 JS 뼈대)' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C5', NULL, 0.2, NULL, '화해신청 — 5분의 1' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C6', NULL, 0.1, NULL, '지급명령 신청 — 10분의 1' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C7', NULL, 0, 5000, '부동산 강제경매 신청 — 정액 5,000원 (RATE_VAL 0=정액사건)' FROM DUAL UNION ALL
  SELECT 'STAMP_MULT', 'C8', NULL, 0, 4000, '채권압류명령 신청 — 정액 4,000원 (레거시 2,000원의 현행 정정)' FROM DUAL UNION ALL
  SELECT 'POST_UNIT', NULL, NULL, 5500, NULL, '1회 송달료(우편료) — 과학기술정보통신부고시 제2025-24호(2025.6.1 시행)' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T01', NULL, 10, NULL, '민사1심 소액사건(가소) 당사자별 10회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T02', NULL, 15, NULL, '민사1심 단독사건(가단) 당사자별 15회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T03', NULL, 15, NULL, '민사1심 합의사건(가합) 당사자별 15회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T04', NULL, 12, NULL, '민사 항소사건(나) 당사자별 12회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T05', NULL, 8, NULL, '민사 상고사건(다) 당사자별 8회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T06', NULL, 5, NULL, '민사 항고·재항고사건(라·마) 당사자별 5회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T07', NULL, 4, NULL, '민사 독촉사건(차) 당사자별 4회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T08', NULL, 3, NULL, '가압류·가처분사건(카합·카단) 당사자별 3회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T09', NULL, 8, NULL, '가압류·가처분 이의사건 당사자별 8회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T10', NULL, 10, NULL, '부동산 등 경매사건(타경) 당사자별 10회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T11', NULL, 5, NULL, '민사 조정사건(머) 당사자별 5회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T12', NULL, 10, NULL, '행정 제1심사건(구단·구합) 당사자별 10회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T13', NULL, 10, NULL, '행정 항소사건(누) 당사자별 10회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T14', NULL, 8, NULL, '행정 상고사건(두) 당사자별 8회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T15', NULL, 3, NULL, '행정 항고사건(루) 당사자별 3회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T16', NULL, 5, NULL, '행정 재항고사건(무) 당사자별 5회' FROM DUAL UNION ALL
  SELECT 'POST_COUNT', 'T17', NULL, 2, NULL, '행정 신청사건(아) 당사자별 2회' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 0, 0.1, 0, '변호사비 산입 구간 — 2천만원까지 10% (변호사보수의 소송비용 산입에 관한 규칙 별표, 2018.4.1 시행분)' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 20000000, 0.08, 2000000, '변호사비 산입 구간 — 2천만원 초과 5천만원까지 200만+초과분 8%' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 50000000, 0.06, 4400000, '변호사비 산입 구간 — 5천만원 초과 1억원까지 440만+초과분 6%' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 100000000, 0.04, 7400000, '변호사비 산입 구간 — 1억원 초과 1.5억원까지 740만+초과분 4%' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 150000000, 0.02, 9400000, '변호사비 산입 구간 — 1.5억원 초과 2억원까지 940만+초과분 2%' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 200000000, 0.01, 10400000, '변호사비 산입 구간 — 2억원 초과 5억원까지 1,040만+초과분 1%' FROM DUAL UNION ALL
  SELECT 'LAWYER', NULL, 500000000, 0.005, 13400000, '변호사비 산입 구간 — 5억원 초과 1,340만+초과분 0.5%' FROM DUAL UNION ALL
  SELECT 'LEGAL_INT', 'CIVIL', NULL, 5, NULL, '법정이율 프리셋 — 민사 연 5% (민법 379조)' FROM DUAL UNION ALL
  SELECT 'LEGAL_INT', 'COMM', NULL, 6, NULL, '법정이율 프리셋 — 상사 연 6% (상법 54조)' FROM DUAL UNION ALL
  SELECT 'LEGAL_INT', 'SOCHOK', NULL, 12, NULL, '법정이율 프리셋 — 소송촉진법 연 12% (시행령, 2019.6.1 이후 적용분)' FROM DUAL
) s
 WHERE NOT EXISTS (SELECT 1 FROM LAW_CALC_RATE ex WHERE ex.CALC_TYPE = s.CT);

COMMIT;

-- 검증:
--   코멘트 전수: SELECT COUNT(*) FROM user_col_comments WHERE table_name LIKE 'LAW_%' AND comments IS NULL;  (0 이어야)
--                SELECT COUNT(*) FROM user_tab_comments WHERE table_name LIKE 'LAW_%' AND comments IS NULL;  (0 이어야)
--   코드:       SELECT CODE_ID, COUNT(*) FROM COMTCCMMNDETAILCODE WHERE CODE_ID LIKE 'LAW_%' GROUP BY CODE_ID ORDER BY CODE_ID;
--   법원:       SELECT COUNT(*) FROM LAW_COURT;  (22)
--   요율:       SELECT CALC_TYPE, COUNT(*) FROM LAW_CALC_RATE GROUP BY CALC_TYPE;  (STAMP 5/STAMP_MULT 8/POST_UNIT 1/POST_COUNT 17/LAWYER 7/LEGAL_INT 3)
