--------------------------------------------------------------------------------
-- 26_seed_idgn.sql — COMTECOPSEQ 채번 시드 (EgovIdGnrService 전략 테이블)
-- RLMS(MariaDB) 클린 설치 세트 — ★라이브 RLMS(2026-08-06 상태)에서 재생성.
-- 실행 계정: rlms. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 생성기: tools/multidb/SeedGen.java (정본=라이브 DB. 손편집 금지 — 다시 뽑을 것)
-- ★값은 라이브가 아니라 1 로 초기화한다(클린 설치라 데이터가 없다).
-- 행이 없으면 해당 기능의 첫 INSERT 가 실패한다 — 키 목록은 라이브 전수를 따른다.
-- ★LAW_COURT_ID=200 / LAW_CALC_RATE_ID=100 — 25 시드가 ID 를 선점하므로 시작점을 올린다(PK 충돌 방지).
--------------------------------------------------------------------------------


INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('ACT_LOG_NO', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('ANSWER_NO', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('ATTACH_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('BANNER_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('BATCH_OPERT_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('BATCH_SCHDUL_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('BBS_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('CATE_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('DOCU_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('FAQ_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('FAVOR_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('FILE_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('GAEJUNG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('GROUP_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAWQUEST_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_ASSIGN_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_CALC_RATE_ID', 100);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_COST_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_COURT_ID', 200);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_DOC_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_LAND_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_LAWYER_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_PARTY_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_PROG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_RECEIPT_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_REQ_HELPER_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_REQ_HIST_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_REQ_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_RSLT_HIST_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_SEIZE_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_STAFF_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LAW_SUIT_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('LOGINLOG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('MEMO_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('NTT_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('ORGNZT_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PMAP_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('POPUP_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PRIVACYLOG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PROMACTLOG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PROMWORK_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PROM_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PROV_HTML_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PROV_TEXT_HST_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('PROV_VRSN_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('QA_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('READ_DUTY_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_DMN_LNK_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_EXCL_LNK_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_FILE_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_HTML_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_IMG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_LNK_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_ORGN_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_VRSN_CATE_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_VRSN_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('REL_WORD_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('ROLE_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('STATS_BBS_VIEW_NO', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('STATS_FT_VIEW_NO', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('STATS_KWD_NO', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('STSFDG_NO', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('SYSLOG_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('TMPLAT_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('USRCNFRM_ID', 1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
  VALUES ('WEBLOG_ID', 1);
-- COMTECOPSEQ: 66 rows

COMMIT;