-- ============================================================================
-- rlms_law_menu_remove.sql — 송무(law) 옵션 해지 (rlms_law_menu.sql 의 역작업)
--   메뉴·프로그램·권한만 소멸 — LAW_* 테이블·데이터·ccm 코드는 보존(§2.1 옵션 해지).
--   적용 후 재기동(또는 reloadSecurity.do + reloadMenu.do) — L7 이 /law/** 를 ADMIN 잠금.
--   재실행 안전(DELETE 는 자연 멱등).
-- ============================================================================
SET DEFINE OFF;

-- 1) 메뉴생성 권한 매핑 (COMTNMENUINFO FK CASCADE 가 있어도 명시 삭제)
DELETE FROM COMTNMENUCREATDTLS WHERE MENU_NO BETWEEN 55000000 AND 55999999;
DELETE FROM COMTNMENUCREATDTLS WHERE MENU_NO IN (15000000, 15010000, 15020000);

-- 2) 메뉴
DELETE FROM COMTNMENUINFO WHERE MENU_NO BETWEEN 55000000 AND 55999999;
DELETE FROM COMTNMENUINFO WHERE MENU_NO IN (15000000, 15010000, 15020000);

-- 3) 프로그램 (⚠️ 참조 메뉴를 먼저 지웠으므로 안전)
DELETE FROM COMTNPROGRMLIST WHERE PROGRM_FILE_NM IN (
  'LAW_HOME', 'LAW_SUIT_LIST', 'LAW_DOC_LIST', 'LAW_DOC_APPROVAL', 'LAW_COST_LIST',
  'LAW_SCHEDULE', 'LAW_ASSIGN_LIST', 'LAW_LAWYER_LIST', 'LAW_REQ_LIST', 'LAW_SEIZE_LIST',
  'LAW_RECEIPT_LIST', 'LAW_STAT_SUMMARY', 'LAW_STAT_INSTANCE', 'LAW_STAT_CASETYPE',
  'LAW_STAT_DEPT', 'LAW_STAT_AGENT', 'LAW_STAT_LOSS', 'LAW_STAT_LANDMAP', 'LAW_CALCSET',
  'LAW_REQ_USER_REG', 'LAW_REQ_USER_LIST'
);

-- 4) 역할 계층·권한 (LAW_MGR 부여 사용자가 있으면 사전 회수 필요 — COMTNEMPLYRSCRTYESTBS)
DELETE FROM COMTNROLES_HIERARCHY WHERE PARNTS_ROLE = 'ROLE_LAW_MGR' OR CHLDRN_ROLE = 'ROLE_LAW_MGR';
DELETE FROM COMTNAUTHORINFO WHERE AUTHOR_CODE = 'ROLE_LAW_MGR';

COMMIT;

-- 검증:
--   SELECT COUNT(*) FROM COMTNMENUINFO WHERE MENU_NO BETWEEN 55000000 AND 55999999;  (0)
--   SELECT COUNT(*) FROM COMTNPROGRMLIST WHERE PROGRM_FILE_NM LIKE 'LAW_%';          (0)
