--------------------------------------------------------------------------------
-- 10_tables.sql — 공통 테이블 46종 + 로그인 뷰 COMVNUSERMASTER
-- LexPortal(송무 단독, MariaDB) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: lexportal. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 원천: Oracle DDL 자동변환 — VARCHAR2→VARCHAR, NUMBER→INT/DECIMAL, CLOB→LONGTEXT, DATE→DATETIME.
-- ※ MariaDB 는 COMMENT ON 문이 없어 컬럼 코멘트를 컬럼 정의에 인라인으로 넣었다(코멘트 필수 규약 유지). 합성 1종(COMTH 변경이력)은 후반부.
--------------------------------------------------------------------------------


-- TABLE COMTCCMMNCODE
CREATE TABLE COMTCCMMNCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE_ID_NM VARCHAR(60) COMMENT '코드ID명',
	CODE_ID_DC VARCHAR(200) COMMENT '코드ID설명',
	USE_AT CHAR(1) COMMENT '사용여부',
	CL_CODE CHAR(3) COMMENT '분류코드',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='공통코드';


-- TABLE COMTCCMMNDETAILCODE
CREATE TABLE COMTCCMMNDETAILCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL COMMENT '코드',
	CODE_NM VARCHAR(60) COMMENT '코드명',
	CODE_DC VARCHAR(200) COMMENT '코드설명',
	USE_AT CHAR(1) COMMENT '사용여부',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID, CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='공통상세코드';


-- TABLE COMTECOPSEQ
CREATE TABLE COMTECOPSEQ
   (	TABLE_NAME VARCHAR(20) NOT NULL,
	NEXT_ID DECIMAL(30,0) COMMENT '다음아이디',
	 CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='COMTECOPSEQ';


-- TABLE COMTNAUTHORGROUPINFO
CREATE TABLE COMTNAUTHORGROUPINFO
   (	GROUP_ID CHAR(20) NOT NULL,
	GROUP_NM VARCHAR(60) NOT NULL COMMENT '그룹명',
	GROUP_CREAT_DE CHAR(20) NOT NULL COMMENT '그룹생성일',
	GROUP_DC VARCHAR(100) COMMENT '그룹설명',
	 CONSTRAINT COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='권한그룹정보';


-- TABLE COMTNAUTHORINFO
CREATE TABLE COMTNAUTHORINFO
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	AUTHOR_NM VARCHAR(60) NOT NULL COMMENT '권한명',
	AUTHOR_DC VARCHAR(200) COMMENT '권한설명',
	AUTHOR_CREAT_DE CHAR(20) NOT NULL COMMENT '권한생성일',
	 CONSTRAINT COMTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='권한정보';


-- TABLE COMTNAUTHORROLERELATE
CREATE TABLE COMTNAUTHORROLERELATE
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	ROLE_CODE VARCHAR(50) NOT NULL COMMENT '롤코드',
	CREAT_DT DATETIME COMMENT '생성일시',
	 CONSTRAINT COMTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE, ROLE_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='권한롤관계';


-- TABLE COMTNBANNER
CREATE TABLE COMTNBANNER
   (	BANNER_ID CHAR(20) NOT NULL,
	BANNER_NM VARCHAR(60) NOT NULL COMMENT '배너명',
	LINK_URL VARCHAR(255) NOT NULL COMMENT '링크URL',
	BANNER_IMAGE VARCHAR(60) NOT NULL COMMENT '배너이미지',
	BANNER_DC VARCHAR(200) COMMENT '배너설명',
	REFLCT_AT CHAR(1) NOT NULL COMMENT '반영여부',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	BANNER_IMAGE_FILE VARCHAR(60) COMMENT '배너이미지파일',
	SORT_ORDR DECIMAL(8,0) COMMENT '정렬순서',
	 CONSTRAINT COMTNBANNER_PK PRIMARY KEY (BANNER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='배너';


-- TABLE COMTNBBS
CREATE TABLE COMTNBBS
   (	NTT_ID DECIMAL(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL COMMENT '게시판ID',
	NTT_NO DECIMAL(20,0) COMMENT '게시물번호',
	NTT_SJ VARCHAR(2000) COMMENT '게시물제목',
	NTT_CN LONGTEXT COMMENT '게시물내용',
	ANSWER_AT CHAR(1) COMMENT '댓글여부',
	PARNTSCTT_NO DECIMAL(10,0) COMMENT '부모글번호',
	ANSWER_LC DECIMAL(8,0) COMMENT '댓글위치',
	SORT_ORDR DECIMAL(8,0) COMMENT '정렬순서',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	NTCE_BGNDE CHAR(20) COMMENT '게시시작일',
	NTCE_ENDDE CHAR(20) COMMENT '게시종료일',
	NTCR_ID VARCHAR(20) COMMENT '게시자ID',
	NTCR_NM VARCHAR(20) COMMENT '게시자명',
	PASSWORD VARCHAR(200) COMMENT '비밀번호',
	ATCH_FILE_ID CHAR(20) COMMENT '첨부파일ID',
	NOTICE_AT CHAR(1) COMMENT '공지사항여부',
	SJ_BOLD_AT CHAR(1) COMMENT '제목볼드여부',
	SECRET_AT CHAR(1) COMMENT '비밀글여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	BLOG_ID CHAR(20) COMMENT '블로그 ID',
	NTT_EXTRA_FIELD_1 VARCHAR(200) COMMENT '게시물 여분필드 1 값 — 게시판 마스터(BBS_EXTRA_FIELD_1)에 정의된 확장항목의 입력값',
	NTT_EXTRA_FIELD_2 VARCHAR(200) COMMENT '게시물 여분필드 2 값',
	NTT_EXTRA_FIELD_3 VARCHAR(200) COMMENT '게시물 여분필드 3 값',
	NTT_EXTRA_FIELD_4 VARCHAR(200) COMMENT '게시물 여분필드 4 값',
	NTT_EXTRA_FIELD_5 VARCHAR(200) COMMENT '게시물 여분필드 5 값',
	NTT_EXTRA_FIELD_6 VARCHAR(200) COMMENT '게시물 여분필드 6 값',
	NTT_EXTRA_FIELD_7 VARCHAR(200) COMMENT '게시물 여분필드 7 값',
	NTT_EXTRA_FIELD_8 VARCHAR(200) COMMENT '게시물 여분필드 8 값',
	NTT_EXTRA_FIELD_9 VARCHAR(200) COMMENT '게시물 여분필드 9 값',
	NTT_EXTRA_FIELD_10 VARCHAR(200) COMMENT '게시물 여분필드 10 값',
	 CONSTRAINT COMTNBBS_PK PRIMARY KEY (NTT_ID, BBS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판';


-- TABLE COMTNBBSMASTER
CREATE TABLE COMTNBBSMASTER
   (	BBS_ID CHAR(30) NOT NULL,
	BBS_NM VARCHAR(255) NOT NULL COMMENT '게시판명',
	BBS_INTRCN VARCHAR(2400) COMMENT '게시판소개',
	BBS_TY_CODE CHAR(6) NOT NULL COMMENT '게시판유형코드',
	REPLY_POSBL_AT CHAR(1) COMMENT '답장가능여부',
	FILE_ATCH_POSBL_AT CHAR(1) NOT NULL COMMENT '파일첨부가능여부',
	ATCH_POSBL_FILE_NUMBER DECIMAL(2,0) NOT NULL COMMENT '첨부가능파일숫자',
	ATCH_POSBL_FILE_SIZE DECIMAL(8,0) COMMENT '첨부가능파일사이즈',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	TMPLAT_ID CHAR(20) COMMENT '템플릿ID',
	CMMNTY_ID CHAR(20) COMMENT '커뮤니티ID',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	BLOG_ID CHAR(20) COMMENT '블로그 ID',
	BLOG_AT CHAR(2) COMMENT '블로그 여부',
	BBS_SKIN_CODE VARCHAR(30) DEFAULT 'BASIC' COMMENT '게시판 스킨 코드(기본 BASIC) — RLMS 확장',
	BBS_EXTRA_FIELD_1 VARCHAR(200) COMMENT '여분필드 1 라벨 — 게시판별 확장 입력항목 정의(타입/코드는 BBS_EXTRA_FIELD_TYPE_1, CODE_ID_1)',
	BBS_EXTRA_FIELD_2 VARCHAR(200) COMMENT '여분필드 2 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_3 VARCHAR(200) COMMENT '여분필드 3 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_4 VARCHAR(200) COMMENT '여분필드 4 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_5 VARCHAR(200) COMMENT '여분필드 5 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_6 VARCHAR(200) COMMENT '여분필드 6 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_7 VARCHAR(200) COMMENT '여분필드 7 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_8 VARCHAR(200) COMMENT '여분필드 8 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_9 VARCHAR(200) COMMENT '여분필드 9 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_10 VARCHAR(200) COMMENT '여분필드 10 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_TYPE_1 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드1 입력타입',
	BBS_EXTRA_FIELD_TYPE_2 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드2 입력타입',
	BBS_EXTRA_FIELD_TYPE_3 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드3 입력타입',
	BBS_EXTRA_FIELD_TYPE_4 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드4 입력타입',
	BBS_EXTRA_FIELD_TYPE_5 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드5 입력타입',
	BBS_EXTRA_FIELD_TYPE_6 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드6 입력타입',
	BBS_EXTRA_FIELD_TYPE_7 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드7 입력타입',
	BBS_EXTRA_FIELD_TYPE_8 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드8 입력타입',
	BBS_EXTRA_FIELD_TYPE_9 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드9 입력타입',
	BBS_EXTRA_FIELD_TYPE_10 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드10 입력타입',
	BBS_EXTRA_FIELD_CODE_ID_1 VARCHAR(30) COMMENT '게시판 여분필드1 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_2 VARCHAR(30) COMMENT '게시판 여분필드2 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_3 VARCHAR(30) COMMENT '게시판 여분필드3 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_4 VARCHAR(30) COMMENT '게시판 여분필드4 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_5 VARCHAR(30) COMMENT '게시판 여분필드5 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_6 VARCHAR(30) COMMENT '게시판 여분필드6 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_7 VARCHAR(30) COMMENT '게시판 여분필드7 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_8 VARCHAR(30) COMMENT '게시판 여분필드8 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_9 VARCHAR(30) COMMENT '게시판 여분필드9 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_10 VARCHAR(30) COMMENT '게시판 여분필드10 공통코드ID',
	LIST_PAGE_UNIT VARCHAR(50),
	SECRET_POSBL_AT CHAR(1) DEFAULT 'Y',
	RICH_EDITOR_AT CHAR(1) DEFAULT 'Y',
	SEARCH_INCLD_AT CHAR(1) DEFAULT 'Y',
	PAGING_AT CHAR(1) DEFAULT 'Y',
	SEARCH_BOX_AT CHAR(1) DEFAULT 'Y',
	 CONSTRAINT COMTNBBSMASTER_PK PRIMARY KEY (BBS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판마스터';


-- TABLE COMTNBBSMASTEROPTN
CREATE TABLE COMTNBBSMASTEROPTN
   (	BBS_ID CHAR(30) NOT NULL,
	ANSWER_AT CHAR(1) NOT NULL COMMENT '댓글여부',
	STSFDG_AT CHAR(1) NOT NULL COMMENT '만족도여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판마스터옵션';


-- 게시판별 작성권한. 열람권한은 메뉴 역할매핑(COMTNMENUCREATDTLS)이 원천이지만,
-- 메뉴가 보인다와 글을 쓸 수 있다는 다른 축이라 별도 매핑이 필요하다.
CREATE TABLE COMTNBBSWRITEAUTHOR (
	BBS_ID      CHAR(30)     NOT NULL COMMENT '게시판ID',
	AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
	CONSTRAINT COMTNBBSWRITEAUTHOR_PK PRIMARY KEY (BBS_ID, AUTHOR_CODE)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판작성권한';


-- TABLE COMTNCOMMENT
CREATE TABLE COMTNCOMMENT
   (	NTT_ID DECIMAL(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL COMMENT '게시판ID',
	ANSWER_NO DECIMAL(20,0) NOT NULL COMMENT '댓글번호',
	WRTER_ID VARCHAR(20) COMMENT '작성자ID',
	-- 표준 원형은 VARCHAR(20) 이라 USER_NM(60) 이 긴 사용자는 ORA-12899 → 60 으로 확장(2026-07-10)
	WRTER_NM VARCHAR(60) COMMENT '작성자명',
	-- 표준 원형은 VARCHAR(200)(바이트) 이라 한글 약 66자에서 ORA-12899 → 문자기준 1000 으로 확장(2026-07-10, UI 글자수 카운터)
	ANSWER VARCHAR(1000) COMMENT '댓글',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	PASSWORD VARCHAR(200) COMMENT '비밀번호',
	 CONSTRAINT COMTNCOMMENT_PK PRIMARY KEY (NTT_ID, BBS_ID, ANSWER_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='댓글';


-- TABLE COMTNEMPLYRINFO
CREATE TABLE COMTNEMPLYRINFO
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	ORGNZT_ID CHAR(20) COMMENT '조직ID',
	USER_NM VARCHAR(60) NOT NULL COMMENT '사용자명',
	PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호',
	EMPL_NO VARCHAR(20) COMMENT '사원번호',
	IHIDNUM VARCHAR(200) COMMENT '주민등록번호',
	SEXDSTN_CODE CHAR(1) COMMENT '성별코드',
	BRTHDY CHAR(20) COMMENT '생일',
	FXNUM VARCHAR(20) COMMENT '팩스번호',
	HOUSE_ADRES VARCHAR(100) COMMENT '주택주소',
	PASSWORD_HINT VARCHAR(100) COMMENT '비밀번호힌트',
	PASSWORD_CNSR VARCHAR(100) COMMENT '비밀번호정답',
	HOUSE_END_TELNO VARCHAR(4) COMMENT '주택끝전화번호',
	AREA_NO VARCHAR(4) COMMENT '지역번호',
	DETAIL_ADRES VARCHAR(100) COMMENT '상세주소',
	ZIP VARCHAR(6) COMMENT '우편번호',
	OFFM_TELNO VARCHAR(20) COMMENT '사무실전화번호',
	MBTLNUM VARCHAR(20) COMMENT '이동전화번호',
	EMAIL_ADRES VARCHAR(50) COMMENT '이메일주소',
	OFCPS_NM VARCHAR(60) COMMENT '직위명',
	HOUSE_MIDDLE_TELNO VARCHAR(4) COMMENT '주택중간전화번호',
	GROUP_ID CHAR(20) COMMENT '그룹ID',
	PSTINST_CODE CHAR(8) COMMENT '소속기관코드',
	EMPLYR_STTUS_CODE CHAR(1) NOT NULL COMMENT '사용자상태코드',
	ESNTL_ID CHAR(20) NOT NULL COMMENT '고유ID',
	CRTFC_DN_VALUE VARCHAR(100) COMMENT '인증DN값',
	SBSCRB_DE DATETIME COMMENT '가입일자',
	LOCK_AT CHAR(1) COMMENT '잠금여부',
	LOCK_CNT DECIMAL(3,0) COMMENT '잠금회수',
	LOCK_LAST_PNTTM DATETIME COMMENT '잠금최종시점',
	CHG_PWD_LAST_PNTTM DATETIME COMMENT '최종 비밀번호 변경 시점 — 비밀번호 유효기간(180일) 만료 판정 기준(RLMS 확장)',
	 CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='업무사용자정보';


-- TABLE COMTNEMPLYRSCRTYESTBS
CREATE TABLE COMTNEMPLYRSCRTYESTBS
   (	SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
	MBER_TY_CODE CHAR(5) COMMENT '회원유형코드',
	AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
	 CONSTRAINT COMTNEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자보안설정';


-- TABLE COMTNFAQINFO
CREATE TABLE COMTNFAQINFO
   (	FAQ_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255) COMMENT '질문제목',
	QESTN_CN VARCHAR(2500) COMMENT '질문내용',
	ANSWER_CN VARCHAR(2500) COMMENT '답변내용',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME NOT NULL COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) NOT NULL COMMENT '최종수정자ID',
	ATCH_FILE_ID CHAR(20) COMMENT '첨부파일ID',
	QNA_PROCESS_STTUS_CODE CHAR(1) COMMENT '질의응답처리상태코드',
	FAQ_CODE VARCHAR(15) COMMENT 'FAQ 카테고리 코드 — 공통코드 faqCode 상세코드(RLMS 확장)',
	 CONSTRAINT COMTNFAQINFO_PK PRIMARY KEY (FAQ_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FAQ정보';


-- TABLE COMTNFILE
CREATE TABLE COMTNFILE
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	CREAT_DT DATETIME NOT NULL COMMENT '생성일시',
	USE_AT CHAR(1) COMMENT '사용여부',
	 CONSTRAINT COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='파일속성';


-- TABLE COMTNFILEDETAIL
CREATE TABLE COMTNFILEDETAIL
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	FILE_SN DECIMAL(10,0) NOT NULL COMMENT '파일순번',
	FILE_STRE_COURS VARCHAR(2000) NOT NULL COMMENT '파일저장경로',
	STRE_FILE_NM VARCHAR(255) NOT NULL COMMENT '저장파일명',
	ORIGNL_FILE_NM VARCHAR(255) COMMENT '원파일명',
	FILE_EXTSN VARCHAR(20) NOT NULL COMMENT '파일확장자',
	FILE_CN LONGTEXT COMMENT '파일내용',
	FILE_SIZE DECIMAL(8,0) COMMENT '파일크기',
	DWLD_CO DECIMAL(8,0) DEFAULT 0,
	 CONSTRAINT COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='파일상세정보';


-- TABLE COMTNGNRLMBER
CREATE TABLE COMTNGNRLMBER
   (	MBER_ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호',
	PASSWORD_HINT VARCHAR(100) COMMENT '비밀번호힌트',
	PASSWORD_CNSR VARCHAR(100) COMMENT '비밀번호정답',
	IHIDNUM VARCHAR(200) COMMENT '주민등록번호',
	MBER_NM VARCHAR(50) NOT NULL COMMENT '회원명',
	ZIP VARCHAR(6) COMMENT '우편번호',
	ADRES VARCHAR(100) COMMENT '주소',
	AREA_NO VARCHAR(4) NOT NULL COMMENT '지역번호',
	MBER_STTUS VARCHAR(15) COMMENT '회원상태',
	DETAIL_ADRES VARCHAR(100) COMMENT '상세주소',
	END_TELNO VARCHAR(4) NOT NULL COMMENT '끝전화번호',
	MBTLNUM VARCHAR(20) NOT NULL COMMENT '이동전화번호',
	GROUP_ID CHAR(20) COMMENT '그룹ID',
	MBER_FXNUM VARCHAR(20) COMMENT '회원팩스번호',
	MBER_EMAIL_ADRES VARCHAR(50) COMMENT '회원이메일주소',
	MIDDLE_TELNO VARCHAR(4) NOT NULL COMMENT '중간전화번호',
	SBSCRB_DE DATETIME COMMENT '가입일자',
	SEXDSTN_CODE CHAR(1) COMMENT '성별코드',
	ESNTL_ID CHAR(20) NOT NULL COMMENT '고유ID',
	LOCK_AT CHAR(1) COMMENT '잠금여부',
	LOCK_CNT DECIMAL(3,0) COMMENT '잠금회수',
	LOCK_LAST_PNTTM DATETIME COMMENT '잠금최종시점',
	CHG_PWD_LAST_PNTTM DATETIME COMMENT '최종 비밀번호 변경 시점 — 비밀번호 유효기간(180일) 만료 판정 기준(RLMS 확장)',
	ORGNZT_ID VARCHAR(20) COMMENT '소속 조직(부서) ID — COMTNORGNZTINFO 참조(RLMS 확장)',
	EMPL_NO VARCHAR(20) COMMENT '사번 (RLMS 확장 — 일반회원 등록/수정 화면 입력)',
	 CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일반회원';


-- TABLE COMTNLOGINLOG
CREATE TABLE COMTNLOGINLOG
   (	LOG_ID CHAR(20) NOT NULL,
	CONECT_ID VARCHAR(20) COMMENT '접속ID',
	CONECT_IP VARCHAR(23) COMMENT '접속IP',
	CONECT_MTHD CHAR(4) COMMENT '접속방식',
	ERROR_OCCRRNC_AT CHAR(1) COMMENT '오류발생여부',
	ERROR_CODE CHAR(3) COMMENT '오류코드',
	CREAT_DT DATETIME COMMENT '생성일시',
	 CONSTRAINT COMTNLOGINLOG_PK PRIMARY KEY (LOG_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='접속로그';


-- TABLE COMTNLOGINPOLICY
CREATE TABLE COMTNLOGINPOLICY
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	IP_INFO VARCHAR(23) NOT NULL COMMENT 'IP정보',
	DPLCT_PERM_AT CHAR(1) NOT NULL COMMENT '중복허용여부',
	LMTT_AT CHAR(1) NOT NULL COMMENT '제한여부',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	 CONSTRAINT COMTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='로그인정책';


-- TABLE COMTNMENUCREATDTLS
CREATE TABLE COMTNMENUCREATDTLS
   (	MENU_NO DECIMAL(20,0) NOT NULL,
	AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
	MAPNG_CREAT_ID VARCHAR(30) COMMENT '매핑생성ID',
	 CONSTRAINT COMTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO, AUTHOR_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='메뉴생성내역';


-- TABLE COMTNMENUINFO
CREATE TABLE COMTNMENUINFO
   (	MENU_NM VARCHAR(60) NOT NULL,
	PROGRM_FILE_NM VARCHAR(60) NOT NULL COMMENT '프로그램파일명',
	MENU_NO DECIMAL(20,0) NOT NULL COMMENT '메뉴번호',
	UPPER_MENU_NO DECIMAL(20,0) COMMENT '상위메뉴번호',
	MENU_ORDR DECIMAL(5,0) NOT NULL COMMENT '메뉴순서',
	MENU_DC VARCHAR(250) COMMENT '메뉴설명',
	RELATE_IMAGE_PATH VARCHAR(100) COMMENT '관계이미지경로',
	RELATE_IMAGE_NM VARCHAR(60) COMMENT '관계이미지명',
	MENU_SE VARCHAR(20) COMMENT '메뉴구분(ADMIN:관리자, USER:사용자)',
	 CONSTRAINT COMTNMENUINFO_PK PRIMARY KEY (MENU_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='메뉴정보';


-- TABLE COMTNORGNZTINFO (2026-07-27 트리 전환: UPPER_ORGNZT_ID 자기참조 + ORDR 표시순서)
CREATE TABLE COMTNORGNZTINFO
   (	ORGNZT_ID CHAR(20) NOT NULL,
	ORGNZT_NM VARCHAR(255) NOT NULL COMMENT '조직명',
	ORGNZT_DC VARCHAR(500) COMMENT '조직설명',
	UPPER_ORGNZT_ID CHAR(20) COMMENT '상위 조직ID (자기참조, NULL=최상위: 본사·지사)',
	ORDR DECIMAL(5,0) COMMENT '형제 내 표시 순서 (오름차순, NULL=마지막)',
	 CONSTRAINT COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='조직정보';


-- TABLE COMTNPOPUPMANAGE
CREATE TABLE COMTNPOPUPMANAGE
   (	POPUP_ID VARCHAR(20) NOT NULL,
	POPUP_SJ_NM VARCHAR(1024) COMMENT '팝업제목명',
	FILE_URL VARCHAR(1024) COMMENT '파일URL',
	POPUP_WIDTH_LC VARCHAR(20) COMMENT '팝업가로위치',
	POPUP_WIDTH_SIZE DECIMAL(38,10) COMMENT '팝업가로사이즈',
	NTCE_BGNDE CHAR(20) COMMENT '게시시작일',
	NTCE_ENDDE CHAR(20) COMMENT '게시종료일',
	STOPVEW_SETUP_AT CHAR(1) COMMENT '그만보기설정여부',
	NTCE_AT CHAR(1) COMMENT '게시여부',
	POPUP_VRTICL_LC VARCHAR(20) COMMENT '팝업세로위치',
	POPUP_VRTICL_SIZE DECIMAL(38,10) COMMENT '팝업세로사이즈',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	POPUP_CN LONGTEXT COMMENT '팝업내용(HTML, 직접편집모드)',
	CN_SE VARCHAR(1) DEFAULT 'F' COMMENT '내용구분(F:파일URL, E:직접편집)',
	 CONSTRAINT COMTNPOPUPMANAGE_PK PRIMARY KEY (POPUP_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='팝업 정보 관리';


-- TABLE COMTNPRIVACYLOG
CREATE TABLE COMTNPRIVACYLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	INQIRE_DT DATETIME NOT NULL COMMENT '조회일시',
	SRVC_NM VARCHAR(500) COMMENT '서비스 명',
	INQIRE_INFO VARCHAR(100) COMMENT '조회 정보 명',
	RQESTER_ID VARCHAR(20) COMMENT '요청자아이디',
	RQESTER_IP VARCHAR(23) COMMENT '요청아이피',
	 CONSTRAINT REQUST_ID_PK PRIMARY KEY (REQUST_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='개인정보조회 로그';


-- TABLE COMTNPROGRMLIST
CREATE TABLE COMTNPROGRMLIST
   (	PROGRM_FILE_NM VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH VARCHAR(100) NOT NULL COMMENT '프로그램저장경로',
	PROGRM_KOREAN_NM VARCHAR(60) COMMENT '프로그램한글명',
	PROGRM_DC VARCHAR(200) COMMENT '프로그램설명',
	URL VARCHAR(100) NOT NULL COMMENT 'URL',
	 CONSTRAINT COMTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='프로그램목록';


-- TABLE COMTNQAINFO
CREATE TABLE COMTNQAINFO
   (	QA_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255) COMMENT '질문제목',
	QESTN_CN VARCHAR(2500) COMMENT '질문내용',
	WRITNG_DE CHAR(20) COMMENT '작성일',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	EMAIL_ADRES VARCHAR(50) COMMENT '이메일주소',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	QNA_PROCESS_STTUS_CODE CHAR(1) COMMENT '질의응답처리상태코드',
	WRTER_NM VARCHAR(20) COMMENT '작성자명',
	ANSWER_CN VARCHAR(2500) COMMENT '답변내용',
	WRITNG_PASSWORD VARCHAR(20) COMMENT '작성비밀번호',
	ANSWER_DE CHAR(20) COMMENT '답변일자',
	EMAIL_ANSWER_AT CHAR(1) COMMENT '메일답변여부',
	AREA_NO VARCHAR(4) COMMENT '지역번호',
	MIDDLE_TELNO VARCHAR(4) COMMENT '중간전화번호',
	END_TELNO VARCHAR(4) COMMENT '끝전화번호',
	 CONSTRAINT COMTNQAINFO_PK PRIMARY KEY (QA_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='QA정보';


-- TABLE COMTNROLEINFO
CREATE TABLE COMTNROLEINFO
   (	ROLE_CODE VARCHAR(50) NOT NULL,
	ROLE_NM VARCHAR(60) NOT NULL COMMENT '롤명',
	ROLE_PTTRN VARCHAR(300) COMMENT '롤패턴',
	ROLE_DC VARCHAR(200) COMMENT '롤설명',
	ROLE_TY VARCHAR(80) COMMENT '롤유형',
	ROLE_SORT VARCHAR(10) COMMENT '롤정렬',
	ROLE_CREAT_DE CHAR(20) NOT NULL COMMENT '롤생성일',
	 CONSTRAINT COMTNROLEINFO_PK PRIMARY KEY (ROLE_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='롤정보';


-- TABLE COMTNROLES_HIERARCHY
CREATE TABLE COMTNROLES_HIERARCHY
   (	PARNTS_ROLE VARCHAR(30) NOT NULL,
	CHLDRN_ROLE VARCHAR(30) NOT NULL COMMENT '자식롤',
	 CONSTRAINT COMTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE, CHLDRN_ROLE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='롤 계층구조';


-- TABLE COMTNSITEMAP
CREATE TABLE COMTNSITEMAP
   (	MAPNG_CREAT_ID VARCHAR(30) NOT NULL,
	CREATR_ID VARCHAR(20) NOT NULL COMMENT '생성자ID',
	MAPNG_FILE_NM VARCHAR(60) NOT NULL COMMENT '매핑파일명',
	MAPNG_FILE_PATH VARCHAR(100) NOT NULL COMMENT '매핑파일경로',
	 CONSTRAINT COMTNSITEMAP_PK PRIMARY KEY (MAPNG_CREAT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사이트맵';


-- TABLE COMTNSTSFDG
CREATE TABLE COMTNSTSFDG
   (	STSFDG_NO DECIMAL(20,0) NOT NULL,
	NTT_ID DECIMAL(20,0) NOT NULL COMMENT '게시물ID',
	BBS_ID CHAR(30) NOT NULL COMMENT '게시판ID',
	WRTER_ID VARCHAR(20) COMMENT '작성자ID',
	-- 표준 원형 20 → USER_NM(60) 초과 시 ORA-12899. 60 으로 확장(2026-07-10, 만족도 JSON UI)
	WRTER_NM VARCHAR(60) COMMENT '작성자명',
	PASSWORD VARCHAR(200) COMMENT '비밀번호',
	STSFDG DECIMAL(1,0) NOT NULL COMMENT '만족도',
	-- 표준 원형 200바이트(한글 약66자) → 1000 CHAR 로 확장(2026-07-10, UI 글자수 카운터)
	STSFDG_CN VARCHAR(1000) COMMENT '만족도내용',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTNSTSFDG_PK PRIMARY KEY (STSFDG_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='만족도';


-- TABLE COMTNSYSLOG
CREATE TABLE COMTNSYSLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	JOB_SE_CODE CHAR(3) COMMENT '업무구분코드',
	INSTT_CODE CHAR(7) COMMENT '기관코드',
	OCCRRNC_DE DATETIME COMMENT '발생일',
	RQESTER_IP VARCHAR(23) COMMENT '요청자IP',
	RQESTER_ID VARCHAR(20) COMMENT '요청자ID',
	TRGET_MENU_NM VARCHAR(255) COMMENT '대상메뉴명',
	SVC_NM VARCHAR(255) COMMENT '서비스명',
	METHOD_NM VARCHAR(60) COMMENT '메서드명',
	PROCESS_SE_CODE CHAR(3) COMMENT '처리구분코드',
	PROCESS_CO DECIMAL(10,0) COMMENT '처리수',
	PROCESS_TIME VARCHAR(14) COMMENT '처리시간',
	RSPNS_CODE CHAR(3) COMMENT '응답코드',
	ERROR_SE CHAR(1) COMMENT '오류구분',
	ERROR_CO DECIMAL(10,0) COMMENT '오류수',
	ERROR_CODE CHAR(3) COMMENT '오류코드',
	 CONSTRAINT COMTNSYSLOG_PK PRIMARY KEY (REQUST_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='시스템로그';


-- TABLE COMTNTMPLATINFO
-- 게시판 템플릿 정본(2026-07 재정의): TMPLAT_SE_CODE=렌더엔진코드(COM005), TMPLAT_CONFIG_CN=표현설정(JSON)
CREATE TABLE COMTNTMPLATINFO
   (	TMPLAT_ID CHAR(20) NOT NULL,
	TMPLAT_NM VARCHAR(255) COMMENT '템플릿명',
	TMPLAT_COURS VARCHAR(2000) COMMENT '템플릿경로',
	USE_AT CHAR(1) COMMENT '사용여부',
	TMPLAT_SE_CODE VARCHAR(20) COMMENT '템플릿구분코드(렌더엔진코드, COM005)',
	TMPLAT_CONFIG_CN VARCHAR(2000) COMMENT '템플릿 표현설정(JSON)',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	 CONSTRAINT COMTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='템플릿';


-- TABLE COMTNUSERLOG
CREATE TABLE COMTNUSERLOG
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	RQESTER_ID VARCHAR(20) NOT NULL COMMENT '요청자ID',
	SVC_NM VARCHAR(255) NOT NULL COMMENT '서비스명',
	METHOD_NM VARCHAR(60) NOT NULL COMMENT '메서드명',
	CREAT_CO DECIMAL(10,0) COMMENT '생성수',
	UPDT_CO DECIMAL(10,0) COMMENT '수정수',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	DELETE_CO DECIMAL(10,0) COMMENT '삭제수',
	OUTPT_CO DECIMAL(10,0) COMMENT '출력수',
	ERROR_CO DECIMAL(10,0) COMMENT '오류수',
	 CONSTRAINT COMTNUSERLOG_PK PRIMARY KEY (OCCRRNC_DE, RQESTER_ID, SVC_NM, METHOD_NM) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자로그';


-- TABLE COMTNWEBLOG (2026-07-20 접속통계 확장: 기기/브라우저/세션 컬럼 + 일자 인덱스)
CREATE TABLE COMTNWEBLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	OCCRRNC_DE DATETIME COMMENT '발생일',
	URL VARCHAR(200) COMMENT 'URL',
	RQESTER_ID VARCHAR(20) COMMENT '요청자ID',
	RQESTER_IP VARCHAR(23) COMMENT '요청자IP',
	DVICE_SE VARCHAR(10) COMMENT '접속 기기 구분 (PC/MOBILE/TABLET/BOT/ETC — User-Agent 파싱)',
	BROWSER_NM VARCHAR(30) COMMENT '브라우저명 (Chrome/Edge/Whale/… — User-Agent 파싱)',
	SESN_ID VARCHAR(60) COMMENT '세션 ID 해시 (SHA-256 앞 160비트 hex — 방문 단위 집계용, 비로그인 포함)',
	 CONSTRAINT COMTNWEBLOG_PK PRIMARY KEY (REQUST_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='웹로그';



  CREATE INDEX IX_COMTNWEBLOG_DT ON COMTNWEBLOG (OCCRRNC_DE)
  ;

-- TABLE COMTSSYSLOGSUMMARY
CREATE TABLE COMTSSYSLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	SVC_NM VARCHAR(255) NOT NULL COMMENT '서비스명',
	METHOD_NM VARCHAR(60) NOT NULL COMMENT '메서드명',
	CREAT_CO DECIMAL(10,0) COMMENT '생성수',
	UPDT_CO DECIMAL(10,0) COMMENT '수정수',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	DELETE_CO DECIMAL(10,0) COMMENT '삭제수',
	OUTPT_CO DECIMAL(10,0) COMMENT '출력수',
	ERROR_CO DECIMAL(10,0) COMMENT '오류수',
	 CONSTRAINT COMTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, SVC_NM, METHOD_NM) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='시스템로그요약';


-- TABLE COMTSWEBLOGSUMMARY
CREATE TABLE COMTSWEBLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	URL VARCHAR(200) NOT NULL COMMENT 'URL',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	 CONSTRAINT COMTSWEBLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, URL) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='웹로그 요약';


-- TABLE TB_ACT_LOG
CREATE TABLE TB_ACT_LOG
   (	IALOG_NO DECIMAL(38,10) NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL COMMENT '참조 테이블명',
	IREF_NO DECIMAL(38,10) NOT NULL COMMENT '참조 행 번호 (SREF_TABLE 의 PK)',
	SNAME VARCHAR(255) NOT NULL COMMENT '대상 명칭 (규정명 등)',
	STASK VARCHAR(255) NOT NULL COMMENT '작업 종류 (열람/로그인/파일다운 등)',
	SUSER_ID VARCHAR(255) NOT NULL COMMENT '사용자 ID',
	SUSER_NAME VARCHAR(255) NOT NULL COMMENT '사용자명',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYY-MM-DD HH24:MI:SS 문자열)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SINS_IP VARCHAR(255) COMMENT '접속 IP'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='시스템 활동 로그 — 열람/로그인/파일다운 등 사용자 행위 기록 (레거시 이관)';



  CREATE UNIQUE INDEX PK_TB_ACT_LOG ON TB_ACT_LOG (IALOG_NO) 
  ;


ALTER TABLE TB_ACT_LOG ADD CONSTRAINT PK_TB_ACT_LOG PRIMARY KEY (IALOG_NO) ;

-- TABLE TB_STATS_BBS_VIEW (2026-07-20 신설 — 게시판 조회통계 적재)
CREATE TABLE TB_STATS_BBS_VIEW
   (	ISBVIEW_NO DECIMAL(38,10) NOT NULL,
	SBBS_ID VARCHAR(30) NOT NULL COMMENT '게시판 ID (COMTNBBSMASTER, RTRIM 저장)',
	INTT_ID DECIMAL(38,10) NOT NULL COMMENT '게시글 ID (COMTNBBS.NTT_ID)',
	ICNT DECIMAL(38,10) NOT NULL COMMENT '조회수',
	SINS_DT VARCHAR(10) NOT NULL COMMENT '집계 일자 (YYYY-MM-DD)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판 조회 통계 — 게시글·일자별 조회수 적재 (사용자 열람 1회=1행)';



  CREATE UNIQUE INDEX PK_TB_STATS_BBS_VIEW ON TB_STATS_BBS_VIEW (ISBVIEW_NO)
  ;


ALTER TABLE TB_STATS_BBS_VIEW ADD CONSTRAINT PK_TB_STATS_BBS_VIEW PRIMARY KEY (ISBVIEW_NO) ;



-- VIEW COMVNUSERMASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID) AS 
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR' AS USER_SE, ORGNZT_ID
    FROM COMTNGNRLMBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
    FROM COMTNEMPLYRINFO;

--------------------------------------------------------------------------------
-- 합성 테이블 1종 — 레거시 운영 DB 에 없으나 라이브 필수 경로가 참조.
-- (죽은 흐름용 방어 테이블 6종은 2026-07-10 사용자 확정으로 제외 — 미생성 목록은 README 참조)
--------------------------------------------------------------------------------

-- COMTHEMPLYRINFOCHANGEDTLS (합성 근거: mapper\com\uss\umt\EgovUserManage_SQL_oracle.xml insertUserHistory —
--   사용자정보 수정 이력. 레거시 COMTN- 변형 구조 1:1, 매퍼가 쓰는 COMTH- 이름으로 생성)
CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID           VARCHAR(20)   NOT NULL COMMENT '업무사용자 ID(로그인 ID)',
  CHANGE_DE           CHAR(20)       NOT NULL COMMENT '변경일자 — 이력 기록 시점',
  ORGNZT_ID           CHAR(20) COMMENT '소속 조직(부서) ID — COMTNORGNZTINFO 참조',
  GROUP_ID            CHAR(20) COMMENT '그룹 ID',
  EMPL_NO             VARCHAR(20) COMMENT '사원번호',
  SEXDSTN_CODE        CHAR(1) COMMENT '성별코드',
  BRTHDY              CHAR(20) COMMENT '생일(생년월일)',
  FXNUM               VARCHAR(20) COMMENT '팩스번호',
  HOUSE_ADRES         VARCHAR(100) COMMENT '자택 주소',
  HOUSE_END_TELNO     VARCHAR(4) COMMENT '자택 전화 끝번호',
  AREA_NO             VARCHAR(4) COMMENT '전화 지역번호',
  DETAIL_ADRES        VARCHAR(100) COMMENT '상세주소',
  ZIP                 VARCHAR(6) COMMENT '우편번호',
  OFFM_TELNO          VARCHAR(20) COMMENT '사무실 전화번호',
  MBTLNUM             VARCHAR(20) COMMENT '이동전화번호',
  EMAIL_ADRES         VARCHAR(50) COMMENT '이메일주소',
  HOUSE_MIDDLE_TELNO  VARCHAR(4) COMMENT '자택 전화 국번(중간번호)',
  PSTINST_CODE        CHAR(8) COMMENT '소속기관코드',
  EMPLYR_STTUS_CODE   CHAR(1) COMMENT '사용자 상태코드',
  ESNTL_ID            CHAR(20) COMMENT '사용자 고유 ID(COMTNEMPLYRINFO.ESNTL_ID)',
  CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='업무사용자 정보 변경 이력(eGov 표준) — 사용자관리에서 수정 저장 시 변경 전 정보를 자동 기록';


-- 브랜드설정 — 로고(텍스트/이미지)·파비콘·연락처. 고객사별 리브랜딩 지점, BRAND_ID='S' 단일 행 (2026-07-31, 연락처 2026-08-04)
CREATE TABLE COM_BRAND (
  BRAND_ID              CHAR(1)       NOT NULL COMMENT '브랜드ID',
  LOGO_TY_CODE          VARCHAR(10)  DEFAULT 'TEXT' NOT NULL COMMENT '로고유형코드',
  LOGO_TEXT             VARCHAR(300) COMMENT '로고텍스트',
  LOGO_ATCH_FILE_ID     CHAR(20) COMMENT '로고첨부파일ID',
  FAVICON_ATCH_FILE_ID  CHAR(20) COMMENT '파비콘첨부파일ID',
  CNTC_ADRES            VARCHAR(300) COMMENT '연락처-주소 (포탈 오시는 길 표시, 비우면 항목 미표시)',
  CNTC_TELNO            VARCHAR(30) COMMENT '연락처-대표전화',
  CNTC_FXNUM            VARCHAR(30) COMMENT '연락처-팩스',
  CNTC_EMAIL_ADRES      VARCHAR(100) COMMENT '연락처-이메일',
  LAST_UPDUSR_ID        VARCHAR(20) COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM       DATETIME COMMENT '최종수정시점',
  CONSTRAINT PK_COM_BRAND PRIMARY KEY (BRAND_ID)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='브랜드설정';
