--------------------------------------------------------------------------------
-- 26_seed_idgn.sql — COMTECOPSEQ 채번(라이브 전량 — 잉여 행 무해)
-- LexPortal(MariaDB) 클린 설치 세트 — 통합본(RLMS 스키마, 2026-08-03 라이브)에서 추출·제품 필터링.
-- 실행 계정: lexportal. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수. 재실행 비멱등(단순 INSERT).
--------------------------------------------------------------------------------


-- ── 채번 (66행) ──
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('ACT_LOG_NO',
        1371);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('ANSWER_NO',
        41);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('ATTACH_ID',
        111);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('BANNER_ID',
        51);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('BATCH_OPERT_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('BATCH_SCHDUL_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('BBS_ID',
        71);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('CATE_ID',
        61);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('DOCU_ID',
        51);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('FAQ_ID',
        14);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('FAVOR_ID',
        61);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('FILE_ID',
        261);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('GAEJUNG_ID',
        21);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('GROUP_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAWQUEST_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_ASSIGN_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_CALC_RATE_ID',
        110);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_COST_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_COURT_ID',
        200);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_DOC_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_LAND_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_LAWYER_ID',
        21);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_PARTY_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_PROG_ID',
        31);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_RECEIPT_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_REQ_HELPER_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_REQ_HIST_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_REQ_ID',
        21);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_RSLT_HIST_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_SEIZE_ID',
        31);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_STAFF_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LAW_SUIT_ID',
        21);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('LOGINLOG_ID',
        1291);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('MEMO_ID',
        31);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('NTT_ID',
        161);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('ORGNZT_ID',
        41);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PMAP_ID',
        21);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('POPUP_ID',
        31);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PRIVACYLOG_ID',
        701);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PROMACTLOG_ID',
        361);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PROMWORK_ID',
        241);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PROM_ID',
        161);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PROV_HTML_ID',
        21);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PROV_TEXT_HST_ID',
        131);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('PROV_VRSN_ID',
        39151);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('QA_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('READ_DUTY_ID',
        41);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_DMN_LNK_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_EXCL_LNK_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_FILE_ID',
        301);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_HTML_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_IMG_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_LNK_ID',
        11);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_ORGN_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_VRSN_CATE_ID',
        201);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_VRSN_ID',
        451);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('REL_WORD_ID',
        61);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('ROLE_ID',
        1);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('STATS_BBS_VIEW_NO',
        121);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('STATS_FT_VIEW_NO',
        551);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('STATS_KWD_NO',
        141);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('STSFDG_NO',
        31);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('SYSLOG_ID',
        18051);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('TMPLAT_ID',
        27);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('USRCNFRM_ID',
        41);
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID)
VALUES ('WEBLOG_ID',
        29981);

COMMIT;