--------------------------------------------------------------------------------
-- 10_tables.sql — 공통 테이블 46종 + 로그인 뷰 COMVNUSERMASTER
-- LexPortal(송무 단독, PostgreSQL) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: lexportal. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 원천: Oracle DDL 자동변환 — VARCHAR2→VARCHAR, NUMBER→INT/NUMERIC, CLOB→TEXT, DATE→TIMESTAMP.
-- ※ 식별자 큰따옴표 전면 제거(PG 소문자 폴딩 ← 매퍼 SQL 비따옴표와 일치).
-- ※ 컬럼/테이블 코멘트는 12_comments.sql(COMMENT ON — PG 네이티브)이 담당. 합성 1종(COMTH 변경이력)은 후반부.
--------------------------------------------------------------------------------


-- TABLE COMTCCMMNCODE
CREATE TABLE COMTCCMMNCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE_ID_NM VARCHAR(60),
	CODE_ID_DC VARCHAR(200),
	USE_AT CHAR(1),
	CL_CODE CHAR(3),
	FRST_REGIST_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID) ) ;

-- TABLE COMTCCMMNDETAILCODE
CREATE TABLE COMTCCMMNDETAILCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	CODE_NM VARCHAR(60),
	CODE_DC VARCHAR(200),
	USE_AT CHAR(1),
	FRST_REGIST_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID, CODE) ) ;

-- TABLE COMTECOPSEQ
CREATE TABLE COMTECOPSEQ
   (	TABLE_NAME VARCHAR(20) NOT NULL,
	NEXT_ID NUMERIC(30,0),
	 CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME) ) ;

-- TABLE COMTNAUTHORGROUPINFO
CREATE TABLE COMTNAUTHORGROUPINFO
   (	GROUP_ID CHAR(20) NOT NULL,
	GROUP_NM VARCHAR(60) NOT NULL,
	GROUP_CREAT_DE CHAR(20) NOT NULL,
	GROUP_DC VARCHAR(100),
	 CONSTRAINT COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID) ) ;

-- TABLE COMTNAUTHORINFO
CREATE TABLE COMTNAUTHORINFO
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	AUTHOR_NM VARCHAR(60) NOT NULL,
	AUTHOR_DC VARCHAR(200),
	AUTHOR_CREAT_DE CHAR(20) NOT NULL,
	 CONSTRAINT COMTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE) ) ;

-- TABLE COMTNAUTHORROLERELATE
CREATE TABLE COMTNAUTHORROLERELATE
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	ROLE_CODE VARCHAR(50) NOT NULL,
	CREAT_DT TIMESTAMP,
	 CONSTRAINT COMTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE, ROLE_CODE) ) ;

-- TABLE COMTNBANNER
CREATE TABLE COMTNBANNER
   (	BANNER_ID CHAR(20) NOT NULL,
	BANNER_NM VARCHAR(60) NOT NULL,
	LINK_URL VARCHAR(255) NOT NULL,
	BANNER_IMAGE VARCHAR(60) NOT NULL,
	BANNER_DC VARCHAR(200),
	REFLCT_AT CHAR(1) NOT NULL,
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	BANNER_IMAGE_FILE VARCHAR(60),
	SORT_ORDR NUMERIC(8,0),
	 CONSTRAINT COMTNBANNER_PK PRIMARY KEY (BANNER_ID) ) ;

-- TABLE COMTNBBS
CREATE TABLE COMTNBBS
   (	NTT_ID NUMERIC(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL,
	NTT_NO NUMERIC(20,0),
	NTT_SJ VARCHAR(2000),
	NTT_CN TEXT,
	ANSWER_AT CHAR(1),
	PARNTSCTT_NO NUMERIC(10,0),
	ANSWER_LC NUMERIC(8,0),
	SORT_ORDR NUMERIC(8,0),
	RDCNT NUMERIC(10,0),
	USE_AT CHAR(1) NOT NULL,
	NTCE_BGNDE CHAR(20),
	NTCE_ENDDE CHAR(20),
	NTCR_ID VARCHAR(20),
	NTCR_NM VARCHAR(20),
	PASSWORD VARCHAR(200),
	ATCH_FILE_ID CHAR(20),
	NOTICE_AT CHAR(1),
	SJ_BOLD_AT CHAR(1),
	SECRET_AT CHAR(1),
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	BLOG_ID CHAR(20),
	NTT_EXTRA_FIELD_1 VARCHAR(200),
	NTT_EXTRA_FIELD_2 VARCHAR(200),
	NTT_EXTRA_FIELD_3 VARCHAR(200),
	NTT_EXTRA_FIELD_4 VARCHAR(200),
	NTT_EXTRA_FIELD_5 VARCHAR(200),
	NTT_EXTRA_FIELD_6 VARCHAR(200),
	NTT_EXTRA_FIELD_7 VARCHAR(200),
	NTT_EXTRA_FIELD_8 VARCHAR(200),
	NTT_EXTRA_FIELD_9 VARCHAR(200),
	NTT_EXTRA_FIELD_10 VARCHAR(200),
	 CONSTRAINT COMTNBBS_PK PRIMARY KEY (NTT_ID, BBS_ID) ) ;

-- TABLE COMTNBBSMASTER
CREATE TABLE COMTNBBSMASTER
   (	BBS_ID CHAR(30) NOT NULL,
	BBS_NM VARCHAR(255) NOT NULL,
	BBS_INTRCN VARCHAR(2400),
	BBS_TY_CODE CHAR(6) NOT NULL,
	REPLY_POSBL_AT CHAR(1),
	FILE_ATCH_POSBL_AT CHAR(1) NOT NULL,
	ATCH_POSBL_FILE_NUMBER NUMERIC(2,0) NOT NULL,
	ATCH_POSBL_FILE_SIZE NUMERIC(8,0),
	USE_AT CHAR(1) NOT NULL,
	TMPLAT_ID CHAR(20),
	CMMNTY_ID CHAR(20),
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	BLOG_ID CHAR(20),
	BLOG_AT CHAR(2),
	BBS_SKIN_CODE VARCHAR(30) DEFAULT 'BASIC',
	BBS_EXTRA_FIELD_1 VARCHAR(200),
	BBS_EXTRA_FIELD_2 VARCHAR(200),
	BBS_EXTRA_FIELD_3 VARCHAR(200),
	BBS_EXTRA_FIELD_4 VARCHAR(200),
	BBS_EXTRA_FIELD_5 VARCHAR(200),
	BBS_EXTRA_FIELD_6 VARCHAR(200),
	BBS_EXTRA_FIELD_7 VARCHAR(200),
	BBS_EXTRA_FIELD_8 VARCHAR(200),
	BBS_EXTRA_FIELD_9 VARCHAR(200),
	BBS_EXTRA_FIELD_10 VARCHAR(200),
	BBS_EXTRA_FIELD_TYPE_1 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_2 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_3 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_4 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_5 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_6 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_7 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_8 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_9 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_TYPE_10 VARCHAR(20) DEFAULT 'text',
	BBS_EXTRA_FIELD_CODE_ID_1 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_2 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_3 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_4 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_5 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_6 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_7 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_8 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_9 VARCHAR(30),
	BBS_EXTRA_FIELD_CODE_ID_10 VARCHAR(30),
	LIST_PAGE_UNIT VARCHAR(50),
	SECRET_POSBL_AT CHAR(1) DEFAULT 'Y',
	RICH_EDITOR_AT CHAR(1) DEFAULT 'Y',
	SEARCH_INCLD_AT CHAR(1) DEFAULT 'Y',
	PAGING_AT CHAR(1) DEFAULT 'Y',
	SEARCH_BOX_AT CHAR(1) DEFAULT 'Y',
	 CONSTRAINT COMTNBBSMASTER_PK PRIMARY KEY (BBS_ID) ) ;

-- TABLE COMTNBBSMASTEROPTN
CREATE TABLE COMTNBBSMASTEROPTN
   (	BBS_ID CHAR(30) NOT NULL,
	ANSWER_AT CHAR(1) NOT NULL,
	STSFDG_AT CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID) ) ;

-- 게시판별 작성권한. 열람권한은 메뉴 역할매핑(COMTNMENUCREATDTLS)이 원천이지만,
-- 메뉴가 보인다와 글을 쓸 수 있다는 다른 축이라 별도 매핑이 필요하다.
CREATE TABLE COMTNBBSWRITEAUTHOR (
	BBS_ID      CHAR(30)     NOT NULL,
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	CONSTRAINT COMTNBBSWRITEAUTHOR_PK PRIMARY KEY (BBS_ID, AUTHOR_CODE)
);

-- TABLE COMTNCOMMENT
CREATE TABLE COMTNCOMMENT
   (	NTT_ID NUMERIC(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL,
	ANSWER_NO NUMERIC(20,0) NOT NULL,
	WRTER_ID VARCHAR(20),
	-- 표준 원형은 VARCHAR(20) 이라 USER_NM(60) 이 긴 사용자는 ORA-12899 → 60 으로 확장(2026-07-10)
	WRTER_NM VARCHAR(60),
	-- 표준 원형은 VARCHAR(200)(바이트) 이라 한글 약 66자에서 ORA-12899 → 문자기준 1000 으로 확장(2026-07-10, UI 글자수 카운터)
	ANSWER VARCHAR(1000),
	USE_AT CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	PASSWORD VARCHAR(200),
	 CONSTRAINT COMTNCOMMENT_PK PRIMARY KEY (NTT_ID, BBS_ID, ANSWER_NO) ) ;

-- TABLE COMTNEMPLYRINFO
CREATE TABLE COMTNEMPLYRINFO
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	ORGNZT_ID CHAR(20),
	USER_NM VARCHAR(60) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	EMPL_NO VARCHAR(20),
	IHIDNUM VARCHAR(200),
	SEXDSTN_CODE CHAR(1),
	BRTHDY CHAR(20),
	FXNUM VARCHAR(20),
	HOUSE_ADRES VARCHAR(100),
	PASSWORD_HINT VARCHAR(100),
	PASSWORD_CNSR VARCHAR(100),
	HOUSE_END_TELNO VARCHAR(4),
	AREA_NO VARCHAR(4),
	DETAIL_ADRES VARCHAR(100),
	ZIP VARCHAR(6),
	OFFM_TELNO VARCHAR(20),
	MBTLNUM VARCHAR(20),
	EMAIL_ADRES VARCHAR(50),
	OFCPS_NM VARCHAR(60),
	HOUSE_MIDDLE_TELNO VARCHAR(4),
	GROUP_ID CHAR(20),
	PSTINST_CODE CHAR(8),
	EMPLYR_STTUS_CODE CHAR(1) NOT NULL,
	ESNTL_ID CHAR(20) NOT NULL,
	CRTFC_DN_VALUE VARCHAR(100),
	SBSCRB_DE TIMESTAMP,
	LOCK_AT CHAR(1),
	LOCK_CNT NUMERIC(3,0),
	LOCK_LAST_PNTTM TIMESTAMP,
	CHG_PWD_LAST_PNTTM TIMESTAMP,
	 CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID) ) ;

-- TABLE COMTNEMPLYRSCRTYESTBS
CREATE TABLE COMTNEMPLYRSCRTYESTBS
   (	SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
	MBER_TY_CODE CHAR(5),
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	 CONSTRAINT COMTNEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID) ) ;

-- TABLE COMTNFAQINFO
CREATE TABLE COMTNFAQINFO
   (	FAQ_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255),
	QESTN_CN VARCHAR(2500),
	ANSWER_CN VARCHAR(2500),
	RDCNT NUMERIC(10,0),
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
	ATCH_FILE_ID CHAR(20),
	QNA_PROCESS_STTUS_CODE CHAR(1),
	FAQ_CODE VARCHAR(15),
	 CONSTRAINT COMTNFAQINFO_PK PRIMARY KEY (FAQ_ID) ) ;

-- TABLE COMTNFILE
CREATE TABLE COMTNFILE
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	CREAT_DT TIMESTAMP NOT NULL,
	USE_AT CHAR(1),
	 CONSTRAINT COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID) ) ;

-- TABLE COMTNFILEDETAIL
CREATE TABLE COMTNFILEDETAIL
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	FILE_SN NUMERIC(10,0) NOT NULL,
	FILE_STRE_COURS VARCHAR(2000) NOT NULL,
	STRE_FILE_NM VARCHAR(255) NOT NULL,
	ORIGNL_FILE_NM VARCHAR(255),
	FILE_EXTSN VARCHAR(20) NOT NULL,
	FILE_CN TEXT,
	FILE_SIZE NUMERIC(8,0),
	DWLD_CO NUMERIC(8,0) DEFAULT 0,
	 CONSTRAINT COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN) ) ;

-- TABLE COMTNGNRLMBER
CREATE TABLE COMTNGNRLMBER
   (	MBER_ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	PASSWORD_HINT VARCHAR(100),
	PASSWORD_CNSR VARCHAR(100),
	IHIDNUM VARCHAR(200),
	MBER_NM VARCHAR(50) NOT NULL,
	ZIP VARCHAR(6),
	ADRES VARCHAR(100),
	AREA_NO VARCHAR(4) NOT NULL,
	MBER_STTUS VARCHAR(15),
	DETAIL_ADRES VARCHAR(100),
	END_TELNO VARCHAR(4) NOT NULL,
	MBTLNUM VARCHAR(20) NOT NULL,
	GROUP_ID CHAR(20),
	MBER_FXNUM VARCHAR(20),
	MBER_EMAIL_ADRES VARCHAR(50),
	MIDDLE_TELNO VARCHAR(4) NOT NULL,
	SBSCRB_DE TIMESTAMP,
	SEXDSTN_CODE CHAR(1),
	ESNTL_ID CHAR(20) NOT NULL,
	LOCK_AT CHAR(1),
	LOCK_CNT NUMERIC(3,0),
	LOCK_LAST_PNTTM TIMESTAMP,
	CHG_PWD_LAST_PNTTM TIMESTAMP,
	ORGNZT_ID VARCHAR(20),
	EMPL_NO VARCHAR(20),
	 CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID) ) ;

-- TABLE COMTNLOGINLOG
CREATE TABLE COMTNLOGINLOG
   (	LOG_ID CHAR(20) NOT NULL,
	CONECT_ID VARCHAR(20),
	CONECT_IP VARCHAR(23),
	CONECT_MTHD CHAR(4),
	ERROR_OCCRRNC_AT CHAR(1),
	ERROR_CODE CHAR(3),
	CREAT_DT TIMESTAMP,
	 CONSTRAINT COMTNLOGINLOG_PK PRIMARY KEY (LOG_ID) ) ;

-- TABLE COMTNLOGINPOLICY
CREATE TABLE COMTNLOGINPOLICY
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	IP_INFO VARCHAR(23) NOT NULL,
	DPLCT_PERM_AT CHAR(1) NOT NULL,
	LMTT_AT CHAR(1) NOT NULL,
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	 CONSTRAINT COMTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID) ) ;

-- TABLE COMTNMENUCREATDTLS
CREATE TABLE COMTNMENUCREATDTLS
   (	MENU_NO NUMERIC(20,0) NOT NULL,
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	MAPNG_CREAT_ID VARCHAR(30),
	 CONSTRAINT COMTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO, AUTHOR_CODE) ) ;

-- TABLE COMTNMENUINFO
CREATE TABLE COMTNMENUINFO
   (	MENU_NM VARCHAR(60) NOT NULL,
	PROGRM_FILE_NM VARCHAR(60) NOT NULL,
	MENU_NO NUMERIC(20,0) NOT NULL,
	UPPER_MENU_NO NUMERIC(20,0),
	MENU_ORDR NUMERIC(5,0) NOT NULL,
	MENU_DC VARCHAR(250),
	RELATE_IMAGE_PATH VARCHAR(100),
	RELATE_IMAGE_NM VARCHAR(60),
	MENU_SE VARCHAR(20),
	 CONSTRAINT COMTNMENUINFO_PK PRIMARY KEY (MENU_NO) ) ;

-- TABLE COMTNORGNZTINFO (2026-07-27 트리 전환: UPPER_ORGNZT_ID 자기참조 + ORDR 표시순서)
CREATE TABLE COMTNORGNZTINFO
   (	ORGNZT_ID CHAR(20) NOT NULL,
	ORGNZT_NM VARCHAR(255) NOT NULL,
	ORGNZT_DC VARCHAR(500),
	UPPER_ORGNZT_ID CHAR(20),
	ORDR NUMERIC(5,0),
	 CONSTRAINT COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID) ) ;

-- TABLE COMTNPOPUPMANAGE
CREATE TABLE COMTNPOPUPMANAGE
   (	POPUP_ID VARCHAR(20) NOT NULL,
	POPUP_SJ_NM VARCHAR(1024),
	FILE_URL VARCHAR(1024),
	POPUP_WIDTH_LC VARCHAR(20),
	POPUP_WIDTH_SIZE NUMERIC,
	NTCE_BGNDE CHAR(20),
	NTCE_ENDDE CHAR(20),
	STOPVEW_SETUP_AT CHAR(1),
	NTCE_AT CHAR(1),
	POPUP_VRTICL_LC VARCHAR(20),
	POPUP_VRTICL_SIZE NUMERIC,
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	POPUP_CN TEXT,
	CN_SE VARCHAR(1) DEFAULT 'F',
	 CONSTRAINT COMTNPOPUPMANAGE_PK PRIMARY KEY (POPUP_ID) ) ;

-- TABLE COMTNPRIVACYLOG
CREATE TABLE COMTNPRIVACYLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	INQIRE_DT TIMESTAMP NOT NULL,
	SRVC_NM VARCHAR(500),
	INQIRE_INFO VARCHAR(100),
	RQESTER_ID VARCHAR(20),
	RQESTER_IP VARCHAR(23),
	 CONSTRAINT REQUST_ID_PK PRIMARY KEY (REQUST_ID) ) ;

-- TABLE COMTNPROGRMLIST
CREATE TABLE COMTNPROGRMLIST
   (	PROGRM_FILE_NM VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH VARCHAR(100) NOT NULL,
	PROGRM_KOREAN_NM VARCHAR(60),
	PROGRM_DC VARCHAR(200),
	URL VARCHAR(100) NOT NULL,
	 CONSTRAINT COMTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM) ) ;

-- TABLE COMTNQAINFO
CREATE TABLE COMTNQAINFO
   (	QA_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255),
	QESTN_CN VARCHAR(2500),
	WRITNG_DE CHAR(20),
	RDCNT NUMERIC(10,0),
	EMAIL_ADRES VARCHAR(50),
	FRST_REGIST_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	QNA_PROCESS_STTUS_CODE CHAR(1),
	WRTER_NM VARCHAR(20),
	ANSWER_CN VARCHAR(2500),
	WRITNG_PASSWORD VARCHAR(20),
	ANSWER_DE CHAR(20),
	EMAIL_ANSWER_AT CHAR(1),
	AREA_NO VARCHAR(4),
	MIDDLE_TELNO VARCHAR(4),
	END_TELNO VARCHAR(4),
	 CONSTRAINT COMTNQAINFO_PK PRIMARY KEY (QA_ID) ) ;

-- TABLE COMTNROLEINFO
CREATE TABLE COMTNROLEINFO
   (	ROLE_CODE VARCHAR(50) NOT NULL,
	ROLE_NM VARCHAR(60) NOT NULL,
	ROLE_PTTRN VARCHAR(300),
	ROLE_DC VARCHAR(200),
	ROLE_TY VARCHAR(80),
	ROLE_SORT VARCHAR(10),
	ROLE_CREAT_DE CHAR(20) NOT NULL,
	 CONSTRAINT COMTNROLEINFO_PK PRIMARY KEY (ROLE_CODE) ) ;

-- TABLE COMTNROLES_HIERARCHY
CREATE TABLE COMTNROLES_HIERARCHY
   (	PARNTS_ROLE VARCHAR(30) NOT NULL,
	CHLDRN_ROLE VARCHAR(30) NOT NULL,
	 CONSTRAINT COMTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE, CHLDRN_ROLE) ) ;

-- TABLE COMTNSITEMAP
CREATE TABLE COMTNSITEMAP
   (	MAPNG_CREAT_ID VARCHAR(30) NOT NULL,
	CREATR_ID VARCHAR(20) NOT NULL,
	MAPNG_FILE_NM VARCHAR(60) NOT NULL,
	MAPNG_FILE_PATH VARCHAR(100) NOT NULL,
	 CONSTRAINT COMTNSITEMAP_PK PRIMARY KEY (MAPNG_CREAT_ID) ) ;

-- TABLE COMTNSTSFDG
CREATE TABLE COMTNSTSFDG
   (	STSFDG_NO NUMERIC(20,0) NOT NULL,
	NTT_ID NUMERIC(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL,
	WRTER_ID VARCHAR(20),
	-- 표준 원형 20 → USER_NM(60) 초과 시 ORA-12899. 60 으로 확장(2026-07-10, 만족도 JSON UI)
	WRTER_NM VARCHAR(60),
	PASSWORD VARCHAR(200),
	STSFDG NUMERIC(1,0) NOT NULL,
	-- 표준 원형 200바이트(한글 약66자) → 1000 CHAR 로 확장(2026-07-10, UI 글자수 카운터)
	STSFDG_CN VARCHAR(1000),
	USE_AT CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
	LAST_UPDT_PNTTM TIMESTAMP,
	FRST_REGISTER_ID VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID VARCHAR(20),
	 CONSTRAINT COMTNSTSFDG_PK PRIMARY KEY (STSFDG_NO) ) ;

-- TABLE COMTNSYSLOG
CREATE TABLE COMTNSYSLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	JOB_SE_CODE CHAR(3),
	INSTT_CODE CHAR(7),
	OCCRRNC_DE TIMESTAMP,
	RQESTER_IP VARCHAR(23),
	RQESTER_ID VARCHAR(20),
	TRGET_MENU_NM VARCHAR(255),
	SVC_NM VARCHAR(255),
	METHOD_NM VARCHAR(60),
	PROCESS_SE_CODE CHAR(3),
	PROCESS_CO NUMERIC(10,0),
	PROCESS_TIME VARCHAR(14),
	RSPNS_CODE CHAR(3),
	ERROR_SE CHAR(1),
	ERROR_CO NUMERIC(10,0),
	ERROR_CODE CHAR(3),
	 CONSTRAINT COMTNSYSLOG_PK PRIMARY KEY (REQUST_ID) ) ;

-- TABLE COMTNTMPLATINFO
-- 게시판 템플릿 정본(2026-07 재정의): TMPLAT_SE_CODE=렌더엔진코드(COM005), TMPLAT_CONFIG_CN=표현설정(JSON)
CREATE TABLE COMTNTMPLATINFO
   (	TMPLAT_ID CHAR(20) NOT NULL,
	TMPLAT_NM VARCHAR(255),
	TMPLAT_COURS VARCHAR(2000),
	USE_AT CHAR(1),
	TMPLAT_SE_CODE VARCHAR(20),
	TMPLAT_CONFIG_CN VARCHAR(2000),
	FRST_REGISTER_ID VARCHAR(20),
	FRST_REGIST_PNTTM TIMESTAMP,
	LAST_UPDUSR_ID VARCHAR(20),
	LAST_UPDT_PNTTM TIMESTAMP,
	 CONSTRAINT COMTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID) ) ;

-- TABLE COMTNUSERLOG
CREATE TABLE COMTNUSERLOG
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	RQESTER_ID VARCHAR(20) NOT NULL,
	SVC_NM VARCHAR(255) NOT NULL,
	METHOD_NM VARCHAR(60) NOT NULL,
	CREAT_CO NUMERIC(10,0),
	UPDT_CO NUMERIC(10,0),
	RDCNT NUMERIC(10,0),
	DELETE_CO NUMERIC(10,0),
	OUTPT_CO NUMERIC(10,0),
	ERROR_CO NUMERIC(10,0),
	 CONSTRAINT COMTNUSERLOG_PK PRIMARY KEY (OCCRRNC_DE, RQESTER_ID, SVC_NM, METHOD_NM) ) ;

-- TABLE COMTNWEBLOG (2026-07-20 접속통계 확장: 기기/브라우저/세션 컬럼 + 일자 인덱스)
CREATE TABLE COMTNWEBLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	OCCRRNC_DE TIMESTAMP,
	URL VARCHAR(200),
	RQESTER_ID VARCHAR(20),
	RQESTER_IP VARCHAR(23),
	DVICE_SE VARCHAR(10),
	BROWSER_NM VARCHAR(30),
	SESN_ID VARCHAR(60),
	 CONSTRAINT COMTNWEBLOG_PK PRIMARY KEY (REQUST_ID) ) ;


  CREATE INDEX IX_COMTNWEBLOG_DT ON COMTNWEBLOG (OCCRRNC_DE)
  ;

-- TABLE COMTSSYSLOGSUMMARY
CREATE TABLE COMTSSYSLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	SVC_NM VARCHAR(255) NOT NULL,
	METHOD_NM VARCHAR(60) NOT NULL,
	CREAT_CO NUMERIC(10,0),
	UPDT_CO NUMERIC(10,0),
	RDCNT NUMERIC(10,0),
	DELETE_CO NUMERIC(10,0),
	OUTPT_CO NUMERIC(10,0),
	ERROR_CO NUMERIC(10,0),
	 CONSTRAINT COMTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, SVC_NM, METHOD_NM) ) ;

-- TABLE COMTSWEBLOGSUMMARY
CREATE TABLE COMTSWEBLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	URL VARCHAR(200) NOT NULL,
	RDCNT NUMERIC(10,0),
	 CONSTRAINT COMTSWEBLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, URL) ) ;

-- TABLE TB_ACT_LOG
CREATE TABLE TB_ACT_LOG
   (	IALOG_NO NUMERIC NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL,
	IREF_NO NUMERIC NOT NULL,
	SNAME VARCHAR(255) NOT NULL,
	STASK VARCHAR(255) NOT NULL,
	SUSER_ID VARCHAR(255) NOT NULL,
	SUSER_NAME VARCHAR(255) NOT NULL,
	SINS_DT VARCHAR(255) NOT NULL,
	SSYS_ID VARCHAR(255),
	SINS_IP VARCHAR(255)
   ) ;


ALTER TABLE TB_ACT_LOG ADD CONSTRAINT PK_TB_ACT_LOG PRIMARY KEY (IALOG_NO) ;

-- TABLE TB_STATS_BBS_VIEW (2026-07-20 신설 — 게시판 조회통계 적재)
CREATE TABLE TB_STATS_BBS_VIEW
   (	ISBVIEW_NO NUMERIC NOT NULL,
	SBBS_ID VARCHAR(30) NOT NULL,
	INTT_ID NUMERIC NOT NULL,
	ICNT NUMERIC NOT NULL,
	SINS_DT VARCHAR(10) NOT NULL
   ) ;


ALTER TABLE TB_STATS_BBS_VIEW ADD CONSTRAINT PK_TB_STATS_BBS_VIEW PRIMARY KEY (ISBVIEW_NO) ;



-- VIEW COMVNUSERMASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID) AS 
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR' AS USER_SE, ORGNZT_ID
    FROM COMTNGNRLMBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
    FROM COMTNEMPLYRINFO;

--------------------------------------------------------------------------------
-- 합성 테이블 1종 — 레거시 운영 DB 에 없으나 라이브 필수 경로가 참조.
-- (죽은 흐름용 방어 테이블 6종은 2026-07-10 사용자 확정으로 제외 — 미생성 목록은 README 참조)
--------------------------------------------------------------------------------

-- COMTHEMPLYRINFOCHANGEDTLS (합성 근거: mapper\com\uss\umt\EgovUserManage_SQL_oracle.xml insertUserHistory —
--   사용자정보 수정 이력. 레거시 COMTN- 변형 구조 1:1, 매퍼가 쓰는 COMTH- 이름으로 생성)
CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID           VARCHAR(20)   NOT NULL,
  CHANGE_DE           CHAR(20)       NOT NULL,
  ORGNZT_ID           CHAR(20),
  GROUP_ID            CHAR(20),
  EMPL_NO             VARCHAR(20),
  SEXDSTN_CODE        CHAR(1),
  BRTHDY              CHAR(20),
  FXNUM               VARCHAR(20),
  HOUSE_ADRES         VARCHAR(100),
  HOUSE_END_TELNO     VARCHAR(4),
  AREA_NO             VARCHAR(4),
  DETAIL_ADRES        VARCHAR(100),
  ZIP                 VARCHAR(6),
  OFFM_TELNO          VARCHAR(20),
  MBTLNUM             VARCHAR(20),
  EMAIL_ADRES         VARCHAR(50),
  HOUSE_MIDDLE_TELNO  VARCHAR(4),
  PSTINST_CODE        CHAR(8),
  EMPLYR_STTUS_CODE   CHAR(1),
  ESNTL_ID            CHAR(20),
  CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE)
);

-- 브랜드설정 — 로고(텍스트/이미지)·파비콘·연락처. 고객사별 리브랜딩 지점, BRAND_ID='S' 단일 행 (2026-07-31, 연락처 2026-08-04)
CREATE TABLE COM_BRAND (
  BRAND_ID              CHAR(1)       NOT NULL,
  LOGO_TY_CODE          VARCHAR(10)  DEFAULT 'TEXT' NOT NULL,
  LOGO_TEXT             VARCHAR(300),
  LOGO_ATCH_FILE_ID     CHAR(20),
  FAVICON_ATCH_FILE_ID  CHAR(20),
  CNTC_ADRES            VARCHAR(300),
  CNTC_TELNO            VARCHAR(30),
  CNTC_FXNUM            VARCHAR(30),
  CNTC_EMAIL_ADRES      VARCHAR(100),
  LAST_UPDUSR_ID        VARCHAR(20),
  LAST_UPDT_PNTTM       TIMESTAMP,
  CONSTRAINT PK_COM_BRAND PRIMARY KEY (BRAND_ID)
);
--------------------------------------------------------------------------------
-- Oracle 호환 DUAL (1행) — 공유 인가 SQL(context-security.xml 쌍둥이)이
-- FROM DUAL 을 대량 사용하므로 PG 에도 동명 테이블을 둔다(고전 이식 심).
-- 매퍼(*_SQL_postgres.xml)는 FROM DUAL 을 이미 제거했으므로 이 테이블 미의존.
--------------------------------------------------------------------------------
CREATE TABLE DUAL (DUMMY VARCHAR(1));
INSERT INTO DUAL VALUES ('X');
COMMENT ON TABLE DUAL IS 'Oracle 호환 DUAL(1행) — 공유 인가 SQL(context-security)의 FROM DUAL 지원용';
COMMENT ON COLUMN DUAL.DUMMY IS '더미(X 1행 고정)';
