--------------------------------------------------------------------------------
-- 10_tables.sql — 테이블 76종 + 로그인 뷰 COMVNUSERMASTER
-- RegNex(규정 단독, MariaDB) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: regnex. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- 원천: Oracle DDL 자동변환 — VARCHAR2→VARCHAR, NUMBER→INT/DECIMAL, CLOB→LONGTEXT, DATE→DATETIME.
-- ※ MariaDB 는 COMMENT ON 문이 없어 컬럼 코멘트를 컬럼 정의에 인라인으로 넣었다(코멘트 필수 규약 유지). 합성 1종(COMTH 변경이력)은 후반부.
--------------------------------------------------------------------------------

-- TABLE COMTCCMMNCODE
CREATE TABLE COMTCCMMNCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE_ID_NM VARCHAR(60) COMMENT '코드ID명',
	CODE_ID_DC VARCHAR(200) COMMENT '코드ID설명',
	USE_AT CHAR(1) COMMENT '사용여부',
	CL_CODE CHAR(3) COMMENT '분류코드',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='공통코드';


-- TABLE COMTCCMMNDETAILCODE
CREATE TABLE COMTCCMMNDETAILCODE
   (	CODE_ID VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL COMMENT '코드',
	CODE_NM VARCHAR(60) COMMENT '코드명',
	CODE_DC VARCHAR(200) COMMENT '코드설명',
	USE_AT CHAR(1) COMMENT '사용여부',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID, CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='공통상세코드';


-- TABLE COMTECOPSEQ
CREATE TABLE COMTECOPSEQ
   (	TABLE_NAME VARCHAR(20) NOT NULL,
	NEXT_ID DECIMAL(30,0) COMMENT '다음아이디',
	 CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='COMTECOPSEQ';


-- TABLE COMTNAUTHORGROUPINFO
CREATE TABLE COMTNAUTHORGROUPINFO
   (	GROUP_ID CHAR(20) NOT NULL,
	GROUP_NM VARCHAR(60) NOT NULL COMMENT '그룹명',
	GROUP_CREAT_DE CHAR(20) NOT NULL COMMENT '그룹생성일',
	GROUP_DC VARCHAR(100) COMMENT '그룹설명',
	 CONSTRAINT COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='권한그룹정보';


-- TABLE COMTNAUTHORINFO
CREATE TABLE COMTNAUTHORINFO
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	AUTHOR_NM VARCHAR(60) NOT NULL COMMENT '권한명',
	AUTHOR_DC VARCHAR(200) COMMENT '권한설명',
	AUTHOR_CREAT_DE CHAR(20) NOT NULL COMMENT '권한생성일',
	 CONSTRAINT COMTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='권한정보';


-- TABLE COMTNAUTHORROLERELATE
CREATE TABLE COMTNAUTHORROLERELATE
   (	AUTHOR_CODE VARCHAR(30) NOT NULL,
	ROLE_CODE VARCHAR(50) NOT NULL COMMENT '롤코드',
	CREAT_DT DATETIME COMMENT '생성일시',
	 CONSTRAINT COMTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE, ROLE_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='권한롤관계';


-- TABLE COMTNBANNER
CREATE TABLE COMTNBANNER
   (	BANNER_ID CHAR(20) NOT NULL,
	BANNER_NM VARCHAR(60) NOT NULL COMMENT '배너명',
	LINK_URL VARCHAR(255) NOT NULL COMMENT '링크URL',
	BANNER_IMAGE VARCHAR(60) NOT NULL COMMENT '배너이미지',
	BANNER_DC VARCHAR(200) COMMENT '배너설명',
	REFLCT_AT CHAR(1) NOT NULL COMMENT '반영여부',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	BANNER_IMAGE_FILE VARCHAR(60) COMMENT '배너이미지파일',
	SORT_ORDR DECIMAL(8,0) COMMENT '정렬순서',
	 CONSTRAINT COMTNBANNER_PK PRIMARY KEY (BANNER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='배너';


-- TABLE COMTNBBS
CREATE TABLE COMTNBBS
   (	NTT_ID DECIMAL(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL COMMENT '게시판ID',
	NTT_NO DECIMAL(20,0) COMMENT '게시물번호',
	NTT_SJ VARCHAR(2000) COMMENT '게시물제목',
	NTT_CN LONGTEXT COMMENT '게시물내용',
	ANSWER_AT CHAR(1) COMMENT '댓글여부',
	PARNTSCTT_NO DECIMAL(10,0) COMMENT '부모글번호',
	ANSWER_LC DECIMAL(8,0) COMMENT '댓글위치',
	SORT_ORDR DECIMAL(8,0) COMMENT '정렬순서',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	NTCE_BGNDE CHAR(20) COMMENT '게시시작일',
	NTCE_ENDDE CHAR(20) COMMENT '게시종료일',
	NTCR_ID VARCHAR(20) COMMENT '게시자ID',
	NTCR_NM VARCHAR(20) COMMENT '게시자명',
	PASSWORD VARCHAR(200) COMMENT '비밀번호',
	ATCH_FILE_ID CHAR(20) COMMENT '첨부파일ID',
	NOTICE_AT CHAR(1) COMMENT '공지사항여부',
	SJ_BOLD_AT CHAR(1) COMMENT '제목볼드여부',
	SECRET_AT CHAR(1) COMMENT '비밀글여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	BLOG_ID CHAR(20) COMMENT '블로그 ID',
	NTT_EXTRA_FIELD_1 VARCHAR(200) COMMENT '게시물 여분필드 1 값 — 게시판 마스터(BBS_EXTRA_FIELD_1)에 정의된 확장항목의 입력값',
	NTT_EXTRA_FIELD_2 VARCHAR(200) COMMENT '게시물 여분필드 2 값',
	NTT_EXTRA_FIELD_3 VARCHAR(200) COMMENT '게시물 여분필드 3 값',
	NTT_EXTRA_FIELD_4 VARCHAR(200) COMMENT '게시물 여분필드 4 값',
	NTT_EXTRA_FIELD_5 VARCHAR(200) COMMENT '게시물 여분필드 5 값',
	NTT_EXTRA_FIELD_6 VARCHAR(200) COMMENT '게시물 여분필드 6 값',
	NTT_EXTRA_FIELD_7 VARCHAR(200) COMMENT '게시물 여분필드 7 값',
	NTT_EXTRA_FIELD_8 VARCHAR(200) COMMENT '게시물 여분필드 8 값',
	NTT_EXTRA_FIELD_9 VARCHAR(200) COMMENT '게시물 여분필드 9 값',
	NTT_EXTRA_FIELD_10 VARCHAR(200) COMMENT '게시물 여분필드 10 값',
	 CONSTRAINT COMTNBBS_PK PRIMARY KEY (NTT_ID, BBS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판';


-- TABLE COMTNBBSMASTER
CREATE TABLE COMTNBBSMASTER
   (	BBS_ID CHAR(30) NOT NULL,
	BBS_NM VARCHAR(255) NOT NULL COMMENT '게시판명',
	BBS_INTRCN VARCHAR(2400) COMMENT '게시판소개',
	BBS_TY_CODE CHAR(6) NOT NULL COMMENT '게시판유형코드',
	REPLY_POSBL_AT CHAR(1) COMMENT '답장가능여부',
	FILE_ATCH_POSBL_AT CHAR(1) NOT NULL COMMENT '파일첨부가능여부',
	ATCH_POSBL_FILE_NUMBER DECIMAL(2,0) NOT NULL COMMENT '첨부가능파일숫자',
	ATCH_POSBL_FILE_SIZE DECIMAL(8,0) COMMENT '첨부가능파일사이즈',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	TMPLAT_ID CHAR(20) COMMENT '템플릿ID',
	CMMNTY_ID CHAR(20) COMMENT '커뮤니티ID',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	BLOG_ID CHAR(20) COMMENT '블로그 ID',
	BLOG_AT CHAR(2) COMMENT '블로그 여부',
	BBS_SKIN_CODE VARCHAR(30) DEFAULT 'BASIC' COMMENT '게시판 스킨 코드(기본 BASIC) — RLMS 확장',
	BBS_EXTRA_FIELD_1 VARCHAR(200) COMMENT '여분필드 1 라벨 — 게시판별 확장 입력항목 정의(타입/코드는 BBS_EXTRA_FIELD_TYPE_1, CODE_ID_1)',
	BBS_EXTRA_FIELD_2 VARCHAR(200) COMMENT '여분필드 2 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_3 VARCHAR(200) COMMENT '여분필드 3 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_4 VARCHAR(200) COMMENT '여분필드 4 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_5 VARCHAR(200) COMMENT '여분필드 5 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_6 VARCHAR(200) COMMENT '여분필드 6 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_7 VARCHAR(200) COMMENT '여분필드 7 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_8 VARCHAR(200) COMMENT '여분필드 8 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_9 VARCHAR(200) COMMENT '여분필드 9 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_10 VARCHAR(200) COMMENT '여분필드 10 라벨 — 게시판별 확장 입력항목 정의',
	BBS_EXTRA_FIELD_TYPE_1 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드1 입력타입',
	BBS_EXTRA_FIELD_TYPE_2 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드2 입력타입',
	BBS_EXTRA_FIELD_TYPE_3 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드3 입력타입',
	BBS_EXTRA_FIELD_TYPE_4 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드4 입력타입',
	BBS_EXTRA_FIELD_TYPE_5 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드5 입력타입',
	BBS_EXTRA_FIELD_TYPE_6 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드6 입력타입',
	BBS_EXTRA_FIELD_TYPE_7 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드7 입력타입',
	BBS_EXTRA_FIELD_TYPE_8 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드8 입력타입',
	BBS_EXTRA_FIELD_TYPE_9 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드9 입력타입',
	BBS_EXTRA_FIELD_TYPE_10 VARCHAR(20) DEFAULT 'text' COMMENT '게시판 여분필드10 입력타입',
	BBS_EXTRA_FIELD_CODE_ID_1 VARCHAR(30) COMMENT '게시판 여분필드1 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_2 VARCHAR(30) COMMENT '게시판 여분필드2 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_3 VARCHAR(30) COMMENT '게시판 여분필드3 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_4 VARCHAR(30) COMMENT '게시판 여분필드4 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_5 VARCHAR(30) COMMENT '게시판 여분필드5 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_6 VARCHAR(30) COMMENT '게시판 여분필드6 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_7 VARCHAR(30) COMMENT '게시판 여분필드7 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_8 VARCHAR(30) COMMENT '게시판 여분필드8 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_9 VARCHAR(30) COMMENT '게시판 여분필드9 공통코드ID',
	BBS_EXTRA_FIELD_CODE_ID_10 VARCHAR(30) COMMENT '게시판 여분필드10 공통코드ID',
	LIST_PAGE_UNIT VARCHAR(50),
	SECRET_POSBL_AT CHAR(1) DEFAULT 'Y',
	RICH_EDITOR_AT CHAR(1) DEFAULT 'Y',
	SEARCH_INCLD_AT CHAR(1) DEFAULT 'Y',
	PAGING_AT CHAR(1) DEFAULT 'Y',
	SEARCH_BOX_AT CHAR(1) DEFAULT 'Y',
	 CONSTRAINT COMTNBBSMASTER_PK PRIMARY KEY (BBS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판마스터';


-- TABLE COMTNBBSMASTEROPTN
CREATE TABLE COMTNBBSMASTEROPTN
   (	BBS_ID CHAR(30) NOT NULL,
	ANSWER_AT CHAR(1) NOT NULL COMMENT '댓글여부',
	STSFDG_AT CHAR(1) NOT NULL COMMENT '만족도여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판마스터옵션';


-- 게시판별 작성권한. 열람권한은 메뉴 역할매핑(COMTNMENUCREATDTLS)이 원천이지만,
-- 메뉴가 보인다와 글을 쓸 수 있다는 다른 축이라 별도 매핑이 필요하다.
CREATE TABLE COMTNBBSWRITEAUTHOR (
	BBS_ID      CHAR(30)     NOT NULL COMMENT '게시판ID',
	AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
	CONSTRAINT COMTNBBSWRITEAUTHOR_PK PRIMARY KEY (BBS_ID, AUTHOR_CODE)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판작성권한';


-- TABLE COMTNCOMMENT
CREATE TABLE COMTNCOMMENT
   (	NTT_ID DECIMAL(20,0) NOT NULL,
	BBS_ID CHAR(30) NOT NULL COMMENT '게시판ID',
	ANSWER_NO DECIMAL(20,0) NOT NULL COMMENT '댓글번호',
	WRTER_ID VARCHAR(20) COMMENT '작성자ID',
	-- 표준 원형은 VARCHAR(20) 이라 USER_NM(60) 이 긴 사용자는 ORA-12899 → 60 으로 확장(2026-07-10)
	WRTER_NM VARCHAR(60) COMMENT '작성자명',
	-- 표준 원형은 VARCHAR(200)(바이트) 이라 한글 약 66자에서 ORA-12899 → 문자기준 1000 으로 확장(2026-07-10, UI 글자수 카운터)
	ANSWER VARCHAR(1000) COMMENT '댓글',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	PASSWORD VARCHAR(200) COMMENT '비밀번호',
	 CONSTRAINT COMTNCOMMENT_PK PRIMARY KEY (NTT_ID, BBS_ID, ANSWER_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='댓글';


-- TABLE COMTNEMPLYRINFO
CREATE TABLE COMTNEMPLYRINFO
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	ORGNZT_ID CHAR(20) COMMENT '조직ID',
	USER_NM VARCHAR(60) NOT NULL COMMENT '사용자명',
	PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호',
	EMPL_NO VARCHAR(20) COMMENT '사원번호',
	IHIDNUM VARCHAR(200) COMMENT '주민등록번호',
	SEXDSTN_CODE CHAR(1) COMMENT '성별코드',
	BRTHDY CHAR(20) COMMENT '생일',
	FXNUM VARCHAR(20) COMMENT '팩스번호',
	HOUSE_ADRES VARCHAR(100) COMMENT '주택주소',
	PASSWORD_HINT VARCHAR(100) COMMENT '비밀번호힌트',
	PASSWORD_CNSR VARCHAR(100) COMMENT '비밀번호정답',
	HOUSE_END_TELNO VARCHAR(4) COMMENT '주택끝전화번호',
	AREA_NO VARCHAR(4) COMMENT '지역번호',
	DETAIL_ADRES VARCHAR(100) COMMENT '상세주소',
	ZIP VARCHAR(6) COMMENT '우편번호',
	OFFM_TELNO VARCHAR(20) COMMENT '사무실전화번호',
	MBTLNUM VARCHAR(20) COMMENT '이동전화번호',
	EMAIL_ADRES VARCHAR(50) COMMENT '이메일주소',
	OFCPS_NM VARCHAR(60) COMMENT '직위명',
	HOUSE_MIDDLE_TELNO VARCHAR(4) COMMENT '주택중간전화번호',
	GROUP_ID CHAR(20) COMMENT '그룹ID',
	PSTINST_CODE CHAR(8) COMMENT '소속기관코드',
	EMPLYR_STTUS_CODE CHAR(1) NOT NULL COMMENT '사용자상태코드',
	ESNTL_ID CHAR(20) NOT NULL COMMENT '고유ID',
	CRTFC_DN_VALUE VARCHAR(100) COMMENT '인증DN값',
	SBSCRB_DE DATETIME COMMENT '가입일자',
	LOCK_AT CHAR(1) COMMENT '잠금여부',
	LOCK_CNT DECIMAL(3,0) COMMENT '잠금회수',
	LOCK_LAST_PNTTM DATETIME COMMENT '잠금최종시점',
	CHG_PWD_LAST_PNTTM DATETIME COMMENT '최종 비밀번호 변경 시점 — 비밀번호 유효기간(180일) 만료 판정 기준(RLMS 확장)',
	 CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='업무사용자정보';


-- TABLE COMTNEMPLYRSCRTYESTBS
CREATE TABLE COMTNEMPLYRSCRTYESTBS
   (	SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
	MBER_TY_CODE CHAR(5) COMMENT '회원유형코드',
	AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
	 CONSTRAINT COMTNEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자보안설정';


-- TABLE COMTNFAQINFO
CREATE TABLE COMTNFAQINFO
   (	FAQ_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255) COMMENT '질문제목',
	QESTN_CN VARCHAR(2500) COMMENT '질문내용',
	ANSWER_CN VARCHAR(2500) COMMENT '답변내용',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME NOT NULL COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) NOT NULL COMMENT '최종수정자ID',
	ATCH_FILE_ID CHAR(20) COMMENT '첨부파일ID',
	QNA_PROCESS_STTUS_CODE CHAR(1) COMMENT '질의응답처리상태코드',
	FAQ_CODE VARCHAR(15) COMMENT 'FAQ 카테고리 코드 — 공통코드 faqCode 상세코드(RLMS 확장)',
	 CONSTRAINT COMTNFAQINFO_PK PRIMARY KEY (FAQ_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FAQ정보';


-- TABLE COMTNFILE
CREATE TABLE COMTNFILE
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	CREAT_DT DATETIME NOT NULL COMMENT '생성일시',
	USE_AT CHAR(1) COMMENT '사용여부',
	 CONSTRAINT COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='파일속성';


-- TABLE COMTNFILEDETAIL
CREATE TABLE COMTNFILEDETAIL
   (	ATCH_FILE_ID CHAR(20) NOT NULL,
	FILE_SN DECIMAL(10,0) NOT NULL COMMENT '파일순번',
	FILE_STRE_COURS VARCHAR(2000) NOT NULL COMMENT '파일저장경로',
	STRE_FILE_NM VARCHAR(255) NOT NULL COMMENT '저장파일명',
	ORIGNL_FILE_NM VARCHAR(255) COMMENT '원파일명',
	FILE_EXTSN VARCHAR(20) NOT NULL COMMENT '파일확장자',
	FILE_CN LONGTEXT COMMENT '파일내용',
	FILE_SIZE DECIMAL(8,0) COMMENT '파일크기',
	DWLD_CO DECIMAL(8,0) DEFAULT 0,
	 CONSTRAINT COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='파일상세정보';


-- TABLE COMTNGNRLMBER
CREATE TABLE COMTNGNRLMBER
   (	MBER_ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호',
	PASSWORD_HINT VARCHAR(100) COMMENT '비밀번호힌트',
	PASSWORD_CNSR VARCHAR(100) COMMENT '비밀번호정답',
	IHIDNUM VARCHAR(200) COMMENT '주민등록번호',
	MBER_NM VARCHAR(50) NOT NULL COMMENT '회원명',
	ZIP VARCHAR(6) COMMENT '우편번호',
	ADRES VARCHAR(100) COMMENT '주소',
	AREA_NO VARCHAR(4) NOT NULL COMMENT '지역번호',
	MBER_STTUS VARCHAR(15) COMMENT '회원상태',
	DETAIL_ADRES VARCHAR(100) COMMENT '상세주소',
	END_TELNO VARCHAR(4) NOT NULL COMMENT '끝전화번호',
	MBTLNUM VARCHAR(20) NOT NULL COMMENT '이동전화번호',
	GROUP_ID CHAR(20) COMMENT '그룹ID',
	MBER_FXNUM VARCHAR(20) COMMENT '회원팩스번호',
	MBER_EMAIL_ADRES VARCHAR(50) COMMENT '회원이메일주소',
	MIDDLE_TELNO VARCHAR(4) NOT NULL COMMENT '중간전화번호',
	SBSCRB_DE DATETIME COMMENT '가입일자',
	SEXDSTN_CODE CHAR(1) COMMENT '성별코드',
	ESNTL_ID CHAR(20) NOT NULL COMMENT '고유ID',
	LOCK_AT CHAR(1) COMMENT '잠금여부',
	LOCK_CNT DECIMAL(3,0) COMMENT '잠금회수',
	LOCK_LAST_PNTTM DATETIME COMMENT '잠금최종시점',
	CHG_PWD_LAST_PNTTM DATETIME COMMENT '최종 비밀번호 변경 시점 — 비밀번호 유효기간(180일) 만료 판정 기준(RLMS 확장)',
	ORGNZT_ID VARCHAR(20) COMMENT '소속 조직(부서) ID — COMTNORGNZTINFO 참조(RLMS 확장)',
	EMPL_NO VARCHAR(20) COMMENT '사번 (RLMS 확장 — 일반회원 등록/수정 화면 입력)',
	 CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일반회원';


-- TABLE COMTNLOGINLOG
CREATE TABLE COMTNLOGINLOG
   (	LOG_ID CHAR(20) NOT NULL,
	CONECT_ID VARCHAR(20) COMMENT '접속ID',
	CONECT_IP VARCHAR(23) COMMENT '접속IP',
	CONECT_MTHD CHAR(4) COMMENT '접속방식',
	ERROR_OCCRRNC_AT CHAR(1) COMMENT '오류발생여부',
	ERROR_CODE CHAR(3) COMMENT '오류코드',
	CREAT_DT DATETIME COMMENT '생성일시',
	 CONSTRAINT COMTNLOGINLOG_PK PRIMARY KEY (LOG_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='접속로그';


-- TABLE COMTNLOGINPOLICY
CREATE TABLE COMTNLOGINPOLICY
   (	EMPLYR_ID VARCHAR(20) NOT NULL,
	IP_INFO VARCHAR(23) NOT NULL COMMENT 'IP정보',
	DPLCT_PERM_AT CHAR(1) NOT NULL COMMENT '중복허용여부',
	LMTT_AT CHAR(1) NOT NULL COMMENT '제한여부',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	 CONSTRAINT COMTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='로그인정책';


-- TABLE COMTNMENUCREATDTLS
CREATE TABLE COMTNMENUCREATDTLS
   (	MENU_NO DECIMAL(20,0) NOT NULL,
	AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
	MAPNG_CREAT_ID VARCHAR(30) COMMENT '매핑생성ID',
	 CONSTRAINT COMTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO, AUTHOR_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='메뉴생성내역';


-- TABLE COMTNMENUINFO
CREATE TABLE COMTNMENUINFO
   (	MENU_NM VARCHAR(60) NOT NULL,
	PROGRM_FILE_NM VARCHAR(60) NOT NULL COMMENT '프로그램파일명',
	MENU_NO DECIMAL(20,0) NOT NULL COMMENT '메뉴번호',
	UPPER_MENU_NO DECIMAL(20,0) COMMENT '상위메뉴번호',
	MENU_ORDR DECIMAL(5,0) NOT NULL COMMENT '메뉴순서',
	MENU_DC VARCHAR(250) COMMENT '메뉴설명',
	RELATE_IMAGE_PATH VARCHAR(100) COMMENT '관계이미지경로',
	RELATE_IMAGE_NM VARCHAR(60) COMMENT '관계이미지명',
	MENU_SE VARCHAR(20) COMMENT '메뉴구분(ADMIN:관리자, USER:사용자)',
	 CONSTRAINT COMTNMENUINFO_PK PRIMARY KEY (MENU_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='메뉴정보';


-- TABLE COMTNORGNZTINFO (2026-07-27 트리 전환: UPPER_ORGNZT_ID 자기참조 + ORDR 표시순서)
CREATE TABLE COMTNORGNZTINFO
   (	ORGNZT_ID CHAR(20) NOT NULL,
	ORGNZT_NM VARCHAR(255) NOT NULL COMMENT '조직명',
	ORGNZT_DC VARCHAR(500) COMMENT '조직설명',
	UPPER_ORGNZT_ID CHAR(20) COMMENT '상위 조직ID (자기참조, NULL=최상위: 본사·지사)',
	ORDR DECIMAL(5,0) COMMENT '형제 내 표시 순서 (오름차순, NULL=마지막)',
	 CONSTRAINT COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='조직정보';


-- TABLE COMTNPOPUPMANAGE
CREATE TABLE COMTNPOPUPMANAGE
   (	POPUP_ID VARCHAR(20) NOT NULL,
	POPUP_SJ_NM VARCHAR(1024) COMMENT '팝업제목명',
	FILE_URL VARCHAR(1024) COMMENT '파일URL',
	POPUP_WIDTH_LC VARCHAR(20) COMMENT '팝업가로위치',
	POPUP_WIDTH_SIZE DECIMAL(38,10) COMMENT '팝업가로사이즈',
	NTCE_BGNDE CHAR(20) COMMENT '게시시작일',
	NTCE_ENDDE CHAR(20) COMMENT '게시종료일',
	STOPVEW_SETUP_AT CHAR(1) COMMENT '그만보기설정여부',
	NTCE_AT CHAR(1) COMMENT '게시여부',
	POPUP_VRTICL_LC VARCHAR(20) COMMENT '팝업세로위치',
	POPUP_VRTICL_SIZE DECIMAL(38,10) COMMENT '팝업세로사이즈',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	POPUP_CN LONGTEXT COMMENT '팝업내용(HTML, 직접편집모드)',
	CN_SE VARCHAR(1) DEFAULT 'F' COMMENT '내용구분(F:파일URL, E:직접편집)',
	 CONSTRAINT COMTNPOPUPMANAGE_PK PRIMARY KEY (POPUP_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='팝업 정보 관리';


-- TABLE COMTNPRIVACYLOG
CREATE TABLE COMTNPRIVACYLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	INQIRE_DT DATETIME NOT NULL COMMENT '조회일시',
	SRVC_NM VARCHAR(500) COMMENT '서비스 명',
	INQIRE_INFO VARCHAR(100) COMMENT '조회 정보 명',
	RQESTER_ID VARCHAR(20) COMMENT '요청자아이디',
	RQESTER_IP VARCHAR(23) COMMENT '요청아이피',
	 CONSTRAINT REQUST_ID_PK PRIMARY KEY (REQUST_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='개인정보조회 로그';


-- TABLE COMTNPROGRMLIST
CREATE TABLE COMTNPROGRMLIST
   (	PROGRM_FILE_NM VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH VARCHAR(100) NOT NULL COMMENT '프로그램저장경로',
	PROGRM_KOREAN_NM VARCHAR(60) COMMENT '프로그램한글명',
	PROGRM_DC VARCHAR(200) COMMENT '프로그램설명',
	URL VARCHAR(100) NOT NULL COMMENT 'URL',
	 CONSTRAINT COMTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='프로그램목록';


-- TABLE COMTNQAINFO
CREATE TABLE COMTNQAINFO
   (	QA_ID CHAR(20) NOT NULL,
	QESTN_SJ VARCHAR(255) COMMENT '질문제목',
	QESTN_CN VARCHAR(2500) COMMENT '질문내용',
	WRITNG_DE CHAR(20) COMMENT '작성일',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	EMAIL_ADRES VARCHAR(50) COMMENT '이메일주소',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	QNA_PROCESS_STTUS_CODE CHAR(1) COMMENT '질의응답처리상태코드',
	WRTER_NM VARCHAR(20) COMMENT '작성자명',
	ANSWER_CN VARCHAR(2500) COMMENT '답변내용',
	WRITNG_PASSWORD VARCHAR(20) COMMENT '작성비밀번호',
	ANSWER_DE CHAR(20) COMMENT '답변일자',
	EMAIL_ANSWER_AT CHAR(1) COMMENT '메일답변여부',
	AREA_NO VARCHAR(4) COMMENT '지역번호',
	MIDDLE_TELNO VARCHAR(4) COMMENT '중간전화번호',
	END_TELNO VARCHAR(4) COMMENT '끝전화번호',
	 CONSTRAINT COMTNQAINFO_PK PRIMARY KEY (QA_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='QA정보';


-- TABLE COMTNROLEINFO
CREATE TABLE COMTNROLEINFO
   (	ROLE_CODE VARCHAR(50) NOT NULL,
	ROLE_NM VARCHAR(60) NOT NULL COMMENT '롤명',
	ROLE_PTTRN VARCHAR(300) COMMENT '롤패턴',
	ROLE_DC VARCHAR(200) COMMENT '롤설명',
	ROLE_TY VARCHAR(80) COMMENT '롤유형',
	ROLE_SORT VARCHAR(10) COMMENT '롤정렬',
	ROLE_CREAT_DE CHAR(20) NOT NULL COMMENT '롤생성일',
	 CONSTRAINT COMTNROLEINFO_PK PRIMARY KEY (ROLE_CODE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='롤정보';


-- TABLE COMTNROLES_HIERARCHY
CREATE TABLE COMTNROLES_HIERARCHY
   (	PARNTS_ROLE VARCHAR(30) NOT NULL,
	CHLDRN_ROLE VARCHAR(30) NOT NULL COMMENT '자식롤',
	 CONSTRAINT COMTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE, CHLDRN_ROLE) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='롤 계층구조';


-- TABLE COMTNSITEMAP
CREATE TABLE COMTNSITEMAP
   (	MAPNG_CREAT_ID VARCHAR(30) NOT NULL,
	CREATR_ID VARCHAR(20) NOT NULL COMMENT '생성자ID',
	MAPNG_FILE_NM VARCHAR(60) NOT NULL COMMENT '매핑파일명',
	MAPNG_FILE_PATH VARCHAR(100) NOT NULL COMMENT '매핑파일경로',
	 CONSTRAINT COMTNSITEMAP_PK PRIMARY KEY (MAPNG_CREAT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사이트맵';


-- TABLE COMTNSTSFDG
CREATE TABLE COMTNSTSFDG
   (	STSFDG_NO DECIMAL(20,0) NOT NULL,
	NTT_ID DECIMAL(20,0) NOT NULL COMMENT '게시물ID',
	BBS_ID CHAR(30) NOT NULL COMMENT '게시판ID',
	WRTER_ID VARCHAR(20) COMMENT '작성자ID',
	-- 표준 원형 20 → USER_NM(60) 초과 시 ORA-12899. 60 으로 확장(2026-07-10, 만족도 JSON UI)
	WRTER_NM VARCHAR(60) COMMENT '작성자명',
	PASSWORD VARCHAR(200) COMMENT '비밀번호',
	STSFDG DECIMAL(1,0) NOT NULL COMMENT '만족도',
	-- 표준 원형 200바이트(한글 약66자) → 1000 CHAR 로 확장(2026-07-10, UI 글자수 카운터)
	STSFDG_CN VARCHAR(1000) COMMENT '만족도내용',
	USE_AT CHAR(1) NOT NULL COMMENT '사용여부',
	FRST_REGIST_PNTTM DATETIME NOT NULL COMMENT '최초등록시점',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	FRST_REGISTER_ID VARCHAR(20) NOT NULL COMMENT '최초등록자ID',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	 CONSTRAINT COMTNSTSFDG_PK PRIMARY KEY (STSFDG_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='만족도';


-- TABLE COMTNSYSLOG
CREATE TABLE COMTNSYSLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	JOB_SE_CODE CHAR(3) COMMENT '업무구분코드',
	INSTT_CODE CHAR(7) COMMENT '기관코드',
	OCCRRNC_DE DATETIME COMMENT '발생일',
	RQESTER_IP VARCHAR(23) COMMENT '요청자IP',
	RQESTER_ID VARCHAR(20) COMMENT '요청자ID',
	TRGET_MENU_NM VARCHAR(255) COMMENT '대상메뉴명',
	SVC_NM VARCHAR(255) COMMENT '서비스명',
	METHOD_NM VARCHAR(60) COMMENT '메서드명',
	PROCESS_SE_CODE CHAR(3) COMMENT '처리구분코드',
	PROCESS_CO DECIMAL(10,0) COMMENT '처리수',
	PROCESS_TIME VARCHAR(14) COMMENT '처리시간',
	RSPNS_CODE CHAR(3) COMMENT '응답코드',
	ERROR_SE CHAR(1) COMMENT '오류구분',
	ERROR_CO DECIMAL(10,0) COMMENT '오류수',
	ERROR_CODE CHAR(3) COMMENT '오류코드',
	 CONSTRAINT COMTNSYSLOG_PK PRIMARY KEY (REQUST_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='시스템로그';


-- TABLE COMTNTMPLATINFO
-- 게시판 템플릿 정본(2026-07 재정의): TMPLAT_SE_CODE=렌더엔진코드(COM005), TMPLAT_CONFIG_CN=표현설정(JSON)
CREATE TABLE COMTNTMPLATINFO
   (	TMPLAT_ID CHAR(20) NOT NULL,
	TMPLAT_NM VARCHAR(255) COMMENT '템플릿명',
	TMPLAT_COURS VARCHAR(2000) COMMENT '템플릿경로',
	USE_AT CHAR(1) COMMENT '사용여부',
	TMPLAT_SE_CODE VARCHAR(20) COMMENT '템플릿구분코드(렌더엔진코드, COM005)',
	TMPLAT_CONFIG_CN VARCHAR(2000) COMMENT '템플릿 표현설정(JSON)',
	FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
	FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
	LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
	LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
	 CONSTRAINT COMTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='템플릿';


-- TABLE COMTNUSERLOG
CREATE TABLE COMTNUSERLOG
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	RQESTER_ID VARCHAR(20) NOT NULL COMMENT '요청자ID',
	SVC_NM VARCHAR(255) NOT NULL COMMENT '서비스명',
	METHOD_NM VARCHAR(60) NOT NULL COMMENT '메서드명',
	CREAT_CO DECIMAL(10,0) COMMENT '생성수',
	UPDT_CO DECIMAL(10,0) COMMENT '수정수',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	DELETE_CO DECIMAL(10,0) COMMENT '삭제수',
	OUTPT_CO DECIMAL(10,0) COMMENT '출력수',
	ERROR_CO DECIMAL(10,0) COMMENT '오류수',
	 CONSTRAINT COMTNUSERLOG_PK PRIMARY KEY (OCCRRNC_DE, RQESTER_ID, SVC_NM, METHOD_NM) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자로그';


-- TABLE COMTNWEBLOG (2026-07-20 접속통계 확장: 기기/브라우저/세션 컬럼 + 일자 인덱스)
CREATE TABLE COMTNWEBLOG
   (	REQUST_ID VARCHAR(20) NOT NULL,
	OCCRRNC_DE DATETIME COMMENT '발생일',
	URL VARCHAR(200) COMMENT 'URL',
	RQESTER_ID VARCHAR(20) COMMENT '요청자ID',
	RQESTER_IP VARCHAR(23) COMMENT '요청자IP',
	DVICE_SE VARCHAR(10) COMMENT '접속 기기 구분 (PC/MOBILE/TABLET/BOT/ETC — User-Agent 파싱)',
	BROWSER_NM VARCHAR(30) COMMENT '브라우저명 (Chrome/Edge/Whale/… — User-Agent 파싱)',
	SESN_ID VARCHAR(60) COMMENT '세션 ID 해시 (SHA-256 앞 160비트 hex — 방문 단위 집계용, 비로그인 포함)',
	 CONSTRAINT COMTNWEBLOG_PK PRIMARY KEY (REQUST_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='웹로그';

  CREATE INDEX IX_COMTNWEBLOG_DT ON COMTNWEBLOG (OCCRRNC_DE)
  ;

-- TABLE COMTSSYSLOGSUMMARY
CREATE TABLE COMTSSYSLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	SVC_NM VARCHAR(255) NOT NULL COMMENT '서비스명',
	METHOD_NM VARCHAR(60) NOT NULL COMMENT '메서드명',
	CREAT_CO DECIMAL(10,0) COMMENT '생성수',
	UPDT_CO DECIMAL(10,0) COMMENT '수정수',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	DELETE_CO DECIMAL(10,0) COMMENT '삭제수',
	OUTPT_CO DECIMAL(10,0) COMMENT '출력수',
	ERROR_CO DECIMAL(10,0) COMMENT '오류수',
	 CONSTRAINT COMTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, SVC_NM, METHOD_NM) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='시스템로그요약';


-- TABLE COMTSWEBLOGSUMMARY
CREATE TABLE COMTSWEBLOGSUMMARY
   (	OCCRRNC_DE CHAR(8) NOT NULL,
	URL VARCHAR(200) NOT NULL COMMENT 'URL',
	RDCNT DECIMAL(10,0) COMMENT '조회수',
	 CONSTRAINT COMTSWEBLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE, URL) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='웹로그 요약';


-- TABLE TB_ACT_LOG
CREATE TABLE TB_ACT_LOG
   (	IALOG_NO DECIMAL(38,10) NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL COMMENT '참조 테이블명',
	IREF_NO DECIMAL(38,10) NOT NULL COMMENT '참조 행 번호 (SREF_TABLE 의 PK)',
	SNAME VARCHAR(255) NOT NULL COMMENT '대상 명칭 (규정명 등)',
	STASK VARCHAR(255) NOT NULL COMMENT '작업 종류 (열람/로그인/파일다운 등)',
	SUSER_ID VARCHAR(255) NOT NULL COMMENT '사용자 ID',
	SUSER_NAME VARCHAR(255) NOT NULL COMMENT '사용자명',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYY-MM-DD HH24:MI:SS 문자열)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SINS_IP VARCHAR(255) COMMENT '접속 IP'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='시스템 활동 로그 — 열람/로그인/파일다운 등 사용자 행위 기록 (레거시 이관)';

  CREATE UNIQUE INDEX PK_TB_ACT_LOG ON TB_ACT_LOG (IALOG_NO) 
  ;
ALTER TABLE TB_ACT_LOG ADD CONSTRAINT PK_TB_ACT_LOG PRIMARY KEY (IALOG_NO) ;

-- TABLE TB_ATTACH
CREATE TABLE TB_ATTACH
   (	IATT_NO DECIMAL(38,10) NOT NULL,
	SCATE_ID VARCHAR(255) NOT NULL COMMENT '첨부 카테고리 ID',
	SREF_TABLE VARCHAR(255) NOT NULL COMMENT '참조 테이블명 (TB_PROM/TB_PROV_HTML/TB_REL_* 등)',
	IREF_NO DECIMAL(38,10) NOT NULL COMMENT '참조 행 번호 (SREF_TABLE 의 PK)',
	SPATH VARCHAR(255) NOT NULL COMMENT '파일 저장 경로',
	SNAME VARCHAR(255) NOT NULL COMMENT '원본 파일명',
	SMAPPING VARCHAR(255) NOT NULL COMMENT '저장 매핑 파일명 (디스크 실제 파일)',
	SEXT VARCHAR(255) NOT NULL COMMENT '파일 확장자',
	SMETA VARCHAR(255) NOT NULL COMMENT '메타 정보',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SCONTENTS LONGTEXT COMMENT '텍스트 추출 내용 (CLOB)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '정렬순번',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	ISIZE DECIMAL(38,10) NOT NULL COMMENT '파일 크기 (byte)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	-- (2026-07-30) 다운로드 집계. 상세 이력은 TB_ACT_LOG(STASK='파일 다운로드')가 별도로 남긴다.
	IDOWN_CNT DECIMAL(38,10) DEFAULT 0 NOT NULL COMMENT '다운로드 횟수 - attachDownload/downloadZip 성공 시 +1 (상세 이력은 TB_ACT_LOG STASK=파일 다운로드)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='도메인 첨부파일 — SREF_TABLE+IREF_NO 다형 참조 (BBS/팝업 등 표준모듈은 COMTNFILE 사용)';

  CREATE UNIQUE INDEX PK_TB_ATTACH ON TB_ATTACH (IATT_NO)
  ;
ALTER TABLE TB_ATTACH ADD CONSTRAINT PK_TB_ATTACH PRIMARY KEY (IATT_NO) ;

-- TABLE TB_CATE
CREATE TABLE TB_CATE
   (	ICATE_NO DECIMAL(38,10) NOT NULL,
	SGUBUN_ID VARCHAR(255) NOT NULL COMMENT '구분 ID (공통코드 SGUBUN — 법령/사규 등)',
	SNAME VARCHAR(255) NOT NULL COMMENT '분류명',
	SFULL_NAME VARCHAR(255) NOT NULL COMMENT '전체 경로명',
	ILEVEL DECIMAL(38,10) NOT NULL COMMENT '계층 깊이 (루트=0)',
	IREF DECIMAL(38,10) NOT NULL COMMENT '상위 분류 번호 (루트=0)',
	IREF_LV_1 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 1단계 분류 번호',
	IREF_LV_2 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 2단계 분류 번호',
	IREF_LV_3 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 3단계 분류 번호',
	IREF_LV_4 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 4단계 분류 번호',
	IREF_LV_5 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 5단계 분류 번호',
	IREF_LV_6 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 6단계 분류 번호',
	IREF_LV_7 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 7단계 분류 번호',
	IREF_LV_8 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 8단계 분류 번호',
	IREF_LV_9 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 9단계 분류 번호',
	IREF_LV_10 DECIMAL(38,10) NOT NULL COMMENT '비정규화 조상 경로 — 10단계 분류 번호',
	SDISP_YN VARCHAR(255) NOT NULL COMMENT '표시 여부 (Y/N)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '정렬순번',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정 분류 트리 — 자기참조(IREF) + 비정규화 조상경로(IREF_LV_1~10)';

  CREATE UNIQUE INDEX PK_TB_CATE ON TB_CATE (ICATE_NO) 
  ;
ALTER TABLE TB_CATE ADD CONSTRAINT PK_TB_CATE PRIMARY KEY (ICATE_NO) ;

-- TABLE TB_CATE_OWNER
CREATE TABLE TB_CATE_OWNER
   (	ICATE_NO DECIMAL(38,10) NOT NULL,
	OWNER_TY VARCHAR(10) NOT NULL COMMENT '소유유형: DEPT(부서) / USER(개인)',
	OWNER_ID VARCHAR(50) NOT NULL COMMENT 'DEPT=ORGNZT_ID / USER=ESNTL_ID',
	INHERIT_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '하위분류 상속 여부 Y/N',
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(NOW(),'YYYYMMDDHH24MISS') COMMENT '등록일시 (YYYYMMDDHH24MISS)',
	SINS_ID VARCHAR(50) COMMENT '등록자 ID',
	 CONSTRAINT TB_CATE_OWNER_CK1 CHECK (OWNER_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_CATE_OWNER_PK PRIMARY KEY (ICATE_NO, OWNER_TY, OWNER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='분류별 작성자(소유) 매핑 — 부서/개인 N명';


-- TABLE TB_CATE_READER
CREATE TABLE TB_CATE_READER
   (	ICATE_NO DECIMAL(38,10) NOT NULL,
	READER_TY VARCHAR(10) NOT NULL COMMENT '열람대상 유형 (DEPT=부서 / USER=개인)',
	READER_ID VARCHAR(50) NOT NULL COMMENT '열람대상 ID — DEPT=ORGNZT_ID / USER=ESNTL_ID',
	INHERIT_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '하위분류 상속 여부 (Y/N)',
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(NOW(),'YYYYMMDDHH24MISS') COMMENT '등록일시 (YYYYMMDDHH24MISS)',
	SINS_ID VARCHAR(50) COMMENT '등록자 ID',
	 CONSTRAINT TB_CATE_READER_CK1 CHECK (READER_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_CATE_READER_PK PRIMARY KEY (ICATE_NO, READER_TY, READER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='분류별 열람제한 매핑 - 지정 시 해당 부서/개인만 열람, 미지정=전체 공개';


-- TABLE TB_DOCU
CREATE TABLE TB_DOCU
   (	IDOCU_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM FK) — 이 행이 실제 저장된 회차',
	SITEM VARCHAR(255) NOT NULL COMMENT '항목 식별자 — 앞 2자 유형 (01=별표/02=별지서식/03=별첨)',
	STITLE VARCHAR(255) NOT NULL COMMENT '항목 제목',
	SCONTENTS LONGTEXT COMMENT '본문 (CLOB)',
	SGAEJUNG_TYPE VARCHAR(255) NOT NULL COMMENT '개정 유형 (NEW/MODIFY/NULLIFY 등)',
	SDISP_YN VARCHAR(255) NOT NULL COMMENT '표시 여부 (Y/N)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SSTART_DT VARCHAR(255) NOT NULL COMMENT '적용 시작일',
	SREASON LONGTEXT COMMENT '개정 사유 (CLOB)',
	SSEARCH_TEXT LONGTEXT COMMENT '검색 텍스트 (CLOB)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SGRP_TITLE VARCHAR(255) NOT NULL COMMENT '그룹 제목 (별표/별지서식 등)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='별표/별지서식 — 회차(IPROM_NO) 단위 누적(변경분만 저장) 모델';

  CREATE UNIQUE INDEX PK_TB_DOCU ON TB_DOCU (IDOCU_NO) 
  ;
ALTER TABLE TB_DOCU ADD CONSTRAINT PK_TB_DOCU PRIMARY KEY (IDOCU_NO) ;

-- (2026-07-30 폐기) TABLE TB_DOCU_FILE — 신규 DB·레거시 레거시 DB 양쪽 모두 0행이라 DROP.
--   별표/별지서식의 개별 첨부는 관련자료 축을 재사용한다:
--     TB_REL_VRSN(SFLAG='DOCUMENT', SFULL_ITEM=TB_DOCU.SITEM) → TB_REL_FILE → TB_ATTACH
--   삭제 연쇄는 TRG_DEL_DOCU(13_triggers_functions.sql)가 담당.

-- TABLE TB_FAVOR
CREATE TABLE TB_FAVOR
   (	IFAVOR_NO DECIMAL(38,10) NOT NULL,
	SGUBUN VARCHAR(255) NOT NULL COMMENT '즐겨찾기 구분 (PROVISION=조문/FULLTEXT=전문/PROM=규정)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '법령 논리 ID (TB_PROM.ILAW_ID)',
	SITEM VARCHAR(255) NOT NULL COMMENT '조항 식별자 (본문 단위 이동 키)',
	SDESC VARCHAR(4000) NOT NULL COMMENT '메모/설명',
	SUSER_ID VARCHAR(255) NOT NULL COMMENT '사용자 ID',
	SUSER_NAME VARCHAR(255) NOT NULL COMMENT '사용자명',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	ISEEN_LAW_NO DECIMAL(38,10) COMMENT '마지막 확인 회차번호(TB_PROM.ILAW_NO) — 홈 개정 소식 알림 판정 기준. 등록·뷰어 열람 시 갱신, NULL=알림 제외'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자 즐겨찾기 — ILAW_ID+SITEM 으로 규정/조항 참조, 사용자별 격리';

  CREATE UNIQUE INDEX PK_TB_FAVOR ON TB_FAVOR (IFAVOR_NO)
  ;
ALTER TABLE TB_FAVOR ADD CONSTRAINT PK_TB_FAVOR PRIMARY KEY (IFAVOR_NO) ;

-- TABLE TB_GAEJUNG
CREATE TABLE TB_GAEJUNG
   (	IGAEJUNG_NO DECIMAL(38,10) NOT NULL,
	SNAME VARCHAR(255) NOT NULL COMMENT '개정구분명 (제정/일부개정/폐지 등)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '정렬순번',
	SDIFF_YN VARCHAR(255) NOT NULL COMMENT '본문 비교(diff) 대상 여부 — N=제정 등 비교할 이전본 없음',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='개정구분 마스터 (제정/일부개정/폐지 등)';

  CREATE UNIQUE INDEX PK_TB_GAEJUNG ON TB_GAEJUNG (IGAEJUNG_NO) 
  ;
ALTER TABLE TB_GAEJUNG ADD CONSTRAINT PK_TB_GAEJUNG PRIMARY KEY (IGAEJUNG_NO) ;

-- TABLE TB_GAEJUNG_LOG
CREATE TABLE TB_GAEJUNG_LOG
   (	IPROM_NO DECIMAL(38,10) NOT NULL,
	IBUSEO_NO DECIMAL(38,10) NOT NULL COMMENT '담당부서 번호',
	IUSER_NO DECIMAL(38,10) NOT NULL COMMENT '작업자 번호',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYY-MM-DD HH24:MI:SS 문자열)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정 등록·수정 작업 로그 — 회차 저장 시점에 자동 1행 기록';

  CREATE UNIQUE INDEX PK_TB_GAEJUNG_LOG ON TB_GAEJUNG_LOG (IPROM_NO) 
  ;
ALTER TABLE TB_GAEJUNG_LOG ADD CONSTRAINT PK_TB_GAEJUNG_LOG PRIMARY KEY (IPROM_NO) ;

-- TABLE TB_GUBUN_READER
CREATE TABLE TB_GUBUN_READER
   (	SGUBUN_ID VARCHAR(50) NOT NULL,
	READER_TY VARCHAR(10) NOT NULL COMMENT '열람대상 유형 (DEPT=부서 / USER=개인)',
	READER_ID VARCHAR(50) NOT NULL COMMENT '열람대상 ID — DEPT=ORGNZT_ID / USER=ESNTL_ID',
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(NOW(),'YYYYMMDDHH24MISS') COMMENT '등록일시 (YYYYMMDDHH24MISS)',
	SINS_ID VARCHAR(50) COMMENT '등록자 ID',
	 CONSTRAINT TB_GUBUN_READER_CK1 CHECK (READER_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_GUBUN_READER_PK PRIMARY KEY (SGUBUN_ID, READER_TY, READER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='구분(최상위) 단위 열람제한 매핑 — 지정 시 해당 부서/개인만 열람, 미지정=전체 공개';


-- TABLE TB_LAWQUEST
CREATE TABLE TB_LAWQUEST
   (	NO DECIMAL(38,0) NOT NULL,
	ID VARCHAR(30) NOT NULL COMMENT '작성자 ID (ESNTL_ID)',
	NAME VARCHAR(30) NOT NULL COMMENT '작성자명',
	YEAR CHAR(4) NOT NULL COMMENT '작성연도 (YYYY)',
	TYPE VARCHAR(20) NOT NULL COMMENT '자문유형 (일반/개발/비축/건설 등)',
	SOSOK VARCHAR(30) COMMENT '의뢰부서',
	GIGWAN CHAR(30) COMMENT '자문기관/로펌',
	LAWER VARCHAR(50) COMMENT '담당 변호사',
	GUMAEK DECIMAL(10,0) NOT NULL COMMENT '자문 금액 (원)',
	ILJA1 CHAR(8) COMMENT '의뢰일자 (YYYYMMDD)',
	ILJA2 CHAR(8) COMMENT '회신일자 (YYYYMMDD)',
	SUBJECT VARCHAR(200) NOT NULL COMMENT '제목',
	QUEST_CON LONGTEXT COMMENT '질의내용 (CLOB)',
	RESPO_CON LONGTEXT COMMENT '회신내용 (CLOB) — 답변권한자 작성',
	WRITEDAY DATETIME NOT NULL COMMENT '작성일',
	READNUM DECIMAL(38,0) NOT NULL COMMENT '조회수',
	BUGET VARCHAR(200) COMMENT '예산',
	PUBLIC_YN VARCHAR(10) DEFAULT '2' COMMENT '공개구분 (1=공개/2=비공개)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='법령질의 — 외부 로펌 법률자문 의뢰·회신 기록 (구 COUNTLAW 개명)';

  CREATE UNIQUE INDEX PK_COUNTLAW ON TB_LAWQUEST (NO) 
  ;
ALTER TABLE TB_LAWQUEST ADD CONSTRAINT PK_COUNTLAW PRIMARY KEY (NO) ;

-- TABLE TB_LAWQUEST_ADMIN
CREATE TABLE TB_LAWQUEST_ADMIN
   (	ADMIN_SABUN VARCHAR(20) NOT NULL,
	ADMIN_NAME VARCHAR(30) COMMENT '답변권한자 성명'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='법령질의 답변권한자 레지스트리 — 등록 사번만 회신 작성 가능';


-- TABLE TB_MEMO
CREATE TABLE TB_MEMO
   (	IMEMO_NO DECIMAL(38,10) NOT NULL,
	SGUBUN VARCHAR(255) NOT NULL COMMENT '메모 구분 (USER=사용자/BUSEO=부서/PROM=규정)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '법령 논리 ID (TB_PROM.ILAW_ID)',
	SITEM VARCHAR(255) NOT NULL COMMENT '조항 식별자',
	SDESC VARCHAR(4000) NOT NULL COMMENT '메모 내용',
	SUSER_ID VARCHAR(255) NOT NULL COMMENT '사용자 ID',
	SUSER_NAME VARCHAR(255) NOT NULL COMMENT '사용자명',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SBUSEO_ID VARCHAR(255) NOT NULL COMMENT '작성 시점 부서 ID',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='개인 메모 — ILAW_ID+SITEM 으로 규정 조항에 부착';

  CREATE UNIQUE INDEX PK_TB_MEMO ON TB_MEMO (IMEMO_NO) 
  ;
ALTER TABLE TB_MEMO ADD CONSTRAINT PK_TB_MEMO PRIMARY KEY (IMEMO_NO) ;

-- TABLE TB_PROM
CREATE TABLE TB_PROM
   (	IPROM_NO DECIMAL(38,10) NOT NULL,
	SGUBUN_ID VARCHAR(255) NOT NULL COMMENT '구분 ID (공통코드 SGUBUN — 법령/사규 등)',
	ICATE_NO DECIMAL(38,10) NOT NULL COMMENT '분류 번호 (TB_CATE FK)',
	IGAEJUNG_NO DECIMAL(38,10) NOT NULL COMMENT '개정구분 번호 (TB_GAEJUNG FK)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '법령 논리 ID — 같은 규정의 개정 회차들을 묶는 키',
	ILAW_NO DECIMAL(38,10) NOT NULL COMMENT '개정 회차 번호',
	STITLE VARCHAR(255) NOT NULL COMMENT '규정 제목',
	SNUM VARCHAR(255) NOT NULL COMMENT '규정 번호 표기 (예: 법률 제19999호)',
	SPROM_DT VARCHAR(255) NOT NULL COMMENT '공포(개정)일자 (YYYY-MM-DD)',
	SSTART_DT VARCHAR(255) NOT NULL COMMENT '시행일자',
	SNULL_DT VARCHAR(255) NOT NULL COMMENT '폐지일자',
	SNULL_DT_PEND VARCHAR(255),
	SURL VARCHAR(255) NOT NULL COMMENT '외부 원문 URL',
	SPROV_FG VARCHAR(255) NOT NULL COMMENT '본문 형식 플래그 (VERSION/VIEWER 등)',
	SPROV_STYLE_CD VARCHAR(255) NOT NULL COMMENT '본문 스타일 코드',
	SPROV_FILE_NO VARCHAR(255) NOT NULL COMMENT 'PDF 뷰어 참조 파일 번호',
	SDISP_YN VARCHAR(255) NOT NULL COMMENT '표시 여부 (Y/N — N=연혁 감춤)',
	SEXISTING_YN VARCHAR(255) NOT NULL COMMENT '현행 여부 — 같은 ILAW_ID 중 1건만 Y',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SGAEJUNG LONGTEXT COMMENT '개정내용 (CLOB)',
	SREASON LONGTEXT COMMENT '개정이유 (CLOB)',
	SBYLAW LONGTEXT COMMENT '부칙 (CLOB)',
	SSEARCH_TEXT LONGTEXT COMMENT '검색 텍스트 (CLOB)',
	ISEQ DECIMAL(38,10) DEFAULT 0 NOT NULL COMMENT '분류 내 정렬순번',
	SPREAMBLE LONGTEXT COMMENT '전문(서문) (CLOB)',
	SEXT_DISP_YN VARCHAR(255) NOT NULL COMMENT '외부 열람 요청 공개 여부 (Y/N)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	IBUSEO_NO DECIMAL(38,10) NOT NULL COMMENT '담당부서 번호',
	SSTATUS VARCHAR(255) NOT NULL COMMENT '상태',
	SDPL_ITEM_YN VARCHAR(255) NOT NULL COMMENT '중복 항목 여부 (Y/N)',
	-- (2026-07-30 폐기) SSTOR_FILE_YN/DT/NM/PATH/DOC_NM/HWP_NM/PDF_NM 7종 —
	--   레거시 은 회차별 원본 문서(DOC/HWP/PDF)를 미리 만들어 보관했으나 RLMS 는 저장하지 않는다.
	--   본문 문서는 /rlms/fulltext/exportProm.do 가 요청 시 PDF/DOCX/HWPX 로 생성(조 범위 발췌 포함).
	SREL_FILE_VIEW_YN VARCHAR(255) COMMENT '관련 파일 뷰 표시 여부 (Y/N)',
	SSUB_TITLE VARCHAR(255) COMMENT '부제목',
	SPARTY VARCHAR(4000) COMMENT '계약 당사자',
	SORDERIDX DECIMAL(3,0) DEFAULT 50 COMMENT '정렬 우선순위 (기본 50)',
	SGAEJUNG_CODE VARCHAR(20) COMMENT '개정구분 코드 (GJ+IGAEJUNG_NO 파생값)',
	SBUSEO_ORGNZT_ID CHAR(20) COMMENT '주관부서 조직 ID (ORG_+IBUSEO_NO 파생값)',
	SSTSFDG_YN VARCHAR(255) DEFAULT 'N'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정 회차(공포) 마스터 — 법령/사규 등 규정의 제·개정 회차 단위 행';

  CREATE UNIQUE INDEX PK_TB_PROM ON TB_PROM (IPROM_NO) 
  ;
ALTER TABLE TB_PROM ADD CONSTRAINT PK_TB_PROM PRIMARY KEY (IPROM_NO) ;

-- TABLE TB_PROM_ACT_LOG
CREATE TABLE TB_PROM_ACT_LOG
   (	IPALOG_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM 참조)',
	SSYS_ID VARCHAR(255) NOT NULL COMMENT '시스템 ID (항상 레거시)',
	SREF_TABLE VARCHAR(255) NOT NULL COMMENT '참조 테이블명',
	IREF_NO VARCHAR(255) NOT NULL COMMENT '참조 행 번호 (SREF_TABLE 의 PK)',
	SACT_TYPE VARCHAR(255) NOT NULL COMMENT '액션 타입 (INSERT/UPDATE/DELETE/APPROVE/REJECT)',
	SACT_NM VARCHAR(255) COMMENT '액션명',
	SACT_DC VARCHAR(4000) NOT NULL COMMENT '액션 설명',
	SUSER_ID VARCHAR(255) NOT NULL COMMENT '사용자 ID',
	SUSER_NM VARCHAR(255) NOT NULL COMMENT '사용자명',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYY-MM-DD HH24:MI:SS 문자열)',
	IPWRK_NO DECIMAL(38,10) NOT NULL COMMENT '워크 번호 (TB_PROM_WRK 참조, 미연결=0)',
	SFIELD_LOG LONGTEXT COMMENT '필드 변경 내역 (CLOB — before/after 직렬화)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정 편집·승인 액션 감사 로그 — SREF_TABLE+IREF_NO 다형 참조';

  CREATE UNIQUE INDEX PK_TB_PROM_ACT_LOG ON TB_PROM_ACT_LOG (IPALOG_NO) 
  ;
ALTER TABLE TB_PROM_ACT_LOG ADD CONSTRAINT PK_TB_PROM_ACT_LOG PRIMARY KEY (IPALOG_NO) ;

-- TABLE TB_PROM_STSFDG (규정 만족도 조사 — 회차별 1인 1회, 2026-07-20 rlms_prom_stsfdg.sql)
CREATE TABLE TB_PROM_STSFDG
   (	IPROM_NO DECIMAL(38,10) NOT NULL,
	SINS_ID VARCHAR(50) NOT NULL,
	ISTSFDG DECIMAL(1,0) NOT NULL,
	SSTSFDG_CN VARCHAR(1000),
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(NOW(),'YYYYMMDDHH24MISS'),
	SUPD_DT VARCHAR(14),
	 CONSTRAINT TB_PROM_STSFDG_CK1 CHECK (ISTSFDG BETWEEN 1 AND 5),
	 CONSTRAINT TB_PROM_STSFDG_PK PRIMARY KEY (IPROM_NO, SINS_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- TABLE TB_PROM_MAP
CREATE TABLE TB_PROM_MAP
   (	IPMAP_NO DECIMAL(38,10) NOT NULL,
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (단일 시스템 — 미사용, NULL 저장. 필터 금지)',
	SNAME VARCHAR(255) NOT NULL COMMENT '노드명 (폴더명 또는 규정 제목)',
	SFULL_NAME VARCHAR(255) NOT NULL COMMENT '전체 경로명',
	SPROM_YN VARCHAR(255) NOT NULL COMMENT '규정 여부 (Y=규정 leaf / N=폴더)',
	ILEVEL DECIMAL(38,10) NOT NULL COMMENT '계층 깊이 (루트=0)',
	IREF DECIMAL(38,10) NOT NULL COMMENT '상위 노드 번호 (루트=0)',
	SDISP_YN VARCHAR(255) NOT NULL COMMENT '표시 여부 (Y/N)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '정렬순번',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '참조 회차 번호 (규정 leaf 만, 폴더=0)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정맵(기능별분류) 트리 — 폴더(SPROM_YN=N)와 규정 leaf(SPROM_YN=Y), IREF 자기참조';

  CREATE UNIQUE INDEX PK_TB_PROM_MAP ON TB_PROM_MAP (IPMAP_NO) 
  ;
ALTER TABLE TB_PROM_MAP ADD CONSTRAINT PK_TB_PROM_MAP PRIMARY KEY (IPMAP_NO) ;

-- TABLE TB_PROM_WRK
CREATE TABLE TB_PROM_WRK
   (	IPWRK_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM 참조)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SSTATUS VARCHAR(255) NOT NULL COMMENT '상태 (편집중/승인요청/승인반려/승인완료/수정권한요청 등 한글 정본)',
	SUSER_ID VARCHAR(255) NOT NULL COMMENT '신청자/처리자 ID',
	SUSER_NM VARCHAR(255) NOT NULL COMMENT '신청자/처리자명',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SREASON LONGTEXT COMMENT '사유/의견 (CLOB)',
	SACT_NM VARCHAR(255) COMMENT '작업종류 (제정편집/개정편집/수정권한)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정 승인 워크플로 — 회차별 상태(편집중/승인요청/승인완료 등) 이력 행';

  CREATE UNIQUE INDEX PK_TB_PROM_WRK ON TB_PROM_WRK (IPWRK_NO) 
  ;
ALTER TABLE TB_PROM_WRK ADD CONSTRAINT PK_TB_PROM_WRK PRIMARY KEY (IPWRK_NO) ;

-- TABLE TB_PROV_HTML
CREATE TABLE TB_PROV_HTML
   (	IPHTML_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM FK)',
	SITEM VARCHAR(255) NOT NULL COMMENT '조항 식별자 (예: 제3조)',
	STITLE VARCHAR(255) NOT NULL COMMENT '조항 제목',
	SCONTENTS LONGTEXT COMMENT '조문 본문 HTML (CLOB)',
	SGAEJUNG_TYPE VARCHAR(255) NOT NULL COMMENT '개정 유형 (신규/개정/삭제 등)',
	SDISP_YN VARCHAR(255) NOT NULL COMMENT '표시 여부 (Y/N)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SSTART_DT VARCHAR(255) NOT NULL COMMENT '적용 시작일',
	SREASON LONGTEXT COMMENT '개정 사유 (CLOB)',
	SSEARCH_TEXT LONGTEXT COMMENT '검색 텍스트 (CLOB)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='조문 HTML 본문 — 회차별 조 단위 본문 1행 (저장 시 TB_PROV_VRSN 으로 분해)';

  CREATE UNIQUE INDEX PK_TB_PROV_HTML ON TB_PROV_HTML (IPHTML_NO) 
  ;
ALTER TABLE TB_PROV_HTML ADD CONSTRAINT PK_TB_PROV_HTML PRIMARY KEY (IPHTML_NO) ;

-- TABLE TB_PROV_TEXT_HST
CREATE TABLE TB_PROV_TEXT_HST
   (	IPTHST_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM 참조)',
	SUSER_ID VARCHAR(255) COMMENT '저장 사용자 ID',
	SINS_DT VARCHAR(255) COMMENT '등록일시 (문자열)',
	STEXT LONGTEXT COMMENT '본문 텍스트 스냅샷 (CLOB)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='회차 본문 일괄편집 이력 — 일괄저장 직전 본문 텍스트 스냅샷';

  CREATE UNIQUE INDEX PK_TB_PROV_TEXT_HST ON TB_PROV_TEXT_HST (IPTHST_NO) 
  ;
ALTER TABLE TB_PROV_TEXT_HST ADD CONSTRAINT PK_TB_PROV_TEXT_HST PRIMARY KEY (IPTHST_NO) ;

-- TABLE TB_PROV_VRSN
CREATE TABLE TB_PROV_VRSN
   (	IPVRSN_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM FK)',
	SFULL_ITEM VARCHAR(255) NOT NULL COMMENT '조문 전체항목 경로 (예: 1조-1항-1호) — 회차간 비교 조인 키',
	SITEM VARCHAR(255) NOT NULL COMMENT '상위 단위 (예: 1조)',
	SSUB_ITEM VARCHAR(255) NOT NULL COMMENT '하위 단위 (예: 1항-1호)',
	SSTYLE_ID VARCHAR(255) NOT NULL COMMENT '스타일 코드',
	SUNIT_TYPE VARCHAR(255) NOT NULL COMMENT '단위 유형 (조/항/호/문장/줄 등)',
	SNATIVE_TYPE VARCHAR(255) NOT NULL COMMENT '원본 단위 유형',
	ILEVEL DECIMAL(38,10) NOT NULL COMMENT '계층 깊이',
	IINDEX DECIMAL(38,10) NOT NULL COMMENT '같은 레벨 내 순서',
	STITLE VARCHAR(500) COMMENT '단위 제목',
	SREASON LONGTEXT COMMENT '개정 사유 (CLOB)',
	SCONTENTS LONGTEXT COMMENT '단위 본문 (CLOB — Oracle Text 인덱스 대상)',
	SGAEJUNG_TYPE VARCHAR(255) NOT NULL COMMENT '개정 유형 (신규/개정/삭제)',
	SDISP_YN VARCHAR(255) NOT NULL COMMENT '표시 여부 (N=삭제 tombstone)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	SSTART_DT VARCHAR(255) NOT NULL COMMENT '적용 시작일',
	SUSER_MODIFIED_YN VARCHAR(255) NOT NULL COMMENT '사용자 수정 여부 (Y/N)',
	SMOVE_FULL_ITEM VARCHAR(255) COMMENT '이동된 경우 새 전체항목 경로',
	SSEARCH_TEXT LONGTEXT COMMENT '검색 텍스트 (CLOB)',
	SGAEJUNG_HIDE_YN VARCHAR(255) COMMENT '개정표시 숨김 여부 (Y/N)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='조문 버전(단위 행) — 본문을 조/항/호 단위로 분해 저장, SFULL_ITEM 으로 회차간 비교';

  CREATE UNIQUE INDEX PK_TB_PROV_VRSN ON TB_PROV_VRSN (IPVRSN_NO) 
  ;
ALTER TABLE TB_PROV_VRSN ADD CONSTRAINT PK_TB_PROV_VRSN PRIMARY KEY (IPVRSN_NO) ;

-- TABLE TB_READ_DUTY (필수 열람 지정 — 2026-07-28 rlms_read_duty.sql)
CREATE TABLE TB_READ_DUTY
   (	IDUTY_NO DECIMAL(38,10) NOT NULL,
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '대상 법령 논리 ID (TB_PROM.ILAW_ID)',
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '대상 회차 (TB_PROM.IPROM_NO — 승인된 개정 회차, UNIQUE)',
	SALL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '전사 대상 여부 Y/N — Y면 TGT 행 무시하고 전 사용자 대상',
	SDUE_DT VARCHAR(8) COMMENT '열람 기한 YYYYMMDD — NULL=무기한, 경과 시 홈 카드 강조',
	SINS_ID VARCHAR(50) COMMENT '지정자 로그인 ID',
	SINS_NM VARCHAR(50) COMMENT '지정자명 (표시 스냅샷)',
	SINS_DT VARCHAR(14) DEFAULT TO_CHAR(NOW(),'YYYYMMDDHH24MISS') COMMENT '지정 일시 (YYYYMMDDHH24MISS 문자열)',
	 CONSTRAINT TB_READ_DUTY_CK1 CHECK (SALL_YN IN ('Y','N')),
	 CONSTRAINT TB_READ_DUTY_PK PRIMARY KEY (IDUTY_NO) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='필수 열람 지정 — 승인 회차에 열람 의무 대상(전사/부서/개인) 지정, 회차당 1건';


-- TABLE TB_READ_DUTY_TGT (필수 열람 대상 행 — DEPT/USER 혼합)
CREATE TABLE TB_READ_DUTY_TGT
   (	IDUTY_NO DECIMAL(38,10) NOT NULL,
	STGT_TY VARCHAR(10) NOT NULL COMMENT '대상 유형: DEPT(부서) / USER(개인)',
	STGT_ID VARCHAR(50) NOT NULL COMMENT 'DEPT=COMVNUSERMASTER.ORGNZT_ID / USER=ESNTL_ID',
	 CONSTRAINT TB_READ_DUTY_TGT_CK1 CHECK (STGT_TY IN ('DEPT','USER')),
	 CONSTRAINT TB_READ_DUTY_TGT_PK PRIMARY KEY (IDUTY_NO, STGT_TY, STGT_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='필수 열람 대상 행 — DEPT(부서)/USER(개인) 혼합 지정 (TB_CATE_READER 패턴)';


-- TABLE TB_READ_DUTY_CHK (필수 열람 확인 — 열람 자동/숙지 버튼 2단계)
CREATE TABLE TB_READ_DUTY_CHK
   (	IDUTY_NO DECIMAL(38,10) NOT NULL,
	SUSER_ID VARCHAR(50) NOT NULL COMMENT '확인자 ESNTL_ID (COMVNUSERMASTER)',
	SUSER_NM VARCHAR(50) COMMENT '확인자명 스냅샷 (퇴사/개명에도 증빙 보존)',
	SORGNZT_ID VARCHAR(50) COMMENT '확인 시점 부서 ORGNZT_ID 스냅샷 (부서 이동에도 증빙 보존)',
	SREAD_DT VARCHAR(14) COMMENT '최초 열람 일시 (뷰어 본문 열람 시 자동, YYYYMMDDHH24MISS)',
	SCONF_DT VARCHAR(14) COMMENT '숙지 확인 일시 (버튼 클릭 — 최종 증빙, YYYYMMDDHH24MISS)',
	 CONSTRAINT TB_READ_DUTY_CHK_PK PRIMARY KEY (IDUTY_NO, SUSER_ID) ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='필수 열람 확인 — 2단계(열람 자동/숙지 버튼), 증빙 영구 보존';


-- TABLE TB_REL_DMN_LNK
CREATE TABLE TB_REL_DMN_LNK
   (	IRDLNK_NO DECIMAL(38,10) NOT NULL,
	SFLAG VARCHAR(255) NOT NULL COMMENT '연계 대상 유형 (PROMULGATION/PROVISION/DOCUMENT)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '연계 대상 법령 논리 ID',
	SFULL_ITEM VARCHAR(255) NOT NULL COMMENT '조문 단위 연계 시 전체항목 코드 (없으면 0)',
	STITLE VARCHAR(255) NOT NULL COMMENT '표시 제목',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '표시 순서',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	ILAW_NO DECIMAL(38,10) NOT NULL COMMENT '연계 대상 개정 회차 번호',
	SAWS_LST_YN VARCHAR(255) NOT NULL COMMENT '항상 최신 적용 여부 — Y=현행 회차로 자동 점프',
	IRVRSN_NO VARCHAR(255) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK — VARCHAR2 특이 설계)',
	SFILE_ITEM DECIMAL(38,10) NOT NULL COMMENT '별표 연계 식별 (기본 0)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 규정/조문 연계(DOMAIN_LINK) 상세';

  CREATE UNIQUE INDEX PK_TB_REL_DMN_LNK ON TB_REL_DMN_LNK (IRDLNK_NO) 
  ;
ALTER TABLE TB_REL_DMN_LNK ADD CONSTRAINT PK_TB_REL_DMN_LNK PRIMARY KEY (IRDLNK_NO) ;

-- TABLE TB_REL_EXCL_LNK
CREATE TABLE TB_REL_EXCL_LNK
   (	IRELNK_NO DECIMAL(38,10) NOT NULL,
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SFLAG VARCHAR(255) NOT NULL COMMENT '제외 유형 (full_text_gubun/full_text_category/full_text_leaf)',
	SGUBUN_ID VARCHAR(255) COMMENT '제외할 구분 (SFLAG=full_text_gubun)',
	ICATE_NO DECIMAL(38,10) COMMENT '제외할 분류 번호 (SFLAG=full_text_category)',
	ILAW_ID DECIMAL(38,10) COMMENT '제외할 특정 법령 (SFLAG=full_text_leaf)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	IEXCL_LAW_ID DECIMAL(38,10) NOT NULL COMMENT '제외범위 소유 법령 — 자동링크 처리 대상 법령'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='조문 자동링크 제외범위 — 구분/분류/특정규정 3종(SFLAG)';

  CREATE UNIQUE INDEX PK_TB_REL_EXCL_LNK ON TB_REL_EXCL_LNK (IRELNK_NO) 
  ;
ALTER TABLE TB_REL_EXCL_LNK ADD CONSTRAINT PK_TB_REL_EXCL_LNK PRIMARY KEY (IRELNK_NO) ;

-- TABLE TB_REL_FILE
CREATE TABLE TB_REL_FILE
   (	IRFILE_NO DECIMAL(38,10) NOT NULL,
	IATT_NO DECIMAL(38,10) NOT NULL COMMENT '첨부 번호 (TB_ATTACH FK)',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	SCATE VARCHAR(255) NOT NULL COMMENT '자유 분류 라벨 (일반/전문/해석/설명 등)',
	IRVRSN_NO DECIMAL(38,10) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK)',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SVIEW_YN VARCHAR(255) DEFAULT 'N' COMMENT '미리보기 가능 여부 (확장자 기반 Y/N)',
	SVIEW_CMPLT_YN VARCHAR(255) DEFAULT 'N' COMMENT '미리보기 변환 완료 여부 (Y/N)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 일반 파일 상세';

  CREATE UNIQUE INDEX PK_TB_REL_FILE ON TB_REL_FILE (IRFILE_NO) 
  ;
ALTER TABLE TB_REL_FILE ADD CONSTRAINT PK_TB_REL_FILE PRIMARY KEY (IRFILE_NO) ;

-- TABLE TB_REL_HTML
CREATE TABLE TB_REL_HTML
   (	IRHTML_NO DECIMAL(38,10) NOT NULL,
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SHTML LONGTEXT COMMENT 'HTML 본문 (CLOB)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	IRVRSN_NO DECIMAL(38,10) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK)',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 직접작성 HTML 표/본문 상세';

  CREATE UNIQUE INDEX PK_TB_REL_HTML ON TB_REL_HTML (IRHTML_NO) 
  ;
ALTER TABLE TB_REL_HTML ADD CONSTRAINT PK_TB_REL_HTML PRIMARY KEY (IRHTML_NO) ;

-- TABLE TB_REL_IMG
CREATE TABLE TB_REL_IMG
   (	IRIMG_NO DECIMAL(38,10) NOT NULL,
	IATT_NO DECIMAL(38,10) NOT NULL COMMENT '첨부 번호 (TB_ATTACH FK)',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	IRVRSN_NO DECIMAL(38,10) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK)',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 이미지 첨부 상세';

  CREATE UNIQUE INDEX PK_TB_REL_IMG ON TB_REL_IMG (IRIMG_NO) 
  ;
ALTER TABLE TB_REL_IMG ADD CONSTRAINT PK_TB_REL_IMG PRIMARY KEY (IRIMG_NO) ;

-- TABLE TB_REL_LNK
CREATE TABLE TB_REL_LNK
   (	IRLINK_NO DECIMAL(38,10) NOT NULL,
	SCATE VARCHAR(255) NOT NULL COMMENT '자유 분류 라벨 (기본 URL)',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SURL VARCHAR(255) NOT NULL COMMENT '링크 URL',
	IREF_NO DECIMAL(38,10) NOT NULL COMMENT '외부 시스템 참조 행 번호 (기본 0)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '표시 순서',
	IRVRSN_NO DECIMAL(38,10) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK)',
	SREF_TABLE VARCHAR(255) NOT NULL COMMENT '외부 시스템 참조 테이블명',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 외부 URL 링크 상세';

  CREATE UNIQUE INDEX PK_TB_REL_LNK ON TB_REL_LNK (IRLINK_NO) 
  ;
ALTER TABLE TB_REL_LNK ADD CONSTRAINT PK_TB_REL_LNK PRIMARY KEY (IRLINK_NO) ;

-- TABLE TB_REL_ORGN
CREATE TABLE TB_REL_ORGN
   (	IRORGN_NO DECIMAL(38,10) NOT NULL,
	IATT_NO DECIMAL(38,10) NOT NULL COMMENT '첨부 번호 (TB_ATTACH FK)',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	IRVRSN_NO DECIMAL(38,10) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK)',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 원본(정본) 파일 상세, 다운로드 허용은 카테고리 SORGNDOWN_YN 정책으로 통제';

  CREATE UNIQUE INDEX PK_TB_REL_ORGN ON TB_REL_ORGN (IRORGN_NO) 
  ;
ALTER TABLE TB_REL_ORGN ADD CONSTRAINT PK_TB_REL_ORGN PRIMARY KEY (IRORGN_NO) ;

-- TABLE TB_REL_VRSN
CREATE TABLE TB_REL_VRSN
   (	IRVRSN_NO DECIMAL(38,10) NOT NULL,
	IPROM_NO DECIMAL(38,10) NOT NULL COMMENT '회차 번호 (TB_PROM FK)',
	ICTNS_ID DECIMAL(38,10) NOT NULL COMMENT '콘텐츠 ID — 회차 간 동일 자료 누적 추적 키',
	SVRSN_YN VARCHAR(255) NOT NULL COMMENT '버전(회차별 분기) 여부 (Y/N)',
	STABLE VARCHAR(255) NOT NULL COMMENT '실제 리소스 테이블명 (TB_REL_FILE/TB_REL_WORD/TB_REL_HTML/TB_REL_LNK 등)',
	SFLAG VARCHAR(255) NOT NULL COMMENT '부착 컨텍스트 (PROMULGATION=규정 전체/PROVISION=조문/DOCUMENT=별표)',
	SFULL_ITEM VARCHAR(255) NOT NULL COMMENT '조문/별표 전체항목 코드 (SFLAG 가 PROVISION/DOCUMENT 일 때)',
	STITLE VARCHAR(4000) NOT NULL COMMENT '제목 (우측 패널 라벨)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '표시 순서',
	SURL VARCHAR(255) COMMENT '외부 URL (TB_REL_LNK 용, 그 외 공백)',
	IRVCATE_NO DECIMAL(38,10) NOT NULL COMMENT '자료 카테고리 번호 (TB_REL_VRSN_CATE FK)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	IRVCATE_NM VARCHAR(100) DEFAULT '미선택' COMMENT '카테고리명 캐시 (기본 미선택)',
	IRVCATE_ODR DECIMAL(10,0) DEFAULT 0 COMMENT '카테고리 순서 캐시'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 마스터(허브) — 회차/조문에 붙은 자료 1건=1행, STABLE 이 실제 상세 테이블';

  CREATE UNIQUE INDEX PK_TB_REL_VRSN ON TB_REL_VRSN (IRVRSN_NO) 
  ;
ALTER TABLE TB_REL_VRSN ADD CONSTRAINT PK_TB_REL_VRSN PRIMARY KEY (IRVRSN_NO) ;

-- TABLE TB_REL_VRSN_CATE
CREATE TABLE TB_REL_VRSN_CATE
   (	IRVCATE_NO DECIMAL(38,10) NOT NULL,
	STITLE VARCHAR(255) NOT NULL COMMENT '카테고리명 (본문/붙임/양식 등)',
	ISEQ DECIMAL(38,10) NOT NULL COMMENT '표시 순서',
	SHIDE_DT VARCHAR(255) NOT NULL COMMENT '숨김 시작일 (0=활성 / YYYYMMDD=해당일부터 숨김)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '법령 논리 ID',
	STEMP VARCHAR(255) COMMENT '회차 매핑 (IPROM_NO 값, 임시등록 시 임시 키)',
	SORGNDOWN_YN VARCHAR(255) DEFAULT 'Y' COMMENT '사용자 화면 원본 다운로드 허용 여부 (Y/N)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 카테고리(본문/붙임/양식 등) — 회차+법령 단위 그룹 헤더';

  CREATE UNIQUE INDEX PK_TB_REL_VRSN_CATE ON TB_REL_VRSN_CATE (IRVCATE_NO) 
  ;
ALTER TABLE TB_REL_VRSN_CATE ADD CONSTRAINT PK_TB_REL_VRSN_CATE PRIMARY KEY (IRVCATE_NO) ;

-- TABLE TB_REL_WORD
CREATE TABLE TB_REL_WORD
   (	IRWORD_NO DECIMAL(38,10) NOT NULL,
	IATT_NO DECIMAL(38,10) NOT NULL COMMENT '첨부 번호 (TB_ATTACH FK)',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SHTML LONGTEXT COMMENT '변환 HTML 본문 (CLOB)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (YYYYMMDDHHMMSS)',
	IRVRSN_NO DECIMAL(38,10) NOT NULL COMMENT '관련자료 마스터 번호 (TB_REL_VRSN FK)',
	STYPE VARCHAR(255) COMMENT '문서 유형 라벨',
	SDEL_YN VARCHAR(255) NOT NULL COMMENT '삭제 여부 (Y/N 소프트삭제)',
	SSEARCH_TEXT LONGTEXT COMMENT '검색 텍스트 (CLOB)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	SHTML_PATH VARCHAR(255) COMMENT '변환 HTML 디스크 경로',
	SSEARCH_TEXT_PATH VARCHAR(255) COMMENT '검색 텍스트 디스크 경로',
	SCLOB_FILE_YN VARCHAR(255) DEFAULT 'N' COMMENT 'SHTML 디스크 파일 저장 여부 (Y/N)',
	SPATH VARCHAR(255) COMMENT '추가 저장 경로'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='관련자료 — 워드/HWP 문서 상세 (HTML 변환본 보관)';


-- TABLE TB_SRC_STORED
CREATE TABLE TB_SRC_STORED
   (	ISSTOR_NO DECIMAL(38,10) NOT NULL,
	SREF_TABLE VARCHAR(255) NOT NULL COMMENT '참조 테이블명',
	SREF_ITEM VARCHAR(255) NOT NULL COMMENT '참조 항목 식별자',
	SGUBUN VARCHAR(255) NOT NULL COMMENT '구분',
	SFLAG VARCHAR(255) NOT NULL COMMENT '원문 유형 (조문/서식)',
	STITLE VARCHAR(255) NOT NULL COMMENT '제목',
	SFULL_TITLE VARCHAR(4000) NOT NULL COMMENT '전체 제목 경로 (규정명 > 제N조)',
	SCONTENTS LONGTEXT COMMENT '원문 본문 (CLOB)',
	SLAW_URL VARCHAR(500) NOT NULL COMMENT '법령 URL',
	SCONTENTS_URL VARCHAR(500) NOT NULL COMMENT '본문 URL',
	SPOPUP_YN VARCHAR(255) NOT NULL COMMENT '팝업 표시 여부 (Y/N)',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '등록일시 (문자열)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '법령 논리 ID',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='레거시 원문 저장소 — 조문/서식 원문 텍스트(SFLAG) 보관, 상세검색·통합검색 원천';

  CREATE UNIQUE INDEX PK_TB_SRC_STORED ON TB_SRC_STORED (ISSTOR_NO) 
  ;
ALTER TABLE TB_SRC_STORED ADD CONSTRAINT PK_TB_SRC_STORED PRIMARY KEY (ISSTOR_NO) ;

-- TABLE TB_STATS_BBS_VIEW (2026-07-20 신설 — 게시판 조회통계 적재)
CREATE TABLE TB_STATS_BBS_VIEW
   (	ISBVIEW_NO DECIMAL(38,10) NOT NULL,
	SBBS_ID VARCHAR(30) NOT NULL COMMENT '게시판 ID (COMTNBBSMASTER, RTRIM 저장)',
	INTT_ID DECIMAL(38,10) NOT NULL COMMENT '게시글 ID (COMTNBBS.NTT_ID)',
	ICNT DECIMAL(38,10) NOT NULL COMMENT '조회수',
	SINS_DT VARCHAR(10) NOT NULL COMMENT '집계 일자 (YYYY-MM-DD)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판 조회 통계 — 게시글·일자별 조회수 적재 (사용자 열람 1회=1행)';

  CREATE UNIQUE INDEX PK_TB_STATS_BBS_VIEW ON TB_STATS_BBS_VIEW (ISBVIEW_NO)
  ;
ALTER TABLE TB_STATS_BBS_VIEW ADD CONSTRAINT PK_TB_STATS_BBS_VIEW PRIMARY KEY (ISBVIEW_NO) ;

-- TABLE TB_STATS_FT_VIEW
CREATE TABLE TB_STATS_FT_VIEW
   (	SGUBUN_ID VARCHAR(255) NOT NULL,
	ISFVIEW_NO DECIMAL(38,10) NOT NULL COMMENT '조회통계 번호 (PK)',
	ICNT DECIMAL(38,10) NOT NULL COMMENT '조회수',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '집계 일자 (YYYY-MM-DD)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)',
	ILAW_ID DECIMAL(38,10) NOT NULL COMMENT '법령 논리 ID'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='규정(전문) 조회 통계 — 규정·일자별 조회수 적재';

  CREATE UNIQUE INDEX PK_TB_STATS_FT_VIEW ON TB_STATS_FT_VIEW (ISFVIEW_NO) 
  ;
ALTER TABLE TB_STATS_FT_VIEW ADD CONSTRAINT PK_TB_STATS_FT_VIEW PRIMARY KEY (ISFVIEW_NO) ;

-- TABLE TB_STATS_KWD
CREATE TABLE TB_STATS_KWD
   (	ISKWD_NO DECIMAL(38,10) NOT NULL,
	SKWD VARCHAR(255) NOT NULL COMMENT '검색 키워드',
	ICNT DECIMAL(38,10) NOT NULL COMMENT '검색 횟수',
	SINS_DT VARCHAR(255) NOT NULL COMMENT '집계 일자 (YYYY-MM-DD)',
	SSYS_ID VARCHAR(255) COMMENT '시스템 ID (항상 레거시)'
   ) 
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='검색어 통계 — 검색 1회당 1행 적재 (인기 검색어 집계 원천)';

  CREATE UNIQUE INDEX PK_TB_STATS_KWD ON TB_STATS_KWD (ISKWD_NO) 
  ;
ALTER TABLE TB_STATS_KWD ADD CONSTRAINT PK_TB_STATS_KWD PRIMARY KEY (ISKWD_NO) ;

-- VIEW COMVNUSERMASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID) AS 
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR' AS USER_SE, ORGNZT_ID
    FROM COMTNGNRLMBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR' AS USER_SE, ORGNZT_ID
    FROM COMTNEMPLYRINFO;

--------------------------------------------------------------------------------
-- 합성 테이블 1종 — 레거시 운영 DB 에 없으나 라이브 필수 경로가 참조.
-- (죽은 흐름용 방어 테이블 6종은 2026-07-10 사용자 확정으로 제외 — 미생성 목록은 README 참조)
--------------------------------------------------------------------------------

-- COMTHEMPLYRINFOCHANGEDTLS (합성 근거: mapper\com\uss\umt\EgovUserManage_SQL_oracle.xml insertUserHistory —
--   사용자정보 수정 이력. 레거시 COMTN- 변형 구조 1:1, 매퍼가 쓰는 COMTH- 이름으로 생성)
CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID           VARCHAR(20)   NOT NULL COMMENT '업무사용자 ID(로그인 ID)',
  CHANGE_DE           CHAR(20)       NOT NULL COMMENT '변경일자 — 이력 기록 시점',
  ORGNZT_ID           CHAR(20) COMMENT '소속 조직(부서) ID — COMTNORGNZTINFO 참조',
  GROUP_ID            CHAR(20) COMMENT '그룹 ID',
  EMPL_NO             VARCHAR(20) COMMENT '사원번호',
  SEXDSTN_CODE        CHAR(1) COMMENT '성별코드',
  BRTHDY              CHAR(20) COMMENT '생일(생년월일)',
  FXNUM               VARCHAR(20) COMMENT '팩스번호',
  HOUSE_ADRES         VARCHAR(100) COMMENT '자택 주소',
  HOUSE_END_TELNO     VARCHAR(4) COMMENT '자택 전화 끝번호',
  AREA_NO             VARCHAR(4) COMMENT '전화 지역번호',
  DETAIL_ADRES        VARCHAR(100) COMMENT '상세주소',
  ZIP                 VARCHAR(6) COMMENT '우편번호',
  OFFM_TELNO          VARCHAR(20) COMMENT '사무실 전화번호',
  MBTLNUM             VARCHAR(20) COMMENT '이동전화번호',
  EMAIL_ADRES         VARCHAR(50) COMMENT '이메일주소',
  HOUSE_MIDDLE_TELNO  VARCHAR(4) COMMENT '자택 전화 국번(중간번호)',
  PSTINST_CODE        CHAR(8) COMMENT '소속기관코드',
  EMPLYR_STTUS_CODE   CHAR(1) COMMENT '사용자 상태코드',
  ESNTL_ID            CHAR(20) COMMENT '사용자 고유 ID(COMTNEMPLYRINFO.ESNTL_ID)',
  CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='업무사용자 정보 변경 이력(eGov 표준) — 사용자관리에서 수정 저장 시 변경 전 정보를 자동 기록';


-- 브랜드설정 — 로고(텍스트/이미지)·파비콘. 고객사별 리브랜딩 지점, BRAND_ID='S' 단일 행 (2026-07-31)
CREATE TABLE COM_BRAND (
  BRAND_ID              CHAR(1)       NOT NULL COMMENT '브랜드ID',
  LOGO_TY_CODE          VARCHAR(10)  DEFAULT 'TEXT' NOT NULL COMMENT '로고유형코드',
  LOGO_TEXT             VARCHAR(300) COMMENT '로고텍스트',
  LOGO_ATCH_FILE_ID     CHAR(20) COMMENT '로고첨부파일ID',
  FAVICON_ATCH_FILE_ID  CHAR(20) COMMENT '파비콘첨부파일ID',
  LAST_UPDUSR_ID        VARCHAR(20) COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM       DATETIME COMMENT '최종수정시점',
  CONSTRAINT PK_COM_BRAND PRIMARY KEY (BRAND_ID)
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='브랜드설정';
