--------------------------------------------------------------------------------
-- 11_indexes.sql — 비제약 인덱스(PK/UK 제외)
-- RegNex(규정 단독) 클린 설치 세트 — 레거시 운영 DB(2026-07-09 기준)에서 추출/정리.
-- 실행 계정: regnex. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수.
-- Oracle Text 도메인 인덱스(IDX_PROV_VRSN_FT)는 14_oracle_text.sql 별도.
--------------------------------------------------------------------------------

CREATE INDEX COMTCCMMNCODE_I01 ON COMTCCMMNCODE (CL_CODE);
CREATE INDEX COMTCCMMNDETAILCODE_I01 ON COMTCCMMNDETAILCODE (CODE_ID);
CREATE INDEX COMTNAUTHORROLERELATE_I01 ON COMTNAUTHORROLERELATE (AUTHOR_CODE);
CREATE INDEX COMTNAUTHORROLERELATE_I02 ON COMTNAUTHORROLERELATE (ROLE_CODE);
CREATE INDEX COMTNBBS_I01 ON COMTNBBS (BBS_ID);
CREATE INDEX COMTNCOMMENT_I01 ON COMTNCOMMENT (NTT_ID, BBS_ID);
CREATE INDEX COMTNEMPLYRINFO_I01 ON COMTNEMPLYRINFO (ORGNZT_ID);
CREATE INDEX COMTNEMPLYRINFO_I02 ON COMTNEMPLYRINFO (GROUP_ID);
CREATE INDEX COMTNEMPLYRSCRTYESTBS_I04 ON COMTNEMPLYRSCRTYESTBS (AUTHOR_CODE);
CREATE INDEX COMTNFAQINFO_I01 ON COMTNFAQINFO (ATCH_FILE_ID);
CREATE INDEX COMTNFILEDETAIL_I01 ON COMTNFILEDETAIL (ATCH_FILE_ID);
CREATE INDEX COMTNGNRLMBER_I01 ON COMTNGNRLMBER (GROUP_ID);
CREATE INDEX COMTNMENUCREATDTLS_I02 ON COMTNMENUCREATDTLS (MENU_NO);
CREATE INDEX COMTNMENUCREATDTLS_I03 ON COMTNMENUCREATDTLS (MAPNG_CREAT_ID);
CREATE INDEX COMTNMENUCREATDTLS_I04 ON COMTNMENUCREATDTLS (AUTHOR_CODE);
CREATE INDEX COMTNMENUINFO_I02 ON COMTNMENUINFO (UPPER_MENU_NO);
CREATE INDEX COMTNROLES_HIERARCHY_I01 ON COMTNROLES_HIERARCHY (PARNTS_ROLE);
CREATE INDEX COMTNROLES_HIERARCHY_I02 ON COMTNROLES_HIERARCHY (CHLDRN_ROLE);
CREATE INDEX IX_TB_ATTACH_01 ON TB_ATTACH (SREF_TABLE, IREF_NO);
CREATE INDEX IX_CATE_OWNER_OWNER ON TB_CATE_OWNER (OWNER_TY, OWNER_ID);
CREATE INDEX IX_CATE_READER_READER ON TB_CATE_READER (READER_TY, READER_ID);
CREATE INDEX IDX_DOCU_ITEM ON TB_DOCU (SITEM);
CREATE INDEX IDX_DOCU_PROM_NO ON TB_DOCU (IPROM_NO);
CREATE INDEX IDX_PROM_CATE_NO ON TB_PROM (ICATE_NO);
CREATE INDEX IDX_PROM_EXISTING_YN ON TB_PROM (SEXISTING_YN);
CREATE INDEX IDX_PROM_ID ON TB_PROM (ILAW_ID, ILAW_NO DESC);
CREATE INDEX IDX_PROM_WRK_PROM_NO ON TB_PROM_WRK (IPROM_NO);
CREATE INDEX IDX_PROM_WRK_STATUS ON TB_PROM_WRK (SSTATUS);
CREATE INDEX IDX_PROV_HTML_ITEM ON TB_PROV_HTML (SITEM);
CREATE INDEX IDX_PROV_HTML_PROM_NO ON TB_PROV_HTML (IPROM_NO);
CREATE INDEX IDX_PROV_VRSN_FULL_ITEM ON TB_PROV_VRSN (SFULL_ITEM);
CREATE INDEX IDX_PROV_VRSN_ITEM ON TB_PROV_VRSN (SITEM, SSUB_ITEM);
CREATE INDEX IDX_PROV_VRSN_NATIVE_TYPE ON TB_PROV_VRSN (SNATIVE_TYPE);
CREATE INDEX IDX_PROV_VRSN_NO ON TB_PROV_VRSN (IPROM_NO);
CREATE INDEX IDX_PROV_VRSN_UNIT_TYPE ON TB_PROV_VRSN (SUNIT_TYPE);
CREATE UNIQUE INDEX UX_READ_DUTY_PROM ON TB_READ_DUTY (IPROM_NO);
CREATE INDEX IX_READ_DUTY_TGT_ID ON TB_READ_DUTY_TGT (STGT_TY, STGT_ID);
CREATE INDEX IX_READ_DUTY_CHK_USER ON TB_READ_DUTY_CHK (SUSER_ID);
CREATE INDEX IDX_REL_FILE_VRSN_NO ON TB_REL_FILE (IRVRSN_NO);
CREATE INDEX IDX_REL_VRSN_PROM_NO ON TB_REL_VRSN (IPROM_NO);
CREATE INDEX IDX_REL_WORD_VRSN_NO ON TB_REL_WORD (IRVRSN_NO);
