--------------------------------------------------------------------------------
-- 22_seed_auth.sql — 권한·권한그룹·역할·매핑·역할계층
-- RegNex 클린 설치 세트 — 통합본(RLMS 스키마, 2026-08-03 라이브)에서 추출·제품 필터링.
-- 실행 계정: regnex. 클라이언트 인코딩 UTF-8(AL32UTF8) 필수. 재실행 비멱등(단순 INSERT).
--------------------------------------------------------------------------------

SET DEFINE OFF

-- ── 권한 (8행) ──
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('IS_AUTHENTICATED_ANONYMOUSLY',
        '스프링시큐리티 내부사용(롤부여 금지)',
        NULL,
        '26/05/08            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('IS_AUTHENTICATED_FULLY',
        '스프링시큐리티 내부사용(롤부여 금지)',
        NULL,
        '26/05/08            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('IS_AUTHENTICATED_REMEMBERED',
        '스프링시큐리티 내부사용(롤부여 금지)',
        NULL,
        '26/05/08            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('ROLE_ADMIN',
        '관리자',
        '시스템 전체 (PGM-001-01/02/04 자동 포함)',
        '20260608            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('ROLE_ANONYMOUS',
        '모든 사용자',
        NULL,
        '26/05/08            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('ROLE_APPROVER',
        '승인자',
        '규정 편집 + 작업 승인/반려 (EDITOR + approve/reject)',
        '20260616            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('ROLE_EDITOR',
        '편집자',
        '규정/분류/부서/개정구분 편집 (PGM-001-01-*, 04-01/03/08 자동 포함)',
        '20260608            ');
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE)
VALUES ('ROLE_USER',
        '조회자',
        '사용자 화면 — 조회/메모/즐겨찾기/도움말',
        '20260608            ');

-- ── 권한그룹 (1행) ──
INSERT INTO COMTNAUTHORGROUPINFO (GROUP_ID, GROUP_NM, GROUP_CREAT_DE, GROUP_DC)
VALUES ('GROUP_00000000000000',
        '0번  그룹입니다',
        '26/05/08            ',
        '0번  그룹입니다');

-- ── 역할 (39행) ──
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_ENTRY_DASH',
        '진입-업무대시보드',
        '\A/rlms/mgr/dashboard\.do(\?.*)?\Z',
        NULL,
        'url',
        '1',
        '20260609            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_ENTRY_HOME',
        '진입-사용자홈',
        '\A/rlms/home\.do(\?.*)?\Z',
        NULL,
        'url',
        '1',
        '20260609            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_ENTRY_MAIN',
        '진입-메인라우터',
        '\A/main\.do(\?.*)?\Z',
        NULL,
        'url',
        '1',
        '20260609            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_MGR_BUSEO_JSON',
        '부서 검색 JSON',
        '\A/rlms/prom/buseoListJson\.do.*\Z',
        NULL,
        'url',
        '469',
        '20260728            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_MGR_LAWQUEST',
        '법령질의 관리',
        '\A/rlms/lawquest/.*\Z',
        NULL,
        'url',
        '450',
        '20260617            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_MGR_PROMMAP_MANAGE',
        '규정맵 관리',
        '\A/rlms/prommap/(manage|importJson|renameJson|deleteJson).*\Z',
        NULL,
        'url',
        '430',
        '20260616            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_MGR_READDUTY_ASSIGN',
        '필수열람 지정 API',
        '\A/rlms/readduty/(dutyInfoJson|saveDuty|deleteDuty|userSearchJson)\.do.*\Z',
        NULL,
        'url',
        '471',
        '20260728            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_MGR_READDUTY_STATUS',
        '필수열람 현황',
        '\A/rlms/readduty/dutyStatus.*\Z',
        NULL,
        'url',
        '472',
        '20260728            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_MGR_STATS',
        '통계 조회',
        '\A/rlms/stats/.*\Z',
        NULL,
        'url',
        '470',
        '20260617            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_01',
        '규정 신규등록',
        '\A/rlms/prom/insertProm.*\Z',
        NULL,
        'url',
        '100',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_02_PREVIEW',
        '규정 미리보기',
        '\A/rlms/prom/preview.*\Z',
        NULL,
        'url',
        '110',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_03_DIFF',
        '규정 대비표',
        '\A/rlms/prom/diffByPromNo.*\Z',
        NULL,
        'url',
        '120',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_04_VALID',
        '규정 유효성검사',
        '\A/rlms/prom/validate.*\Z',
        NULL,
        'url',
        '130',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_07_SEQ',
        '규정 정렬변경',
        '\A/rlms/prom/updatePromSequence.*\Z',
        NULL,
        'url',
        '140',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_08_APPR',
        '신청승인/반려',
        '\A/rlms/promwork/(approve|reject)PromWork.*\Z',
        NULL,
        'url',
        '151',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_08_REQ',
        '승인요청',
        '\A/rlms/promwork/insertPromWork.*\Z',
        NULL,
        'url',
        '150',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_09_LIST',
        '작업승인관리목록',
        '\A/rlms/promwork/selectPromWorkList.*\Z',
        NULL,
        'url',
        '160',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_11_APPR',
        '수정승인/반려',
        '\A/rlms/promwork/(approve|reject)UpdatePromWork.*\Z',
        NULL,
        'url',
        '171',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_11_REQ',
        '수정권한요청',
        '\A/rlms/promwork/updatePromWork.*\Z',
        NULL,
        'url',
        '170',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_01_12_HIST',
        '제개정내역관리',
        '\A/rlms/promwork/selectPromWorkHistory.*\Z',
        NULL,
        'url',
        '180',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_04_01_BUSEO',
        '부서관리',
        '\A/rlms/buseo/.*\Z',
        NULL,
        'url',
        '400',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_04_03_CATE',
        '분류관리',
        '\A/rlms/cate/.*\Z',
        NULL,
        'url',
        '410',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_PGM_001_04_08_GAEJUNG',
        '개정구분관리',
        '\A/rlms/gaejung/.*\Z',
        NULL,
        'url',
        '420',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_FAVOR',
        '사용자 즐겨찾기',
        '\A/rlms/favor/.*\Z',
        NULL,
        'url',
        '630',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_FULLTEXT',
        '사용자 검색 5종',
        '\A/rlms/fulltext/.*\Z',
        NULL,
        'url',
        '600',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_LAWQUEST',
        '법령질의 공개열람',
        '\A/rlms/lawquest/lawQuestFront.*\Z',
        NULL,
        'url',
        '440',
        '20260618            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_MEMO',
        '사용자 메모',
        '\A/rlms/memo/.*\Z',
        NULL,
        'url',
        '620',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_PROMMAP_VIEW',
        '사용자 규정맵 조회',
        '\A/rlms/prommap/(view|treeJson|promListJson).*\Z',
        NULL,
        'url',
        '617',
        '20260616            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_PROM_DIFF',
        '사용자 신구대조',
        '\A/rlms/prom/diffByPromNo.*\Z',
        NULL,
        'url',
        '115',
        '20260616            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_PROM_GET',
        '사용자 법령 조회',
        '\A/rlms/prom/(selectPromList|selectPromDetail|selectPromHistory|searchHistory).*\Z',
        NULL,
        'url',
        '610',
        '20260512            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_PROM_VIEWJSON',
        '사용자 규정뷰 JSON',
        '\A/rlms/prom/(treeJson|historyJson|relatedListJson|provTextHstListJson).*\Z',
        NULL,
        'url',
        '615',
        '20260616            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_READDUTY_CONFIRM',
        '필수열람 숙지확인',
        '\A/rlms/readduty/confirmDuty\.do.*\Z',
        NULL,
        'url',
        '473',
        '20260728            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('ROLE_USR_RELATED_VIEW',
        '사용자 관련자료 조회',
        '\A/rlms/related/(relDetail|attachView|attachDownload).*\Z',
        NULL,
        'url',
        '616',
        '20260616            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('web-000001',
        '로그인롤',
        '\A/uat/uia/.*\.do.*\Z',
        '로그인허용을 위한 롤',
        'url',
        '1',
        '26/05/08            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('web-000003',
        '모든접근제한',
        '\A/.*\.do.*\Z',
        '모든자원에 대한 접근 제한 롤',
        'url',
        '9999',
        '26/05/08            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('web-000004',
        '회원관리',
        '\A/uss/umt/.*\.do.*\Z',
        '회원관리에 대한 접근 제한 롤',
        'url',
        '1',
        '26/05/08            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('web-000005',
        '실명확인',
        '\A/sec/rnc/.*\.do.*\Z',
        '실명확인에 대한 접근 제한 롤',
        'url',
        '1',
        '26/05/08            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('web-000008',
        '파일다운로드',
        '/cmm/fms/FileDown.do.*',
        '파일다운로드에 대한 접근 제한 롤',
        'url',
        '1',
        '26/05/08            ');
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES ('web-000012',
        'Validator모듈',
        '/validator.do',
        'Validator에 대한 접근 제한 롤',
        'url',
        '1',
        '26/05/08            ');

-- ── 권한-역할 매핑 (76행) ──
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('IS_AUTHENTICATED_FULLY',
        'ROLE_ENTRY_DASH',
        TO_DATE('2026-06-09 13:33:14','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('IS_AUTHENTICATED_FULLY',
        'ROLE_ENTRY_HOME',
        TO_DATE('2026-06-09 13:33:14','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('IS_AUTHENTICATED_FULLY',
        'ROLE_ENTRY_MAIN',
        TO_DATE('2026-06-09 13:33:14','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('IS_AUTHENTICATED_FULLY',
        'ROLE_USR_READDUTY_CONFIRM',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_MGR_BUSEO_JSON',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_MGR_READDUTY_ASSIGN',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_MGR_READDUTY_STATUS',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_MGR_LAWQUEST',
        TO_DATE('2026-06-17 11:11:18','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_MGR_PROMMAP_MANAGE',
        TO_DATE('2026-06-16 09:45:31','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_MGR_STATS',
        TO_DATE('2026-06-17 11:57:34','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_01',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_02_PREVIEW',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_03_DIFF',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_04_VALID',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_07_SEQ',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_08_APPR',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_08_REQ',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_09_LIST',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_11_APPR',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_11_REQ',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_01_12_HIST',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_04_01_BUSEO',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_04_03_CATE',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_PGM_001_04_08_GAEJUNG',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_FAVOR',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_FULLTEXT',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_LAWQUEST',
        TO_DATE('2026-06-18 10:29:40','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_MEMO',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_PROMMAP_VIEW',
        TO_DATE('2026-06-16 09:45:31','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_PROM_DIFF',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_PROM_GET',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_PROM_VIEWJSON',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'ROLE_USR_RELATED_VIEW',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'web-000001',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'web-000003',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'web-000004',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'web-000005',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'web-000008',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ADMIN',
        'web-000012',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ANONYMOUS',
        'web-000001',
        TO_DATE('2026-05-08 17:07:40','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ANONYMOUS',
        'web-000012',
        TO_DATE('2026-05-08 17:07:40','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ANONYMOUS',
        'web-000004',
        TO_DATE('2026-05-08 17:07:40','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_APPROVER',
        'ROLE_MGR_READDUTY_STATUS',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_APPROVER',
        'ROLE_MGR_BUSEO_JSON',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_APPROVER',
        'ROLE_MGR_READDUTY_ASSIGN',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_02_PREVIEW',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_03_DIFF',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_04_VALID',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_07_SEQ',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_08_APPR',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_08_REQ',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_01',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_MGR_STATS',
        TO_DATE('2026-06-17 11:57:34','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_MGR_PROMMAP_MANAGE',
        TO_DATE('2026-06-16 09:45:31','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_MGR_LAWQUEST',
        TO_DATE('2026-06-17 11:11:18','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_MGR_READDUTY_STATUS',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_MGR_BUSEO_JSON',
        TO_DATE('2026-07-28 14:30:59','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_09_LIST',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_USR_PROM_DIFF',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_USR_PROMMAP_VIEW',
        TO_DATE('2026-06-16 09:45:31','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_USR_LAWQUEST',
        TO_DATE('2026-06-18 10:29:40','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_04_08_GAEJUNG',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_04_03_CATE',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_04_01_BUSEO',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_12_HIST',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_11_REQ',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_EDITOR',
        'ROLE_PGM_001_01_11_APPR',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_PROM_GET',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_PROM_DIFF',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_PROMMAP_VIEW',
        TO_DATE('2026-06-16 09:45:31','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_MEMO',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_RELATED_VIEW',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_FULLTEXT',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_FAVOR',
        TO_DATE('2026-06-08 15:00:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_PROM_VIEWJSON',
        TO_DATE('2026-06-16 08:18:02','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_USER',
        'ROLE_USR_LAWQUEST',
        TO_DATE('2026-06-18 10:29:40','YYYY-MM-DD HH24:MI:SS'));

-- ── 역할계층 (6행) ──
INSERT INTO COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE)
VALUES ('IS_AUTHENTICATED_ANONYMOUSLY',
        'IS_AUTHENTICATED_REMEMBERED');
INSERT INTO COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE)
VALUES ('IS_AUTHENTICATED_REMEMBERED',
        'IS_AUTHENTICATED_FULLY');
INSERT INTO COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE)
VALUES ('ROLE_ANONYMOUS',
        'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE)
VALUES ('ROLE_APPROVER',
        'ROLE_ADMIN');
INSERT INTO COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE)
VALUES ('ROLE_EDITOR',
        'ROLE_APPROVER');
INSERT INTO COMTNROLES_HIERARCHY (PARNTS_ROLE, CHLDRN_ROLE)
VALUES ('ROLE_USER',
        'ROLE_EDITOR');

COMMIT;
